navikt/familie-ba-sak

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeMedBegrunnelser.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtbetalingsperiodeMedBegrunnelser/UtbetalingsperiodeMedBegrunnelserService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/domene/UtvidetVedtaksperiodeMedBegrunnelser.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/dataGenerator/behandling/kjørRevurdering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtvidetVedtaksperiodeMedBegrunnelserTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceTest.kt
Fjerne toggle som allerede burde ha vært fjernet. Den har vært skrudd på i 3 uker og ikke funnet feil med.
Nop
Fjerner bare kode. Eksisterende tester burde fange feil
=> Fjern toggle for ny måte å generere vedtaksperioder

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/MigrerFraInfotrygdTest.kt
Slett toggle som ikke ble brukt backend:
- Endre mottaker endringsårsaker ble ikke brukt
- Migrering fosterbarn ble kun brukt i tester
Nei
=> Slett toggles som ikke brukes

.deploy/nais/app-preprod.yaml
tester å enklere kunne jobbe med frontend lokalt
=> gir frontend-lokalt tilgang til preprod

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningsUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningsUtilsTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8803
Hva: 
Legger ved fuksjoner for å beregne differanse for ordinær sekundærlandssak. 
=> Legg til funksjonalitet for å beregne oridnær differanse

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtbetalingsperiodeMedBegrunnelser/UtbetalingsperiodeMedBegrunnelserService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt
Sletter to toggles som har vært på lenge nok.
Nei
Trengs ikke
=> Slett toggles som ikke trengs lenger

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt
Reverterer denne PRen som var en quick-fix på en behandling som hadde hengt seg opp i en rar state: https://github.com/navikt/familie-ba-sak/pull/2493
Trenger strengt tatt ikke fjerne endringene, men kanskje tryggest da det er en litt funky måte å løse problemet på? 🤷 
Det er en revert
=> Revert - Bug: får ikke henlagt teknisk endring-behandling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/domene/EØSBegrunnelse.kt, src/main/resources/db/migration/V208__legg_til_eos_begrunnelse_tabell.sql
**Leses:**
Ali i ett
Favro:
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6543
Hvorfor:
Vi trenger å få inn EØS-begrunnelser i løsningen.
Hva:
Lager en ny tabell for EØS-begrunnelser, slik at de kan holdes helt avskilt fra nasjonale begrunnelser.
=> Legg til EØS begrunnelse tabell

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/InnhenteOpplysningerOmBarn.kt
I #2458 oppdaget jeg ikke at brevmalen vi bruker i `ManueltBrevRequest.tilBrev()` for `INNHENTE_OPPLYSNINGER_ETTER_SØKNAD_I_SED` var feil, og dermed at det ene flettefeltet manglet. Vi oppdaget det under testing av frontenden for de nye brevene. 
Bruker riktig brevmal og legger til dokumentliste som flettefelt
=> Rett opp brevmal og flettefelt for EØS-brev

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/EndringstidspunktService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/EndringstidspunktUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/EndringstidspunktUtilsTest.kt
Sammenligner kompetanse perioder for nåværende behandling og siste iverksatt behandling for å finne ut første endringstidspunkt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8693
=> Sammenlignet kompetanse perioder for å finne ut første endringstidspunkt

README.md
Litt tynt med info rundt autentisering. Rydder opp og legger til litt info om bruk av Postman
Nei
_Jeg har ikke skrevet tester fordi:_ det er dokumentasjon
=> Juster litt på README for å gi litt mer utfyllende informasjon

src/main/kotlin/no/nav/familie/ba/sak/task/BehandleAnnullertFødselTask.kt
Logge error ved annuler hendlese melding og identene dette gjelder til securelogs. Dette er en quick fiks. Oppretting av oppgave til saksbehandler kommer senere
=> Logger error og identer ved annuler fødselshendelse

src/main/resources/application-preprod.yaml, src/main/resources/application-prod.yaml, src/test/integrasjonstester/kotlin/DevLauncherPostgres.kt
Flytter scope til config. Slik at man ikke trenger gcp secret
=> Flytter scope til config fra gcp secret

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/eøs/EØSBegrunnelseUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/SanityEØSBegrunnelse.kt
Legg til EØS-hjemler i objektet fra sanity
Robustgjør kall mot sanity
=> Feature/eøs hjemler og robustgjøring

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseController.kt
Som diskutert under Produksjonsstatus-sesjonen onsdag 8. juni: Introdusere toggles for Sekundærland og To primærland sidan EØS blir tilgjengeleg for alle saksbehandlere frå torsdag 9. juni.
=> Toggles for å støtte EØS sekundærland og to primærland

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/sanity/sanityQueries.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/SanityBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/SanityEØSBegrunnelse.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeUtilTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8839
Legge til logikk for riktig opplisting av EØS-hjemler. Fant i samme slengen ut at folketrygdloven-hjemler aldri ble vist i brev, så legger til de også.
Tar gjerne imot forslag for å slippe mutableList!
Husk også å merge familie-brev først!
=> EØS-hjemler

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeUtil.kt, src/main/resources/landkoder/landkoder.json
Midlertidig løsning til vi får kodeverk til å funke med [ISO 3166-1 alfa-2](https://no.wikipedia.org/wiki/ISO_3166-1_alfa-2).
Henter landkodene fra en lokal fil.
=> Midlertidig fiks. Henter landkoder fra lokal fil

src/main/resources/db/migration/V210__upb_utbetalingsland.sql
Tilknyttet Favro-task: [TEA-8898](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8898)
Utvide UPB tabell med `utbetalingsland` kolonne. Inneholder kun flyway-script.
=> Utvidet UPB tabell med kolonnen utbetalingsland 

README.md, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/IntegrasjonClientMock.kt, src/test/integrasjonstester/kotlin/DevLauncherPostgresPreprod.kt, src/test/resources/application-dev-postgres-preprod.yaml
Opprettet profil dev-postgres-preprod for å kunne kjøre mot det syntetiske miljø i preprod. Se README for oppsett
=> Opprettet dev profil dev-postgres-preprod for å kunne kjøre mot preprod

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningsUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningsUtilsTest.kt
[Er en fix av denne](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8986)
Nei
=> Test og fix av feil som oppstår ved bruker av desimaltall i kalkuleFraUtenlandskPeriodebeløp

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestFagsakSøk.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt
For å kunne navigere mellom forskjellige fagsaker må alle fagsaker listes opp i søk på person.
Søk på fagsak kan/bør forenkles men det må taes i en egen PR
=> Ta med fagsakeier i søk på person/fagsak

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Nye tekster i henhold til dette favrokortet: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8760
Testes ikke automatisk
=> Legg til flere begrunnelsestekster

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassUtenlandskePeriodebeløpTilKompetanserService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/utenlandskperiodebeløp/TilpassUtenlandskePeriodebeløpTilKompetanserTest.kt
Fix av [denne](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8996)
Nei
=> Utvider tilpasning av utenlandsk periodebeløp til kompetanse med sjekk k på endring av annen forelders aktivitetsland

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt
Sjekker om barna er en historisk ident før man fortsetter migrering
=> Sjekk for barnas ident er historisk.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilpassDifferanseberegningService.kt
Tilkjent ytelse oppdateres feil. Kommenterer ut koden
=> Legger på en feature toggle som alltid er false

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Legger til standardbegrunnelse for vedtaksbrev sekundærland
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8968
Sanity studio: https://familie-brev.sanity.studio/ba-brev/desk/begrunnelse;eos;innvilget;85fb78c8-66eb-4528-9583-ffc5f1d26161
Jeg _tror_ alle valgfeltene i teksten skal være dekket fra før?
=> Legg til standardbegrunnelse for sekundærland

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt
Ved migrering så sjekker man om løpende sak er av type I for institusjon.
=> Legger til en ny sjekk for om en sak er institusjon ved migrering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseType.kt
Fikser tekstene jeg har lagt til i #2624 og #2625 -> de skal ligge i EØS-begrunnelsesfilen slik at de blir plukket opp riktig. Det lærte jeg i dag 😇 
=> Flytt EØS-begrunnelser til EØS-begrunnelsesfil

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/AndelTilkjentYtelseTidslinjeUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/Differanseberegning.kt
`outerJoin` har blitt lagt til i tidslinje-rammeverket, og tar det i bruk på differanseberegning. 
Nei
_Jeg har ikke skrevet tester fordi:_  Koden alt er dekket av tester, og det er ingen funksjonell endring
=> Tar i bruk outer join på tidslinjer i differanseberegning for å forenkle koden

src/main/kotlin/no/nav/familie/ba/sak/common/TidslinjeUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SatsService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsvurderingTidslinjer.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/TilkjentYtelseBuilder.kt
Tar et par util-funksjoner ut av test, og samler et par som har med barnets alder å gjøre på samme sted
Nei
_Jeg har ikke skrevet tester fordi:_ Ingen funksjonell endring, bare flytting
=> Flytter og samler et par util-funksjoner ut av test, og samler like

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestTilkjentYtelse.kt
Trenger et felt for å si om en ytelsesperiode (pr aktør) skal utbetales eller ikke for å generere riktige "pølser" i frontend.
Nei
_Jeg har ikke skrevet tester fordi:_ Det er greiest å teste i frontend om man får det som trengs
=> Legger på et felt i RestYtelsePeriode som sier om beløpet skal utbetales

src/main/kotlin/no/nav/familie/ba/sak/sikkerhet/TilgangService.kt
... for fagsaker uten behandling(er)
=> Fikser en bug i TilgangService.validerTilgangTilFagsak

src/main/kotlin/no/nav/familie/ba/sak/ekstern/bisys/BisysService.kt
Alle stønadstyper ble satt til UTVIDET. Settes nå til utvidet eller småbarnstillegg. Pluss mer logging for videre feilsøking
=> Fikser feil i stønadstype for bisys og logging for videre feilsøking

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevperiodeData.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeUtilTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevperiodeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevPeriodeTestKlasser.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeUtilTest.kt, src/test/resources/brevperiodeCaser/EØS_OPPHØR.json
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9027
Legger til funksjonalitet for opphørsbegrunnelser på EØS. Eksisterende kode fungerte kun i tilfellene for innvilgelse, da man så på kompetansene som overlappet med vedtaksperioden. For opphørsbegrunnelser må man se på kompetansene som slutter rett før opphørsperioden. Dette er det jeg har lagt til.
Om jeg har løst det på en grei måte? Og navngivning tar jeg gjerne feedback på 🗡️ 
=> Opphørsbegrunnelser EØS

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingStegController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingStegControllerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8817
Kun la de som har tilgang til togglene "teknisk endring" godkjenne og henlegge behandlinger som er opprettet med årsak teknisk endring/opphør.
Nop
=> Legg henlegg og godkjenn teknisk behandling bak toggle

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingStegController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt
Knyttet til denne: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8817
Nei
Unødvendig
=> Bruke visningsnavnet til enum i stedet for enumnavnet i feilmelding

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtils.kt
Slet med å finne hvilke resultater vi fikk ved ugyldig behandlingsresultat. Sender med det i feilen slik at det skal bli lettere å debugge
=> Send med hvilke behandlingsresultater vi fikk ved ugyldig behandlingsresultat

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9173
Legger til ny begrunnelse
Budre ikke være nødvendig
=> Legg til SMÅBARNSTILLEGG_HADDE_IKKE_FULL_OVERGANGSSTØNAD begrunnesle

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingsresultatSteg.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingsresultatStegTest.kt
La til en validering som stopper migreringsbehandling hvis Behandlingsresultat er en av dem
AVSLÅTT, AVSLÅTT_OG_OPPHØRT, AVSLÅTT_OG_ENDRET, AVSLÅTT_ENDRET_OG_OPPHØRT, DELVIS_INNVILGET
=> La til en validering som stopper migreringsbehandling hvis Behandlingsresultat er Avslått eller Delvis Innvilget

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/common/RessursUtils.kt
Oppdaterer sentry-bibliotekene. 
Er testet ok i preprod: https://github.com/navikt/familie-ba-sak/actions/runs/2833277650
=> Oppdater sentry-logback og sentry-spring-boot-starter

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9251
Legger til opphørstest 3 til 8 for eøs
Legger bare til ekstra verdier i enum
=> Legg inn opphørbregrunnelse for eøs 3-8

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/samhandler/SamhandlerKlient.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/institusjon/InstitusjonService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/institusjon/SamhandlerController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrerInstitusjonOgVerge.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/SamhandlerTestConfig.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/institusjon/SamhandlerControllerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrerInstitusjonOgVergeStegTest.kt
2 endepunkt for å hente info fra tss. Enten for orgnr eller navn. Og selve integrasjonen mot tss-endepunktet
=> Controller og klient for å søke etter samhandler for å få tssEksternId

src/main/kotlin/no/nav/familie/ba/sak/task/SendMeldingTilBisysTask.kt
Var inne for å se hvor mange opphørsmeldinger vi hadde sendt til bisys, fant noe smårusk som burde fikses.
- Riktig beskrivelse av task 
- logging av at vi sender melding til bisys
=> Riktig  beskrivelse av bisys Task + logging

src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTaskTest.kt
Rettar feilen Eivind meldte på Slack med at behandle fødselshendelse feila for syntetisk fnr: https://nav-it.slack.com/archives/C01G9BA8JKZ/p1661344421087229
N/A
- [x ] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇
- [x ] Nei
=> Bugfix/behandle fødselshendelse syntetisk

pom.xml
ECBClient i `familie-felles` er oppdatert. Oppdaterer derfor `ba-sak` med ny versjon av `familie-felles`
=> Oppdatert familie-felles til siste versjon

src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/Tidslinje.kt
Tidslinje-klassen var ikke dokumentert, og det var utydelig hva design-tanken var. Forsøker å utbedre det her.
=> Legger til litt manglende javadoc på Tidslinje

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt
Logg ident for å feilsøke en sak i prod
Nei
Kun lagt til logging
=> Logg hvilken ident som feiler ved findByFødselsnummerOrNull

src/main/resources/db/migration/V223__sokers_aktivitet_endre_enumverdier.sql
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9429
Fjerner feltene som ble laget for å holde ba-sak bakoverkompatibel til ba-sak-frontend er oppdatert. Avhengig av https://github.com/navikt/familie-ba-sak-frontend/pull/2293. 
=> Migrer bort avviklede enumfelter

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/Personident.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt
Lagt til fødselsnummersjekk i equals og mer logging for feilsøking
Dekkes av eksisterende tester
=> Fiks av equals for personident og mer logging

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestRegistrerInstitusjonOgVerge.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrerInstitusjonOgVerge.kt
Tillate orgnummer i institusjon til å være null
=> Tillater orgnummer til å være null in InstitusjonInfo

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9251
Legger til ny opphørstekst for EØS. Har fjernet det som gjør at teksten trenger masse spesiallogikk (i samarbeid med fag), slik at den nå vil fungere ut av boksen 🚀 
Nop
Unødvendig
=> Lagt til EØS-opphørsbegrunnelse

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9463
Lagt til en ny nasjonal innvilget begrunnelse. Uten noen flettefelter eller andre kompliserte ting 👍 
Nei
=> Lagt til ny nasjonal innvilget begrunnelse

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentServiceTest.kt
I stedet for å deaktivere og så legge til samme personident, så lagrer man bare ned hvis den ikke eksisterer en aktiv fra før.
Denne vil jeg teste i miljø før man merger
=> Omskrivning av logikken for å lagre ned personident

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/domene/EndretUtbetalingAndel.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/småbarnstilleggkorrigering/SmåbarnstilleggKorrigeringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/StandardbegrunnelseUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtbetalingsperiodeMedBegrunnelser/UtbetalingsperiodeMedBegrunnelserService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/dataGenerator/behandling/KjørRevurdering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggBarnetrygdGeneratorTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/StandardbegrunnelseTest.kt
Kjører ktlint på en del filer for å forberede senere PR
Nei
_Jeg har ikke skrevet tester fordi:_ det bare er formateringsendringer
=> Kjører ktlint på en del filer for å forberede senere PR

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/Beregning.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/SendVedtakTilInfotrygdTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkServiceTest.kt
Skriver om til å bruke andeler tilkjente ytelser direkte, i stedet for å gå veien via tilkjent ytelse. Det er for å lette overgangen til løskobling av andeler og endringer
Nei
_Jeg har ikke skrevet tester fordi:_ testene finnes, men de måtte justeres tilsvarende
=> Skriver om til å bruke andeler tilkjente ytelser direkte

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtbetalingsperiodeMedBegrunnelser/UtbetalingsperiodeMedBegrunnelserService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtbetalingsperiodeMedBegrunnelser/UtbetalingsperiodeUtil.kt
Slettar toggle som no har gjort nytta si.
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9361
Nei
Har kun sletta kode
=> Tea-9361: Fjernar bruk av toggle i koden, og slettar koden som da blir ubrukt

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/Personident.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentTest.kt
Prøver å finne ut av (og fikse) feilande task som feilar på databaseconstraint
=> Utvidar equals og hashcode på personident så dei tar høgde for aktiv/inaktiv, pluss ekstra logging

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt
=> Enda litt meir logging

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt
=> No er vi på sporet av noko, så loggar også fnr for å sjå kva det faktisk er

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt
Ønsker å debugge denne litt bedre: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9576
Ser derfor behov for å logge opprettetÅrsak - da denne er helt sentral i beslutningen om saken sendes rett til iverksetting etter behandlingsresultat. Skjønner ikke helt at denne skal ha en annen årsak enn omregning18år, men saken er veldig merkelig så alt kan ha skjedd 🤷 
Nop
Bare logging
=> Logg opprettetÅrsak på Behandling

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/behandlingstema/BehandlingstemaUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingUtilsTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/MigrerFraInfotrygdTest.kt, src/test/resources/application-dev-postgres-preprod.yaml
Støtte for å migrere primærlandsaker for EØS. Saker med sakskoder BA OR EU og BA UT EU i Infotrygd
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9517
Test
OR EU
https://barnetrygd.dev.intern.nav.no/fagsak/200008607/saksoversikt
https://barnetrygd.dev.intern.nav.no/fagsak/200008555/saksoversikt
UT EU
https://barnetrygd.dev.intern.nav.no/fagsak/200008611/saksoversikt
https://barnetrygd.dev.intern.nav.no/fagsak/200008558/saksoversikt
Utrulling vil bli gradvis ved at man tar en sak, verifiserer etterpå i ba-sak/infotrygd/økonomi. Og så øker man mengden gradvis
=> Feature/migrering eøs

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt
Støtte for  søkersaktivitet er null, som den er ved migrering
=> Fikser at stønadsstatistikk ikke feiler ved migrering eøs

src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/MigrerFraInfotrygdTest.kt
Migrer EØS tester feiler på master. Disabler og fikser siden så deploy ikke stopper opp
=> Disabler tester som feiler på master

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/SendTilBeslutter.kt
Fjern validering som skjer for tidlig. Den skjer fremdeles i iverksett mot oppdrag steget
=> Fjern validering av andeler med duplikatoffset i send til beslutter steget

src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt
Sender søkers aktivitetsland til datavarehus
=> Send med søkersAktivitetsland til datavarehus

src/main/kotlin/no/nav/familie/ba/sak/config/KafkaAivenConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/config/KafkaAivenErrorHandler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/rest/TidslinjeController.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/producer/KafkaProducer.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/KafkaAivenErrorHandlerTest.kt
- Fant en controller med @Unprotected
- Skrev om errorhandler i kafka til å ikke arve fra en deprikert klasse
- Slettet VedtakDVH kode, og et par små kompiler warnings
=> Fjerner unprotected på controller, endret kafka-config til å ikke bruke deprikerte metoder og et par andre compilerwarnings

.github/workflows/build-and-deploy-krise-eksisterende-image-rett-i-prod.yml
Byggejobben som pushar ut eit eksisterande image i prod feila fordi vi ikkje hadde sjekka ut git-repoet, og dermed fekk ikkje byggejobben tak i nais-yaml-filene.
=> Køyrer checkout i krisedeploy-byggejobben

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt
Sjekker en antakelse om at andeler til `TilkjentYtelseUtils.beregnTilkjentYtelse` ikke har endringer på vei inn i kallet.
Nei
_Jeg har ikke skrevet tester fordi:_ det er bare logging som legges på.
=> Legger på logging for å se om hypotesen om at andeler ikke har endringer, holder

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
Som ein del av arbeidet med å skilje seg heilt ut frå Finn. Det har også komme ein god del nye versjonar, som vi ikkje har oppdaga sia dei har skjedd under ny groupid. Så oppdaterer til nyaste.
=> Unleash har bytta pakkenamn både i koden og i Maven central, og lansert nye versjonar

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetIAndelTilkjentYtelseTask.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt
Forbedrer loggingen av behandlinger, samt filtrerer ut henlagte behandlinger.
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9533
Nei
=> Forbedre logging i "rett feilaktige offset"-fix + filtrer ut henlagte behandlinger

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9533
=> Kun hent ut distinkte behandlingId-er fra spørring om duplikate offsets

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetController.kt
Endepunkt for å faktisk køyre oppdateringa.
Nei
=> Tea-9686: Endepunkt for å faktisk køyre oppdateringa

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetIAndelTilkjentYtelseTask.kt
- Ikke bry oss hvis nyere behandling som er avsluttet er henlagt
- Logge ut antall behandlinger i hver logg-entry
Nei
=> Forbedre offset-fix

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9731
Nei
Unødvendig
=> Lagt til tre nye begrunnelser

pom.xml
JUnit er eit testbibliotek, og ikkje noko vi bør levere med i prodkoden.
Sørgjer også for at vi ikkje gjenintroduserer det ved å leggje det som ein _banned dependency_. Det er sikkert ei liste som bør utvidast etter kvart, kanskje med sånt som mockk etc.
Kun pom-endringar
=> Junit ut av prodkoden

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetController.kt
=> Gjer oppdatering transaksjonell

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseController.kt
Fjerner siste EØS-funksjonsbryter i denne omgang
Nei,
_Jeg har ikke skrevet tester fordi:_ det er bare en feilmelding som fjernes
=> Fjerner funksjonsbryter KAN_BEHANDLE_EØS_TO_PRIMERLAND

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsperiodeMal.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/NyUtbetalingsoppdragGeneratorTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragIntegrasjonTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/EndringstidspunktTest.kt
(https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9568)
For institusjon så skal det utbetales til institusjonens tss-ekstern-id
Testet i preprod med 
callId: 9e901118-4d59-4654-86c5-9b5452639fc4
vedtakId: 1171851
behandlingsId: 100108301
fagsak: 200011051
XML i oppdrag
Bør få inn et par tester, men lager en draft av denne i tilfelle noen andre ønsker å gjøre den ferdig før jeg er frisk
=> Sender med tss-ekstern-id til oppdrag for institusjon

src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkController.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9781
Navn på endepunkt
=> Nytt endepunkt for å sende vedtak på nytt til stønadsstatistikk

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtbetalingsperiodeMedBegrunnelser/UtbetalingsperiodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/EndringstidspunktTest.kt
Vi får denne feilen i sentry no. Trur det blir lettare å finne ut av med litt meir logging av kva som faktisk er feil.
=> Tar med dei faktiske regelverka som slår til i feilmeldinga, for enklare feilretting i neste runde

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/AvstemmingService.kt
logging for å finne hvilken aty som mangler kildebehandling
=> Logging for feilede konsistensavstemning

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetController.kt
Nytt endepunkt for å rette utvalgte behandlinger med offset
=> feat: Nytt endepunkt for å rette offset for en liste med behandlinger

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetIAndelTilkjentYtelseTask.kt
Åpne for å fikse offset om neste behandling er fortsatt_innvilget
=> feat: Mulighet til å fikse offsett når neste behandling er fortsatt_innvilget

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetIAndelTilkjentYtelseTask.kt
Endepunkt for å resette offset for en behandling blir ignorert for endepunktet man bruker for å resette en spesifikk behandling
=> feat: reset offset for en manuell behandling blir ignorert

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonClient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/UtgåendeJournalføringService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/organisasjon/OrganisasjonService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/JournalførVedtaksbrev.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/IntegrasjonClientMock.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/IntergrasjonTjenesteTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceEnhetstest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceTest.kt
Endret journalføring av utsendte brev til institusjon/verge til å bli journalført på bruker istadenfor institusjon/verge.
Brev sendt til institusjon feilet i test i preprod, ref. https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9748
Oppdatert eksisterende tester.
=> Journalfører utsendte brev på bruker og fyller ut AvsenderMottaker for institusjon/verge

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonClient.kt
=> Fix på url organisasjonservice i integrasjoner

src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkServiceTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9504
Legger kodene for institusjon, ensling_mindreårig og småbarnstillegg i "behanlingUnderkategori" som avtalt.
=> Saksstatistikk institusjon/verge

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceEnhetstest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceTest.kt
=> Fix på manuell utsending brev til institusjon

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetIAndelTilkjentYtelseTask.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetIAndelTilkjentYtelseTaskTest.kt
endepunkt for å simulere alle behandlinger etter en dato for å finne offset-feil
=> Undersok om flere saker har offset feil

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetController.kt
Endrer til å bruke LocalDateTime i simulerjobben for offsett, fordi man ikke fikk love med LocalDate
=> Endrer til localdatetime for datoer i rettoffset jobb

README.md
Oppdater readme med oppskrift for å kalle endepunkt i prod fra postman.
Nei.
Bare Readme oppdatering
=> Oppdater readme med oppskrift for å kalle endepunkt i prod fra postman

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetController.kt
Utvider rett offset søket til å ikke ha sluttdato
=> Utvider rett offset søket til å ikke ha sluttdato

pom.xml
Samlar dependabot-oppgraderingar, pluss tar bort spesialtilpassing for tidsserie-avhengnad som ikkje lenger er nødvendig
=> Oppdateringar 11.10.22

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetController.kt
Litt fikser som Ida og jeg plukket opp i første kjøring
=> Legger på securelogger, null-sjekk og bedre loggmelding

.deploy/nais/azure-ad-app-lokal.yaml
Tilsvarande som EF har gjort for familie-ef-sak
Tilrettelegging for [Tea-9108](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9108)
=> Opne for familie-prosessering-lokal, for å kunne utvikle denne enklare

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt
Forvekslet enhetsnavn og enhetsId etter en omskrivning
=> Fikser Enhets-objekt i ManuelBrevRequest

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt
=> Named arguments for enhet

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Splittet 1 begrunnelse for opphør EØS til 3 ulike begrunnelser. 
=> Splittet 1 begrunnelse-opphør EØS til 3 begrunnelser

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/AutovedtakStegService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/AutovedtakFødselshendelseService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/VelgFagSystemService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/småbarnstillegg/AutovedtakSmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/AutobrevStegServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakControllerTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakServiceTest.kt
Saksbehandler må kunne behandle søknad, frå ny institusjon, når eit barn flytter frå ein institusjon til ein anna. SB vil då opprette ny fagsak og behandling for søknad på ny institusjon, og så opprette revurdering og sende varsel til eksisterande institusjon.
BA-sak må difor støtte fleire åpne fagsake av typen institusjon på eit barn.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9843
_Jeg har ikke skrevet tester …
=> Skal kunne opprette flere fagsaker av typen institusjon

pom.xml
Oppdatering til seneste prosessering-backend, hvor jdbc og core har blitt slått sammen
=> Oppdatering av prosessering, hvor jdbc-modulen er fjernet og byttet med core

src/main/resources/db/migration/V228__index_konsistensavstemming.sql
Legger på noen indexer for å få raskere konsistensavstemming
=> perf: indexer for å få raskere konsistensavstemming

src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyController.kt, src/main/kotlin/no/nav/familie/ba/sak/task/KonsistensavstemMotOppdragStartTask.kt
Endrer testkall for test av konsitensavstemming til POST-kall
=> Endrer testkall for test av konsitensavstemming til POST-kall

src/main/resources/application-preprod.yaml, src/main/resources/application-prod.yaml, src/main/resources/application.yaml
Rydder bort resten av onprem-config for kafka onprem.
Testet i preprod
=> Rydder opp i kafka-configen etter at man sluttet å sende til onprem

src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassKompetanserService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/EndretUtbetalingAndelTidslinjeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/komposisjon/TidslinjeJoin.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/TilpassKompetanserTilRegelverkTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/KompetanseBuilder.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/StringTilTidslinje.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/VilkårVurderingBuilder.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/EndretUtbetalingAndelTidslinjeServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/TidslinjerTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingTestController.kt
Hvis ett eller flere barn har en endringsperiode med etterbetaling 3 år, skal det ikke være nødvendig å fylle ut kompetanse for EØS-perioder
Kan med en liten fordel leses commit for commit
Nei
=> Feature/etterbetaling 3 år skal ikke kreve kompetanse

README.md, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt
Når man tester lokalt kan det være nyttig å sette individuelle funksjonsbrytere av eller på
Nei
_Jeg har ikke skrevet tester fordi:_. Dette _ER_ testing
=> Gjør det mulig å sette individuelle funksjonsbrytere med VM options

src/main/kotlin/no/nav/familie/ba/sak/config/CacheConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonClient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/samhandler/SamhandlerKlient.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/AbstractMockkSpringRunner.kt
Lagt på caching mot TSS. Renamet eksisterende kodeverk-cache til dailyCache.
=> Daglig caching på samhandlerInfo

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt
Gjere det mogleg å henlegge behandlinger, som er i ein "umogleg" state p.g.a. andre feil og kor det ikkje er mogleg å fikse.
=> TEA-9749 Gjere det mogleg å henlegge med teknisk vedlikehold på "Fatte vedtak"-steget

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/domene/EØSBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt
Favro: [https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9934](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9934)
Fikser gal fritekstvalidering som følge av ufullstendig kopiering av vedtaksperioder fra underkjent vedtak over til nytt aktivt vedtak
Testet manuelt, og ga opp å lage test som evt. kunne fanget opp manglende kopiering ved ny utvidelse. Virket som mer bry enn det er verdt
=> Tar med eøsBegrunnelser fra underkjent vedtak videre

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/Filtreringsregel.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/FiltreringsregelTest.kt
feil i sjekken for erBost, som stopper nav syntetisk
=> Fikser sjekken for erBostNummer

src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/tid/TidspunktClosedRange.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/TidspunktClosedRangeTest.kt
`TidspunktClosedRange` brukes mye i tidslinjer, typsik for å skrive ting som `fraOgMed..tilOgMed`. Det har vært en del svakheter i hvordan uendelighet har blitt håndtert. Her prøver jeg å rydde opp i det og lage mange flere tester. 
Er ikke fryktelig lett å gjøre lesbart, dessverre. Er en del spesialtilfeller som må håndteres. Men tar gjerrne innspill på hvordan det kan gjøres bedre.
=> Fikser TidspunktClosedRange til å håndtere en del særtilfiller, og bygger ut tester

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequestTest.kt
Nokon nye begrunnelser for ordinær.
=> TEA-10226 Nye begrunnelser ordinær

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeMedBegrunnelser.kt
Logging for å finne ut meir om feilen i [`Tea-9919`](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9919)
=> Legg på litt ekstra logging for å binærsøke problemet

src/main/kotlin/no/nav/familie/ba/sak/kjerne/institusjon/SamhandlerController.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/institusjon/SamhandlerControllerTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9444)
Første sjekkboks, resten er dekka i [frontend-PR](https://github.com/navikt/familie-ba-sak-frontend/pull/2391)
=> Feilmelding viss finner ikkje institusjon

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtbetalingsperiodeMedBegrunnelser/UtbetalingsperiodeMedBegrunnelserService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtbetalingsperiodeMedBegrunnelser/UtbetalingsperiodeUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/domene/PersonResultat.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtbetalingsperiodeMedBegrunnelser/UtbetalingsperiodeUtilTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/PersonResultatTest.kt
Forberedende til: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10291
Gjør noen forbedringer som trengs i oppgaven over. Sikkert fint å lese commit for commit
Nei
Finnes allerede tester. Tenker det ikke er nødvendig å legge til flere, men lov til å si seg uenig 🤷
=> Forbedringer: sikrer at alle vilkår for persontype er oppfylt i periode for å skape splitt

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatServiceTest.kt
Koden i [denne](https://github.com/navikt/familie-ba-sak/pull/3041) PRen har en bug som gjør at vi får ENDRET som resultat selv om det ikke skulle ha vært det. Har bla. ført til en task som feiler mot iverksetting fordi den ikke har noen utbetalingsperioder. Denne behandlingen skulle aldri ha vært iverksatt mot oppdrag fordi den skulle kun ha fått behandlingsresultat AVSLÅTT, men på grunn av denne buggen så fikk den AVSLÅTT OG ENDRET.
PRen jeg har lenket til over er knyttet til denne oppgaven: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10293
Nei
=> Legg kode som har bug bak toggle

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BegrunnelseUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/UtgjørendeVilkårUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/StandardbegrunnelseUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseType.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtakPeriodeValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/Vedtaksperiode.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeUtil.kt
Lagt inn støtte for begrunnelser for institusjon. Dei er skilt frå dei andre ordinære, men foreløpig ikkje implementert filtrering.
Er veldig usikker på kor det er naturleg å teste her? Og kor det i så fall skulle bli testa?
=> TEA-8832 Begrunnelser vedtaksbrev for intitusjon

README.md, src/test/integrasjonstester/kotlin/DevLauncherPostgresPreprod.kt, src/test/resources/hentMiljøvariabler.sh
Har tatt KS si løysing, og lagt på eit flagg for å skru det av
Skal vi ha standard på eller av?
Lokalt hos meg var det litt knot med at eg måtte få lagt inn _KUBECONFIG_ som global miljøvariabel for å få det til å køyre.
=> Hentar miljøvariablar for oppkopling mot preprod for utvikling/test automatisk

.deploy/ba-sak-proxy/nais.yaml, .deploy/nais/app-preprod.yaml, .deploy/nais/app-prod.yaml, README.md, pom.xml, src/test/resources/application-dev-postgres-preprod.yaml, src/test/resources/application-postgres.yaml, src/test/resources/bootstrap-postgres.yaml
Vi brukte vault da vi køyrde ba-sak on-prem, men ikkje på gcp
Fint å bli kvitt ubrukte avhengnadar
=> Vi treng ikkje lenger avhengnaden til vault, så fjernar den og all bruk

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/ForlengetSvartidsbrev.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequestTest.kt
Det vart brukt feil brevmal for forlenget svartidsbrev institusjon. Dette er fiksen.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10510
=> Fiks for forlenget svartidsbrev institusjon

pom.xml
=> Oppgraderer til nyaste patch-versjon av Spring Boot. Greitt å vera på nyaste 2.7.x før vi går over til 3.0 etter kvart

src/main/kotlin/no/nav/familie/ba/sak/common/Tid.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggService.kt
Bruke riktig datoformat i beskrivelsen på historikkinnslag for korrigert vedtak.
**_Før_**
**_Etter_**
=> Riktig datoformat på vedtaksdato i logginnslag for korrigert vedtak

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelseRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakControllerTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakServiceTest.kt
Tilknyttet denne oppgaven: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9841
Lager et endepunkt som:
- Tar inn en personIdent
- Returnerer fagsakId+aktør for alle fagsaker hvor personIdent enten er søker eller personIdent mottar løpende ordinær barnetrygd
Skal brukes av ba-mottak for å finne ut hvilke personer&fagsaker en Vurder livshendelse-oppgave skal opprettes på.
Se kommentarer i koden
=> Endepunkt: finn fagsaker hvor person er søker eller mottar løpende ordinær barnetrygd

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/DummyFeatureToggleService.kt
, i lokal utvikling kan det vera det mest formålstenlege
=> Flippar standardverdien for funksjonsbrytarar til å vera på

src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/PersonResultatTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt
=> Desse to testane rota det litt til med now()-kall, så bruker heller hardkoda verdiar

.github/workflows/build-pr.yml, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/AbstractVerdikjedetest.kt
Viss nokon ved ein feil legg inn ein verdikjedetest utanfor akkurat denne pakka, vil vi no registrere det og køyre denne saman med resten av verdikjedetestane.
Det opnar også for seinare refaktorisering - det er på ingen måte opplagt for meg at den beste strukturen er den vi har no med alle verdikjedetestane i ei pakke. Eg trur det kan vera betre å ha dei i pakkar der dei funksjonelt høyrer heime, tilsvarande som vi gjer med dei andre testane våre.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9759)
=> Heller enn å basere oss på ein litt sårbar variant med i kva pakke verdikjedetestane ligg, bruker vi heller JUnit-mekanismen tag

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/VedtakEndring.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceEnhetstest.kt
Delmal 1 hentes inn i vedtaksbrevet dersom vedtaket har EØS periode uten til og med dato.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9732)
=> Introduserer skal ha årleg kontroll som ein mogleg delmal for vedtak endring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favro: [Tea-10567](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10567)
Legger til en begrunnelsestekst for opphør ved avtale om fast bosted hos annen forelder
=> Legg til opphørsbegrunnelse for avtale om fast bosted

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Tilknyttet samme sak som denne: [Tea-10567](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10567)
Legger til en begrunnelsestekst for reduksjon ved avtale om fast bosted hos annen forelder
=> Legg til reduksjonsbegrunnelse for avtale om fast bosted

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/behandlingstema/BehandlingstemaUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingUtilsTest.kt
Tar i bruk overstyrt behandlingKategori fra NyBehandling-dto istedenfor hardkodet verdi ved helmanuell migrering.
Har oppdatert eksisterende
=> Støtte for manuell migrering av flere sakstyper

src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkService.kt
Fjerner tekststrenger fra resultbegrunnelse for saksstatistikk
=> Fjerner standardbegrunnelse fra resultatBegrunnlse for saksstatistikk

.github/workflows/build-and-deploy-preprod.yml, .github/workflows/build-and-deploy-prod.yml
Enabler larger runner for github actions 
=> Larger runner på github for preprod og prod jobbene

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt
Endrer de funksjonelle feilmeldingene på maskinell migrering for å være til hjelp for saksbehandler og ikke utvikler.
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10738
=> Oppdaterer de funksjonelle feilmeldinger ved maskinell migrering

src/main/resources/application-preprod.yaml, src/main/resources/application.yaml
Endrer scope til klage sånn at det matcher hvordan det er gjort i ef-sak
https://github.com/navikt/familie-ef-sak/blob/master/src/main/resources/application.yml
https://github.com/navikt/familie-ef-sak/blob/master/src/main/resources/application-dev.yml
https://github.com/navikt/familie-ef-sak/blob/master/src/main/resources/application-prod.yml
=> Bruk oppsett som de har i EF for scopet til klage

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SatsService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/YtelseSatsMapper.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/Sats.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtbetalingssikkerhetTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/YtelseSatsMapperTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/TilkjentYtelseBuilder.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SatsServiceIntegrationTest.kt
Introduserer UTVIDET_BARNETRYGD som egen sats,  og tar. den i bruk. Inntil satsendring er den identisk som ordinær barnetrygd.
Les commit for commit. Ble litt linting, så lagde en commit med det, og en med det funksjonelle.
Nei
=> Legger til sats for utvidet barnetrygd og tar den i bruk

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt
og setter oppgaven til ferdigstilt i db dersom den ikke var oppdatert iht. kilden.
Se [https://nav-it.slack.com/archives/CK59Y6EHE/p1673448087229159?thread_ts=1673435260.397199&cid=CK59Y6EHE](https://nav-it.slack.com/archives/CK59Y6EHE/p1673448087229159?thread_ts=1673435260.397199&cid=CK59Y6EHE)
=> Validerer oppgavestatus før patch-kallet til Oppgave

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/AndelTilkjentYtelseTidslinjeUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/Differanseberegning.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningsUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilpassDifferanseberegningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/matematikk/BigDecimalTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/matematikk/SammenliknbarTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/FiltrerTidslinje.kt
Fjerner funksjonsbryter som nå er på i prod (første commit). Benytter anledningen til å flytte en del util-funksjoner til nye hjem (resten av commit'ene).
Nei
_Jeg har ikke skrevet tester fordi:_ alt skal fungere som før
=> Teknisk/fjern toggle differanseberegning utvidet og småbarnstillegg

src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringUtilTest.kt
Diskusjon på slack
https://nav-it.slack.com/archives/GU4MVCGCD/p1674815983931239
https://nav-it.slack.com/archives/GU4MVCGCD/p1674819932205559
Screenshot:
=> Ikke ta med manuelle ytelser i resultat.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/AutovedtakFødselshendelseService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/MigrerFraInfotrygdTest.kt
Feil fødselshendelsetasken i stedet for å logge og opprette oppgave, siden det er tasker i baks-mottak med fødselsehendelser man lytter på. De sendes ikke til sak før etter 1 døgn
=> Feil tasken i stedet for å logge error og lage oppgave

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSteg.kt
=> Behandlingsresultat: gjør koden mulig å nå hvis toggle er på

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt
Øker antall satsendringer per halvtime til 50
=> Øker antall satsendringer per halvtime til 50

src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VurderTilbakekrevingSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingUtil.kt
Snakket med Anna og vi ble enige om å ha en hard validering på migreringsbehandlingene slik at de ikke går gjennom med manuelle posteringer
=> Stopp migreringsbehandlinger med manuelle posteringer

.deploy/nais/app-preprod.yaml, src/main/resources/application-dev.yaml, src/main/resources/application.yaml, src/test/resources/application-dev-postgres-preprod.yaml
- Skrur ned max antall replicas i preprod for raskere deploy
- Setter up max-lifetime for hikari for å redusere connection closed logging
- Setter deploy_env til dev på de-profilene slik at ikke klage går mot prod scope fra f.eks postgres-preprod profilen
=> Diverse forbedringer i konfig

src/main/kotlin/no/nav/familie/ba/sak/task/IverksettMotOppdragTask.kt
Legger til fagsakId på task, slik at man slipper å måtte søke opp fagsak i database
=> Legger til fagsakId på metadata for iverksett, for å lettere kunne feilsøke

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatServiceTest.kt
Vi ønsker å fjerne duplikater i lista vi får tilbake fra finnPersonerFremstiltKravFor metoden.
=> Behandlingsresultat - I tilfelle det er duplikater i søknad eller persongrunnlag så ønsker vi å fjerne dem.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt
Øker antall satsendringer per dag til 200 per halvtime
Endrer til å bruke page med antallFagsaker for å iterere gjennom satsendringer.
=> Antall satsendringer økes, og introdusert paging på hent satsendringer

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/TriggesAv.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/dataGenerator/brev/MinimertUtbetalingsperiodeDetalj.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/TriggesAvTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-11377
Vi har hatt en feil som kicker inn dersom vi har vi har utvidet på to barn der det ene har endring og det andre ikke er endret.
Dersom søker får utvidet og alle barna har delt bosted og pengene allerede er utbetalt til søker gjelder endringsbegrunnelse nummer 11.
Dersom søker får utvidet og kun noen av barna, men ikke alle, har delt bosted og pengene allerede er utbetalt til søker gjelder endringsbegrunnelse nummer 9. Dette er fordi det ikke er den endrede utbetalingen som gjør om søker får full utvidet barnetrygd. 
[Endringsbegrunnelse nummer 9](https://familie-brev.sanity.studio/ba-test/desk/begrunnelseBa;endretUtbetalingsperiode;e5b01952-7c6b-4ba4-b11c-1743efced182)
> Du har allerede …
=> Endre logikk for om begrunnelse skal trigges ved utvidet med og uten delt bosted

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt
Dobler frekvensen for satsendringsjobben fra hver halvtime til hvert kvarter
=> Endrer satsendringjobben til å kjøre hver 15 min

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveServiceTest.kt
Klarer ikke å endre behandlede enhet fordi oppgave allerede er ferdigstilt i gosys. 
Endrer slik at om oppgaven er en VurderLivshendelse-oppgaver lukker vi den bare i ba også. Ønsker ikke å lukke behandle sak oppgaver fordi vi er redde for at saken skal bli glemt av saksbehandler
=> Ferdigstill oppgaver som er ferdigstilt i Gosys

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskService.kt, src/main/resources/application.yaml, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendringTest.kt
- Autobrev starter 1 time tidligere for å bli ferdig til kl 8
- Øker maxantall som skal polles
- Flytter Transactional til opprettelsen av tasken, slik at også taskene opprettes i egen tråd fra scheduler. Dette fordi at taskene skal committes med engang og ikke i en bulk på 200.
=> Optimalisering av satsendring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt
Dagens økning i antall satsendringer. 400 * 6 * 10 = 24000 totalt
=> Skrur opp antall satsendringer

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendringTest.kt
Midlertidig filtrere bort satsendring for de med EØS-sekundærland. Man trenger å se nærmere på disse og nå stopper de opp på 
no.nav.familie.ba.sak.common.Feil: Resultat FORTSATT_INNVILGET er ikke støttet etter behandlingsresultat for satsendringsbehandling.
=> Midlertidig filtrere bort EØS sekundærland ved satsendring

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiKlient.kt
Legger på litt mer logging slik at det skal være lettere å finne tilbake til det eksterne kallet ble gjort
=> Legg på litt informasjon i logg

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt
Øker satsendringer til 600 per 10 minutt. Totalt 36000 per dag
=> Øker satsendringer til 600 per 10 minutt. Totalt 36000 per dag

.deploy/nais/app-prod.yaml
Øker antall podder i forbindelse med satsendring.
=> Skrur opp podder i forbindelse med satsendring

src/main/kotlin/no/nav/familie/ba/sak/internal/PreprodController.kt
=> Fiks at settFomPåTommeVilkårTilFødselsdato kan kjøres i preprod

src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringService.kt
Det ser ikke ut som vi får noe utbetalingsoppdrag for denne behandlingen selv om burde ha fått det. Legger til litt debugging  i et håp om å bli mer klok
https://barnetrygd.intern.nav.no/fagsak/1778531/2199950/simulering
=> Jeg skjønner ikke hva som skjer i prod så legger på midlertidig debugg

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringService.kt
Oppretter ferdigstill behandling eller iverksett mot oppdrag task ved satsendring avhengig av neste steg på behandlingen. Slik at det opprettes riktig task ved fortsatt_innvilget og eøs.
=> Oppretter ferdigstill behandling eller iverksett mot oppdrag task ved satsendring avhengig av neste steg på behandlingen

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringService.kt
Ferdigstill behandling krever at behandling status er IVERKSETT_VEDTAK. Så setter riktig status før satsendring.
=> Setter riktig behandlingstatus for å kjøre ferdigstill behandling for satsendring av eøs

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringService.kt
Har fått flere saker som stopper pga. utbetaling overstiger 100%, og noen av de skulle ikke ha slått ut. Legger på bedre logging for å se hvorfor dette skjer, da en gjennomgang av koden ikke viser noen logisk grunn.
Nei
Bare logging
=> Legg på logging av hvilke andeler man sammenligner for å sjekke om utbetaling overstiger 100%

src/main/kotlin/no/nav/familie/ba/sak/task/DistribuerDødsfallDokumentPåFagsakTask.kt
=> Forhindre at tasker opprettes

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/mottaker/Brevmottaker.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/mottaker/BrevmottakerService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/Logg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/mottaker/BrevmottakerServiceTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10505
Vi ønsker å opprette historikk innslag når vi legger til eller fjerner brevmottaker.
Se bilder av logginnslag:
=> Vi legger til logg innslag dersom brevmottaker legges til eller fjernes

.deploy/nais/app-prod.yaml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringStatistikk.kt
- Reduserer antall pods til 5 for å ikke bruke flere connections enn man har
- Logging av statistikk for satsendring
Config og logg
=> Redusering av max antall pods, logging satsendringstatistikk

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/test/integrasjonstester/kotlin/DevLauncherPostgresPreprod.kt
Kode bak toggle ble aldri brukt siden toggelnavnet ikke samsvarte med det i unleash (Hadde en \n på slutten 🙃)
Fikser det ☝️og gjør så vi går mot familie-brev i preprod når vi bruker DevPostgresPreprod
=> Fjern newline i toggle

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringStatistikk.kt
Task som var tenkt til å kjøres hver halvtime kjører langt oftere enn hver halv time. Endrer til å kjøre hver halvtime
=> Fikser feil i hvor ofte task kjører. Den kjørte langt oftere enn hver halvtime

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt
Legger på toggle på sjekken som avgjør om man skal gå til journalfør vedtaksbrev eller iverksett mot oppdrag etter beslutte vedtak. 
Ser også på om behandlingen skal sende ut et vedtaksbrev i samme sjekk
=> Flytt kode bak featuretoggle

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSøknadUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSøknadUtilsTest.kt
Endrer logikken for utledning av søknadsresultat når beløp går fra >0 kr til 0kr pga differanseberegning/endret utbetaling andel.
Tidligere: 
- Hvis nåværende beløp er 0kr så setter vi Innvilget/avslått (avhenig av årsak til 0kr) **uansett andelen var >0 kr eller ikke eksisterte i forrige behandling**
Nå:
- Vi setter kun Innvilget/avslått hvis andelen ikke eksisterte i forrige behandling, så det er snakk om en ny andel
- Hvis forrige beløp var større enn 0kr og vi nå har satt andelen til 0kr pga differanseberegning/endret utbetaling andel ønsker vi ikke at det skal reflekteres i søknadsresultatet (Endretresultatet tar seg av det)
| Andel i forrige behandling | Andel i nåværende behandling | Søknadsresultat                                                                    | …
=> Behandlingsresultat: bug med søknadsresultatet for andeler satt til 0kr

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSøknadUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatValideringUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatStegTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSøknadUtilsTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-11402
Nei
Kun tekstlige endringer
=> Behandlingsresultat: forbedre feilmeldinger til saksbehandler

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt
Migrering: Filtrerer bort sakstype med resultet henlagt i åpen sak sjekken mot infotrygd. Etter samtale med Birgitte
=> Filterer bort infotrygdsaker med resultat henlagt før migrering

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10717
Satt flagg behandlesAvApplikjsjon til FAMILIE_BA_SAK ved opprettelse av oppgave. Dette hindrer SB til å lukke oppgavene manuelt ved gosys for åpne behandlinger i ba-sak.
=> Satt flagg behandlesAvApplikjsjon til FAMILIE_BA_SAK ved opprettelse av oppgave

src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceEnhetstest.kt
=> la til mockk respons for findByFagsakAndAvsluttet

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt
favro; https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10717
Vi får feilmeldinger fra produksjon https://jira.adeo.no/browse/FAGSYSTEM-265870
Vurder livshendelse oppgaver som opprettes etter avbrutt autovedtak ved fødsel kan ikke ferdigstilles fra Gosys.
Det er kun vurder livshendelse som er tilknyttet en åpen behandling i BA-sak som skal ha "behandles av applikasjon" flagg. De andre vurder livshendelse oppgavene må kunne ferdigstilles fra Gosys.
_Har du husket …
=> setter ikke behandlesAvApplikasjon for VurderLivshendelse oppgaver

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt
Logg for å debugge satsendringer som stopper opp med melding "fom og tom innenfor samme kalendermåned"
=> Logg for debugging av valideringsfeil ved satsendring

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelerTilkjentYtelseOgEndreteUtbetalingerService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/RevurderingMedEndredeUtbetalingandelerTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-11746
Fjerner toggle som har vært på lenge i prod.
Nei
Fjerner bare en toggle
=> Chore: fjern toggle for frikobling av andeler og endringer

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/EndringstidspunktService.kt
Legger på logger for å skjønne hvordan resultatet av endringstidspunkt har blitt som det har blitt.
Nei
=> Legg på logger så vi kan se utledningen av tidligste endringstidspunkt

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/Behandlingsresultat.md, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/domene/Kompetanse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIKompetanseUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIKompetanseUtilTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeUtilTest.kt
FAvro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-11836
Hvis forrige kompetanse ikke var utfylt ordentlig pga migrering (og eventuelle autovedtak) så ønsker vi ikke at det skal bli returnert "endring".
Nei
=> Bug: endring i kompetanse

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/DummyFeatureToggleService.kt, src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt
Fjerner toggle for funksjonalitet som har lenge vært på i prod uten problemer.
Frontend: https://github.com/navikt/familie-ba-sak-frontend/pull/2553
Nei
Fjerner bare en toggle
=> Chore: Fjerner toggle for trekk i løpende utbetaling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIVilkårsvurderingUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIVilkårsvurderingUtilTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-11846
Nei
=> Bug: endring i vilkårsvurdering hvis SB aldri har manuelt vurdert saken

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/VurderTilbakekrevingStegTest.kt
=> Fikser tester som feilet etter månedskifte

src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/VurderTilbakekrevingStegTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceIntegrasjonTest.kt
Fjerner midlertidig Disabled fra tester som ikke kjørte
=> Fjerner midlertidig disabled etter at testene har blitt fikset

src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceEnhetstest.kt
Skyldes denne: https://github.com/navikt/familie-ba-sak/pull/3390
Skjønner ikke hvordan testen har passert på PRen, men feiler etter merge 🤔
Nei
Retter opp test:)
=> Rett opp test som feiler

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-11481
Dropper steget "registrer mottaker"/"registrere institusjon og verge" hvis saken er av typen enslig mindreårig. 
Nei.
Jeg tenker det er unødvendig 🤷‍♂️
=> EM: fjern registrer mottaker steget

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequestTest.kt
Oppfølging av #3423 
Legger til tester + gjør en omskriving som Ida ba om 😇 
=> Legg til tester og omskriv validering av mottakerland SED for årlig kontroll EØS

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt
Knyttet til denne: https://github.com/navikt/familie-ba-sak-frontend/pull/2571
Hvis antall uker svarfrist ikke er satt er det saksbehandler som har klart å gjøre noe feil.
Nei
Unødvendig? 🤷‍♂️
=> Chore: Kast funksjonell feil i stedet for feil hvis antall uker svarfrist ikke er satt

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/InternKonsistendsavstemming/InternKonsistensavstemmingScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/InternKonsistendsavstemming/InternKonsistensavstemmingService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/InternKonsistendsavstemming/InternKonsistensavstemmingUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyController.kt, src/main/kotlin/no/nav/familie/ba/sak/task/InternKonsistensavstemmingTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/InternKonsistendsavstemming/InternKonsistensavstemmingUtilTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-11936)
Legger på scheduler så intern konsistensavstemming kjøres en gang i måneden.
Fikser også en del småting. 
Leses gjerne commit for commit
=> Lag intern konsistensavstemming scheduler

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt
Sørger for at migrering av institusjon også kjører behandlingssteget RegistrerInstitusjonOgVerge slik at migrerinssaker får Registrer Mottaker-skjermbildet
Trenger å teste i miljø at vanlige Institusjon-saker oppfører seg som før etter endring
=> Endrer første steg for institusjon til å være RegistrerInstitusjonOgVerge

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/internkonsistensavstemming/InternKonsistensavstemmingScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/internkonsistensavstemming/InternKonsistensavstemmingService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/internkonsistensavstemming/InternKonsistensavstemmingUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/task/InternKonsistensavstemmingTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettInternKonsistensavstemmingTaskerTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/internkonsistensavstemming/InternKonsistensavstemmingUtilTest.kt
Rename av pakken `InternKonsistendsavstemming` til `internkonsistensavstemming`
=> rename av pakkenavn

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BegrunnelseUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/RestBehandlingsgrunnlagForBrev.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeUtilTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevperiodeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceUtilsTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12222
Sørger for at man finner søkers ident, som = barnets ident ved enslig mindreårig saker.
Nei
Unødvendig 🤷‍♂️
=> Bug: klare å vise begrunnelse for enslig mindreårig

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSøknadUtils.kt
Denne feilen i sentry har dukket opp et par ganger, men det gir ikke mening at den dukker opp. Skal ikke være mulig å sette andel til 0kr hvis det ikke eksisterer endret utbetaling andel eller differanseberegning:
Når jeg går inn på saken så finner jeg ingen andel med 0kr. Logger derfor mer info så vi kan skjønne hvordan det har skjedd
Nei
Bare logging
=> Chore: Logg mer info om hvilken andel som er satt til 0kr

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingValidering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingStegTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/RevurderingMedEndredeUtbetalingandelerTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12264
Det må eksistere en periode på under 18-vilkåret som starter på fødselsdatoen til personen. Legger på validering som sikrer dette.
Anna har godkjent teksten.
Syns logikken er såpass triviell. Har testet manuelt. Si ifra hvis noen likevel mener jeg skal skrive tester, det er helt fair 🤗
=> Legg på validering som sikrer at under 18 vilkåret er vurdert fra fødselsdato

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregnAndelerTilkjentYtelseMedGjeldendeSatserTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/VilkårTilTilkjentYtelseTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/VilkårVurderingBuilder.kt
Unødvendig å utlede ytelsetypen, når vi vet at vi genererer andeler for barna (altså ordinær andel).
Nei
Endrer ikke på noen logikk. Eksisterende tester er dekkende.
=> Chore: Hardkode ytelsetypen til Ordinær for barnas andeler

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/internkonsistensavstemming/InternKonsistensavstemmingScheduler.kt
=> Start intern konsistensavstemming 29. i måneden

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/domene/OppgaveRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt
Endepunkt for å få gjenåpnet en ferdigstilt oppgave. Denne skal brukes for å gjenåpne/klone de feilaktige lukket oppgave i forbindelse med henlegg behandling
Tar en liste med behandlinger inn med oppgavetype. Sjekker om den er ferdigstilt i denne perioden og oppretter en lik oppgave som den ferdigstilte oppgaven. Altså en kloning.
Manuell testing preprod før prod
=> Endepunkt for å gjenåpne oppgave av spesifisert type, på en gitt dato.

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt
Alle saker som skulle gjenåpnes havnet i ignore pga tull i hodet da jeg skulle sjekke om temaet var BAR og riktig oppgavetype
=> Feil i sjekk som gjorde at alle gjenåpninger ble ignore

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/domene/OppgaveRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/HenleggBehandling.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt
- Støtte for flere oppgaver av samme type ved gjenåpning av oppgave
- Sørger for at henlegg behandling for satsendring ikke lukker sakstyper som ikke er BehSak
=> Fiks bug i gjenåpne opppgave og henlegg behandling pga satsendring

src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/AndelTilkjentYtelseOffsetTest.kt
Test som feilet pga ny måned og satsendring
=> Fikser som feiler pga satsendring

.github/workflows/build-and-deploy-prod.yml
=> Prøver  å ta med outputs fra prepro ved deploy prod

src/main/kotlin/no/nav/familie/ba/sak/task/DistribuerDokumentPåJournalpostIdTask.kt
Støtte for gammel kontrakt for tasker distribuerDokumentPåFagsak. Som er på format
{"journalpostId":"6124542145","brevmal":"VEDTAK_OPPHØR_DØDSFALL"}
=> Støtte for gammel kontrakt for tasker distribuerDokumentPåFagsak

.deploy/nais/app-preprod.yaml, .deploy/nais/app-prod.yaml
Endrer cpu og minne limit til å følge blogposten som er postet på #nais-announcements: 
Slacktråd: https://nav-it.slack.com/archives/C01DE3M9YBV/p1680172494569329
Bloggpost om CPU: https://home.robusta.dev/blog/stop-using-cpu-limits
Bloggpost om minne: https://home.robusta.dev/blog/kubernetes-memory-limit
=> Fjern cpu limit. Sett minne limit lik request

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt
Endepunkt for å trigge en søk etter fagsaker som det ikke er kjørt satsendring på. Logger resultatet til log
=> Finn fagsaker uten siste sats

.deploy/nais/app-preprod.yaml, .deploy/nais/app-prod.yaml
=> Lagt til ECB i outbound rule

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt
Etter oppgradering får man org.springframework.dao.DataIntegrityViolationException:
The column index is out of range: 1, number of columns: 0
Virker som man må ha med en kolonne i inner selecten
=> Native query for satsendring funker ikke i spring boot 3

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/AvstemmingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingHentOgPersisterService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/KonsistensavstemMotOppdragStartTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/KonsistensavstemmingTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/KonsistensavstemMotOppdragStartTaskTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/KonsistensavstemmingUtplukkingIntegrationTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12386
- Henter alle behandlinger i en spørring for å unngå at man får duplikate behandlinger over flere sider
- Gjør om lista med behandlinger til Set i tillfelle duplikate behandlinger i lista.
=> Unngå paging på konsistensavstemming, og fjern evt duplikater

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt
Fjerner spørringer som ble brukt i forbindelse med offset-feilen. Ingen av disse brukes lenger.
Nei
Fjerner bare ubrukt kode
=> Chore: Fjern spørringer som ikke brukes

pom.xml
* Fjerner awaitility-kotlin som ikke er i bruk
* Tar i bruk wiremock direkte, i stedet for via spring-cloud-contract-wiremock
- [x ] Nei
=> Liten opprydding i dependencies

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForGjeldendeOgForrigeBehandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForPerson.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForVedtaksperioder.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/VedtaksperiodeProdusent.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeMedBegrunnelserStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/domeneparser/DomeneparserUtil.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/vedtaksperiode_begrunnelse_sammenlign_mot_forrige_behandling.feature
=> Sammenligne mot forrige behandling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForVedtaksperioder.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/vedtaksperiode_kompetanser.feature
=> Legg til støtte for kompetanser uten tom

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForPerson.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForVedtaksperioder.kt
=> Gjør andeler for vedtaksperiodegrunnlag ikke-nullable.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForPerson.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForVedtaksperioder.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/VedtaksperiodeProdusent.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/RevurderingMedEndredeUtbetalingandelerTest.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/vedtaksperiode_avslag.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/vedtaksperiode_kompetanser_to_barn.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/vedtaksperiode_vilkår.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/vedtaksperiode_vilkår_to_barn.feature
Vi har hatt en misforståelse der vi har trodd av ikke-innvilgede perioder for personer skal lage egne vedtaksperioder med mindre de har samme fra-og-med og til-og-med dato som de innvilgede periodene etter at de var kombinert. Dette stemmer ikke. 
De egentlige reglene er at de innvilgede og de ikke-innvilgede periodene for enkeltpersoner i en periode alltid skal slås sammen når vi lager vedtaksperioder, med unntak av ikke-innvilgede perioder der vi har et eksplisitt avslag i vilkårene. Dersom vi har eksplisitte avslag skal de kun slås sammen med periodene til de andre personene dersom fra-og-med datoen er lik, til-og-med datoen er lik og det ikke er noen innvilgelser i samme periode. Se bildet under for eksempler: 
Forklaring av vedtaksperiodene: 
Periode 1: Vi ville bare begrunnet …
=> Kombiner ikke-innvilgede perioder med innvilgede. Lag egne perioder for eksplisitte avslag.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceEnhetstest.kt
Fikser test som feiler i master 🤔
=> Justere refusjon eøs delmal tekst

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingService.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiTestUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingStegTest.kt
Sett disse nå flere ganger så tenker det er like bra å bare fjerne de
`MANUELL_VURDERING` finnes ikke i dev eller prod, og er ikke i bruk, burde også fjernes fra kontrakter? 
=> Fjerner ubrukte metoder og felter

src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/vedtaksperiode_avslag.feature
Vil legge til tester for avslag på søker slik at vi forsikrer oss mot å brekke funksjonalitet på det fremover.
=> Legg til test for avslag på søker.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/mottaker/BrevmottakerController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/mottaker/BrevmottakerService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/mottaker/BrevmottakerControllerTest.kt
Denne endepunkten ble aldri tatt i bruk
=> Brevmottakere fjerner ubrukt endepunkt

.github/workflows/build-pr.yml, pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForVedtaksperioder.kt
Fjerner maven plugins som ikke lenger er i bruk
=> Fjerner jacoco og sonar som ikke lenger er i bruk

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeMedBegrunnelser.kt
=> Skal ikke vise utbetaling i en avslagsperiode.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingStegController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/UtvidetBehandlingController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/mottaker/BrevmottakerController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/utenlandskperiodebeløp/UtenlandskPeriodebeløpController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/ValutakursController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/rest/TidslinjeController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/korrigertetterbetaling/KorrigertEtterbetalingController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/korrigertvedtak/KorrigertVedtakController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/småbarnstilleggkorrigering/SmåbarnstilleggKorrigeringController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/feilutbetaltValuta/FeilutbetaltValutaController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeHentOgPersisterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeMedBegrunnelserController.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/ValutakursControllerTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/utenlandskperiodebeløp/UtenlandskPeriodebeløpControllerTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeRepositoryTest.kt
Her var det flere controllers som manglet tilgangskontroll. 
Sånn at man risikerte å få ut informasjon til kode6-brukere selv om man ikke har tilgang
Hvordan tilgangskontroll burde gjøres i `VedtaksperiodeMedBegrunnelserController`
=> Legger til manglende Tilgangskontroll i controllers

.deploy/nais/app-preprod.yaml, .deploy/nais/app-prod.yaml
Mangler meldinger i sentry. Prøver å legge til sentry i outbound.
=> Legger til sentry i outbound

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForVedtaksperioder.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/vedtaksperiode_vilkår.feature
Vi må begrunne eksplisitte avslag på søker selv om det ikke finnes noen barn i perioden. 
=> Ikke avgrens søker sine vilkår etter barn ved eksplisitt avslag

.deploy/nais/kafka/dev/dvh_vedtak_topic.yaml, .deploy/nais/kafka/prod/dvh_vedtak_topic.yaml
Dvh lager en ny app for å konsumere stønadsstatistikk. Gir tilgang til denne.
=> Gir tilgang til ny app som skal konsumere stønadsstatistikk

.github/workflows/manual-deploy-kafka-aiven.yml
=> fikser deploy script

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/VedtaksperiodeProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/vedtaksperiode_avslag.feature
Når vi har avslag og opphør i samme periode skal vi få en opphørsperiode
Blir dette riktig logikk? 
=> Perioder som er avslag og opphør med samme fom og tom skal slås sammen

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt
Mer validering på NAV-12506. Ignorerer de med småbarnstillegg og delt bosted. 
=> Validering om at man ikke fikser automatisk de med delt bosted eller småbarnstillegg

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/sanity/CachedSanityKlient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/sanity/SanityKlient.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DbContainerInitializer.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/SanityKlientMock.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/datagenerator/behandling/KjørRevurdering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevperiodeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/SanityKlientTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/StandardbegrunnelseTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeUtilTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/config/AbstractSpringIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/AbstractVerdikjedetest.kt
Legger inn sanity-kall i en klass.
Lager en singletoninstans for tester, som cachear resultatet fra sanity for å unngå at man kaller sanity flere ganger i tester
~Oppgraderer postgres til 15, som nå er tilgjengelig fra GCP~
=> Legger inn henting av sanity-data i en klass

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForVedtaksperioder.kt
Vi har en feil som jeg ikke skjønner noe av. Klarer ikke å reprodusere den lokalt så legger til logging
=> Legg til logging i produsering av vedtaksperiode

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt
Etter at storparten av sakene er fikset, så har jeg en håndfull til som kan likevel kan fikses ved å ikke sjekke forrige behandling. Så fjerner litt validering. Gjør valideringen manuelt før fiks
=> Fjerner validering for å fikse noen saker til

src/main/kotlin/no/nav/familie/ba/sak/ekstern/tilbakekreving/FagsystemsbehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/VedtakRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/VedtakService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/ekstern/tilbakekreving/HentFagsystemsbehandlingRequestConsumerTest.kt
Trenger kun å hente vedtaksdatoet på flere steder, så henter kun det der det trengs
=> Forbedring: Henter kun vedtaksdato der det er ønskelig

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/sanity/SanityQueries.kt
Vi har byttet ut feltet "behandlingstema" med "tema" for å organisere sanity-begrunnelser. Nå som alle tekstene har fått feltet "tema" fylt ut kan vi gå over til å benytte oss av det i stedet for det gamle behandlingstema.
=> bruk tema og ikke behandlingstema når man henter begrunnelser fra sanity

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12449
Vi legger til begrunnelser som trengs for praksis endring eøs funksjonaliteten.
=> Legg til praksis endring eøs begrunnelser

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt
=> 1000 satsendringer per 10 min

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt
=> Øker til 1200 satsendring per 10 min

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringStatistikk.kt
En tips fra Joh an som kanskje fikser oppdatering av metrikker for satsendring
=> Setter overwrite på metrikker i satsendring for å se om den oppdateres oftere

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringServiceTest.kt
* Henter ikke aktører på nytt når man allerede har de fra andeler
=> Forbedring av finne aktører som har ugyldig etterbetalingsperiode

.github/workflows/codeql.yml
=> Tester codeQL

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt
Setter ned litt utenfor arbeidstid. 1200 per 5 min var litt for mange for ba-sak
=> Finjusterer antall satsendringer utenfor arbeidstid

.deploy/nais/app-preprod.yaml, .deploy/nais/app-prod.yaml, src/main/resources/application.yaml
Ser ut til at ECB har fått ny URL
=> Bytter url til Valutakurs

.github/workflows/codeql.yml
Skrur av CodeQL til å kun kjøre på master og  ikke ved hver PR pg push. 
https://nav-it.slack.com/archives/C01G9BA8JKZ/p1687505020991449
=> Skrur av codeql i brancher

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/EndringsTidspunktUtil.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-13762
Bug ved revurdering av saker der vi ikke får med oss endringer i andeler.
Skal legge til tester i ny PR når vi fjerner toggle
=> sammenlign andeler ved utledning av endringsTidspunkt

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/EndringsTidspunktUtil.kt
Vi opplever litt feil utleding av endringstidspunktet. Legger til litt logging slik at vi kan feilsøke enklere.
=> Logg endringer for endringstidspunktet

src/main/kotlin/no/nav/familie/ba/sak/sikkerhet/AuditLogger.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/sikkerhet/AuditLoggerTest.kt
Endringen er testet i preprod i familie-klage og merget: https://github.com/navikt/familie-klage/pull/336
Endringen er gjort på forespørsel fra Roger Dybdal: https://nav-it.slack.com/archives/CH4NLKAR0/p1689077799460959
=> Auditlogger: Logger navn på produktområde da det gir mer mening for brukerne som ikke har noe forhold til hver enkelt app

src/main/kotlin/no/nav/familie/ba/sak/sikkerhet/AuditLogger.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/sikkerhet/AuditLoggerTest.kt
Ref: https://nav-it.slack.com/archives/CH4NLKAR0/p1689237228023819?thread_ts=1689077799.460959&cid=CH4NLKAR0
=> Bugfix: Fjerner en header som ikke lenger skal være med etter det ble lagt til navn på PO

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt
Reverts navikt/familie-ba-sak#3771
Henning og jeg tok feil angående hva logikken skulle ha vært her 😇
=> Revert "Autovedtak fødselshendelse: behandlingstype kan ikke være førstegangsbehandling dersom fagsak har status avsluttet"

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/ForsattInnvilget.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/Førstegangsvedtak.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/OpphørMedEndring.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/VedtakEndring.kt
Fjerner deprecatede felter. Se [her](https://github.com/navikt/familie-ba-sak/pull/3795) for mer informasjon.
Er testa i preprod: https://github.com/navikt/familie-ba-sak/actions/runs/5782440695/job/15669259379
=> Fjern deprecatede felter

.deploy/nais/app-preprod.yaml, .deploy/nais/app-prod.yaml
Anbefalning fra NAIS om å fjerne cpu-limits: https://nav-it.slack.com/archives/C01DE3M9YBV/p1680172494569329
=> fjerner cpu-limit etter anbefalning fra nais-teamet

.deploy/nais/app-preprod.yaml, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelseRepository.kt
Trekker ut repo metode fra https://github.com/navikt/familie-ba-sak/pull/3583 og laget endepunkt for å sammenligne ny med gammel måte å hente offset.
=> Nyoffset test

pom.xml
bumpe versjoner på det som kan bumpes så vi holder oss oppdatert :) 
Er det noen pakker vi ikke burde bumpe? Har f.eks. latt være å bumpe unleash siden vi venter på unleash-next
=> bump versjoner

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/SanityBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/VilkårFilterUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/domeneparser/VedtaksperiodeMedBegrunnelserParser.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/brevbegrunnelse_vilkår.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/utdypende_vilkårsvurdering_reduksjon.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/utdypende_vilkårsvurdering_utbetaling.feature
Vi må filtrere på utdypende vilkårsvurdering når vi skal finne relevante begrunnelser. 
Legger på ekstra logikk for å filtrere utdypende vilkår. 
Endrer også på følgende: 
**Filtrerer på periodetype**
I Sanityoppsettet skiller vi mellom begrunnelser som gjelder `INNVILGET_ELLER_ØKNING`, `INGEN_ENDRING`, `IKKE_INNVILGET` eller `REDUKSJON`. Filtrerer så kun `INNVILGET_ELLER_ØKNING` kan komme med for en person dersom personen har innvilget i perioden, `IKKE_INNVILGET` og `REDUKSJON` dersom personen ikke har innvilget og `Reduksjon` dersom personen ikke har noen vilkår i perioden. 
I tillegg kan reduksjonstekster som gjelder delt bosted som skal deles komme med dersom personen har innvilget i perioden fordi personen fremdeles har utbetaling om barnetrygden reduseres fordi den er delt. …
=> Begrunnelse filtrering utdypende vilkårsvurdering

.deploy/nais/app-preprod.yaml, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DbContainerInitializer.kt
=> Oppgraderer til postgres 15 i dev

.github/workflows/build-and-deploy-prod.yml, .github/workflows/codeql.yml, README.md
Ønsker å rename master-branchen til main siden vi har det på de fleste andre applikasjonene våre
Er det noe jeg ikke har tenkt på som også bør renames?
=> Rename master-branch til main

src/main/resources/application-prod.yaml
Trenger å kunne teste med forvalterrollen i prod
=> Legger inn riktig forvaltergruppe i prod

src/main/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/HentAlleIdenterTilPsysResponseDTO.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/producer/KafkaProducer.kt, src/main/kotlin/no/nav/familie/ba/sak/task/HentAlleIdenterTilPsysTask.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/FinnIdenterMedLøpendeBarnetrygdForGittÅrTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-14562
* Det er lagt til tester for repository query (identer som har hatt barnetrygd i løpet av angitt år)
* Det er lagt til start og slutt melding i kafka-meldinger til pensjon (med identer som har hatt barnetrygd i løpet av angitt år)
=> Nav 14562 pensjon integrasjon

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt
=> Legger til callid på forvaltertjeneste

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/VilkårFilterUtil.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/utdypende_vilkårsvurdering_utbetaling.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-14648)
Slik koden er nå får vi det ikke begrunnet tilfellene der vi beholder et vilkår, men de utdypende vilkårene endrer seg. Endrer så begrunnelsene knyttet t il utdypende vilkårsvurdering dukker opp. 
=> Få med begrunnelser som endrer utdypende vilkårsvurdering i periode

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt
Endrer ene endepunktet til å ta inn en liste med behandlinger, itererere alle disse og returnerere en liste med de som ikke har korrekt opphørsdato
=> Endrer forbalterendepunkt til å ta inn en liste i stedet for en behandling

src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyService.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/begrunnelser/LagGyldigeBegrunnelserTestUtil.kt
Lager testverktøy for å hente test om gyldige begrunnelser for en behandling. 
Dette gjør det mulig å hente en cucumbertest fra localhost eller preprod via endepunktet 
`{{host}}/internal/behandling/{{behandlingId}}/begrunnelsetest`
=> Lag verktøy for å kunne hente test på gyldige begrunnelser fra en behandling

src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/begrunnelser/LagGyldigeBegrunnelserTestUtil.kt
Gjør så vilkår resultatene fra gyldig begrunnelse test generatoren blir sortert på fra-og-med-datoen og slått sammen
For eksempel er GIFT_PARTNERSKAP-, BOSATT_I_RIKET-, LOVLIG_OPPHOLD- og BOR_MED_SØKERvikårene slått sammen side de har samme data her:
=> Sorter vilkårresultater etter fom dato og slå sammen like vilkårresultater

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BegrunnelseGrunnlagForPersonIPeriode.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/mangler_data_person.feature
[Favro ](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-14708)
Nå får vi en feil i periodene der vi ikke har data på et barn. For eksempel i periodene det ikke var født. Fikser så vil lager en tom data klasse for personer uten data i perioden. 
=> Fiks feil der vi ikke fikk data på barn i periode det ikke var født

.deploy/nais/app-preprod.yaml, .deploy/nais/app-prod.yaml, .deploy/nais/kafka/dev/aapen-familie-ba-sak-identer-med-barnetrygd.yaml, .deploy/nais/kafka/prod/aapen-familie-ba-sak-identer-med-barnetrygd.yaml, src/main/kotlin/no/nav/familie/ba/sak/config/PensjonConfig.kt
+ gitt tilgang til riktig app i controller også
=> Lagt inn riktig app i acl for kafka(identer med barnetrygd) 

src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyService.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/begrunnelser/LagGyldigeBegrunnelserTestUtil.kt
Oppdaterer testverktøyet for å lage gyldig begrunnelser test. 
* Flytt data fra forrige behanding over denne behandlingen. 
* Gjør så vi lager personresultat for forrige behandling. 
* Bruker riktig id for andeler forrige behandling.
=> Oppdaterer testverktøyet for å lage tester for gyldige begrunnelser

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt
endepunkt for å får rekjørt med en annen versjon enn 1 i oppdrag
=> Mulighet til å sende med versjon på patcheendepunktet for en enkelt behandling for opphørsfiks

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt
Får feilmelding når vi sier vi har sendt inn ny linje og linja allerede er sendt inn for fagsak tidligere. Forsøker å endre til at alle linjene er "ENDR".
=> Setter alle perioder til erEndringPåEksisterendePeriode

src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/begrunnelser/LagGyldigeBegrunnelserTestUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BegrunnelseGrunnlagForPeriode.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/VilkårFilterUtil.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/revurdering_med_opphør.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/test.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-14675)
Nå feiler begrunnelseløypa dersom vi opphører i en revurdering fordi vi får splitt på forrige behandling midt i opphørsperioden. Endrer så vi kun tar med data fra forrige behandling når vi har reduksjon på tvers av behandlinger. 
=> Bugfix/begrunnelser opphør revurdering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/VilkårFilterUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/reduksjon_utvidet.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-14845)
Legger til støtte for begrunnelser for redukjson av utvidet barnetrygd
=> Legg til støtte for reduksjon i utvidet barnetrygd

src/main/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/PensjonController.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/PensjonService.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-14562
Endre returtype for pensjon-endepunkt for personer med barnetrygd til string (fra UUID)
=> NAV-14562- Endre returtype for pensjon-endepunkt til string

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt
Venter med å merge denne til endelig avklaring fra Steinar.
=> Sender kun de korrigerte utbetalingsperiodene

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/VilkårFilterUtil.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/brevbegrunnelse_vilkår.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-14930)
Dersom vi mister et vilkår skal ikke innvilgelsesbegrunnelsene komme for det vilkåret. 
Fikser så vi sammeligner periodeResultatet på begrunnelsene og om vi får eller mister vilkår
=> Gi riktige begrunnelsertyper når vi mister eller får vilkår

.deploy/nais/app-prod.yaml
DENNE MÅ IKKE MERGES FØR DATABASEN ER OPPGRADERT!
Gjør klar for oppgradering av database til søndag
https://github.com/navikt/familie/blob/master/doc/Google%20cloud/oppgrader-database.md 
DENNE MÅ IKKE MERGES FØR DATABASEN ER OPPGRADERT!
Fremgangsmåte testet i preprod, og preprod/prod for migrering
=> Oppgraderer postgres spec til 15 i nais. Denne må inn etter oppgradering

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/UtgjørendeVilkårUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevperiodeData.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseType.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeMedBegrunnelser.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/domene/UtvidetVedtaksperiodeMedBegrunnelser.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/VedtaksperiodeProdusent.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/datagenerator/behandling/KjørRevurdering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevperiodeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksbegrunnelseTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtvidetVedtaksperiodeMedBegrunnelserTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/EndringstidspunktTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/ReduksjonFraForrigeIverksatteBehandlingTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/RevurderingDødsfallTest.kt
Fjerne vedtaksperiode_ny togglen siden den har vært enabled i prod en god stund og fungerer greit.
=> fjern vedtaksperiode_ny toggle

src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/domene/EndretUtbetalingAndel.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/VedtaksperiodeGrunnlagForPerson.kt, src/main/resources/db/migration/V250__fjern_begrunnelser_fra_endret_utbetaling_andel.sql, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
Fjerner vedtaksbegrunnelser fra EndretUtbetalingAndel
=> Fjern vedtaksbegrunnelser fra EndretUtbetalingAndel

src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/reduksjon_fra_forrige_behandling.feature
Rydder opp etter PR-tilbakemelding i #3922 😊 Endrer behandlingsId og aktørId fra reelle preprod-data til kunstige verdier
=> Generaliser behandlingsid og aktørid i begrunnelsestest

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Etter diskusjon ønsker vi å endre på apinavnet til denne begrunnelsen.
=> Endre på apinavn

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/kompetanser.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15080)
Gjør så vi sender med opphørsbegrunnelser for barn i perioder der barnet ikke har noen andeler knyttet til seg. Ser også på kompetanse for forrige periode dersom det opphør eller reduksjon. 
=> Legg til støtte for opphørsbegrunnelser for eøs

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingMigreringUtils.kt
Favro: [NAV-14535](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-14535)
Har ikke klart å finne ut nøyaktig hvorfor det feiler, så legger til litt logging rundt der feilen oppstår for å enklere kunne debugge videre.
=> Lagt til logging for å kunne debugge feil ved opprettelse av "Endre migreringsdato"-behandling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favro: [NAV-15319](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15319)
Vi ønsker å legge til flere endret utbetalingsbegrunnelser.
=> Legg til nye endret utbetalings begrunnelser

src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/begrunnelser/LagGyldigeBegrunnelserTestUtil.kt
Oppdaterer endepunktet som gir oss tester. 
* Endrer formatet på nådatoen
* Legger til feltene "Behandlingsresultat" og "Behandlingsårsak" på behandling
=> Oppdater test begrunnelse generatoren

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15523
For reduksjon og opphørstekster fra forrige behandling må vi også bruke lista som er filtrert på rolle OG fagsaktype.
=> Vi ønsker å filtrere ut reduskjon og opphørstekster fra forrige behandling basert på filtrertPåRolleOgFagsaktype

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15566
=> Legg til ny etter endret utbetaling begrunnelse

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevEøsBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevPeriodeProdusent/BrevPeriodeProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/VedtaksperiodeGrunnlagForPerson.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/Landkoder.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BrevPeriodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/domeneparser/BrevPeriodeParser.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/kompetanser.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/kompetanser.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/vilkår.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15585)
Legger til løype for å lage eøs-begrunnelser som skal sendes til familie-brev med det nye oppsettet
=> Legg til ny løype for å lage eøs-begrunnelser som skal sendes til familie-brev

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/SanityBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/SanityEØSBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/FortsattInnvilgetFilter.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/VedtakBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/forstatt_innvilget.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15590)
Lager egen løype når vi finner gyldige begrunnelser når vedtaksperiodetypen er fortsatt innvilget. I denne løypa bryr vi oss kun hva vi har i denne perioden, og ikke hva vi hadde i forrige periode eller behandling. 
=> Lag egen løype for gyldige begrunnelser fortsatt innvilget

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Favro: [NAV-15586](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15586)
Lagt til manglende EØS-begrunnelser tilknyttet praksisendring
=> Lagt til nye EØS-begrunnelser tilknyttet praksisendring

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt
Etter at stønadTom er ferdig populert på tilkjent_ytelse, så kan denne merges ned. Tar i bruk ny query uten sjekk på utebetalingsoppdrag for å finne hvem man skal fjerne løpende flagget på.
=> Tar i bruk ny query for finnFagsakerSomSkalAvsluttes

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeGenerator.kt
Vi fikser TOM ved ingen utbetaling, ref standup.
=> Vi fikser TOM ved ingen utbetaling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeGenerator.kt
Vi sjekker om tom er null først, flytter opp tom sjekken i when
=> Fiks presedens på null tom sjekk

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevEøsBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevPeriodeProdusent/BrevPeriodeProdusent.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15412
Løser foreløpig dette for den nye løsningen som kommer senere i løpet.
Tenker det er greit da dette ikke er prioritert til lansering.
=> Legg til antallbarn basert på barn med utbetaling i brevperiode

src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/begrunnelser/LagGyldigeBegrunnelserTestUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/BehandlingsGrunnlagForVedtaksperioder.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/institusjon.feature
For enslig mindreårig bruker vi samme person som søker og barn. Når vi da har endret utbetaling får vi feil siden vi ikke har noen utbetaling som er spesifikk for søker. Vi får derfor en feil på at vi har har endret en utbetaling på personen uten å ha innvilget noen utbetaling på personen (som søker). 
Endrer så vi ikke kaster feil i disse tilfellene.
=> Fiks feil ved endret utbetaling på institusjonssak

src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/KontrollerNyUtbetalingsgeneratorService.kt
Lagt til litt mer detaljert logging på kontrollerNyUtbetalingsgenerator.
=> Lagt til litt mer detaljert logging på kontrollerNyUtbetalingsgenerator

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Favro: [NAV-15586](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15586)
=> Lagt til ny avslagsbegrunnelse for selvstendig rett EØS

src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyService.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/vedtaksperioder/LagVedtaksperiodeTestUtil.kt
Temmelig klipp og lim fra `lagGyldigeBegrunnelserTest` med de endringene som er mellom testene
=> Lag testgenerator for vedtaksperiodetester

src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/KontrollerNyUtbetalingsgeneratorService.kt
Er kun interessert i antall andeler tilkjent ytelse som finnes neste måned
=> Teller kun andeler etter dagens dato ved logging

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/VedtaksperiodeProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/brev_periode_type.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/endret_utbetaling.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/endret_utbetaling.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15562)
Vi skal ikke slå sammen perioder som er endret til 0%, kun de som har vilkår som ikke er oppfylt.
=> Kun slå sammen vedtaksperioder uten innvilgede vilkår

src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BrevPeriodeUtil.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/innvilgete-vilkår.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-14673)
Legg til tester på flettefelt for innvilgete begrunnelser slik at vi har tester som feiler dersom vi endrer noe. 
Fikse slik at beløp med 'unbreakable whitespace' ikke feiler på .equals()
=> legg til tester for flettefelt på innvilgelsesbegrunnelser

src/main/kotlin/no/nav/familie/ba/sak/common/Utils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/UtilsTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15881
Vi ønsker stor forbokstav i alle navn når vi sender ut vedtaksbrev (opphør ved dødsfall)
Før
`HENSE-RAVNEN HOPP` -> `Hense-ravnen Hopp`
Etter
`HENSE-RAVNEN HOPP` -> `Hense-Ravnen Hopp`
=> Vi ønsker stor forbokstav i alle navn, vi manglet stor bokstav på navn etter bindestrek

src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValideringTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15724
Nå som vi har nye endret utbetalingsårsaker så ønsker vi å legge til validering på dette, siden dersom SB velger feil årsak til feil tid kan dette føre til feil i utbetaling og feil i vedtaksbrev.
=> Vi legger til validering for våre nye endre utbetalings årsaker

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/UtgjørendeVilkårUtils.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/opphør_samme_måned.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15571)
Når et vilkår er oppfylt i kun en måned ønsker vi fortsatt å finne personen som begrunnelsen hører til. 
La til test for ny løsning og fix for gammel
=> Vilkår som blir oppfylt og opphørt i samme måned skal fortsatt flette inn person i begrunnelse

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15973
Nye eøs praksisendring begrunnelser.
=> Nye eøs praksisendring begrunnelser

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/endret_utbetaling_med_reduksjon.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15751)
Manglet en begrunnelse i Standardbegrunnelse.kt, la den til
=> legg til endretUtbetalingReduksjonEndreMottaker i Standardbegrunnelse.kt

pom.xml
=> Oppgrader en del pakker

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16034
Legger til ny begrunnelse for endret utbetaling periode.
Nei
Legger bare til begrunnelse
=> Legg til begrunnelse for endret periode for selvstendig rett etterbetaling utvidet

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/VedtakBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/VilkårFilterUtil.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/kombinasjon_av_vilkår_og_endretutbetaling.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16025
Vi har noen begrunnelser som vi ønsker å begrunne på barna der vi må se på utvidet vilkåret til søker.
Vi sender derfor med søker sine utvidet vilkår når vi finner begrunnelser for person.
=> Sjekk utvidet på søker når man finner begrunnelse for barn

src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/Tidslinje.kt
Fjernet error funnet i code scanning (CodeQL) ved å legge til manglende override av hashCode
Ref: https://github.com/navikt/familie-ba-sak/security/code-scanning/1
=> Fix manglende override av hashCode (tilsvarende equals) i Tidslinje

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt
Må vente på tommel opp fra fag på om dette er OK i prod også + at vi må anonymisere aktørene
=> Lag endepunkt for å hente tester som er bak autentisering

src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/begrunnelser/LagGyldigeBegrunnelserTestUtil.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevPerioder/selvstendig_rett.feature
Favro: NAV-16177
I den gamle flettefeltkoden skjer noe galt 🤷 og vi får derfor ikke ut en flettet tekst fra familie-brev i dette caset.
Det fungerer derimot i den nye koden. Legger til test som bekrefter oppførselen til den nye flettefeltløsningen
=> Test fletting av begrunnelse selvstendig rett primærland

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16175)
Begrunnelsen "Foreldrene bor sammen, endret mottaker" dukker ikke opp fordi den ikke er lagt inn i ba-sak. 
Legger den til.
=> Legg til begrunnelse

src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BrevbegrunnelseUtil.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevPerioder/endret_utbetaling.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16083)
Vi fletter inn feil barn i brevperioden når vi reduserer utbetalingen til 0.
Dette er endret i ny løsning. Lager test som verifiserer dette. 
=> Lag test for brevperiode ved endret utbetaling

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/UnleashNextMedContextService.kt
Send med behandlingsid til unleash
=> Send med behandlingsId til unleash

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSteg.kt
Feilmeldingen vi har nå 👇 gir oss ikke så mye å gå på. Gir med litt mer info.
=> Gi mer info om behandling

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/domene/PdlHentIdenterResponse.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/AktørIdRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/AktørMergeLogg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/AktørMergeLoggRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt, src/main/resources/db/migration/V254__aktoer_merge_logg.sql, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/internal/ForvalterServiceTest.kt
- Patcheendepunkt for å patche barnets ident med ny ident, brukt ved merge
- Sletter kode som ikke var i bruk
Ekstra nøye sjekk at patchesql er riktig
=> Patcheendepunkt for å patche barnets ident med ny ident, brukt ved merge

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/VedtaksperiodeProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskService.kt
Forbedre feilmelding og legg på mer info på task
=> Gjør det tydelig at autobrev ikke skal kunne opphøre

src/main/kotlin/no/nav/familie/ba/sak/task/HentAlleIdenterTilPsysTask.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16761)
Vi ønsker ikke å sende med personer fra infotrygd til pensjon i preprod da disse ikke finnes i PDL i testmiljø. Men filteret som nå ligger i familie-ba-infotrygd må flyttes til tasken i Ba-sak, siden vi trenger et lite utvalg av personer senere i testkjeden, idet vi gjør noen tilfeldig uttrekk av periodedata fra infotrygd som knyttes til eksisterende testpersoner i ba-sak.
kun en liten endring som er enkel å verifisere visuelt
=> Lar være å sende med personer fra infotrygd til pensjon i preprod

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/domene/Vilkår.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/fødselshendelse_annenpart.feature
I stedet for å kaste Ikke implementert for ANNENPART, så returnerer man heller en tom liste for hentOrdinæreVilkårFor når det er ANNENPART
=> Fikser bug for fødselshendelser med annenpart hentet inn i persongrunnlag

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/FiltreringsreglerService.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16318
Jeg kjenner ikke til alle hendelser, så fint hvis noen kan se over denne.
For akkurat fødselshendelse så er det vel mest relevant å se på barn i hendelsen når man skal sjekke om barn lever regelen stemmer.
=> Vi ønsker å se på barn i hendelsen og ikke eksisterende barn ved fødselshendelse

src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskService.kt
Man har en feilende task av type Autobrev, som forsøker å lage tasker av typen SendAutobrev6og18ÅrTask. Denne feiler fordi man nå har lagt på properties for å se alder, men denne var Integer og ikke String.
=> Autobrev klarer ikke å lage tasker av SendAutobrev6og18ÅrTask pga Int property

.github/workflows/build-and-deploy-krise-rett-i-prod.yml
Når noe går galt er det fint å kunne verifisere at ting funker igjen når vi har en fiks. Det er ikke alltid like lett å teste i prod. Gjør så KRISE_RETT_I_PROD-actionen også pusher til preprod
=> Gjør så KRISE_RETT_I_PROD også pusher til preprod

.github/workflows/build-pr.yml, src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleController.kt, src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/UnleashNextMedContextService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/KonsistensavstemmingScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingStegController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/IverksettMotOppdrag.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VurderTilbakekrevingSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/AbstractMockkSpringRunner.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingStegControllerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringServiceEnhetTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/VurderTilbakekrevingStegTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/KonsistensavstemmingSchedulerTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/TekniskEndringAvFødselshendelseTest.kt
Flytter to toggler og sletter én. Sjekk gjerne at instillingene i unleash er riktige.
Oppretter også et endepunkt for frontend slik at vi kan bruke unleash next der også. 
Status: **Flyttet**
Gammel: https://unleash.nais.io/#/features/strategies/familie-ba-sak.behandling.korreksjon-vedtaksbrev
NY: https://teamfamilie-unleash-web.nav.cloud.nais.io/projects/default/features/familie-ba-sak.behandling.korreksjon-vedtaksbrev
Status: **Slettet**
Var kun rester igjen av den i testfiler
Status: **Flyttet**
Gammel: https://unleash.nais.io/#/features/strategies/familie-ba-sak.teknisk-vedlikehold-henleggelse.tilgangsstyring
Ny: https://teamfamilie-unleash-web.nav.cloud.nais.io/projects/default/features/familie-ba-sak.teknisk-vedlikehold-henleggelse.tilgangsstyring
Status: **Flyttet**
Gammel: …
=> Flytt toggler til ny unleash

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16833
Tidligere ble kun oppgaver patchet dersom status var FERDIGSTILT. Nå blir oppgaver heller ikke patchet dersom status er FEILREGISTRERT.
=> NAV-16833 - Ikke patch Oppgave hvis status er FEILREGISTRERT

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Legger til en ny tekst for å løse denne oppgaven: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16832
Rydder også opp en funksjon som ikke ble brukt.
Nei
Legger bare inn begrunnelse og fjerner kode
=> Legger til ny begrunnelse for UK Midlertidig differanse

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevKlient.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeMedBegrunnelserController.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/BrevKlientMock.kt
Litt irriterende å ikke enkelt kunne se hvilken behandling det er vi får feil på når vi får feil på disse sakene så legger til behanlding i logg
=> Legg til behandling i debuglog

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/opphør.feature
[Feil i sentry](https://sentry.gc.nav.no/organizations/nav/issues/521283/?environment=prod&query=is:unresolved&statsPeriod=14d)
Når vi lager begrunnelse som gjelder opphør for søker fletter vi ikke inn barna som hadde utbetaling i samme periode i forrige behandling. 
Endrer så de barna blir flettet inn
=> Ta med barna som har mistet utbetaling fra forrige behandling på opphørsbegrunnelse som gjelder søker

src/test/resources/application-dev-postgres-preprod.yaml
Har endret ingress i ba-infotrygd-feed til en som ikke er deprecated, så må endre her også
=> Endret dev ingress for feed appen

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favro: NAV-17079
Legger til nye begrunnelser fra Sanity. Har delt opp commitene etter vedtaksbegrunnelsestype og sakstype
=> Legg til flere nye begrunnelser

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17152)
Vil legge til eøs-opphørs-begrunnelser som mangler.
=> legg til opphørsbegrunnelser for eøs

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17443
Legg til noen flere eøs tekster for BA
=> Legg til 4 eøs tekster

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassKompetanserService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/TilpassKompetanserTilRegelverkTest.kt
Fjerner de funskjonelle endringene fra https://github.com/navikt/familie-ba-sak/pull/4281 frem til vi har fikset feil som ble innført i PRen
=> Reverter endring som lager feil

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingHentOgPersisterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt
=> utkast til logging

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt
=> bugfix filter på avslutta behandlinger

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingHentOgPersisterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt
Fjerner forvaltningsmetode som ikke lenger trengs
=> Fjerner forvaltningsmetode som ikke lenger trengs

src/main/kotlin/no/nav/familie/ba/sak/common/Feil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatStegTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringTest.kt
Reverts navikt/familie-ba-sak#4301
får UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only
=> Revert "filtrer ut satsendringsfeil som feiler på vilkår og legg de i satskjø…"

src/main/kotlin/no/nav/familie/ba/sak/task/PatchMergetIdentTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/PatchMergetIdentTaskTest.kt
Fikser feil ved patching av ident. Skrivet seg vekk fra å bruke singelOrNull på Set<PersonEnkel> og heller bruke det på Set<String>.
=> Skrevet om måten man finner en aktør på ved patching

.deploy/nais/app-preprod.yaml, .deploy/nais/app-prod.yaml, .github/workflows/codeql.yml, Dockerfile, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/ekstern/tilbakekreving/HentFagsystemsbehandlingRequestConsumerTest.kt
- Setter ned antall pods til før satsendring
- Skrur av autobuild på codeql og heller bygger manuelt
- Flytter JAVA_OPTS til nais-filene
=> Java opts til nais-filene, codeql manuell bygg og nedskalering av podder

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/internkonsistensavstemming/InternKonsistensavstemmingService.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettInternKonsistensavstemmingTaskerTask.kt
Endrer så vi ikke henter inn hele fagsaken når vi henter alle fagsakene. Endrer også slik at vi kun henter i batcher
=> Del opp intern konsistensavstemming

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevPeriodeProdusent/BrevPeriodeProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevPerioder/endret_utbetaling.feature
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17891
Tar kun med barn som har endret utbetaling med årsak allerede utbetalt i periodeteksten hvis det også finnes utvidet i perioden. Hvis det ikke er utvidet i perioden så ønsker vi ikke å ha med barn med nullutbetaling. 
Testen som feiler nå har ikke noe med denne koden å gjøre
=> Riktig barn i periodetekst ved endret utbetaling allerede utbetalt

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringService.kt
Ønsker å logge feilen som blir kastet når satsendring feiler slik at vi kan skjønne hva som har skjedd.
=> logg feil på satsendringsfeil

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18063
=> Ny eøs begrunnelse

src/test/enhetstester/kotlin/no/nav/familie/ba/sak/ekstern/tilbakekreving/HentFagsystemsbehandlingRequestConsumerTest.kt
Fjerner disabled fra en midlertidig disabled test
=> Fjerner Disabled på test

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/opphør.feature
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18088
Barn med eksplisitt avslag skal ikke komme med i begrunnelser som gjelder søker i "ikke innvilgede"-perioder som ikke er eksplisitte avslag. Avklart med Anna at dette blir riktig måte å gjøre det på.
Nei
=> Bug: barn med avslag skal ikke inn i opphørsbegrunnelse

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeUtil.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18142
Som nevnt i favrokortet så er det ønskelig at vi fjerner restriksjoner på kulepunkt for fortsatt innvilget.
=> Fjerner restriksjoner på kulepunkt for fortsatt innvilget

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragValidator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutovedtakBrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelerTilkjentYtelseOgEndreteUtbetalingerService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/SendAutobrev6og18ÅrTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrServiceTest.kt
NAV-18064
Ikke send autobrev omregning 6 år hvis det er nullutbetaling.
=> Ikke send autobrev omregning 6 år hvis det er nullutbetaling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18290
=> Legg til flere begrunnelser#

src/main/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIEndretUtbetalingAndelUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatEndringUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIEndretUtbetalingAndelUtilTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18236
Tok en prat med Linda og Anna, og vi ble enige om at vi ønsker behandlingresultatet ENDRET dersom man har gått fra ingen endret utbetaling andeler til noe endretutbetalingandeler. Selvom beløpet er lik mellom behandlingene.
=> Vi skal bry os om all endring i endret andeler

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIEndretUtbetalingAndelUtilTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18693
2x nye begrunnelser.
=> Nye begrunnelser (fengsel)

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt
Legger til månedlig valutajustering som årsak.
Dette for å kunne jobbe med månedlig valutajustering litt parallelt uten at alle må legge det inn.
=> Legg til månedlig valutajustering årsak

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18707
1x ny begrunnelse
=> Ny begrunnelse for enslig mindreårig

src/main/kotlin/no/nav/familie/ba/sak/common/TekstSaniteringUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestOppdaterJournalpost.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/ecb/ECBService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/TekstSaniteringUtilTest.kt
VI får feil på et sted vi har lagt til validering. 
https://sentry.gc.nav.no/organizations/nav/issues/559726/?project=3&project=112&query=is:unresolved
Antar det er fordi vi får in instutisjon i id. Gjør så valideringen er litt mindre hissig
=> Gjør validering mindre aggressiv

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestOppdaterJournalpost.kt
Vi får en del feil ved initialisering av denne klassen i [sentry](https://sentry.gc.nav.no/organizations/nav/issues/559878/?project=112#exception). Legger på litt logging så vi vet hva som blir sendt inn
=> Logg ved feil på ident

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/SnikeIKøenService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/SnikeIKøenServiceTest.kt
Fikser bug som ble funnet under testing av [snike i køen for autovedtak](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17952)
=> Sjekker om behandlingPåVent har vært innom vilkårsvurdering før tilbakestilling etter sniking i køen

src/main/resources/application.yaml
Bør antageligvis forskyves på lik linje med AutobrevScheduler [her](https://github.com/navikt/familie-ba-sak/pull/3293) for å redusere sjansen for at [denne](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-19993) typen feil kan oppstå igjen som følge av fagsakstatus ikke blir oppdatert raskt nok.
=> Starter FagsakStatusScheduler 1 time tidligere

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ISanityBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/RestSanityBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/eøs/RestSanityEØSBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-20240
Vi ønsker å kunne slå av begrunnelser i prod fra sanity
=> Legg til slått av i produksjon

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/VedtaksperiodeGrunnlagForPerson.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/endret_utbetaling.feature
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-20034
Case:
- Barn med andel satt til 0kr pga allerede utbetalt kommer med i begrunnelse hvor det ikke skulle ha kommet med. Årsaken er at begrunnelsen gjelder søker og det andre barnet, og når en begrunnelse gjelder søker så fletter vi inn alle barn med utbetaling
- Problemet her er at man tidligere sa at en person har utbetaling om det finnes en andel på personen i perioden
Løser dette ved å si at en person har utbetaling i perioden hvis en av disse stemmer:
- Det er utbetaling av beløp større enn 0kr
- Det er andel som …
=> Bugfix: ikke ta med barn med 0kr-utbetaling (pga allerede utbetalt) i søkers innvilgetbegrunnelse

src/main/kotlin/no/nav/familie/ba/sak/task/TaBehandlingerEtterVentefristAvVentTask.kt
Eksisterende tasker med typo fikses av meg manuelt.
=> Fix typo taBehanldingerEtterVentefristenAvVent

src/main/kotlin/no/nav/familie/ba/sak/common/Feil.kt, src/main/kotlin/no/nav/familie/ba/sak/config/ApiExceptionHandler.kt
Endrer feilmeldingene dersom vi får MånedligValutaJusteringFeil. Endrer også default httpStatus for Feil til INTERNAL_SERVER_ERROR og BAD_REQUEST for FunksjonellFeil
=> Lag bedre feilhåndtering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSteg.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatStegTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-20292)
For å fikse edge case med barn som fyller 18 år med en måneds mellomrom
=> Legger til FORTSATT_OPPHØRT som gyldig behandlingsresultat ved omregning

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestValutakurs.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligvalutajustering/MånedligValutajusteringSevice.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/Valutakurs.kt, src/main/resources/db/migration/V259__valutakurs_legg_til_vurderingsform.sql, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatStegTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/domene/Datagenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/ValutakursBuilder.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/ValutakursControllerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/ValutakursServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/ValutakursTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/domeneparser/VedtaksperiodeMedBegrunnelserParser.kt
Del én av denne oppgaven: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-20353
Vi ønsker å markere om en valutakurs er lagt inn av systemet eller en saksbehandler. Derfor trenger vi å lagre ned denne informasjonen i databasen. 
Legger til et felt for vurderingsform i valutakurs-tabellen
=> Marker automatisk valutajustering

src/main/kotlin/no/nav/familie/ba/sak/task/FjernGamleFeiledeTasksIPreprod.kt
Kopiert over fra baks-mottak, en scheduled job som sletter feilede tasker som er eldre enn 1 måned i preprod
Manuelt testet https://logs.adeo.no/s/nav-logs-legacy/app/r/s/ugBzx
=> Fjern gamle tasker som har feilet i preprod

.deploy/nais/app-prod.yaml
Vi har fått oom. Endrer memory request tilbake til forrige verdi
=> Øk memory request

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/config/ApplicationConfig.kt, src/main/resources/application.yaml
Tar i bruk tellAPIEndepunkterIBruk-interceptor fra familie-felles-metrikker
=> Tar i bruk tellAPIEndepunkterIBruk-interceptor fra familie-felles-metrikker

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragGeneratorService.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OppdaterStønadTomPåTilkjentYtelseTask.kt
Ref [denne](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-19991) oppgaven har vi en del saker igjen i prod som har feil tilkjentYtelse.stønadTom og som trenger å blir oppdatert. Har derfor laget et endepunkt vi kan bruke for å oppdatere. 
Er foreløpig 305 fagsaker dette gjelder. Kan sees med denne spørringen:
select distinct b.fk_fagsak_id
from tilkjent_ytelse ty
join andel_tilkjent_ytelse aty on ty.id = aty.tilkjent_ytelse_id
join endret_utbetaling_andel eua on eua.fk_behandling_id = aty.fk_behandling_id
join behandling b on b.id = aty.fk_behandling_id
join fagsak f on b.fk_fagsak_id = f.id
where aty.prosent = 0
and eua.tom = ty.stonad_tom
and eua.aarsak in ('ALLEREDE_UTBETALT', 'ENDRE_MOTTAKER', 'ETTERBETALING_3ÅR')
and f.status = 'LØPENDE' …
=> lag endepunkt for å oppdatere stønadTom for tilkjente Ytelser der det kan være aktuelt.

pom.xml
Reverts navikt/familie-ba-sak#4505
=> Revert "Bump org.wiremock:wiremock-standalone from 3.5.3 to 3.5.4"

src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/ReduksjonFraForrigeIverksatteBehandlingTest.kt
Magisk
favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15264
=> Fjern @disabled på test nå som det magisk funker

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragGeneratorService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt
Ser ut til fungere fint med togglen skrudd på for prod, velger derfor å fjerne den 😊
=> fjern stønadTom-featureToggle

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingService.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/86f241541982404a7491d82d?card=NAV-20714
Vi ønsker å propagere tekst for hvorfor en tilbakekreving er opprettet fra EF, BA og KS.
Vi har derfor utvidet request objectet og fyller nå ut begrunnelseForTilbakekreving
=> Populer begrunnelseForTilbakekreving

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligvalutajustering/MånedligValutajusteringScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilpassDifferanseberegningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/ValutakursController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
Nå har vi to feature toggles for valutajustering som dekker litt forskjellige features. Endrer så vi har en toggle per feature slik at vi ikke ruller ut alt samtidig.
=> Granuler featuretoggles for valutajustering

src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/AbstractMockkSpringRunner.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtilsEndretUtbetalingAndelTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/RestFagsakTest.kt
Gjort et par tester mer stabile
=> Testforbedringer

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Favrokort: 
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21070
=> Legg til EØS begrunnelser for utbetalingstabell

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt
Ved feilsøking av NAV-21072 så ønsket jeg mer logg. Denne PR legger på mer logg til neste gang
=> Logg for hva frist ferdigstillelse endres fra og til ved sett på vent

src/main/resources/db/migration/V264__behandling_opprettetaarsak_tekniskopphor_til_tekniskendring.sql
Følger opp med en flyway script til denne:
https://github.com/navikt/familie-ba-sak/pull/4553
=> Flywayscript for teknisk opphør til teknisk ending

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/UtgåendeJournalføringService.kt
Ikke legg til behandlingId til eksternReferanseId hvis behandling er null
Da vil den id bli slik som dette
12_verge_171a0572-b6dd-4a4b-b15c-1ffdd573e85a
12_13_4c89e7f2-15ad-42f0-95f6-46062c0c44aa
12_50b7cfaf-3296-4bc0-ab0b-359715436e63
12_13_verge_92a34f87-5774-47b4-9d24-3d29f2aa7cf3
=> Ikke legg til behandlingId til eksternReferanseId hvis behandling er null

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligvalutajustering/MånedligValutajusteringScheduler.kt
For at den schedulerte funksjonen ikke skal kjøre på alle podder har vi på en sjekk som gjør at den kun kjører hvis podden er leader. 
Dette skaper krøll når vi skal prøve å kjøre funksjonen fra endepunkt, da vi kan treffe pod som ikke er leader. 
Endrer så leader-sjekken kun skjer i løypa for scheduleren og ikke for koden som kjøres fra endepunktet.
=> Kun ha leader-check på scheduleren

src/main/kotlin/no/nav/familie/ba/sak/task/MånedligValutajusteringFinnFagsakerTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/MånedligValutajusteringTask.kt
Øker antall fagsaker som blir automatisk valutajustert til 1000
Gir egen callId til hver task som oppdaterer valutakurs for en fagsak
=> Øk antall fagsaker som blir automatisk valutajustert

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursServiceTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21290)
I førstegangsbehandlinger skal det være tillatt å gjøre valutajustering tidligere enn 01.01.23
=> Tillatt tidligere datoer enn 01.01.23 for førstegangsbehandling

src/main/resources/application-preprod.yaml
Favrkort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21473
Vi ønsker å bruke nytt og identisk dataset ba-v2 i preprod.
=> Bruk BA-v2 dataset

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentGenereringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/HenleggBehandling.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequestTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/HenleggelseTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/OpplysningspliktTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21450)
=> Fjerner mottakerNavn og mottakerIdent fra ManueltBrevRequest

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursService.kt
Legger til logger for hva som avgjør tidspunkt for første valutakurs
=> Logg tidspunkt for første valutakurs og hva som trigget det

src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21536
Retter opp en bug som ble introdusert [her](https://github.com/navikt/familie-ba-sak/pull/4532) 2. mai. Nå har vi sendt feil stønadTom-dato i alle vedtak til stønadstatistikk siden det. Retter opp til å bruke riktig tom-dato
Nei
Burde ha bedre tester på dette, men prioriterer det ikke nå da jeg vil få ut fiksen asap
=> Bug: feil tom-dato for utbetalingsperioder til stønadstatistikk

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21581
Vi har en bug der vi prøver å utlede endringstidspunkt fra vedtaksperioder, men så har vi ingen vedtaksperioder med fom noe som kan oppstå når man har fortsatt innvilget som behandlingsresultat.
endrer derfor logikken til å bruke eksisterende logikk for å hente endringstidspunkt, da eksisterende logikk i vedtaksperiodeservice håndterer slike tilfeller OK. også er det greit å bruke felles kode for å utlede endringstidspunkt.
=> Vi fikser en bug der vi alltid forventer at periode skal ha fom og tom, noe de ikke har under fortsatt innvilget

src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkController.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/FinnBehandlingerMedVedtakEtterDatoTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettPubliserVedtakV2Task.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskerForVedtakEtterVedtaksdatoTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkServiceTest.kt
Favro: [NAV-21536](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21536)
Det tok for lang tid å kjøre opprettelse av `PubliserVedtakV2Task` for 50 000 behandlinger på en gang, så fordeler nå arbeidet i ca 50 tasker med 1000 behandlinger i hver.
=> Fordeler resending av vedtak til dvh i tasker 

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt
Dersom det allerede eksisterer en åpen tilbakekreving på en fagsak, skal ikke beslutte vedtak-steget kaste en feil selv om det er en feilutbetaling uten et talbakekrevingsvalg
=> Ikke kast feil ved åpen tilbakekreving på fagsak

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursService.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21649
Saksbehandler melder at de ikke kan oppdatere utenlandsk perodebeløp uten at "alt" forsvinner. 
Legger på litt logging for å prøve å skjønne hva som går galt
=> Legg til logger for automatiske valutakurser

src/main/resources/db/migration/V266__drop_index_oppdrag_not_null.sql
Reverts navikt/familie-ba-sak#4667
=> Revert "Drop index drop index tilkjent_ytelse_utbetalingsoppdrag_not_null_idx"

src/main/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/Barnetrygd.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/PensjonController.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/PensjonService.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/README.md
=> Legger til README, kommentarer etc. under pensjon-mappa

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21717
=> Ny begrunnelse for eøs borger

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/IVedtakBegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21715
Vi ønsker at begrunnelser som er av type avslag, reduksjon og opphør skal støtte fritekst.
=> Reduksjon, opphør og avslagsbegrunnelser skal støtte fritekst

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilpassDifferanseberegningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/ValutakursController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/ValutakursControllerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingStegTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21685
Sletter flere toggler som aldri ble brukt, samt sletter toggelen for automatisk valutajustering på manuelle saker. Denne har vært på i prod 
=> Chore: slett toggle for automatisk valutajustering på manuelle saker + rydd i ubrukte toggler

src/main/kotlin/no/nav/familie/ba/sak/config/SentryConfiguration.kt
Retter en typo som ble funnet under vakt. 
Nei
Det fantes ikke noen eksiterende tester. Virker som det er mye arbeid å lage tester for en typo. 
- [ X] Nei
=> NAV-21927: Fikser typo i SentryConfiguration

src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/Logg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/sammensattKontrollsak/SammensattKontrollsakService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggServiceEnhetTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/sammensattKontrollsak/SammensattKontrollsakServiceTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21976
=> Ved opprettelse, endring og fjerning av sammensatt kontrollsak så ønsker vi å lagre det til behandlingsloggen.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favro: [NAV-22051](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22051)
Lagt til manglende opphørs-begrunnelse.
=> Ny opphørs-begrunnelse OPPHØR_SEKUNDÆRLAND_INGEN_AV_FORELDRENE_JOBBER

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringService.kt
Fjerner unødvendig logging som trigger alarm ved snike i køen
=> Fjerner unødvendig logging som trigger alarm ved snike i køen

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/autovedtak_småbarnstillegg.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/gyldigeBegrunnelser/overgangsstønad_og_småbarnstillegg.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22258
=> Vi fikser opp i en test som blir påvirket av dagens dato. Dette gjør vi ved å fastsette dagens dato i testen

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentServiceTest.kt
Ønsker å validere fødselsnummer også når vi patcher på eksisterende aktør
=> valider fødselsdato når vi legger til nytt fødselsnummer på aktør

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt
Hastefix i prod. Skjer en feil i kallet mot integrasjoner i prod. Gjemmer derfor mer av den nye koden bak feature toggle
=> Gjemmer mer av den nye funksjonaliteten bak feature toggle

.github/workflows/sonar.yml
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22720
Forrige PR: https://github.com/navikt/familie-ba-sak/pull/4817
Korrigerer en typo. 
Nei
Ikke relevant.
=> NAV-22720: Korrigerer typo for kjøring av enhetstester

.github/workflows/sonar.yml
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22720
Forrige PR: https://github.com/navikt/familie-ba-sak/pull/4817
Bytter fra `mvn test` til `mvn verify` da JaCoCo rapporten ikke ble laget i `mvn test`
Nei
Ikke relevant.
=> Nav 22720 bytt fra test til verify

pom.xml
Favro:  https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22720
Tilknyttet PR: https://github.com/navikt/familie-ba-sak/pull/4817
Setter folder for tests and sources manuelt for å sørge for at `resources` også blir analysert slik at vi får med oss issues i `.sql` filer og lignende
Nei
Ikke relevant
=> NAV-22720: Setter sonar sources & tests folders

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22859
=> Legg til ny begrunnelser som er ønsket i BA-sak

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22895
=> Legg til 4 nye eøs innvilgelses begrunnelser

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentService.kt
MiniPr for å forbedre leselighet etter tilbakemelding på [tilsvarende kode i KS](https://github.com/navikt/familie-ks-sak/pull/918)
=> trekk søkers aktørId ut i egen variabel for bedre leselighet

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23011
=> Ny eøs innvilgelse begrunnelse

src/main/kotlin/no/nav/familie/ba/sak/config/UtbetalingsgeneratorConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/FagsystemBA.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/Opphør.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/Utbetalingsoppdrag.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragGeneratorService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/YtelsetypeBA.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/FagsystemBATest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/OpphørTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragKtTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/YtelsetypeBATest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/config/UtbetalingsgeneratorConfigTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22995
Splitter opp eksisterende logikk for å gjøre det mer oversiktlig og enklere å teste 
Nei
=> NAV-22995: Splitter opp eksisterende logikk og skriver tester

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
Feature toggle ble skrudd på 1. oktober. Har vært skrudd på uten problemer siden.
Endrer ikke funksjonalitet fra 1. oktober
=> Slett toggle etterbetaling 3 måneder

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23140
Ny reduksjonsbegrunnelse EØS
=> Ny reduksjonsbegrunnelse EØS

src/main/kotlin/no/nav/familie/ba/sak/config/ClockConfig.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/ClockConfigTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22995
Clock kan injectes i klasser for å gjøre de frakoblet systemklokken, da blir det blandt annet lettere å skrive gode enhetstester.
Nei
=> NAV-22995: Legger til ClockConfig

src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/OppdragSteg.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/komponentMocks/MockBehandlingMigreringsinfoRepository.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/komponentMocks/MockUnleashService.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22995
Rydder opp i eksisterende logikk i forberedelse til en kommende PR: https://github.com/navikt/familie-ba-sak/pull/4852
Nei
Ikke relevant.
=> NAV-22995: Rydder opp i cucumber setup

src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/BeregnetUtbetalingsoppdragDataGenerator.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22995
Disse metodene skal brukes videre i en kommende PR: https://github.com/navikt/familie-ba-sak/pull/4852
Metodene gjør det lettere å opprette testdata for tester. 
Legger til disse metodene i en egen PR da den andre PRen er veldig stor. 
Nei
Ikke relevant.
=> NAV-22995: Legger til og oppdatere eksistrende metoder for å lage testdata i forbindelse med endringer på utbetalingsoppdrag

.deploy/nais/app-preprod.yaml, .deploy/nais/app-prod.yaml, Dockerfile, src/main/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/PensjonService.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/task/HentAlleIdenterTilPsysTask.kt
Mer logging og CPU tweaking for å feilsøke restarts
=> Feilsøking Pensjon. Mer logging, CPU i preprod, forvalterendepunkt

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/ArbeidsfordelingService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/ArbeidsfordelingServiceTest.kt
Fjerner feature toggelen da den har vært på i prod lenge.
Jeg har ikke skrevet tester fordi: Ingen endringer ut over fjerning av toggle. Eksisterende tester hvor toggle var på kjører fortsatt "OK".
=> Fjerner feature toggle: `OPPRETT_SAK_PÅ_RIKTIG_ENHET_OG_SAKSBEHANDLER`

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23266
Legger til nye begrunnelser.
=> Legger til 4 nye begrunnelser relatert til institusjon og 3mnd etterbetaling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligvalutajustering/MånedligValutajusteringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingStegTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
Denne skrivefeilen har irritert meg i seks måneder nå, så var vel på tide å bruke de 10 sekundene det tok å fikse det
=> Korriger skrivefeil

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentServiceTest.kt
Lagt til mer logger slik at det blir lettere å gjøre patching, eller sending av melding til fag
=> Mer utfyllende logger for et par identhendelser-feil

.deploy/nais/azure-ad-app-lokal.yaml
For at vi skal kunne kjøre opp familie-klage lokalt mot preprod når vi utvikler trenger vi å tillate familie-klage-lokal i ba-sak.
Nei
=> Klage: legg til familie-klage-lokal i listen over apper som kan kalle ba-sak

src/main/kotlin/no/nav/familie/ba/sak/ekstern/bisys/BisysController.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/ekstern/bisys/BisysControllerIntegrasjonsTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23542
=> Vi endrer fra 5 til 10 år på bisys begrensning

src/main/kotlin/no/nav/familie/ba/sak/ekstern/bisys/BisysController.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/ekstern/bisys/BisysControllerIntegrasjonsTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23542
Vi fjerner denne begrensningen etter ønske.
=> Vi fjerner tidsbegrensning på bisysy endepunkt

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/SisteUtvidetAndelOverstyrer.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/UtbetalingsoppdragGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/BeregnetUtbetalingsoppdragDataGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/SisteUtvidetAndelOverstyrerTest.kt
Flytter kode relatert til overstyring av `sisteAndelPerKjede` inn i et object i egen fil. Justerer også logikken noe ved å hoppe ut av flyten tidligere dersom vi ikke trenger å overstyre noe.
=> Liten omstrukturering/opprydding av kode for overstyring av sisteAndelPerKjede for utvidet barnetrygd

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/gyldigeBegrunnelser/vilkår.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/gyldigeBegrunnelser/vilkår_delt_bosted.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23749
Vi må ta hensyn til delt bosted i vilkårsvurderingen når vi skal lage  begrunnelsedata for dette
=> Vi må ta hensyn til delt bosted i vilkårsvurderingen når vi skal lage  begrunnelsedata for dette

.deploy/nais/app-preprod.yaml, src/main/kotlin/no/nav/familie/ba/sak/ekstern/tilbakekreving/HentFagsystemsbehandlingRequestConsumer.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/producer/KafkaProducer.kt, src/main/resources/application-preprod.yaml, src/main/resources/application.yaml, src/test/resources/application-dev-postgres-preprod.yaml
Team Tilbake skal ta over tilbakekrevingsløsningen. Den eksisterende løsningen kjører nå i teamfamilie nais teamet, og for å ta ordentlig eierskap til løsningen og gjøre det til en NAV fellestjeneste ønsker vi å flytte det til et NAIS team som er mer generelt.
Er det noe jeg har glemt?
Jeg har ikke skrevet tester fordi: Det er en ren konfigurasjonsendring
=> Ta i bruk tilbakekreving som er flyttet til nytt nais team i preprod

src/main/kotlin/no/nav/familie/ba/sak/common/Utils.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/internkonsistensavstemming/InternKonsistensavstemmingUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevEøsBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevPeriodeProdusent/BrevPeriodeProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/HjemlerKombinator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/HjemmeltekstUtleder.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/StandardbegrunnelseUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingValidering.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23567
Har endret bruk av Utils.slåSammen til List.slåSammen() og lagt til funksjon for å ta imot tom liste. 
=> Rydd opp i slåsammen metoder

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/SendTilBeslutter.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/SendTilBeslutterTest.kt
Sletter toggle for å fylle inn sb navn i godkjenne vedtak-oppgave. Har kjørt fint i prod en uke.
Nei
=> Slett toggle for å fylle inn sb navn i godkjenne vedtak-oppgave

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/gyldigeBegrunnelser/etter_endret_utbetaling_som_ikke_gjelder_søker.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543
Vi ønsker bare å hente inn barn som var i endret utbetalinger i forrige periode ved bruk av etter endret utbetaling begrunnelser, ref favrokort.
=> Vi ønsker bare å hente inn barn som var i endret utbetalinger i forrige periode ved bruk av etter endret utbetaling begrunnelser

.deploy/nais/app-prod.yaml
=> skrur på auditlogging

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24108
Nye begrunnelser som er etterspurt er nå lagt inn
=> Nye begrunnelser etterspurt som er lagt inn

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/domene/PdlHentIdenterResponse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt
Logger ut ident vi har gjort oppslag på mot PDL når vi ikke finner folkeregisterident blant de returnerte identene.
Relatert feilende task: https://familie-prosessering.intern.nav.no/service/familie-ba-sak/task/1332204501
=> Legger til ekstra logging for debugging av manglende folkeregister-ident

pom.xml
[NAV-24177](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24177)
Bumper utbetalingsgenerator til siste versjon for å få med endring som sikrer deterministisk generering utbetalingsoppdrag.
=> Bumper utbetalingsgenerator til siste versjon

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt
For å kunne kjøre konsistensavstemming midt på dagen må vi hente alle fnr også for avsluttede fagsaker
=> henter fnr for alle fagsaker ikke bare aktive i konsistensavstemming

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestUtvidetBehandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/UtvidetBehandlingService.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24106
Vi legger til søknad mottatt dato i behandlingresponsen
=> Vi legger til søknad mottatt dato i behandlingresponsen

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/TilpassArbeidsfordelingService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/TilpassArbeidsfordelingServiceTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24403
Fjerner toggle som allerede er skrudd på i dev og prod. 
Nei
Ikke relevant.
=> NAV-24403: Fjerner toggle for oppretting av behandlinger på Vikafossen

pom.xml
Fikser en endring mot ECB som returnerer ny content type
=> Oppgraderer valutakurs-klient

.github/workflows/main.yaml, .github/workflows/manual-deploy-dev.yaml, .github/workflows/manual-deploy-prod.yaml
Workflowen klarer ikke håndtere alle testene samtidig. Matcher eksisterende funksjonalitet.
=> Skip tests for byggeworkflows

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt
Favro: NAV-24544
Legger til toggle for ulovfestet motregning for å styre om funksjonalitet skal brukes
=> Legg til feature toggle for ulovfestet motregning

.nais/app-dev.yaml
legger til familie-prosessering-lokal som inbound så man kan bruke familie-prosessering lokal-mot-preprod profil mot ba-sak
=> application: familie-prosessering-lokal som inbound for å lettere sette opp familie-prosessering lokalt

README.md
Lagt til doc om at Copilot brukes
=> Doc om Copilot lagt til

pom.xml
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24617
Oppdater familie-kontrakter til nyeste versjon som inneholder ny årsak for hvorfor vedtak skal omgjøres, se PR her: https://github.com/navikt/familie-kontrakter/pull/1001
=> Oppdater familie-kontrakter for å få ny klage-årsak

src/main/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlageService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/klage/dto/OpprettKlageDto.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24618
Vi skal endre fra kravMottattDato til klageMottattDato. Utvidet dto-objektet til å inneholde begge, og at begge er optional. Hvis klageMottattDato finnes bruker vi den, hvis ikke bruker vi kravMottattDato.
Steg 1 så jeg kan gjøre oppgraderinger frontend. Etter frontend-endringene kommer jeg tilbake hit for å rydde.
Nei
Syns ikke det gir mening her:)
=> Klage: endre fra krav mottatt til klage mottatt-dato

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/InnkommendeJournalføringServiceV2.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlageService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/klage/dto/OpprettKlageDto.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24618
Rydder opp i grensesnitt mot frontend. Fjerner kravMottattDato helt, og gjør i tillegg klageMottattDato påkrevd. Rydder også litt ellers i koden ved å rename til klageMottattDato der det er relevant.
Må merges etter denne: https://github.com/navikt/familie-ba-sak-frontend/pull/3610
Nei
=> Klage: fjern kravMottattDato

pom.xml, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonClientTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/InnkommendeJournalføringServiceEnhetTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/InnkommendeJournalføringServiceV2Test.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/JournalføringControllerTest.kt, src/test/resources/familieintegrasjoner/json/hentTilgangsstyrteJournalposterForBruker.json, src/test/testdata/kotlin/no/nav/familie/ba/sak/datagenerator/JournalpostGenerator.kt
Favro: [NAV-22989](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22989)
Oppdaterer `familie-kontrakter` for å få med endringer relatert til bedre melding til saksbehandler dersom et dokument i dokumentoversikten er sperret.
Ingen nye tester da jeg kun bumper en avhengighet.
=> NAV-22989: Oppdaterer familie-kontrakter

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveController.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/domene/DataForManuellJournalføring.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24775
Ønsker å hente klagebehandlinger i eget kall, og trenger derfor ikke sende den med til frontend sammen med journalføring-data lenger. Denne PRen må merges etter tilhørende frontend: https://github.com/navikt/familie-ba-sak-frontend/pull/3632
Nei
=> Klage: ikke send med klagebehandlinger i data for manuell journalføring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingController.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24805
Lager eget endepunkt for å hente ut tilbakekrevingsbehandlinger, sånn at saksoversikten vår ikke går ned hvis tilbakekreving er nede.
Tilsvarende PR i ks: https://github.com/navikt/familie-ks-sak/pull/1197
ja! Se kommentar
=> Tilbake: lag eget endepunkt for å hente tilbakekrevingsbehandlinger

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentControllerTest.kt
Brev er brukket for fagsak. Re-introduserer gammel funksjonalitet inntil ny er fikset.
=> Bruk tidligere funksjon: leggTilEnhet inntil byggMottakerdataFraFagsak er fikset

.github/workflows/build-pr.yaml, .github/workflows/sonar.yaml, pom.xml
Lagd profiler for mvn for å kjøre de ulike testene og bruker de i GHA scriptene. Siden jeg alltid glemmer hva av grupper jeg skal inkludere og eksludere
Kun kjøre enhetstester
```
mvn test -Penhetstest
```
Kun kjøre integrasjonstester
```
mvn test -Pintegrasjonstest
```
Kun kjøre verdikjedetester
```
mvn test -Pverdikjedetest
```
=> Lagd mvn-profiler for enhetstest, integrasjonstest og verdikjedetest

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24951
Lagt til nye EØS innvilgelsesbegrunnelser
=> Nye begrunnelser for EØS innvilgelse

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543
=> Vi kaster ikke lenger feil ved ingen lagVedtakOppgaver når FerdigstillLagVedtakOppgaver kjøres

src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonController.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24650
Sletter disse gamle endepunktene som frontend ikke lenger bruker.
=> Vi sletter deprecated person endepunkter

src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentServiceTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25005
Test feiler ved bygg pga. hardkodet datoer. 
Nei
=> NAV-25005: Benytter variabler i assert og ikke hardkodet dato

.github/workflows/build-pr.yaml
NAV-24974
Midlertidig skrur av profil for jacoco for itester
=> Midlertidig skrur av profil for jacoco for itester

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestJournalføring.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/InnkommendeJournalføringServiceV2.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/JournalføringMetrikk.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/JournalføringMetrikkV2.kt
Favro:  [NAV-25024](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25024)
Tilpasser logikken for metrikker da vi nå alltid oppretter en fagsak ved journalføring/ferdigstilling. 
Nei
Fant ingen gode måter å teste `Metrics.counter(...)` på. Tror ikke det er så viktig heller.
=> NAV-25024: Korrigerer metrikktelling da vi nå alltid oppretter fagsakved journalføring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/domene/SatskjøringRepository.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatskjøringRepositoryTest.kt
Legger til CRON-jobb for å slette feilede satsenderinger hver hverdag, slik at de kan bli kjørt på nytt.
- [] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
=> Legg til CRON-jobb for å slette feilede satsenderinger hver hverdag.

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentControllerTest.kt
Toggle har stått på en stund og kan fint fjernes. Fjerner også funksjonalitet som nå er erstattet.
N/A
=> Fjern toggle: INNHENTE_OPPLYSNINGER_KLAGE_BREV

.github/workflows/sonar.yaml
Var feil path. Skal være mer rett nå
=> Fikser path i sonar.yaml for opplasting av testrapport

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25180
=> Legger til nye begrunnelser ønsket

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25180
=> Legger til enda flere begrunnelser

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/søknadreferanse/SøknadReferanse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/søknadreferanse/SøknadReferanseRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/søknadreferanse/SøknadReferanseService.kt, src/main/resources/db/migration/V280__lag_tabell_for_soknad_referanse.sql, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/LagreMigreringsdatoTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/søknadreferanse/SøknadReferanseServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/OppdragSteg.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/søknadreferanse/SøknadReferanseRepositoryTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/VedtakServiceTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25243) 
Relatert til [denne](https://github.com/navikt/familie-baks-mottak/pull/1345) 
Vi ønsker å ta i mot søknadsinfo fra baks-mottak, for å bruke journalpostId til å hente ut digitale søknader
=> Ta i mot søknadsinfo fra baks-mottak

.nais/app-dev.yaml, .nais/app-prod.yaml, src/main/resources/logback-spring.xml
NAV-25299
https://github.com/navikt/familie-ks-barnehagelister/pull/223
Sender securelogs også til team_logs i gcp
=> Sender securelogs også til team_logs

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25388
Nya tekstarrr
=> Legger til nye eøs tilleggstekster

src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25398
Når vi går videre til registrer søknad så ønsker vi å sende inn fagsak aktør i barnasidenter.
=> Ved overgang til registrer persongrunnlag steget så skal fagsak aktør  sendes inn som barn

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/søknad/SøknadMapperV9.kt
Relatert til [Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25323) og [denne](https://github.com/navikt/familie-kontrakter/pull/1020) 
Dumpe nyeste versjon av familie-kontrakter, og ta i bruk hjelpefunksjon når vi sjekker verdien til et spørsmål i søknaden.
Hjelpefunksjonen blir testet i familie-kontrakter
=> bump nyeste version av familie-kontrakter

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/RelatertBehandlingUtleder.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/RelatertBehandlingUtlederTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25125
Fjerner toggle da den har vært skrudd på en stund alt.
=> NAV-25125: Fjerner toggle for relatert behandling id

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestPerson.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/UtvidetBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagService.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25346)
Trenger å sende med hvorvidt en person er manuelt registrert i søknaden slik at vi kan markere hen i vilkårsvurderingen i frontend. 
Testes manuelt
=> Legg til om person er manuelt lagt til i søknad i dataobjekt som sendes til frontend

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt
Endepunktet ble brukt til testing av alarmer
=> Fjern log-error endepunkt

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favro: NAV-25592
Legger til ny [begrunnelse](https://familie-brev.sanity.studio/ba-brev/structure/__edit__begrunnelse-1bf3caa1-5ba3-445c-9693-4144b0e2c519%2Ctemplate%3Dbegrunnelse%2Ctype%3Dbegrunnelse)
=> Legg til ny begrunnelse for motregning

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/AvregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/domene/Simulering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/SamhandlerTestConfig.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/AvregningServiceTest.kt
Reverts navikt/familie-ba-sak#5448
=> Revert "Legger til overlappendePerioderMedAndreFagsaker til simulering"

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/AutovedtakFinnmarkstillegg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/Brev.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25762
Legger til finnmarkstillegg som årsak + vedtaksbrev
=> Legger til finnmarkstillegg som årsak + brev

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlageClient.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlagebehandlingHenter.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlagebehandlingHenterTest.kt
Favro: [NAV-25831](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25831)
Tar i bruk nytt endepunkt i familie-klage for henting av klagebehandlinger som er mer tilpasset BAKS.
=> NAV-25831: Utvider KlageClient med kall mot nytt endepunkt i familie-klage for henting av klagebehandlinger

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlRestClient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/SystemOnlyPdlRestClient.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/preutfylling/PreutfyllBosattIRiketService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/preutfylling/PreutfyllLovligOppholdService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/MockPdlRestClient.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/preutfylling/PreutfyllBosattIRiketServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/preutfylling/PreutfyllLovligOppholdServiceTest.kt
[Bolkspørring mot PDL er bare tilgjengelig for systembruker](https://arc.net/l/quote/lnburlxl).
Bruker systembruker for å hente adresser i bolk.
Per nå brukes bare spørringen for å hente adresser til preutfylling, som ikke viser adressen, bare om personen bor i Norge.
=> Bruk SystemOnlyPdlRestClient for å hente adresser i bolk

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestHentFagsakerForPerson.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/domene/RestFinnOppgaveRequest.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/AutovedtakStegService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/Filtreringsregel.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/FiltreringsreglerService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/småbarnstillegg/AutovedtakSmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingMetrikker.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentDistribueringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/statsborgerskap/StatsborgerskapService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/PersonopplysningGrunnlagForNyBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/VilkårsvurderingForNyBehandlingUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingMetrics.kt, src/main/kotlin/no/nav/familie/ba/sak/task/DistribuerDokumentPåJournalpostIdTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/MockPersonopplysningerService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/SanityKlientMock.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/FiltreringsregelTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/AutomatiskBeslutningServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtbetalingssikkerhetTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevTypeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingStateTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceIntegrationTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25872
Vi går bort ifra values()
=> Values() til Entries for enum

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25765
Vi legger til finnmarkstillegg begrunnelse (dummy foreløpig)
=> Vi legger til en foreløpig dummy tekst for innvilgelse av finnmarkstillegg

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt
Trenger for undersøke hvorfor man ikke finner riktig person i relasjon
=> Legg til behandling.id i fallback-logging for søk

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardstillegg/FinnPersonerSomBorIFinnmarkNordTromsEllerPåSvalbardTask.kt
Konverter Int til String før det lagres i metadata
=> Lagre metadata som String i task

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt
Favro: [NAV-25971](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25971)
Legger til endepunkt for å teste om fagsaker vi har logget ut at har utbetalinger over 100% fortsatt feiler for å feilsøke hvorfor de feiler.
=> Legger til nytt endepunkt i ForvalterController for å sjekke om utbetalingene til person i fagsak overstiger 100%

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt
Legger til enda litt mer logging, utvidelse av #5568
=> Legg til logging i endepunkt som oppretter tasker for å finne personer med oppholdsadresse på Svalbard

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt
Kunne visst ikke ha `ORDER BY` på den måten 🥸
=> Fjern ORDER BY i spørring for å hente identer

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardstillegg/FinnFagsakerForPersonerSomBorPåSvalbardTask.kt
Farvo: NAV-25970
Vi ønsker å finne ut hvilke fagsaker der minst én aktør har oppholdsadresse på Svalbard, og hvilke saker som kanskje skal få Svalbard tillegg, i.e. søker og minst ett barn bor på Svalbard
- Legger til task som tar inn en liste med fagsaker og lister ut hvilke fagsaker der deltakere har oppholdsadresse på svalbard
- Legger til endepunkt som oppretter tasker for å finne fagsaker
Legger til div parametre på endepunktet, slik at det er lettere å finne ut hvor mye en pod håndterer før alle taskene opprettes
=> Task for å finne fagsaker på Svalbard

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardstillegg/FinnFagsakerForPersonerSomBorPåSvalbardTask.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelseRepository.kt
Det kastes en feil fordi enum'et konverteres til indeksen, ikke til navnet 🥸
=> Sjekk enum som string i stedet for enum SQL

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Legg til ny opphørsbegrunnelse
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26075
=> Legg til ny opphørsbegrunnelse

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/minside/MinSideBarnetrygdController.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/minside/MinSideBarnetrygdControllerTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26084
Fjerner toggle da den har vært skrudd på i prod en stund.
Nei
=> NAV-26084: Fjerner toggle fra min side endepunkt

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakController.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26085
Fjerner toggle da den har vært skrudd på i prod en stund.
Nei
Ikke relevant.
=> NAV-26085: Fjerner toggle for bruk av ny modal for oppretting av fagsak

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardstillegg/FinnPersonerSomBorPåSvalbardIFagsakerTask.kt
Vi trenger enda mer detaljer om hvilke personer som bor på Svalbard i gitte fagsaker
=> Finn personer som bor på Svalbard i gitte fagsaker

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SatsService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SvalbardtilleggGeneratorTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26077
=> Svalbardstillegg 1 oktober justering

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregnAndelerTilkjentYtelseMedGjeldendeSatserTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseGeneratorTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/VilkårTilTilkjentYtelseTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/VilkårVurderingBuilder.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26119
Sletter toggle koblet til svalbardtillegget
=> Sletter toggle koblet til svalbardtillegget

src/main/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIVilkårsvurderingUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25968
Anna flyttet denne over til institusjonsmappen, så vi må endre på typen.
=> Flytt begrunnelse

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepositoryTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26210
Legger til metode på FagsakRepository for å finne løpende fagsaker for svalbardtillegg kjøring. Metoden skal brukes av scheduler-klasse som oppretter tasker for kjøring av Svalbardtillegg. 
Legger også til en feature toggle. 
Nei
=> NAV-26210: Legger til metode på FagsakRepository for å finne løpende fagsaker for svalbardtillegg kjøring.

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardstillegg/AutovedtakSvalbardtilleggScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardstillegg/AutovedtakSvalbardtilleggTaskOppretter.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardstillegg/AutovedtakSvalbardtilleggSchedulerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardstillegg/AutovedtakSvalbardtilleggTaskOppretterTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26210
Legger til `AutovedtakSvalbardtilleggScheduler` og tilhørende klasser/tester. 
Skal opprette tasker for alle fagsaker som har en iverksatt behandling (med personopplysningsgrunnlag) og som inneholder en person som har en relevant adresse på Svalbard
Oppretting av tasker blir gjort i https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26202
Nei
=> NAV-26210: Legger til AutovedtakSvalbardtilleggScheduler til tilhørende klasser/tester.

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggTaskOppretter.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggSchedulerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggTaskOppretterTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26280
Refaktorerer AutovedtakFinnmarkstilleggScheduler slik at strukturen ligner mer på AutovedtakSvalbardtilleggScheduler
Nei
=> NAV-26280: Refaktorerer AutovedtakFinnmarkstilleggScheduler slik at strukturen ligner mer på AutovedtakSvalbardtilleggScheduler

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggBegrunnelseService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggBegrunnelseUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/AutovedtakSvalbardtilleggBegrunnelseService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/AutovedtakSvalbardtilleggBegrunnelseUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/AutovedtakSvalbardtilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggBegrunnelseServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggBegrunnelseUtilTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/AutovedtakSvalbardtilleggBegrunnelseServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/AutovedtakSvalbardtilleggBegrunnelseServiceTest.kt.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/AutovedtakSvalbardtilleggBegrunnelseUtilTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/AutovedtakSvalbardtilleggServiceTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26203
Legger til begrunnelse for vedtaksperioder for svalbardtilegg.
- [x ] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇
- [ x] Nei
=> Autokjøring svalbardtillegg, begrunne vedtaksperioder 

src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyService.kt
Favro: [NAV-26278](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26278)
Trekker deler av logikken i metoden `oppdaterVilkårUtenFomTilFødselsdato` ut i egne hjelpemetoder for bedre lesbarhet.
[Issue i Sonar](https://sonarcloud.io/project/issues?impactSeverities=HIGH&issueStatuses=OPEN%2CCONFIRMED&id=navikt_familie-ba-sak&open=AZJxcoo393Lv11l1eJJJ)
=> NAV: 26278: Legger til noen hjelpemetoder for å gjøre automatisk utfylling av VilkårResultater i dev mindre kompleks

.nais/app-prod.yaml
NAV-26316
pgaudit "write,ddl,role"
doc.nais.io/persistence/cloudsql/how-to/enable-auditing#configure-database-flags-for-your-sql-instance
=> Endrer pgaudit til anbefalte verdier i dokumentasjonen

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentGenereringService.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26385
Per nå dukker alle funksjonelle feil opp som feil når generering av brev feiler.
Oppdaget under vakt, så fikser dette.
=> Fiks støyende logg når det dukker opp funksjonelle feil ved generering av brev

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggTaskOppretter.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggTaskOppretterTest.kt
Favro: NAV-26388
- Setter ned antall behandlinger som kjøres per 10. minutt til 100
- Legger til mer logging
- Opprett tasker i egen transaksjon
=> Forbedrer opprettelse av autovedtak finnmarkstillegg

src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/komponentMocks/MockPersongrunnlagService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/fake/FakePersonopplysningerService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagIntegrationTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26471
Utvider oppdatering av adresser etter kopi av personopplysning grunnlag med test.
=> Utvider oppdatering av adresser etter kopi av personopplysning grunnlag med test
