navikt/familie-ba-sak

README.md, pom.xml, src/main/kotlin/no/nav/familie/ba/sak/behandling/FagsakController.kt, src/main/kotlin/no/nav/familie/ba/sak/config/FlywayConfiguration.kt, src/main/kotlin/no/nav/familie/ba/sak/task/AvstemMotOppdrag.kt, src/main/kotlin/no/nav/familie/ba/sak/task/DefaultRestTaskMapper.kt, src/main/kotlin/no/nav/familie/ba/sak/økonomi/AvstemmingService.kt, src/main/kotlin/no/nav/familie/ba/sak/økonomi/AvstemmingTaskDTO.kt, src/main/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiKlient.kt, src/test/kotlin/DevLauncher.kt, src/test/kotlin/no/nav/familie/ba/sak/task/AvstemMotOppdragTest.kt, src/test/kotlin/no/nav/familie/ba/sak/util/DbContainerInitializer.kt, src/test/resources/application-postgres.yaml
Task som kjører løpende grensesnittavstemming. Når tasken er fullført, beregner den når neste avstemming skal kjøre og oppretter en task på det. Er litt usikker på om vi skal sende med fagområde som parameter etc på requesten til familie-oppdrag eller om familie-oppdrag kan klare å trekke det ut av tokenet. 
Er litt usikker på hvordan vi skal sette i gang den aller første avstemmingen. Lagde et endepunkt for det som jeg har brukt for å teste, men det er jo litt malplassert i FagsakControlleren. Endepunktet slettes så klart når vi har trigget første avstemming. Vi kan evt gjøre en manuell insert til task-basen, men litt hassle å få all inputdataen riktig (call-id, payload osv). Tar gjerne i mot meninger/innspill her. 
Ellers litt flikking på det lokale postgres-oppsettet slik at man kan …
=> Grensesnittavstemming

src/main/kotlin/no/nav/familie/ba/sak/task/IverksettMotOppdrag.kt
Iverksetting-tasken kjører `økonomiservice.iverksettVedtak(..)` i sin `doTask`. Denne oppdaterer statusen på behandlingen til `SENDT_TIL_IVERKSETTING`. Fikser slik at `onCompletion` sjekker at behandlingen har den oppdaterte statusen og ikke `OPPRETTET`.
=> Bugfix: Sjekk riktig status etter at iverksetting har kjørt

src/test/kotlin/no/nav/familie/ba/sak/økonomi/BeregningTest.kt
Behandling på fnr 0 er allerede i bruk i en annen test - switcher denne til 12345 for å unngå kollisjon.
=> Integrasjonstestbugfix.

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/mottak/MottakController.kt, src/main/kotlin/no/nav/familie/ba/sak/task/IverksettMotOppdrag.kt, src/test/kotlin/no/nav/familie/ba/sak/BehandlingIntegrationTest.kt, src/test/kotlin/no/nav/familie/ba/sak/BehandlingNegativeIntegrationTest.kt, src/test/kotlin/no/nav/familie/ba/sak/økonomi/BeregningTest.kt, src/test/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiIntegrasjonTest.kt
Restrukturering av BehandlingService for å støtte at vi kan oppdatere en behandling dersom det kommer flere hendelser på samme søker innenfor et gitt tidsrom (foreløpig må behandlingen være OPPRETTET eller UNDER_BEHANDLING)
Tester er endret pga endret flyt.
Test for å oppdatere behandling er lagt til.
EDIT: Vi har nå to endepunkter, ett for frontend og ett for hendelser, som håndterer nye behandlinger på litt ulik måte.
=> Opprett eller oppdater behandling

src/main/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiKlient.kt
Send over listen av oppdrag til konsistensavstemming uten å stringifisere den først, da server-siden ikke klarer å deserialisere stringen.
=> Bugfix: Deserialisering av oppdrag til konsistensavstemming

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/Vilkårsvurdering.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/BehandlingIntegrationTest.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårVurderingTest.kt, src/test/kotlin/no/nav/familie/ba/sak/beregning/BeregningNegativeIntegrationTest.kt, src/test/kotlin/no/nav/familie/ba/sak/dokument/DokumentServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/task/FerdigstillBehandlingTest.kt, src/test/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiIntegrasjonTest.kt
Lista av restvilkårresultat som sendes inn til `lagreEllerOppdaterVedtakForAktivBehandling` ser ikke ut til å ha blitt brukt på en stund. Ikke stor endring, men tar det i egen pr siden det treffer en del filer
=> Fjern ubrukt parameter

src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/PersonController.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/IntegrasjonOnBehalfClient.kt, src/main/kotlin/no/nav/familie/ba/sak/validering/Persontilgang.kt, src/main/kotlin/no/nav/familie/ba/sak/validering/PersontilgangConstraint.kt, src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt, src/test/kotlin/no/nav/familie/ba/sak/validering/PersontilgangTest.kt
Tilgangskontroll gjøres her mot returverdien til kontrolleren, ikke på parametere på vei inn. Dette fordi vi på det tidspunktet ikke har alle data vi trenger å gjøre kontroll mot (vi har kun personident på søker, ikke på familierelasjonene). Sjekken gjøres derfor mot returverdien slik at vi ikke må gjøre et ekstra oppslag mot PDL.
=> Lagt på tilgangskontroll ved henting av personinfo.

src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/søknad/SøknadDTO.kt
Legger til "inkludertISøknad" slik at vi lagrer alle barna som ble vurdert og huker av de som det ble søkt for. Dette for å presentere hva som ble lagret og for at saksbehandler kan se hvilke barn pdl hentet.
=> Utvider søknaden for å matche dto frontend.

src/main/kotlin/no/nav/familie/ba/sak/beregning/BeregningController.kt, src/main/kotlin/no/nav/familie/ba/sak/beregning/TilkjentYtelseService.kt, src/main/kotlin/no/nav/familie/ba/sak/beregning/domene/PeriodeResultat.kt, src/test/kotlin/no/nav/familie/ba/sak/beregning/BeregningServiceTest.kt, src/test/resources/beregning/vilkår_til_tilkjent_ytelse/søker_med_ett_barn_inntil_to_perioder.csv
Noen småfikser på beregning 🔨 
- Returner en tom liste opp til beregningsoversikten i frontend hvis søker ikke har fått noen utbetaling. Tidligere feilet endepunktet og skapte støy i logger/alerts
- I tilfeller hvor det ikke er 18-års vilkåret som begrenser tom-dato for stønaden, settes tom-dato til den siste måneden hvor vilkårene er innfridd. Tidligere var tom-datoen satt til måneden etter, klassisk misforståelse rundt begrepsbruk 🤦‍♀️ 
- Kast feil dersom både søker og barn har nullverdi i fom eller tom på vilkårsresultatet. Tidligere feilet denne "stille" og vilkårsvurderingen gikk gjennom, det ble bare ikke opprettet andeler og neste skjermbilde kræsjet.
=> Bugfix: Beregning

src/main/kotlin/no/nav/familie/ba/sak/beregning/BeregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/beregning/TilkjentYtelseService.kt, src/test/kotlin/no/nav/familie/ba/sak/beregning/BeregningServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/beregning/VilkårTilTilkjentYtelseTest.kt
Logikk for å hente riktig sakstype i beregning. For tredjelandsborgere er det avhengig av søknadsgrunnlaget, ikke bare behandlingskategorien
=> Bugfix: Beregning med Tredjelandsborger

src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakController.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/StatusFraOppdrag.kt, src/main/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiService.kt
Ny behandlingstype for teknisk opphør, for å støtte opphør på mer enn migreringer. Noen justeringer i opphørsfunksjonalitet etter store endringer i vilkårsvurdering og beregning i det siste. 
Har testet dette med postgres lokalt og ser ut til å fungere.
=> Teknisk opphør mot økonomi

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingController.kt, src/main/kotlin/no/nav/familie/ba/sak/task/SimuleringTask.kt
In the previous PR we created a task for simulating "behandling" for "fødselshendelse", but we did not save it to task repository, which caused the task never being executed. The PR fixes the bug by saving the task, and also added log to make the execution of task easier to trace.
=> Save the simulation task after creating it

src/main/kotlin/no/nav/familie/ba/sak/økonomi/Utbetalingsoppdrag.kt, src/main/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiService.kt, src/test/kotlin/no/nav/familie/ba/sak/toTrinnKontroll/ToTrinnKontrollTestConfig.kt, src/test/kotlin/no/nav/familie/ba/sak/økonomi/UtbetalingsoppdragTest.kt
Når Utbetalingsoppdraget lages, sender vi med et flagg som sier om det er første behandling på fagsaken slik at vi vet hvilken kode vi skal bruke for oppdraget (NY eller UENDR)
=> Fiks for å iverksette migrering på nytt etter opphør

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingController.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/StegService.kt, src/test/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTaskTest.kt
Utvider hendelse DTO med morsIdent. Etter at ba-mottak har tatt i bruk morsIdent, så skal søkersIdent slettes.
=> Utvider kontrakt til å ta imot morsIdent

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/BehandlingResultat.kt, src/main/kotlin/no/nav/familie/ba/sak/dokument/MalerService.kt, src/test/kotlin/no/nav/familie/ba/sak/dokument/MalerServiceTest.kt
Når man kaller dokgen sender man template-navn i url. Endrer navnene til å være bedre tilpasset dette ved å fjerne spaces. Endret i samme slengen til å konsekvent bruke lowercase, som er det som påvirkes her. 
Endring i dokgen: https://github.com/navikt/familie-ba-dokgen/pull/40
=> Oppdater nøkler på templates

src/main/kotlin/no/nav/familie/ba/sak/oppgave/OppgaveService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettOppgaveTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/dto/OpprettOppgaveDTO.kt, src/main/kotlin/no/nav/familie/ba/sak/task/dto/OpprettOppgaveTaskDTO.kt
Pga TEA-1381 (https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-1381) må vi kunne legge ved en beskrivelse når vi oppretter en oppgave.
Dersom en beskrivelse legges ved, kommer denne i tillegg til den generiske beskrivelsen ("-----laget av familie-ba-sak med fagsak....")
Kode som pr. nå benytter opprettOppgave eller opprettOppgaveTask er uberørt av denne endringen.
=> Utvid opprettOppgave med beskrivelse som parameter.

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/StegService.kt
Har lagt til et par metrikker og gjort noen utbedringer etter gjennomgang med @EAamli . (https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-1139
).
På steg-oversikt er det ønskelig å sortere stegene i sin "naturlige" rekkefølge. Finner ikke noen måte å sortere legend på Graph, så legger til steg i beskrivelse-taggen i stedet for i en egen tag siden legend (beskrivelse) for graph sorteres alfabetisk by default. Hvis noen vet hvordan man kan sortere på tag tas det gjerne i mot tips. For alle pie charts kan man velge å sortere på antall ved å klikke på header som jeg nå har kalt "Antall".
=> Sorter beskrivelse for lesbarhet i grafana

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingController.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt, src/main/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdBarnetrygdClient.kt, src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/GDPRInnhentingTest.kt, src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt, src/test/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdBarnetrygdClientMock.kt, src/test/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTaskTest.kt
Siden det feilet mot infotrygd-replikaen i dag, og dette kjøres utenfor task-rammeverket, flytter vi dette til BehandleFødselshendelseTask så det går an å rekjøre tasken dersom det feiler mot infotrygd-replika i fremtiden.
Det er også gjort noen endringer for å gjøre ting tydeligere:
- siden det er lett å glemme hvordan rutingen skal se ut når vi går live, er flyten skrevet inn som kommentarer.
- korrekt navngivning av variabler/funksjonsnavn mot infotrygd-replika
- unngå dobbel negasjon
Metrikk er flyttet til tasken og fortsetter å telle på samme måte som tidligere.
=> Sjekk mot infotrygd og ruting av hendelser: Flytt til task og redegjør flyt.

src/main/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdFeedClient.kt, src/main/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdFeedService.kt, src/main/kotlin/no/nav/familie/ba/sak/infotrygd/domene/FeedDto.kt, src/main/kotlin/no/nav/familie/ba/sak/task/SendFeedTilInfotrygdTask.kt, src/test/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdFeedClientTest.kt, src/test/kotlin/no/nav/familie/ba/sak/infotrygd/SendFeedTilInfotrygdTaskTest.kt
En task 'send feed til Infotrygd' per barn ble opprette.
Det er redusert til at en task per fødselsmleding blir opprettet.
=> Opprett en task send til infotrygd per fødselsmelding

.github/workflows/build-and-deploy-preprod-skip-e2e.yml
Til testing av brancher i miljø. Kan kun trigges manuelt (workflow dispatch).
På pull requester kjøres flyt med e2e.
=> Legg til preprod-workflow uten e2e-tester

src/main/kotlin/no/nav/familie/ba/sak/dokument/MalerService.kt, src/main/kotlin/no/nav/familie/ba/sak/dokument/domene/maler/Innvilget.kt
- Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-2468
- Oppdaterer innvilgelsemaler for førstegangsvedtak (manuell) og revurdering: https://github.com/navikt/familie-ba-dokgen/pulls
- Trenger da etterbetalingsbeløp for begge og feilutbetaling for revurdering. Ikke implementert simulering enda.
=> Legg til etterbetaling og feilutbetaling på innvilgelsebrev 

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt, src/main/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkEventListener.kt, src/main/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkEventPublisher.kt, src/main/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkService.kt, src/main/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkTestController.kt, src/main/kotlin/no/nav/familie/ba/sak/task/PubliserVedtakTask.kt, src/main/kotlin/no/nav/familie/ba/sak/vedtak/producer/KafkaProducer.kt, src/main/kotlin/no/nav/familie/ba/sak/vedtak/verktøy/KafkaController.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt, src/test/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkEventPublisherFailSafe.kt, src/test/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/task/FerdigstillBehandlingTaskTest.kt, src/test/kotlin/no/nav/familie/ba/sak/task/PubliserVedtakTaskTest.kt
Ny metode for mapping til SakDVH-kontrakten i SaksstatistikkService.
Publiserer sakshendelse ved opprettelse og oppdatering av fagsakstatus.
Lagt til assertions på at meldinger blir publisert til kafka-topic i enkelte integrasjonstester som treffer den nye koden.
Lagt til Test config med fail-safe SaksstatistikkEventPublisher bean, for at saksstatistikk ikke skal være en show stopper i test context. 
Lagt til getSakDVH i i testcontroller for enkelhets skyld i preprod.
=> Mapping og publisering av melding til datavarehus-topic ved fagsakoppdateringer

src/main/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkService.kt, src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt
Fjerner any()-matcher'en for hentPersoninfoMedRelasjoner og samler alle mock-responser 
i en answers blokk med branching basert på capture(slot) istedenfor
=> Fikser bug i ClientMocks

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/dokument/MalerService.kt
I enkelte tilfeller er det ønskelig å vise flere punkter begrunnelser for en begrunnelse. Splitter begrunnelser på linjeskift, slik at disse sendes som liste til dokgen. Vurderte muligheten for å lagre som separate databaseinnslag, men tror det blir veldig rotete mtp id'er og oppdatering. 
Forrige forsøk på å legge inn unicode bulletpoints så veldig rart ut. 
Resultat nå:
=> Forbedringer på malerservice - gjør det mulig å sende liste begrunnelser

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt, src/test/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTaskTest.kt, src/test/kotlin/no/nav/familie/ba/sak/økonomi/KonsistensavstemmingSchedulerTest.kt
Kjører fødselshendelser i egen transaksjon så rollback fungerer. Rollback testet manuelt.
=> Oppdatert felles-prosessering

src/main/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkEventListener.kt, src/main/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkService.kt, src/main/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkTestController.kt, src/test/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkServiceTest.kt
Går vekk fra å bruke UtbetalingBegrunnelser og henter resultat og resultatBegrunnelser fra BehandlingResultat istedenfor.
I tillegg har vi en fiks for ikke å sende saksstatistikk ved autovedtak som rulles tilbake.
Har lagt inn Todo's på uthenting av resultatBegrunnelse ved OPPHØRT, HENLAGT OG DELVIS_INNVILGET resultat. Men sistnevnte kan nok langt på vei bruke en kombinasjon av resultatBegrunnelsene for AVSLÅTT OG INNVILGET når disse er godkjent
=> Fiks: Sende riktig resultatstruktur til datavarehus

src/main/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkService.kt, src/test/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkServiceTest.kt
Tea-2677
Lagt til default value. Burde vi ha andre dataoer på de nye årsakene?
Lag til test som detekterer nye.
=> Default verdi for behandlingsårsak og test for å catche nye

.github/workflows/build-and-deploy-preprod.yml
Ser at det er hensiktsmessig å ha åpne drafts en stund for diskusjon mens arbeidet fortsatt er WIP. Da er det fort gjort å glemme at det deployer mens man utveksler kode. Vet ikke om dette funker, men vi kan jo prøve? 
https://github.community/t/dont-run-actions-on-draft-pull-requests/16817/16
=> Teste ut for å unngå så mye trafikk ved draft-pr

src/main/kotlin/no/nav/familie/ba/sak/common/Tid.kt, src/test/kotlin/no/nav/familie/ba/sak/common/TidTest.kt, src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-2746
I dag oppdaga en av superbrukerne at t.o.m ble forskjøvet et år i brevet : 31.12.19 -> 31.12.20 🐛 
Fikk gjenskapt samme greia for desember 2020 og 2018, men skjer ikke desember 2017. What?😭 
Vi bruker visst week years **Y** når vi formaterer datoer, og for de årene som blir forskjøvet lander 31. desember i uke 1 påfølgende år 🗓️ 
Endrer nå til year-of-era (**y**) på alle og legger til en liten test.
=> Fiks bug pga bruk av week based year

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingService.kt
@oyvindhagen  kom med en god observasjon, og denne sjekken gjøres egentlig duplikat. Kaller derfor bare sjekken og legger inn en kommentar.
=> Tydligere kode etter pr-review

src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakController.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestFagsakSøk.kt, src/main/kotlin/no/nav/familie/ba/sak/beregning/BeregningService.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakControllerTest.kt
Utvider søkEtterPågåendeSak-tjenesten med ekstra input-parameter over søkers barn
og endrer logikken som avgjør om det finnes sak tilknyttet søker i ba-sak/infotrygd
til å inkludere saker tilknyttet barna
=> Endringer ifm. utvidelse av rutingreglene for dokument

src/main/kotlin/no/nav/familie/ba/sak/config/KafkaProducerConfig.kt
egen objectmappper for kafka, som skipper json med verdier null, slik at det skal validere med json schema.
Nei
=> Eksluderer non-null fields kafka json

src/main/kotlin/no/nav/familie/ba/sak/dokument/MalerService.kt
Bruker samme logikk for å generere innvilget og opphørt brev som for innvilget. Resultatet er støttet, men det var ikke mappet opp ved brevgenerering. Har bedt Eivind om å bekrefte at det er riktig å bruke samme logikk for de 2 resultatene.
Nei
Bug
Alt i ett
=> BUG: innvilget og opphørt brevgenerering

src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestPersonResultat.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårResultat.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårService.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårsvurderingUtils.kt, src/main/resources/db/migration/V107__vilkår_resultat_er_automatisk_vurdert.sql, src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårServiceTest.kt
Legger til logikk for å vurdere om et vilkår er automatisk behandlet. Oppdaterer kun under 18 år vilkår på data i produksjon da vi ikke kan garantere for gift vilkåret. Logikken frontend var at "endretAv=VL". Det blir riktig for autovedtak, men ikke for manuell behandling der vi "manuelt" bygger en vilkårsvurdering.
Lager det som draft slik at jeg kan endre på migreringsscriptet.
VilkårResultat begynner å bli litt stor, så man kan vurdere om man heller skulle innført en status på vilkåret (IKKE_TATT_STILLING_TIL, AUTOMATISK_VURDERT, MANUELT_VURDERT, MANUELT_OVERSTYRT etc)
Alt i ett
=> BUG: Automatisk vurdert vilkår

src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt
Dato i opphørsbrevene var feil. Den var satt til f.o.m dato, men skal være t.o.m dato
Siden vi per i dag setter opphørs-begrunnelse på den siste oppfylte perioden, skal datoen i brevet til f.eks. teksten "du flyttet fra Norge november 2020" være t.o.m på den siste perioden. 
Alt i ett
=> Sett dato i opphørsbrev til tom-dato

src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/PersonController.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestPersonInfo.kt, src/main/kotlin/no/nav/familie/ba/sak/pdl/PersonopplysningerService.kt
Utvider RestPersonInfo med harTilgang, og henter adressebeskyttelsegradering dersom saksbehandler ikke har tilgang (på samme måte som hentMaskertFagsakdeltakerVedManglendeTilgang i FagsakService).
Dette trengs for å gi korrekt feilmelding når saksbehandler prøver å endre til en kode 6 / 7 bruker via "endre bruker" i manuell journalføringsvinduet.
Annoteringen PersontilgangConstraint blir fjernet, da den da blir overflødig.
Hovedfunksjonaliteten er allerede testet, det er kun gjort små modifikasjoner. Ser over at ting ser riktig ut på vei ut til frontend.
- [x ] Nei
=> Legger til harTilgang til RestPersonInfo

src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt, src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt
Sjekken på dato ble bare gjort på måned. Sjekker nå også på år.
Annet ikke aktuelt.
Endrer på clientmocks da det ikke gir så mye verdi å ha mockdata på barn født inneværende måned. Dette er mest nyttig for fødselshendelser.
=> Bug - måned og år compare på begrunnelser

src/main/resources/db/migration/V110__slett_tomme_vedtakbegrunnelser.sql
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-3643 
Bug meldt inn via sentry hvor saksbehandler får feil ved forsøk på å gå inn på vedtaksside. 
Tidligere la man til "tomme entries" som man så la til begrunnelse i. Nå gjøres en antakelse om at begrunnelser bare legges til og slettes. Bugen er at noen behandlinger (som den Berit har trøbbel med) er under behandling og har påbegynt begrunnelsedelen med tom begrunnelse. 
Har validert i prod at man kun sletter på behandlinger hvor vedtak ikke er gjort 
`select * from vedtak_begrunnelse inner join vedtak v on v.id = vedtak_begrunnelse.fk_vedtak_id where begrunnelse is null and vedtaksdato is not null;
`
=> Slett tomme vedtakbegrunnelser

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/RegistrerPersongrunnlag.kt
Sett målform til forrige behandlings målform som default for at varsel om revurdering skal kunne sendes på nynorsk 
Bakgrunn: 
Siden registrering av persongrunnlag og sending av brev skal kunne skje før registrering av søknad defaultes det til bokmål inntil vi får integrert mot tjenesten som tilbyr målform (KRR?). I revurderinger uten søknad (f.eks. nye opplysninger) får man aldri mulighet til å sette målform igjen og denne defaulter til målform. I disse tilfellene setter jeg derfor til den gamle. 
Validerer i miljø
=> Sett forrige målform som default på revurdering

src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/PersonRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseUtils.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakBegrunnelseTest.kt
Ved generering av begrunnelsestekst for reduksjon, grunnet fylte 6 år, til vedtaksbrev ble ikke barnets fødselsnummer inkludert. 
=> La til barns fødselsnummer til 6års begrunnelse

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/beregning/domene/PeriodeResultat.kt
Ref nylige feil i # team-familie-alerts på slack: https://nav-it.slack.com/archives/CK59Y6EHE/p1613650956160400
Frontend gjør validering på enkeltvilkår, men validering som ser på helhet gjøres ved validerVilkårsvurderingOgSendInn. Da håndteres VILKÅRSVURDERING-steget backend, som også beregner tilkjent ytelse fra vilkårsvurdering, som gjør ytterligere sjekker på vilkårene. Manglende datoer i vilkårsvurderinga har nå trigga error i `PeriodeResultat.overlapper`, men er egentlig en funksjonell feil. Funksjonen brukes kun til dette. 
Alt i ett
=> Kast funksjonell feil ved manglende dato fra vilkårsvurdering 

src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestPersonResultat.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårsvurderingUtils.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårsvurderingUtilsTest.kt
Bug som oppstår når _samme_ periode skal muteres fra avslag til løpende JA eller omvendt.
Beskrivelse:
1. Lage avslag på perioden
2. Endre samme periode til en JA -løpende periode 
3. Når den validerer kommer den til å sammenligne med alt som eksisterer på vilkåret, inkludert seg selv og kaster feil
4. I databasen blir derfor ingenting endret (som jo er rett hvis det finnes feil), men i frontenden holder man fortsatt på å redigere vilkår som man nå egentlig skal rette opp i henhold til feilmelding (som er feil at blir kasta). Hvis man reloader siden ser man hvordan dataene som ligger backend er.
Tror det løser seg ved å fikse sammenlignenden på 3.
Et par linjer er bare for 💄 ✨  , selve bugfixen skjer [på denne linja](https://github.com/navikt/familie-ba-sak/compare/fix/avslag-validering?ex …
=> Fiks feil ved mutering av eksisterende vilkår

src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt, src/main/kotlin/no/nav/familie/ba/sak/dokument/DokumentController.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakBegrunnelseTest.kt, src/test/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiIntegrasjonTest.kt
**Bakgrunn:**
I forbindelse med lagring av vedtaksbegrunnelser for avslag er det behov for å lagre vedtak tidligere. 
Nå lagrer vi nye vedtak hver gang en saksbehandler trykker seg videre fra vilkårsvurderinga og ender med mange vedtak.  
Ønsker å initiere tomt vedtak til tidligere i løpet og kun lagre nye rader i databasen på nye behandlinger og etter underkjenning. 
**Denne pr'en:** 
- rename `lagreEllerOppdater` -> `oppdater` (stedene det kalles gjør bare oppdater og skal kaste feil hvis vedtak ikke finnes, så endring av navn er for å tydeliggjøre at det er det den brukes til, også ved senere bruk. Lagring/initiering skal kun skje via en egen metode med mer businesslogikk)
- Fjern vedtaksbrevlogikk fra `oppdater` og la `oppdaterVedtakMedStønadsbrev` lagre selv
_Har du husket alle …
=> Funksjon eksplisitt for oppdatering og egen for brev

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdBarnetrygdClient.kt, src/main/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdController.kt, src/main/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdService.kt, src/test/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdBarnetrygdClientMock.kt, src/test/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdBarnetrygdClientTest.kt, src/test/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdControllerTest.kt
Modulen for barnetrygd i familie-kontrakter har endrede pakkenavn i hht standard pakkenavn for familie-kontrakter.
Denne commiten synker kun ba-sak med familie-kontrakter.
=> Synk med ny versjon av kontrakter

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/StegService.kt, src/test/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkEventPublisherFailSafe.kt, src/test/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkTest.kt, src/test/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTaskTest.kt, src/test/kotlin/no/nav/familie/ba/sak/toTrinnKontroll/ToTrinnKontrollTest.kt
Flyttet logikk for utsending av saksstatistikk ned til metodene som lagrer til databasen. Dette gjør av vi sender ut oftere og ved endringer. Det blir vanskeligere å opprette saker og behandlinger uten at det sendes til DVH som i journalføringsservice, som brukte metode som ikke sendte til dvh.
Det er større sjanse for dupliserte meldinger, men tror dette skal være ok.
Sikkert lurest å starte med FagsakService og BehandlingService
=> Flytter sending av saksstatistikk til å få med flere hendelser

src/main/kotlin/no/nav/familie/ba/sak/behandling/MigrerBehandlingerUtenInitialisertVedtak.kt
https://github.com/navikt/familie-ba-sak/pull/831
Da dette ble gjort ble ikke initiering gjort på behandlingene som var opprettet tidligere enn migrering og ikke hadde kommet til vedtaksteget enda. 
Fører til følgende bug for behandlingene dette treffer:
https://nav-it.slack.com/archives/C01G9BA8JKZ/p1615207754045000
=> Migrer behandlinger opprettet før vedtakinitiering ble innført ved opprettelse av behandling

src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/Vedtak.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårService.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårsvurderingUtils.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/AvslagBegrunnelseOppdateringTest.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/AvslagBegrunnelseTest.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårsvurderingStegUtilsTest.kt
Dersom man har ikke-oppfylte perioder og legger til en oppfylt periode som overlapper med disse muteres/fjernes periodene som treffes. I tilfellene hvor de eksisterende periodene blir slukt helt (og dermed fjernes) ble avslagbegrunnelsene nå hengende igjen i databasen. (Orphanremoval kan ikke brukes her pga begrunnelsens tilknytning til vedtak.)
- [Test av funksjonalitet](https://github.com/navikt/familie-ba-sak/compare/bugfix/avslagbegrunnelser?expand=1#diff-4ae7b132675b3120a2ea60776cf82646335ce44f3097272cae2821e3d1ccdf8cR250-R268)
- [Oppdatert endreVilkår-funksjon](https://github.com/navikt/familie-ba-sak/compare/bugfix/avslagbegrunnelser?expand=1#diff-50759c261f5c1a9857e2172b9a91e1ea7087a460d28e5e39eae649fba76dde06R44-R69)
=> Fiks bug som gjør at avslagbegrunnelser blir hengende igjen når periode blir "slukt" av innvilget periode

src/main/kotlin/no/nav/familie/ba/sak/behandling/MigrerJournalføringBehandlingerMedManglendeData.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/MigrerNyeBehandlinger.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/StegService.kt, src/main/kotlin/no/nav/familie/ba/sak/dokument/DokumentService.kt, src/main/kotlin/no/nav/familie/ba/sak/journalføring/JournalføringService.kt
- [Bugfix: Saksbehandler får ikke opp søker for å sende brev](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4045)
- Årsak: PersonopplysningsGrunnlag fantes ikke
- Løsning: `NyBehandling` må gjennom funksjonen `håndterNyBehandling` (blir da likt som ved opprettelse via fødselshendelse og manuelt fra behandlingsmeny) 
Se kommentarer.
Migrering testes på tilsvarende caser i dev.
Når det gjelder utplukking av behandlinger for migrering i prod har Eivind fått fagsakider og skal dobbeltsjekke at det er korrekt før migrering.
=> Bugfix: Saksbehandler får ikke opp søker for å sende brev

src/main/kotlin/no/nav/familie/ba/sak/behandling/MigrerJournalføringBehandlingerMedManglendeData.kt
Virker som sjekk av leader ble gjort før leader election er klart og at 60 sek kanskje er helt på grensa. Øker ventetid til 4 min.
=> Vent 4 min før sjekk av leaderelection

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
Vært noe forvirring i preprod fordi avslagtoggle også slår av validering av støttet behandlingresultat. Skiller derfor ut i egen toggle.
=> Skill ut toggle for å unngå forvirring i preprod

src/main/kotlin/no/nav/familie/ba/sak/brev/BrevPeriodeService.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakUtilsTest.kt
Etter å ha sett sortering i kontekst med mange perioder har man kommet fram til at alle perioder med fom-dato skal inn i vanlig sortering. De rødmerkede periodene uten slutt skal altså ikke lenger spesialhåndteres.
=> Justering brev: Oppdater sortering av avslagsperioder

src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestVedtak.kt
Begrunnelse fom dato e optional for avslag, derfor må den også være optional for fritekst.
=> Friteks fom dato optional

src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/Person.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseSpesifikasjon.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/AvslagBegrunnelseSammenslåingTest.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakUtilsTest.kt, src/test/kotlin/no/nav/familie/ba/sak/common/UtilsTest.kt
Vi har behov for å vite om det dreier seg om et eller flere barn i begrunnelsene  ("barnet/"barna" - kommer som neste pr). 
Flytter derfor sammenslåing av string "et nivå inn". 
Kunne alternativt lagt til en bool `gjelderFlereBarn` i likehet med `gjelderSøker`, men måtte da gjentatt samme sjekk alle steder det sendes inn, så synes det var ryddigere å ta det inn her. 
Ingen funksjonell endring, oppdatert tester. 
=> Send inn datoer i stedet for sammenslått string ved brevtekst-generering

src/main/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringService.kt, src/test/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringServiceTest.kt
Fikser en bug i migrering hvor opphørsgrunn i saksstaistikk er satt til "0", mens vi filterer på nullOrEmpty
Nei
=> Støtte for opphørsgrunn 0 saksoversikt fra infotrygd ved migrering

src/main/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdBarnetrygdClient.kt, src/main/resources/application-e2e.yaml
Kun for å hente saker - nødvendig for å kunne lage e2e-test for migrering.
=> Kaller mockserver for e2e infotrygd-barnetrygd

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/BehandlingSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/config/WebConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/SchedulingController.kt
Autobrev feilet ettersom default steg-sekvens ikke var riktig for automatisk autobrev, det har blitt fikset med en dedikert sekvens for autobrev.
I tillegg har api for å rigge autobrev manuelt fått ny uri.
E2E test som sjekkes inn i separat PR tester denne endringen.
Kjør E2E tester fra PR https://github.com/navikt/familie-ba-e2e/pull/56/files
=> Opprettet ny stegsekvens definisjon for autobrev

src/main/kotlin/no/nav/familie/ba/sak/totrinnskontroll/TotrinnskontrollService.kt
Automatisk totrinnskontroll får saksbehandler og beslutter satt som felt i Totrinnskontroll. Når dette trigges fra frontend, som f. eks ved manuell migrering, så vil IverksettMotOpprdag-steget feile fordi saksbehandler og beslutter er satt til innlogget bruker.
Vil dette skape noen problemer for andre automatisk totrinnskontroll? Tror ikke det
Det er tester, men hvordan teste med å kjøre i saksbehandler sikkershetscontext? Det har vi ikke funnet noen mekanismer på.
=> Sette beslutter til system ved automatisk totrinnskontroll

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/simulering/SimuleringService.kt
Det skal egentlig ikke være mulig at `restSimulering.tidSimuleringHentet == null`, men side toggler var skrudd av backend og på frontend har man endt i denne situasjonen
=> Oppdatere simulering

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingService.kt
-Bugfix:[ Fritekst forsvinner ved underkjennelse](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4484)
- Kopier brevtekster ved underkjenning av vedtak, da fritekster ikke kan re-genereres som andre begrunnelsetekster
=> Bugfix: Fritekst forsvinner ved underkjennelse

src/main/kotlin/no/nav/familie/ba/sak/pdl/PdlRestClient.kt, src/main/kotlin/no/nav/familie/ba/sak/pdl/StsOnlyPdlRestClient.kt
I forbindelse med bugfix mot pdl for azure tokens ble det laget logikk for å fjerne nav-consumer-token. Dette var uheldig for stsOnly klienten.
Nei
Ikke aktuelt
alt i ett
=> BUG: Legger til eksplisitt httpHeaders funksjon for stsOnly klienten mot pdl.

src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatService.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/YtelsePerson.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/YtelsePersonUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/PersonResultat.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårsvurderingService.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingResultatMedSøknadTest.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/resultat/YtelsePersonResultatTest.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/resultat/YtelsePersonUtilsTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4674
Søknad uten endring skal kunne gi et eget resultat som ikke er støttet enda, da det kan hende bruker søker om akkurat det man har fått tidligere. I disse tilfellene blir det feil å gi avslag.
Gir nå:
Nei
- Endringen i [disse to testene ](https://github.com/navikt/familie-ba-sak/compare/feature/h%C3%A5ndtering-fortsatt-innvilget?expand=1#diff-259a01501a7f7a63e82f7f8c6ac965969e923cccdfdc45fd03e4ac8ef1e9d5edL363-L454)gjenspeiler den funksjonelle endringen
- Fikk en feil i e2e og gjorde en oppdatering [her](https://github.com/navikt/familie-ba-sak/pull/1039/commits/09f4d61d1b533d68f3b6b7e3180586367a106086) som kan …
=> Søknad uten endring skal gi "ikke støttet"-feil i stedet for AVSLAG

src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/PersongrunnlagService.kt, src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/test/kotlin/no/nav/familie/ba/sak/arbeidsfordeling/ArbeidsfordelingIntegrationTest.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseIntegrasjonTest.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/GDPRInnhentingTest.kt
Første del av støtte for skjønnsmessig vurdering, hvor fakta som fravikes skal lagres.
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4790
Denne oppgaven utvider lagring av registeropplysninger ved manuell behandling. I neste ledd vil mer data bli inkludert her.
**Tilpassede PDL-requests vs flere kall:** Vi vurderer å lage tilpassede pdl-requests for de ulike databehovene, framfor å gjøre flere kall og "fylle på" med f.eks historikk og statsborgerksap i etterkant. Samtidig husker vi at man ved automatiske behandlinger ønska å hente litt etter litt ved behov underveis i behandlingen, så mulig nåværende løsning er mest hensiktsmessig? 
Alt i ett
=> Lagre flere registeropplysninger ved manuell behandling

src/test/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringServiceTest.kt
MigreringServiceTest kjører Tasks ved å hente de ut fra TaskRepository, og deretter kjøre task.doTask og task.onCompletion, for å teste hele løypa.
Dette har ikke forårsaket problemer inntil nå nettopp. Nå feiler det fordi payload-JSONen i en gitt task er tom (og tryner dermed i mapping til POJO). Det feiler kun i Github Actions og ikke lokalt.
Disabler testene inntil videre, da dette er problematisk å grave i, tar lang tid, og fordi vi må vurdere om det er en bedre måte å teste med tasks på. (e2e er nevnt)
=> Disable tester i MigreringServiceTest som bruker Tasks direkte.

src/test/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringServiceTest.kt
Fiksen består i å unmocke den statiske IverksettMotOppdragTask.opprettTask, som er mocket i FødselhendelseServiceTest.
Testrekkefølgen ble endret de siste dagene på Github Actions, som førte til at FødselhendelseServiceTest ble kjørt før MigreringServiceTest, som krever en umocket variant av IverksettMotOppdragTask.opprettTask.
=> Fiks for MigreringServiceTest-tester

src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakController.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/PersonController.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/PersongrunnlagService.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/bostedsadresse/GrBostedsadresse.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/bostedsadresse/GrMatrikkeladresse.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/bostedsadresse/GrUkjentBosted.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/bostedsadresse/GrVegadresse.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/opphold/GrOpphold.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/statsborgerskap/GrStatsborgerskap.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestPerson.kt, src/main/kotlin/no/nav/familie/ba/sak/common/Utils.kt, src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
Første ledd i visning av registeropplysninger frontend ([favrokort her](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4791)).
Kommer mapping av historisk data for bostedsadresse og sivilstand når dette er på plass. 
Ønsker spesielt feedback på om denne constraint-endringen gir mening:
commit: [Legg til constraint på nivå nærmere datauthenting. Funksjonene blir kalt mange steder, blant annet hvor det ikke sjekkes fagsaktilgang. Legger det derfor her for å unngå risiko for datalekkasje.](https://github.com/navikt/familie-ba-sak/commit/68de4fc03ac158378c624e0c821c033c25e72b77)
Validert ny mapping. 
Commit for commit skal være ganske oversiktlig, men ["Legg til mapping av …
=> Returner registeropplysninger på fagsak

src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/bostedsadresse/GrVegadresse.kt, src/main/kotlin/no/nav/familie/ba/sak/common/Utils.kt, src/test/kotlin/no/nav/familie/ba/sak/common/UtilsTest.kt, src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt
I det nye kalenderapiet sjekkes det at vi ikke jobber med urealistiske datoer, i dette tilfellet etter år 2500. 
Fiks mockdatoer på oppholdstillatelse sånn at frontend ikke brekker. 
Siden det er satt et så høyt årstall antar jeg målet med mocken er en dato man er garantert "aldri" slutter og ikek en realistisk dato. Setter derfor til 2499 som er det høyeste frontend godtar.
=> Oppdater mock til å returnere datoer frontend godtar

src/main/kotlin/no/nav/familie/ba/sak/stønadsstatistikk/StønadsstatistikkService.kt, src/test/kotlin/no/nav/familie/ba/sak/stønadsstatistikk/StønadsstatistikkServiceTest.kt
Ved sending av stønadsstatistikk på gamle meldinger, så får man ikke vedtaksdato for deaktiverte vedtak. 
Nei
alt i ett
=> Støtte for vedtaksdato på deaktiverte vedtak i stønadsstatistikk

src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/bostedsadresse/GrVegadresse.kt, src/test/kotlin/no/nav/familie/ba/sak/common/UtilsTest.kt
Liten fiks: oppdaterer adressemapping til å ikke vise "postnummer" som string, men kun selve nummeret.
**Før**
**Etter**
På matrikkeladresse hvor det er masse tall/nr vil man fortsatt vise hva de forskjellige tallene er (Matrikkel $matrikkelId, bruksenhet $bruksenhetsnummer, postnummer $postnummer).
=> Ikke vis "postnummer" som tekst i vegadresse-string

src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt, src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakBegrunnelseTest.kt
Løser: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4888 
- Legger til validering ved sletting av begrunnelse og kaster feil dersom fritekst blir liggende igjen alene
- Legger til test for dette caset
Tidligere kom ikke denne feilmeldingen og man fikk lov til å legge til fritekster uten at vanlige begrunnelser er satt. Dette førte til en state hvor man kunne forsøke å lagre nye fritekster når det ikke fantes vanlige og dette trigga dårlig feilvisning (vil ikke være mulig nå).
@MarcusGustafson74 Som du nevnte vil man ikke kunne legge til fritekstbegrunnelser når ingen vanlige begrunnelser er satt (boksen skjules)
Alt i ett
=> Feilhåndtering: Fritekster kan kun settes i kombinasjon med vanlige begrunnelser

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VurderTilbakekrevingSteg.kt, src/test/kotlin/no/nav/familie/ba/sak/dokument/DokumentServiceTest.kt
En tilbakebetalingsbehandling skal opprettes i familie-tilbake om det finnes om tilbakebetaling og om det ikke allerede finnes en åpen tilbakebetalingsbehandling.
Siste sjekken ble ikke gjort men er lagt inn nå.
Eksisterende tester er ikke konstruert å teste på det nivået og inforing gir mer jobb enn det gir av verdi.
=> Opprettt tilbakebehandling bare om åpenbehandling ikke finnes

src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/PersongrunnlagService.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/statsborgerskap/StatsborgerskapService.kt, src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestPerson.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/IntegrasjonClient.kt, src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt
Vis norsk navn på land i stedet for ISO-landkode. Så TUR -> Tyrkia. Fikser formatering så det ikke blir uppercase.
Når vi skal få på plass postnummer bør vi cache, men tenker det går fint for enkelte landkoder nå.
Lagt til mock, men bør kanskje skrive for mapfunksjonen? 
Kan se ut som det er noen filer det er lenge siden er formatert, så kan være enklere å lese prn med whitespace changes skjult
=> Vis navn på land i registeropplysninger

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlRestClient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PersonopplysningerService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/internal/PdlBostedsadresseperioderResponse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/bostedsadresse/GrBostedsadresse.kt, src/main/resources/pdl/hentBostedsadresseperioder.graphql, src/main/resources/pdl/hentperson-enkel-manuell-behandling.graphql, src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt, src/test/resources/pdl/PdlIntegrasjon/bostedsadresseperioderResponse.json
Under saksbehandling vurderer saksbehandler ut i fra datoen personen selv har oppgitt for flyttingen og ikke fregs vedtaksdato, slik vi henter nå (se doc).
Dette vil ikke løse alt, men en av tingene i: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-5139
Venter på svar angående resterende. Lager en ny pr på fjerning av toggles og logging når vi har kommet til bunns i resten.
=> Erstatt gyldigFraOgMed med angitt flyttedato på bostedsadresse

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt
Tillate migrering på infotrygds kjøredato i alle miljøer, bortsett fra prod
Prøvde også å endre betingelsen til `!env.erProd()`, men da var det en mengde tester som brakk
Dekket av eksisterende
=> Fjerner blokkering av migrering på Infotrygd kjøredato i preprod

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestRegisterhistorikk.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-5139
Jeg snek inn [logikk og tester her](https://github.com/navikt/familie-ba-sak/pull/1171/commits/989f3a5cd712fa9113575c98184607fde8e83edf), men bruker først funksjonaliteten i denne pr'en.
Velger å ikke fylle inn back-to-back når fom-dato mangler, da man ikke kan være 100% på at den er back-to-back med første periode.
https://github.com/navikt/familie-ba-sak/pull/1171/commits/989f3a5cd712fa9113575c98184607fde8e83edf
=> Fyll ut tom-datoer til frontend når bostedsadresser er back-to-back

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/SchedulingController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autorevurdering/SatsendringScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autorevurdering/SatsendringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt
Utplukking av behandlinger til satsendringen i september https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-5529
- Gjenbruker logikk for uthenting av siste iverksatte behandlinger på løpende saker (samme som vi lagde til konsistensavstemming og brukes der)
- Filtrerer ut de med andel september 2021 og beløp 1354
Siden satsendring allerede er ute antas det at vi ikke trenger å spesialhåndtere saker som utredes eller ligger mellom sb1 og sb2 på kjøretidspunkt. Disse vil behandles med ny sats dersom de har tillegg september 2021. Vil uansett gjøre en kontroll i etterkant av kjøring for å validere at ingen ligger igjen med 1354 framover. 
Validert ved å teste script mot …
=> Utplukking av saker med satsendring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingMetrikker.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt
Må slå på toggle for å stoppe nye caser på gammelt format, samtidig som vi har behov for å behandle ferdig de som ligger hos beslutter på gamlemåten. Behandlingene som ligger hos beslutter kan ikke migreres fordi det skal re-genereres når beslutter godkjenner og de gamle vedtaksbegrunnelsene mangler person-informasjonen man trenger for å generere begrunnelser på den nye måten.
=> Midlertidig håndtering av behandlinger hos beslutter som som skal gjennom på gammel modell

src/main/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/ArbeidsfordelingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkEventListener.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkEventPublisher.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkService.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkTestController.kt, src/test/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkEventPublisherFailSafe.kt, src/test/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkServiceTest.kt
Sender saksstatistikk ved manuelt enhetsbytte. 
Måtte flytte logikken for forrigeBehandligid ned til sakstatistikkService for å  unngå cyclic dependency problemer med å ha behandlingService i ArbeidsfordelingService. Tenker at det var like greit når vi likevel alltid gjør en query.
alt i ett
=> Send saksstatistikk ved manuelt enhetsbytte

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt, src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiIntegrasjonTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingIntegrationTest.kt
Retter opp i bug hvor beregn tilkjent ytelse returnerte fagsak som prøvde å mappe opp gyldige begrunnelser på gamle vedtaksperioder.
=> BUG: beregning returnerer fagsak unødvendig

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt
Fikser feil der begrunnelsene ble lagret samtidig som "parent" og det likte ikke hibernate.
[org.hibernate.TransientPropertyValueException]  En feil har oppstått: Not-null property references a transient value - transient instance must be saved before current operation : no.nav.familie.ba.sak.kjerne.vedtak.domene.Vedtaksbegrunnelse.vedtaksperiodeMedBegrunnelser -> no.nav.familie.ba.sak.kjerne.vedtak.domene.VedtaksperiodeMedBegrunnelser
=> Fikser feil ved kopiering av begrunnelser til nytt vedtak.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt
Legger til filtrering slik at saker som skulle hatt gammel sats i september, men har blitt revurdert til noe annet, ikke plukkes opp. Ikke krise hvis det hadde blir utført overflødig autokjøring på de, siden vi i utgangspunktet var forberedt på at man kanskje måtte regne med noen slike, men greit å unngå når man kan.
Neste steg blir å kjøre på alle behandlinger i testmiljø.
=> Ikke automatisk revurder saker som har fått revurdering uten gammel sats

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseSpesifikasjon.kt
Enabler fødselshendelsebegrunnelse for frontend, men lar det ikke være en gyldig begrunnelse å velge for saksbehandler da dette bestemmes av gyldigeBegrunnelser på vedtaksperioden.
Mulig vi bør fjerne "erTilgjengeligFrontend" ettersom det er ikke det feltet som bestemmer om det er valgbart lenger. @MarcusGustafson74 dette er noe du kan ha i bakhodet når man rydder opp i gammel vedtaksperiodeløsning.
Nei
=> Bug: begrunnelse ikke gyldig for å mappe til visningstekst frontend.

README.md, pom.xml, src/main/resources/application-dev.yaml
Vi [reverta bump tidligere i sommer](https://github.com/navikt/familie-ba-sak/commit/349869429c700e8246656824b423d989d824db3c) fordi bumpen førte til nye constraint-navn og tap av all data lokalt. Årsaken til dette er trolig at de fleste har kjørt med `-Dspring.profiles.active=dev` i henhold til readme, også under postgres-kjøring, siden vi er vant til å eksplisitt sette profiler på klasser og launchere. Dessverre er ikke det tilstrekkelig for bootstrap og vi må sette på et høyere nivå, sånn jeg forstår det.
Antakeligvis har postgres-configen tidligere overskrevet dev-configen, mens nå skjer det motsatte. Oppdaterer readme for å tydeliggjøre dette.
=> Bump spring boot til 2.5.3

src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt
Fikser migreringstester som feiler på master pga. utdatert sats i test databeløp.
Vurderte å bruke sats()-funsksjonen fra ØkonomiTestUtils, istedenfor hardkodede beløp i MigreringServiceTest,
men da måtte i så fall satsen vært oppdatert der også. Tok ikke sjansen på det 😅 
=> Fikser migreringstester som feiler på master

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragGenerator.kt
I Simulerings oppdrag til Økonomin ble poster som skulle opphøres satt sist i requesten, dette medførte i mange tilfeller at simuleringen feilet. I denne PR blir disse poster alltid satt først. 
- [/] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️ 
PR må deployes for vi kan verifisere om fiksen løser problemet.
=> Satt opphørs poster først i requesten

src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevKlient.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/DokumentService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/MalMedData.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/AutovedtakNyfødtBarnFraFør.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/AutovedtakNyfødtFørsteBarn.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/Avslag.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/Brev.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/Dødsfall.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/ForsattInnvilget.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/Førstegangsvedtak.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/HenleggeTrukketSøknadBrev.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/InnhenteOpplysningerBrev.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/OpphørMedEndring.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/Opphørt.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/VarselOmRevurderingBrev.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/VedtakEndring.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/Vedtaksbrev.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/DistribuerVedtaksbrev.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevUtilsTest.kt
**Hva?** 
Gjøre det mulig å lese lagret BrevType-stringer fra database til enums (feks _VEDTAK_ENDRING_)
**Hvorfor?**
I forbindelse med at vi ønsker å kunne gjøre distribusjon av manuelle brev async har vi behov for å lagre og hente opp igjen hvordan brev som skal sendes. 
**Hvordan?**
I nåværende løsning er dette `interface BrevType` som implementeres av enumklassene `Vedtaksbrevtype` og `EnkelBrevType`. 
Siden interface ikke har constructors feiler deserialisering fra databasen. `
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `no.nav.familie.ba.sak.kjerne.dokument.domene.maler.BrevType` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional …
=> Samle brevmaler til én enum class uten interface

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseSpesifikasjon.kt
Prodfeil: I vedtaksbegrunnelsen 'reduksjon barn under 18år' blir ikke barn som fyller 18 år påfølgende måned inkludert.
=> Barn 18 år i inneværende og påfølgende måned skal tas med i 18års

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt, src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveServiceTest.kt
Ettersom SB kan opprette behandlinger utenom den "vanlige" løypa er det ikke alltid at ba-sak er oppretter av oppgave. Derfor er det helt vanlig at vi ikke nødvendigvis har noe å ferdigstille hos oss. Endrer derfor til logging istedet for error ved slike tilfeller.
Såvidt jeg vet har dette kun vært vanlig i testene hittil.
Nei
=> Bug: Forbedrer håndtering av ferdigstillelse av oppgaver.

src/main/kotlin/no/nav/familie/ba/sak/config/SchedulingConfig.kt, src/test/kotlin/DevLauncher.kt, src/test/kotlin/DevLauncherPostgres.kt, src/test/kotlin/no/nav/familie/ba/sak/config/AbstractSpringIntegrationTest.kt, src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakControllerTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/AbstractVerdikjedetest.kt
Task scheduling routine can run in background when tests are running, which will break the tests.
To disable Task Scheduling either we use "mock-scheduling" profile for all the tests, or on the contrary we use "scheduling-task" profile when we are not testing. The latter is easier because remembering to add "mock-scheduling" to any new test is error prone, and the error message is also difficult to connect to the reason
=> Fix master build errors: use task-scheduling profile

src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevUtil.kt
Gjedler korreksjonssaken under behandling i prod.
Det er ikke så elegant å spesialhåndtere disse, men alternativet var å ha mildere typesikring på ordinære vedtaksbrev. Ordinære vedtaksbrev har en del ting disse ikke skal ha, så om de skulle vært med der måtte man enten hatt rausere typesikring i signaturen til funksjonen eller i selve vedtaksbrevet, og da faller jo litt av vitsen bort.
=> Ta hensyn til korrigert vedtaksbrev

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingService.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6077
Fjerner den gamle løsningen rundt tekstene til nedtrekksmeny hvor man velger begrunnelser.
Ikke noen ny funksjonalitet
- [ x] Nei
=> Fjern gammel funksjonallitet til nedtrekksmeny

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fødselshendelse/vilkårsvurdering/Regler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/sivilstand/GrSivilstand.kt, src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt, src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveIntegrationTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/dokument/DokumentServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/fødselshendelse/VilkårVurderingTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/sikkerhet/RolletilgangTest.kt, src/test/kotlin/no/nav/familie/ba/sak/task/FerdigstillBehandlingTaskTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6406
Kan vi miste gyldig data med denne filtreringen? Jeg mener nei ettersom vi ikke kan vite når historisk datagrunnlag er gjeldende uten fom-dato.
=> BUG: Filtrer bort sivilstand historikk uten fom-dato.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SatsService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtbetalingssikkerhetTest.kt
Sikkerheten per nå sørger for at en person ikke kan ha mer enn 2 andeler og utbetaling opp til 2500kr samme periode. 
Foreslått endring gjør at kun persontype med småbarnstillegg kan ha 2 andeler og sum er maks av hypotetisk sats man kunne fått, basert på satsliste.
Det stemmer at småbarnstillegget legges på søker? Hvis ikke må man bare bytte barn og søkers sjekk
Alt i ett
=> Baser utbetalingssjekk på persontype

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelseRepository.kt
Det er avvik på konsistensavstemming mellom økonomi og ba-sak.
Årsaken ser ut å være at ved henting av løpende tilkjenteytelser så sammenlignes den faktiske timestampem med timestampen ved midnatt.
=> Trunkere dagens datum ved henting av løpende tilkjente ytelser

src/main/kotlin/no/nav/familie/ba/sak/ekstern/skatteetaten/SkatteetatenController.kt
Utvidet stub til å ha identer som forstås av skatt
nei
=> Stubbet testdata for utvidet med tenor-identer

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt
Fjerner "smartness" ved at vi kun sjekker resultat på partene i saken som har blitt vurdert, men det blir feil f.eks. om det kun er endringer på søker som igjen påvirker barna.
=> BUG: Inkluder alle personene i behandlingen til vurdering av behandlingsresultat

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelseRepository.kt
Konsistensavstemmingen klarte ikke å hente poster som blir avsluttet inneværende måned, årsaken er at year month trukerer på måned. Fiksen er å også trunkere spørringen på månad.
=> Trunkerer på måned ved henting av tilkjent ytelser

.github/workflows/build-pr.yml
Legg til stopping av workflow actions på samme branch.
Tilgangene for workflowen skal være så restriktive som mulig siden kun `permissions.actions` er satt skal alt annet bli satt til `no access`. https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
=> Cancel workflow action på samme branch

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrereSøknad.kt
Ved registrering av søknad til GrunnlagController endepunkt 
```"/{behandlingId}/registrere-søknad-og-hent-persongrunnlag"```
så overskrives oppgavens kategori med Nasjonal uansett om den var satt til EØS ved oppretting av oppgaven. Fikser dette her
=> fikser setting av behandlingskategori under registrering av søknad

src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevUtil.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevUtilsTest.kt
Gi periodetype for full utbetaling dersom du har en delt bosted endring som er endret til full utbetaling samtidig som en utvidet tilkjent ytelse som ikke er endret
Oppdaterer testene
=> Endre periodetype dersom du har en ikke-endret utvidet ytelse delt bosted endring med full utbetaling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/Behandlingutils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/FerdigstillBehandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrerPersongrunnlag.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrereSøknad.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/TilbakestillBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkService.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/RevurderingMedEndredeUtbetalingandelerTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårServiceTest.kt
Endrer fra forrige iverksatte til forrige behandling som ikke er henlagt flere steder da det gir mer mening å bygge videre på disse fremfor den siste som er iverksatt.
Denne endringen har jeg gjort fordi at i en revurdering jeg så på i prod så hentet vi vilkårsvurdering fra forrige iverksatte behandling og ikke den siste behandlingen med endringer.
Kan det være behov for å kun se på de iverksatte barna i enkelte tilfeller hvor jeg har endret nå?
Endret der det trengs.
Alt i ett
=> Bug: hent siste behandling som ikke er henlagt istedet for siste iverksatte behandling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingUtils.kt
Select tekster trenger ikke å filtreres ettersom det er gyldigeBegrunnelser som bestemmer hvilke begrunnelser som kan velges for en gitt periode.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7422
=> BUG: filtrering visningstekster for begrunnelser

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt
Når vi ikke klarer å automatisk behandle småbarnstillegg så kaster vi den til manuell behandling. Ved å sende SB til vurder tilbakekreving har vi ikke hentet simuleringen. Ved å sende til behandlingsresultat derimot så vil SB hente simuleringen selv.
Nei
Finnes fra før
Alt i ett
=> Forbedring: flyt ved manuell behandling av autovedtak småbarnstillegg

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/YtelsePersonUtils.kt, src/test/resources/behandlingsresultatPersoner/RV14_OPPHØRT_SAMME_OPPHØRDATO_ALLE_TY.json
legger til test med opphørsdato lik inneværendeMåned, og opphør tilbake i tid
forsøker å fikse ved å endre på regler i YtelsePersonUtils
=> Retter behandlingsresultat ved flytting av opphørsdato

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/domene/MigreringResponseDto.kt
Utvider responseDto til å ha med mer info om migrert stønad, slik at det blir identifisert den uten bruk av id som kan endre seg. 
Merges ikke ned før ting er ID er klart
=> Utvider response tilbake til ba-migrering til for å identifisere stønad migrert

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/Filtreringsregel.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/FiltreringsreglerFakta.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/FiltreringsreglerService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/utfall/FiltreringsregelIkkeOppfylt.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/utfall/FiltreringsregelOppfylt.kt, src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/FiltreringsregelForFlereBarnTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/FiltreringsregelTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FødselshendelseHenleggelseTest.kt
Implementerer filtreringsregel for å ikke automatisk innvilge fødselshendelser der mor mottar utvidet barnetrygd.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7141
Nei
Alt i ett
=> Filtreringsregel fødselshendelse, mor mottar utvidet barnetrygd

src/main/kotlin/no/nav/familie/ba/sak/kjerne/metrikker/TeamStatistikkService.kt
Endrer til å telle metrikker hver halvtime fremfor rett etter deploy og hver påfølgende halvtime. Dette vil være litt bedre tror jeg for jevn telling ettersom vi deployer så ofte.
Tatt cron herfra: https://riptutorial.com/spring/example/21209/cron-expression. Skrik ut om det blir feil :)
=> Telling av teamstatistikk hver 30 minutt

src/main/kotlin/no/nav/familie/ba/sak/sikkerhet/TilgangService.kt
Forhindre at systemet ikke får tilgang til å gjøre ting som dette:
org.springframework.cache.Cache$ValueRetrievalException: Value for key '(1109215, VL)' could not be loaded using 'no.nav.familie.ba.sak.sikkerhet.TilgangService$$Lambda$2513/0x000000080205da88@6961f628'
Nei
=> BUG: System har tillatelse til å gjøre alt i systemet.

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonClient.kt, src/main/kotlin/no/nav/familie/ba/sak/sikkerhet/SikkerhetContext.kt, src/main/kotlin/no/nav/familie/ba/sak/sikkerhet/TilgangService.kt
Etter overgang til nye endepunkter i familie-integrasjoner sjekker den ting på en litt annen måte som gjør at det feiler for enkelte personer. Endrer slik at vi aldri spør familie-integrasjoner når man er i systemkontekst.
Nei
Dette er egentlig en revert fra før omskrivningen.
Alt i ett
=> BUG: Spør aldri integrasjoner om tilgang når man er i systemkontekst.

src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkService.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt
@stigebil har dere tenkt på personer som har flyttet ut av Norge med denne kontrollen? Her feilet det fordi personen har flere adresser uten fom (som er greit langt tilbake i tid), men om personen har flyttet ut av Norge vil vedkommende fortsatt få opp de gamle adressene sine?
Nei, bare det over.
=> BUG: Godtar alle adresser som gyldige NO adresser ved sending til DVH.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/vilkårsvurdering/Regler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/vilkårsvurdering/utfall/VilkårOppfyltÅrsak.kt, src/main/kotlin/no/nav/familie/ba/sak/task/StartSatsendringForAlleBehandlingerTask.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/vilkårsvurdering/BosattIRiketVilkårTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FødselshendelseHenleggelseTest.kt
Forbedrer regel for vurdering om søker er bosatt i riket basert på funksjonelle krav.
1. Finnes det kun adresser uten fom -> OPPFYLT
2. Har siste adresse fom før vurderingstidspunktet (altså fra barnets fødselsdato) og tom=null (altså ikke utflyttet) -> OPPFYLT
3. Finnes det nå flere adresser uten fom betyr det at vedkommende ikke har bodd på samme adresse fra vurderingstidspunktet og saksbehandler bør se på saken -> IKKE_OPPFYLT
4. Vurder som vanlig basert på adresser med fom.
Nei
Alt i ett
=> Forbedring bosatt i riket

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/JournalføringService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt, src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/kotlin/no/nav/familie/ba/sak/common/TidTest.kt, src/test/kotlin/no/nav/familie/ba/sak/config/AbstractMockkSpringRunner.kt, src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/Datagenerator.kt, src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiIntegrasjonTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingIntegrationTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceIntegrationTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtilsTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/SendTilBeslutterTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/VedtakServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseSpesifikasjonTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceUtilsTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/AutobrevSmåbarnstilleggOpphørTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/PeriodeMapperTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårVurderingMatcherTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingStegUtilsTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingUtilsTest.kt, src/test/kotlin/no/nav/familie/ba/sak/task/FerdigstillBehandlingTaskTest.kt, src/test/kotlin/no/nav/familie/ba/sak/task/TaskRepositoryTestConfig.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7660
Endrer opprett oppgave til taskbasert slik at dersom _noe_ feiler ved opprettelse av behandling eller etter i samme transaksjon så opretter vi ikke behandle sak oppgave på behandlinger som rollbackes.
Forbedringen gjelder i alle tilfeller hvor man oppretter behandling, men ble oppdaget gjennom journalføring.
Nei
Jeg har ikke skrevet noen tester på dette da jeg ser for meg at det egentlig bare blir testing av rammeverk (spring og task) som er unødvendig.
Alt i ett
=> Forbedring: opprett behandle sak oppgave

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt
Støtte for flere delytelser i infotrygd ved migrering. Tar i bruk den som har tom == null. Ved flere delytelser med tom==null, så beholder man eksisterende feilsjekk
Nei
=> Ved migrering så sammenlign med aktive delytelse

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt, src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt
Lagt inn validering av om identen som skal migreres er en aktiv ident. Dette fordi man oppdager barnetrygdsaker i infotrygd på historiske identer og man ikke har lyst til å migrere disse akkurat nå.
Senere ønsker vi kanskje å legge inn sjekk på om det kun er 1 løpende sak totalt på alle identene til en person, men dette blir bestemt etter en analyse fase.
nei
altiett
=> Sjekk om ident er aktiv før man migrering, og kast feil hvis den er historisk

src/main/resources/db/migration/V179__korreksjon_av_versjon_satsendring_06_01_2022.sql
Fikk trøbbel med å starte app'en lokalt fra tom DB. Virket som spring tolket task'en opprettet i migrering V174 som en ny task når taskrammeverket skulle oppdatere tilstand til PLUKKET. Endre versjon fra 0 til 1 virker å ha løst det.
Alltid bekymret for DB-endringer ....
_Jeg har ikke skrevet tester fordi:_ Burde ikke påvirke funksjonalitet, bare om app'en starter eller ikke
- [x ] Nei
=> Justerer versjon fra 0 til 1 på task som opprettes i migrerering V174

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingStegController.kt
Legger til endepunkt for å manuelt kjøre valideringsmetoden for behandlingsresultatsteget. Dette skal brukes frontend for å vise meldingen på noen behandlinger som slipper den strenge valideringen backend.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7769
Mulig fag ønsker den aktuelle feilmeldingen i oppgaven og ikke den vi allerede har. Endret isåfall.
Nei
Kun testet manuelt lokalt
Alt i ett
=> Endepunkt for validering av behandlingsresultatsteg

src/main/kotlin/no/nav/familie/ba/sak/common/Tid.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7900
Koden som sjekket om en ny vilkårperiode splittet en eksisterende periode brukte funksjonen isBetween() som så på om dato var lik eller større/mindre. Dette blir feil, da eksisterende periode kun blir splittet hvis den er strengt i mellom.
=> Bug: Kun splitte vilkår-perioder som er strengt i mellom

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/ef-sak/EfSakRestClient.kt
Synes feilmeldingen [her](https://sentry.gc.nav.no/organizations/nav/issues/44437/?environment=prod&project=112&query=is%3Aignored) var litt kryptisk, så oppdaterer metode for kall mot ef
=> Bruk nye metoder for kall mot EF

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdGenerator.kt, src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7961
Etter samtaler med Eivind og Anna ble det bestemt at vi i første omgang kun skal gi saksbehandler eksplisitt beskjed om hva som er galt, så de kan rette det opp. Er en veldig corner-case som så og si aldri vil skje, og hvis det vil skje er det gjerne i kombo med migrering. Da kan det fikses opp ved å endre migreringsdato lenger tilbake i tid.
=> Bug: Kast feil hvis tom er før fom på utvidet-vilkåret

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentController.kt, src/main/kotlin/no/nav/familie/ba/sak/sikkerhet/TilgangUtils.kt, src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentControllerTest.kt
Fix for [denne feilen](https://sentry.gc.nav.no/organizations/nav/issues/44971/?environment=prod&project=112&query=is%3Aunresolved).
Gir funksjonell feil dersom veileder prøver å hente brev før det er generert.
Kun feilmelding
=> Returner bedre feilmeldinger til veiledere som prøver å hente brev som ikke er genererte

src/main/resources/db/migration/V192__delete_begrunnelse_opphor_ikke_mottat_opplysninger.sql
Begrunnelses enum som blitt fjernet gjøre at vedtaksperioder for disse behandlingen som refererer til begrunnelsene ikke kan vises. Fjern derfor begrunnelser som blitt fjernet, i dette tilfelde: opphør ikke mottat opplysninger
=> Fjern begrunnelse opphor ikke mottat opplysninger

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt
DB-spørringer trigger i Hibernate flushing av objekter til  db. Det kan da oppstå problemer om endringer som bare er gyldige i korrekt rekkefølge kommer i samme batch, da kan rekkefølgen bli feil og årsake db-constraint feil. Dette er caset i migreringskoden som fikses med endringen i denne PRen
Endringen er av en type som ikke trenger testes.
=> Persisterte aktørid søker og barn tidelig i migrering

.deploy/nais/app-preprod.yaml, .deploy/nais/app-prod.yaml, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/AvstemmingService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/DataChunkRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/task/KonsistensavstemMotOppdragStartTask.kt, src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/AvstemmingServiceTest.kt
Opprettelse av konsistensavstemming datatasker viste seg å bruke mer minne en tilgjengelig, derfor har opprettelsen blitt splittet i subtransaksjoner.
=> Splitt opprettelse av konsistensavstemming datatasker i subtransaksjoner.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt
Fjerner validering av delt bosted igjen (la den på i går fordi vi så at den var borte). Valideringen baserer seg kun på prosent = 50 når man skal se på om det er lov til å legge på en delt bosted-endringsperiode. Dette blir feil hvis man allerede har laget en endringsperiode som sier at ja den skal utbetales=100 prosent, men senere vil endre den til nei.
Laget nytt kort på det her: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8188
=> Fjern validering av delt bosted 

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrerPersongrunnlag.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårServiceTest.kt
Lagrer kun migreringsdato på behandlinger som påvirker migreringsdatoen. Bruker tidligste migreringsdato på fagsakId til alt annet enn å populere utvidet behandling.
Validerer nå også ny migreringsdato for endre migreringsdato-behandlinger, men usikker på om det trengs. Det gir aldri mening å legge til ny migreringsdato som er lik eller senere uavhengig av hvilken behandling man er på.
Lurer også på hvorfor vi alltid må kopiere over migreringsdatoen. Det spiller jo ingen rolle for funksjonalitet - annet enn en melding til SB på vilkårsvurderingen. Men samtidig gir det heller ikke noe verdi for SB om X år å ha med denne informasjonen videre.
Ikke skrevet tester da jeg stort sett fjerner kode.
alt i ett
=> Bug validering - endre migreringsdato

src/main/kotlin/no/nav/familie/ba/sak/ekstern/skatteetaten/AndelTilkjentYtelsePeriode.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/skatteetaten/SkatteetatenService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelseRepository.kt, src/test/kotlin/no/nav/familie/ba/sak/ekstern/skatteetaten/SkatteetatenServiceIntegrationTest.kt, src/test/kotlin/no/nav/familie/ba/sak/ekstern/skatteetaten/SkatteetatenServiceTest.kt
- Slår sammen perioder selv om infotrygd sin siste periode tom er null
- Oppretter perioder fra kun AndelTilkjentYtelse til den siste iverksatte behandling, som kan være forskjellig ved endret migreringsdato.
Gammel response til høyre. Ny til venstrre
Denne har 2 andel tilkjent ytelse og viser nå kun den siste iverkastte
ser ikke ut til at sjekk mot behandling på virker ytelsen i noe særlig grad
alt i ett
=> Fikser et par bugs i sammenslåinger av perioder for skatt på migrerte saker

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/Behandlingutils.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingUtilsTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8247
Vi får nyUnderkategori = null fra frontend når årsak er "endre migreringsdato". Siden behandlingTypen til en "endre migreringsdato" behandling er MIGRERING_FRA_INFOTRYGD (og ikke revurdering), endte disse behandlingene opp med å treffe else clausen. Dvs. at siden den nye underkategorien = null, ble underkategorien satt til ordinær.
Er bare antagelse, har ikke fått testet om det er faktisk det som skjer, men ganske sikker.
=> Bug: behandlingstema ved endre migreringsdato

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiService.kt, src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiServiceTest.kt
En toggle regulerte om oppdrag allerede sendt skulle kaste feil. Men så sluttet Toggelen å virke derfor er toggelen erstattet med et teller. Telleren skal det settes et larm på.
Skriver ikke tester på tellere.
=> Teller for samme oppdrag allerede sendt konflikt

src/main/kotlin/no/nav/familie/ba/sak/config/SentryConfiguration.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/domene/OppgaveRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/HenleggBehandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/SendTilBeslutter.kt, src/main/kotlin/no/nav/familie/ba/sak/task/FerdigstillOppgaver.kt, src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveIntegrationTest.kt, src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt
Ferdigstiller alle oppgaver av en gitt type på en behandling. Bruker save and flush i tilfelle ferdigstillelse av oppgave #2 feiler. Fikser også sentry der man ikke finner metode som feiler slik at fingerprint ikke blir lik.
=> BUG: Ferdigstill alle oppgaver av en gitt type

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentUtils.kt
Gjøre om til funksjonell feil så vi ikke får innslag i loggen når saksbehandler prøver å sette en behandling som er avsluttet på vent.
Sende med frontend-feilmelding når behandlingen allerede er satt på vent. (Kan denne også gjøres om til funksjonell feil eller vil vi ha innslag i loggen hvis det skjer?)
=> Rette opp i feilmeldinger ved validering av sett på vent

src/main/kotlin/no/nav/familie/ba/sak/ekstern/bisys/BisysService.kt, src/test/kotlin/no/nav/familie/ba/sak/ekstern/bisys/BisysServiceTest.kt
Setter beløp fra "kalkulertUtbetalingsbeløp", og ikke "sats" som blir feil ved delt bosted.
=> BisysService: Fikser beløp-mapping 

src/main/kotlin/no/nav/familie/ba/sak/ekstern/tilbakekreving/HentFagsystemsbehandlingRequestConsumer.kt
Vi fikk spor på logg at hent fagsystemsbehandling request for EF fra familie-tilbake leses av familie-ba-sak. Det skjer fordi groupId er forskjellige og topicnavn er samme. Topic i kafka sender alle meldinger til alle grupper(når groupId er forskjellige). For å fikse det la jeg til en tilleggsvalidering som unngår EF meldinger. Samme sjekk finnes i EF.
=> Fikset slik at ba-sak ikke leser EF HentFagsystemsbehandlingRequest fra familie-tilbake

src/main/kotlin/no/nav/familie/ba/sak/ekstern/bisys/BisysService.kt, src/test/kotlin/no/nav/familie/ba/sak/ekstern/bisys/BisysServiceTest.kt
Fikser sammenslåing av overlappende perioder mellom ba-sak og infotrygd, inkludert perioder fra infotrygd som slutter med null
=> BisysService: Fikser sammenslåing av overlappende perioder

src/main/kotlin/no/nav/familie/ba/sak/config/SentryConfiguration.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/UtvidetBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentService.kt
Bruker enabled fra config til å styre om Sentry skal være påskrudd eller ikke. Endrer feilhåndtering for gjenoppta behandling på vent.
=> Chore: Sentry + sett på vent feilmelding

src/main/kotlin/no/nav/familie/ba/sak/common/Feil.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlRestClient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PersonopplysningerService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/domene/PdlHentPersonResponse.kt, src/main/resources/pdl/hentperson-enkel.graphql, src/main/resources/pdl/hentperson-med-relasjoner-og-registerinformasjon.graphql, src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PersonopplysningerServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/mockserver/domene/RestScenarioPerson.kt, src/test/resources/pdl/PdlIntegrasjon/gyldigRequestForBarnMedOpphørtStatus.json, src/test/resources/pdl/PdlIntegrasjon/gyldigRequestForBarnUtenFødselsdato.json, src/test/resources/pdl/PdlIntegrasjon/gyldigRequestForMor3Barn1Opphørt1UtenFødselsdato.json, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForBarn.json, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForBarnMedAdressebeskyttelse.json, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForBarnMedOpphørtStatus.json, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForBarnUtenFødselsdato.json, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForDødMor.json, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForMor3Barn1Opphørt1UtenFødselsdato.json, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForMorMedUkjentStatsborgerskap.json, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForMorMedXXXStatsborgerskap.json, src/test/resources/pdl/pdlManglerFoedselResponse.json, src/test/resources/pdl/pdlMatrikkelAdresseOkResponse.json, src/test/resources/pdl/pdlOkResponse.json, src/test/resources/pdl/pdlTomAdresseOkResponse.json, src/test/resources/pdl/pdlUkjentBostedAdresseOkResponse.json
Kaster feil på personer uten fødselsdato eller har opphørt status. Filtrerer bort slike personer i mapping så vi sitter igjen med relasjoner som kan behandles i løsningen.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8377
Er en del testfiler som man stort sett kan se bort i fra da det kun er data som trengs for at pdl->ba-sak modell ikke skal brekke.
Alt i ett
=> Bedre innhenting av relasjoner

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt
Fra tid til annen opplever vi alarm fra migreringsløypa når vi prøver å behandle en fødselshendelse OG migrering på samme person 🤯  Vi har løst dette ved å catche og rekjøre task på fødselshendelseløypa og tror det er fint å gjøre det samme her. Må også da unngå å lagre aktør før opprettelse av fagsak (gjøres i metoden man kaller uansett)
Nei
Ikke aktuelt
Alt i ett
=> Håndterer aktør-krasj i databasen ved å plukke opp constraint exception og logger warning.

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestVedtaksperiodeMedBegrunnelser.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeMedBegrunnelserController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8209
Lager endepunkt som oppdaterer vedtaksperiodene på en behandling. Skal brukes for fortsatt innvilget behandlinger, hvor man kan velge om man vil ha med eller uten perioder. Default er uten perioder (sånn som det er i dag). Hvis man vil ha med perioder brukes samme logikk som for de andre behandlingsresultatene i dag. Endringstidspunkt skal ikke tas høyde for for fortsatt innvilget (er jo ingen endringer). Ønsker man vedtaksbrev med perioder skal man få alle periodene.
Tar gjerne imot tips til navn på endepunktet.
=> Vedtaksbrev med perioder for fortsatt innvilget

src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/statsborgerskap/StatsborgerskapService.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/StatsborgerskapServiceTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8419
Vi prøver å løse at statsborgere fra Storbritannia med periode `(fra=null, til=null)` blir håndtert som EØS-borgere. Ifølge Anna og Birgitte skal disse håndteres som tredjelandsborgere.
Kanskje med å lese testene og se om dere er enige i at de oppfyller behovet fra favrooppgaven, at det ikke er noe jeg har glemt å tenke på.
=> Håndter null som statsborgerperiode ved vurdering av medlemsskap

src/main/resources/db/migration/V203__oppdater_tilkjent_ytelse_stonad_tom_fra_andel_tilkjent_ytelse.sql
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8441
Fikser feil der siste andel tilkjent ytelse tom dato var forskjellig fra tom datoen til tilkjent ytelse
Vi har et problem der den seneste til og med datoen på andeler tilkjent ytelse ikke samsvarer med til og med datoen på tilkjent ytelse. Endrer derfor på tom-datoen til tilkjent ytelse til å være samme som seneste tom-dato på de tilknyttede andelene.
=> Oppdater tilkjent ytelse tom der den er ulik maks andel tilkjent ytelse tom

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakStatusScheduler.kt
Vi har hatt en bug der tilkjent ytelse har hatt feil tom-datoer. Siden vi bruker dette til å avgjøre om en fagsak er avsluttet eller ikke er det derfor noen fagsaker som står som løpende, men som brude vært avsluttet. Siden bugen vedrørende tilkjent ytelse er rettet opp kjører vi derfor scriptet som avslutter fagsaker 08.04.22 14.30. 
Det er viktig at dette skjer før månedsskiftet fordi vi bruker detter til å avgjøre hvem "Autobrev 6 og 18 år" skal sendes ut. 
=> Legg på cron-job 18 april som oppdaterer fagsagstatuser

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt
Forhindrer at saksbehandler migrerer en sak og opphører den umiddelbart i ba-sak, og at en maskinell migrering trigges senere på samme sak. Den maskinelle migreringen vil stoppe med KUN_ETT_MIGRERINGFORSØK_PER_DAG feil den dagen. Ved rekjøring neste dag så vil infotrygd ha lest fra fil og avsluttet saken. Siden noen saker flyttes tilbake manuelt, så forhindrer man ikke migrering ved senere dato. Da vil den bli stoppet av at det ikke finnes sak i infotrygd hvis den alt er migrert, eller så kan man migrere.
Nei
=> Ikke migrer hvis det alt er en migreringsbehandling for denne dagen

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdGenerator.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8456
Slå sammen periodene til barna som har samme prosent og er etterfølgende.
Før slo vi sammen utvidet-andelene til søker som hadde samme beløp og var etterfølgende. Dette blir feil da vi ønsker å reflektere splittene i utvidet-vilkåret. Slår derfor istedet sammen barnas andeler før disse "merges" med utvidet periodene. Dette gjør at vi kun får splitter på utvidet-andelene hvis det er endring i utvidet vilkåret, eller endring i prosent på barnas andeler (delt bosted).
Må testes godt.
Alt i ett
=> Bugfix: sammenslåing av utvidet-andeler

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdGenerator.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceTest.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdTest.kt
Forsøk nr. 2 på denne: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8456
Kombinere barnas andeler til 1 tidslinje som kun er splittet ved ulik prosent før man kombinerer barnas andeler med utvidet-tidslinjen.
Påvirker alle utvidet-saker, så må testes nøye.
Alt i ett
Kan godt gå gjennom muntlig hvis det er ønskelig!
=> Bugfix: Generering av utvidet-andeler

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/SanityBegrunnelse.kt
Fikse alle feilene i loggene som ligner på denne `på begrunnelsen innvilgetEnighetOmAtAvtalenOmDeltBostedErOpphort er ikke blant verdiene til enumen EndretUtbetalingsperiodeDeltBostedTriggere[]`.
Har ikke ført til feil for saksbehandler, men fyller opp loggene våre med error-logging som ikke skal være der.
Løsningen er å ikke prøve å map til enum hvis verdien fra sanity er null. Det er funksjonen `finnEnumverdi` som logger error hvis stringen ikke finnes blandt enumverdiene man prøver å mappe til. Det vil alltid skje når man sender inn tom streng som jeg hadde gjort i utgangspunktet. 
Nei
Ganske triviell endring.
=> Bugfix: Unngå unødvendig error-logging 

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdGenerator.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdTest.kt
Knyttet til denne oppgaven på favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8456
Påbygg på denne PRen: https://github.com/navikt/familie-ba-sak/pull/2347
Etter de nye endringene (se PR over) ble ikke utvidet-andeler splittet opp ved satsendring. Denne PRen sørger for at vi deler opp utvidet-andeler ved satsendring. Det har kun vært 1 satsendring som har påvirket utvidet barnetrygd tidligere, og den var i 2019, så vi oppdaget ikke at dette var en mangel før koden fikk levd litt i prod. 
Nop.
=> Bugfix: Splitt utvidet-andeler når det er satsendring

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/Datagenerator.kt, src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/MigrerFraInfotrygdTest.kt
Støtte for migrering av utvidet med småbarnstøtte. Disse har 2 delytelser i infotrygd hvor den ene er småbarnstillegget, og den andre er barnetrygd for alle barn +utvidet
Testet i preprod med fnr i email
https://barnetrygd.dev.intern.nav.no/fagsak/100058301/100071351/tilkjent-ytelse
nope
=> Tillate flere delytelser ved migrering for saker av type utvidet

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/AutovedtakStegService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/AutobrevStegServiceTest.kt
**Favro**: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8634
**Hva**: Vi skal håndtere autovedtak for åpen behandling med status _Fatter vedtak_ likt som ved status _Utredes_
**Hvorfor**: Autovedtakskjøring stanser dersom fagsak har en åpen behandling med status _Fatter vedtak_, og oppretter en task til manuell oppfølging av vakt. Vi har ikke tidligere lagt inn håndtering av status _Fatter vedtak_
=> Bugfix autovedtak: Håndter åpen behandling med status fatter vedtak 

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/tidslinjer/rest/RestTidslinjer.kt
Tidslinjer som er åpne, dvs går mot uendelig, feiler i konverteringen til rest-tidslinjer, der det må være en endelig LocalDate.
Legger på en quickfix, som setter en dato langt inne i fremtiden. Men det er ikke en endelig løsning. 
Nei. 
_Jeg har ikke skrevet tester fordi:_ Det er en quickfix for en funksjonalitet som bare brukes som debug/test
=> Konverterer uendelig til et tidspunkt langt inne i fremtiden

src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/BeskjæreTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/EndreTid.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/BeskjæreTidslinjeTest.kt
Beskjæring av tidsliner har fått en overhaling. Tidligere variant håndterte ikke uendelig på en sikker måte, og manglet tester
Uendelige tidspunkter er en utfordring. Nå er "uendelig" basert på at det finnes et underliggende tidspunkt, som representerer en praktisk grense. Kanskje et riktigere konsept hadde vært hhv "herfra og tidligere" eller "herfra og senere", ikke "uendelig med en grense". Men da begynner det egentlig å likne på en _periode_, der enten fra-og-med eller til-og-med er "ekte" uendelig. Men det løser ikke alle problemer, det heller. 
Rotproblemet er effektiv kombinasjoner av tidslinjer, der null, én, flere eller alle kan være helt eller delvis uendelige. Uendelige tidspunkter var ment å pakke inn problematikken, og i hvert fall slippe å håndtere null overalt. Men …
=> Herder beskjæring av tidslinjer. 

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevPeriodeTestKlasser.kt, src/test/resources/brevperiodeCaser/REDUKSJON_BOR_MED_SØKER_OG_DELT_BOSTED.json, src/test/resources/brevperiodeCaser/SMÅBARNSTILLEGG.json
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8367
Knyttet til denne PRen: https://github.com/navikt/familie-brev/pull/258
Må sende med felt som sier om søker får utbetalt utvidet eller ikke i perioden. Dette er for å velge riktig for valgfeltet "du får/har rett til".
~Vet ikke om dette er beste måte å løse problemet på. Tidligere versjon sendte med beløp som ble utbetalt på søker, men det ble feil, da vi skal se bort fra småbarnstillegg. I stedet for å sende med beløp utbetalt for utvidet på søker, tenkte jeg det var like enkelt å sende med en boolsk verdi. Men er egentlig ikke så veldig fan av at vi sender med så mange spesifikke verdier i BegrunnelseData-objektet. Men vanskelig å gjøre noe med det før vi tar et steg tilbake og …
=> Legg til felt i BegrunnelseData som sier om utvidet er utbetalt eller ikke på søker i perioden

src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/AutovedtakStegService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevOpphørSmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/VedtakOmOvergangsstønadTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/AutobrevStegServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevOpphørSmåbarnstilleggServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/BehandleSmåbarnstilleggTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8654
`autovedtakStegService.kjørBehandling` tar inn et argument `behandlingsdata` som ikke er strengt typet, men som har en forventet type vi kan utlede fra argumentet `autovedtaktype`. I ett tilfelle mottar `autovedtakStegService.kjørBehandling` en `behandlingsdata` og en `autovedtaktype` som ikke matcher med hverandre og vi kaster `ClassCastException`.
```java
java.lang.ClassCastException: class no.nav.familie.ba.sak.kjerne.autovedtak.omregning.AutovedtakBrevBehandlingsdata cannot be cast to class no.nav.familie.ba.sak.kjerne.personident.Aktør (no.nav.familie.ba.sak.kjerne.autovedtak.omregning.AutovedtakBrevBehandlingsdata and no.nav.familie.ba.sak.kjerne.personident.Aktør are in unnamed …
```
=> Rett opp og forebygg feil type argumenter til kjøring av autovedtak

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtilsTest.kt
I dag støtter systemet kun kombinasjon AVSLÅTT og OPPHØRT som YtelsePersonResultat, men AVSLÅTT og FORTSATT_OPPHØRT bør støttes og skulle utlede behandlingsresultat som AVSLÅTT_OG_OPPHØRT
Fagsystem: https://jira.adeo.no/browse/FAGSYSTEM-221341
=> fikset slik at systemet støtter AVSLÅTT og FORTSATT_OPPHØRT

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/småbarnstillegg/RestartAvSmåbarnstilleggService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/småbarnstillegg/RestartAvSmåbarnstilleggServiceTest.kt
**Favro:** https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8621
**Hvorfor skal bør denne endringen komme inn?**
Nå oppretter vi en oppgave til saksbehandler for alle saker der vi har oppstart av småbarnstillegg inneværende måned. For saker som er migrert fra Infotrygd vil det alltid se ut som småbarnstillegg ble oppstartet måneden etter. 
**Hva endrer denne PRen?**
Ignorerer saker som ble migrert fra Infotrygd forrige måned når vi henter saker der vi skal varsle bruker at vi gjennoppstarter småbarnstilleg.  
=> Ikke opprett oppgave på småbarnstillegsaker der fagsaken var migrert forrige måned

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevOpphørSmåbarnstilleggService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevOpphørSmåbarnstilleggServiceTest.kt
Retter opp en liten feil som ble innført her: https://github.com/navikt/familie-ba-sak/pull/2421
Ved opphør av småbarnstillegg skal man bruke "omregning brev" som autovedtak-type + "omregning småbarnstillegg" skal være behandlingsårsaken. Dette er fordi opphør av småbarnstillegg skal fungere på samme måte som ved omregning 6/18år. 
Sånn koden er før mine endringer i denne PRen ville man ha brukt småbarnstillegg-løypa for autobrev, som ikke fungerer når det er opphør.
(Dette er PRen som innførte omregning småbarnstillegg som en årsak hvis noen skulle være interessert i å etterforske litt: https://github.com/navikt/familie-ba-sak/pull/1863)
Litt vanskelig å forstå småbarnstillegg vs. omregning småbarnstillegg. Noen forslag for å gjøre det enklere å skjønne?
_Har du husket alle punktene i …
=> Bug: bruk omregningsbrev og -årsak ved "opphør av småbarnstillegg"-autovedtak

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/MigrerFraInfotrygdTest.kt
Flytter filtreringsregler til ba-sak fra infotrygd ved migrering og litt opprydding av toggles
=> Flytter filtreringsregler fra ba-infotrygd til ba-sak, rydder opp i toggles som er skrudd på

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt
Etter diskusjon på slack:  https://nav-it.slack.com/archives/C036C6VAWH3/p1653030760824749
Hvorfor: 
Ser det er en validering som forventer at vi skal ha minst en fødselsdato med om ikke begrunnelsen gjelder søker, men i dette tilfellet har vi ingen fødselsdatoer.
Begrunnelsen det gjelder er “13. Barn uten fødselsnummer”. Ser fødselsdagene ikke blir brukt der, så antar vi kan skippe valideringen om det er snakk om den begrunnelsen
Hva: Hopper over valideringen som sjekker at vi sender med minst ett av barna sine fødselsdager dersom vi bruker begrunnelse "13. Barn uten fødselsnummer" (heter AVSLAG_UREGISTRERT_BARN i ba-sak)
_Jeg har ikke …
=> Hopp over validering for om vi har barnas fødselsdager dersom begrunnelsen er AVSLAG_UREGISTRERT_BARN

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt
Veldig vanskelig å forklare skriftlig. Har prøvd meg på en forklaring under, men bare pling på meg hvis det er noe du lurer på. Forklarer med glede 😃 
Det er en (lang) historie bak bugen, tar det i korte trekk her så det er lettere å sette seg inn i casen. Vet ikke om alt her er så relevant for å forstå casen, men skriver det ned i korte trekk uansett.
- Det var en behandling i prod som manglet to vilkår på søker. Vi rettet opp feilen, men for å få tilbake vilkårene på saken i prod så ble vi enige om at Anna og Birgitte skulle lage en teknisk endring-behandling hvor disse to vilkårene dukker opp igjen. 
- Denne behandlingen fikk da resultat fortsatt innvilget, noe som ikke var støttet som resultat for teknisk endring behandlinger, fordi den gikk videre til iverksetting mot økonomi uansett …
=> Bug: får ikke henlagt teknisk endring-behandling

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/MigrerFraInfotrygdTest.kt
- Åpner opp for å migrere stønader som har barn over 18, men kun de som har antall barn under 18 lik antall barn på stønaden
- Saker uten barn og uten delytelse til egen feiltype. Disse skal nok aldri migreres
=> Filtrere vekk barn over 18, så lenge antall barn stemmer overens med antall barn under 18

src/main/kotlin/no/nav/familie/ba/sak/config/KafkaAivenConfig.kt
Fix KafkaAivenConfig to remove json serializer
The message sent to DVH with Kafka Aiven is now serialized to json text before sending. This is to keep compatible with the KafkaAivenTemplate shared with other messages which assume the template accepts string
=> Fix message sent to Kafka Aiven

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevBegrunnelseGrunnlagMedPersoner.kt, src/test/resources/brevperiodeCaser/ETTER_ENDRET_UTBETALING.json
Favro (nederste bug): https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8721
**Opplevd feil**
Får med for mange barn i begrunnelse for etter endret utbetaling. Skulle ha kun hatt med barn som i forrige periode hadde endret utbetaling, men opplever å få med alle barna i perioden.
**Årsak**
Hvis søker er med i personerPåBegrunnelse så la vi tidligere på alle barna med utbetaling i tillegg, så lenge det ikke var endret utbetaling eller avslag. 
**Løsning**
Gir heller ikke mening å legge på alle barn hvis det er "etter endret utbetaling"-begrunnelse heller, fordi man da gjerne vil snakke om samme barn som i "endret utbetaling". Sørger derfor for at man kun sender med de personene som vi har funnet som relevante for begrunnelsen.
Nop. Eller det er litt …
=> Bug: for mange barn kommer med i "etter endret utbetaling"-begrunnelse

.deploy/nais/app-preprod.yaml, .deploy/nais/app-prod.yaml, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/sanity/SanityService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevKlient.kt
Tidligere har vi hentet begrunnelsene fra sanity ved å gå via familie-brev, selv om vi ikke trengte å flette inn noen brukerdata. Dette er fordi ba-sak en gang i tiden kjørte on-prem hvor det var vanskelig å nå saniyt fra, mens familie-brev kjørte fra gcp. Nå som ba-sak kjører på gcp kan vi hente begrunnelsene direkte fra sanity. 
=> Ikke gå via famlile-brev når vi bare skal hente data om begrunnelsene

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingUtilsTest.kt
Knyttet til denne bugen: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8680
Fjerner validering av avslag uten perioder for vilkåret "bor med søker". Dette for å tillate at man kan ha et avslag uten periode, i kombinasjon med en løpende oppfylt periode. 
For "bor med søker"-vilkåret kan man nemlig ønske å sette vilkåret til både oppfylt og ikke oppfylt i samme periode. Eksempel:
- Søker søker om full barnetrygd
- Men, avtale om delt bosted skal fortsatt følges. Derfor:
- Vi avslår full barnetrygd (avslag uten periode)
- Vi innvilger delt barnetryd
Nop
=> Fjern validering av avslag uten perioder for "bor med søker"

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/InnhenteOpplysningerOmBarn.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/brevperioder/VarselbrevMedÅrsakerOgBarn.kt
Dette er en fortsettelse av #2458 
Endrer til å bruke et eksisterende flettefelt for barnas fødselsdatoer som jeg fant i Sanity, heller enn å lage et nytt som er helt identisk.
Her er det i sanity:
=> Bruk eksisterende flettefelt for barnas fødselsdatoer

src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValideringTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8910
I dag er validering sånn at det kaster feil når minst et av de barn har forskjellige endring på delt bosted ytelse og utvidet ytelse i samme periode. Etter å diskutere det med Anna fjernet denne valideringen fordi det kan være alle barn på en utvidet sak har delt bosted men ingen utbetaling. På denne tilfellen bør saken ikke stoppes
_Jeg har ikke skrevet tester …
=> Fjernet validering som sjekker om endring på delt bosted ytelse og utvidet ytelse i samme periode er lik

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/Valutakurs.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/ValutakursServiceTest.kt
Sletting av valutakurs-skjema er litt for aggressivt når det fjerner valutakoden. Passer på å beholde valutakoden i alle tilfeller der skjemaet tømmes for innhold
Nei
=> Beholder valutakode på skjemaer som tømmes for innhold

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtilsTest.kt
Feilen:
Brukte tidligere enn funksjon for å slå sammen som gjorde om hele listen til en streng og byttet ut siste komma med et og. Det funker ikke med listen jeg sendte inn. Skriver derfor min egen funksjon.
Tar kun også med distinkte hjemler så vi ikke får med flere av samme hjemmel hvis flere begrunnelser er koblet til samme hjemmel.
=> Bug: Sammenslåing av hjemler

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggUtilsTest.kt
Vi har tre vedtakOmOvergangsstønad-tasker som feiler fordi ef har gjort et fortsatt innvilget-vedtak. Hos oss har disse tre taskene kommet forbi testen som sjekker om vedtaket om overgangsstønad påvirker fagsaken. Dette har skjedd fordi splitten i andel tilkjent ytelse er annerledes nå enn tidligere. Eksempel:
- Tidligere hadde du andel tilkjent ytelse for småbarnstillegg fra jan 22 - sept 22
- Kommer fortsatt innvilget-vedtak i mai som sier at personen fortsatt får overgangsstønad jun 22 - sept 22
- Vi har logikk som slår sammen tidligere OS-perioder, men ikke de som er frem i tid. Dvs. når vi skal generere nye andel tilkjent ytelse vil vi få jan 22 - mai 22 og jun 22 - sept 22. 
- Utbetalingene vil forbli de samme, men fordelt på to perioder. Dette er ikke endringer som skal påvirke …
=> Bug: behandler for mange vedtak om overgangsstønad

src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/Tidslinje.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/TidslinjeTest.kt
Nå blir feilmeldingen fra `TidslinjeFeilException` `null` siden vi ikke sender med messagen videre til `IllegalStateException`.
Sender med verdiene for feilene vi får fra TidslinjeFeilException videre til IllegalStateException
=> Legg til tidslinjefeilen som en del av Exceptionen

.deploy/nais/app-preprod.yaml
Skru på PITR for å minimere datatap ved behov for restore av database.
=> skrur på Point in Time Recovery i preprod

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestUtenlandskPeriodebeløp.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningsUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilkjentYtelseDifferanseberegning.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/domene/Valutaberegning.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/utenlandskperiodebeløp/UtenlandskPeriodebeløp.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/utenlandskperiodebeløp/UtenlandskPeriodebeløpController.kt, src/main/resources/db/migration/V213__kalkulert_maanedlig_belop_upb.sql, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningsUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/domene/Datagenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/utenlandskperiodebeløp/UtenlandskPeriodebeløpServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/SkjemaBuilder.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/UtenlandskPeriodebeløpBuilder.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/utenlandskperiodebeløp/UtenlandskPeriodebeløpRepositoryTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/utenlandskperiodebeløp/UtenlandskePeriodebeløpUtfyltTest.kt
* Feltet `kalkulertMånedligBeløp` er lagt til på `UtenlandskPeriodebeløp` og beregnes ved oppdatering gitt at `beløp` og `intervall` er satt.
* DB-migrering for feltet i UPB-tabellen.
* Beregning av månedlig beløp tar ikke lenger hensyn til skuddår dersom intervall er `UKENTLIG`, men bruker multiplikator 4.35 istedenfor.
* Differanseberegning er justert og bruker nå feltet `kalkulertMånedligBeløp` direkte fremfor å beregne beløpet selv.
* Endret type på feltet `intervall` fra `string` til `Intervall`.
* Justert tester som er berørt av endringene.
=> Lagt til kalkulertMånedligBeløp på UtenlandskPeriobebeløp

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/utenlandskperiodebeløp/UtenlandskPeriodebeløp.kt
Ved endring fra type `string` til type `Intervall` på feltet `intervall` i `UtenlandskPeriodebeløp` ble intervall lagret som ordinal-tallet til enumen fremfor navnet. Denne PR'en sørger for at navnet er det som lagres ned. Skapte problemer da gamle UtenlandskePeriodeBeløp ikke lenger kunne hentes frem. 
=> Sørger for at intervall lagres med ENUM-navn og ikke ordinal-tall

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/AndelTilkjentYtelsePraktiskLikhet.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilpassDifferanseberegningService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningIntegrasjonTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingTestController.kt
Prøver å unngå feil som kan oppstå når endring i tilkjent ytelse trigger differanseberegning, hovedsakelig
Håndtering av AndelTilkjentYtelse er et gjentakende kilde til problemer, kanskje spesielt i kombinasjon med tidslinjer. Trenger en grundig gjennomgang av løsning og alternativer
=> Legger på funksjonsbrytere på differanseberegning, utvider tester og herder logikken for lagring av oppdatert tilkjent ytelse

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseController.kt
Lenke til sak i Favro: [TEA-9011](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9011)
Vi ønsker å stoppe behandlinger hvor søker har utvidet barnetrygd og Norge er sekundærland.
Har lagt inn en ekstra validering ved oppdatering av kompetanse, som sjekker om resultat er "Norge er sekundærland" og om søker har utvidet barnetrygd. Kaster feil med feilmelding dersom begge kriteriene er oppfylt. Sjekken styres også av en feature-toggle.
=> Kaster feil dersom EØS-utvidet og Norge er sekundærland.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningsUtils.kt
Det har oppstått litt utfordringer med nasjonaltPeriodebeløp som notNullable for eksisterende behandlinger. Setter feltet tilbake til å være nullable.
=> Reversert nasjonaltPeriodebeløp til å være nullable igjen

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/vilkårsvurdering/Regler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/vilkårsvurdering/utfall/VilkårKanskjeOppfyltÅrsak.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FødselshendelseHenleggelseTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9035
**Hvorfor:**
Vi har krav om at
> moren ved fødselen har oppholdt seg eller skal oppholde seg i Norge i mer enn 12 måneder. Se barnetrygdloven § 4, 1. ledd, bokstav a)
I og med at vi ikke gjør noe kontroll mot hvor lenge mor har bodd i Norge eller hvilken periode hun har fått oppholdstillatelse for, kontrollerer vi ikke om hun har oppholdt seg i Norge i 12 måneder.
Konsekvensen er at noen får barnetrygd automatisk uten å ha krav på det.
Dette gjelder blant annet statsborgere fra Ukraina.
I og med at det for tiden er stort fokus på statsborgerne fra Ukraina, og at disse borgeren ikke har rett til barnetrygd før de har oppholdt seg i Norge i mer enn 12 måneder, må vi gjøre noe med dette så …
=> Send ukrainske tredjelansdborgere til manuell oppfølging

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/EndringstidspunktService.kt
… 
når det ikke finnes noen endring i kompetanse perioder, sendte det første månedsdag av TIDENES_ENDE til frontend, da viser frontend en feil dato på dato-modal. Frontend bør ikke vise noe i det hele tatt når det finnes endringer. Fikset slik at det returnerer null og da viser frontend ikke oppdater førsteendringstidspunkt lenke
=> fikset slik at det ikke viser oppdater første endringstidspunkt lenke når det finnes ingen endringer

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/domene/Kompetanse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevPeriodeTestKlasser.kt, src/test/resources/brevperiodeCaser/EØS_INNVILGET.json
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8968
Henger sammen med denne endringen i familie-brev: https://github.com/navikt/familie-brev/pull/284
Problemet med at vi nå har enumen `.tilTekst()` som output til `EØSBegrunnelseData` er at vi fletter inn den teksten i begrunnelsesbrev, men tekstene er på bokmål, ikke i klarspråk og har forskjellig grammatisk form
Vi endrer til å bevare format på enum for annen forelders aktivitet når det sendes til brev. Enumen plukkes opp i familie-brev og fører til et valgfelt slik at vi får riktig målform og grammatikk
**OBS**: Når dette merges vil begrunnelsene som bruker `EØS-flettefelt` for `Annen forelders aktivitet` til å bruke rene enumverdier, inntil vi får endret disse begrunnelsene til å bruke …
=> Bevar format på enum for annen forelders aktivitet når det sendes til brev

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggService.kt
Når vedtakOmOvergangsstønadTasker som feiler, er det noen ganger vanskelig å debugge fordi vi ikke vet hvilke perioder EF har sendt over. Legger derfor på logging, slik at vi ikke trenger å spørre EF om disse periodene når vi skal debugge.
Nei
Bare logging
=> Legg til logging av OS-perioder fra EF ved autovedtak småbarnstillegg

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/ReduksjonFraForrigeIverksatteBehandlingTest.kt
Vi har en task som feiler fordi vedtaksperiodene blir generert feil når man reduserer småbarnstillegg. Det skulle i utgangspunktet ha dukket opp en "utbetaling med reduksjon fra forrige iverksatte behandling"-periode, men det gjør det ikke. Automatisk kjøring finner derfor ikke en periode å begrunne, da denne perioden blir slått sammen med to andre perioder fordi innholdet er likt, og man ikke klarer å identifisere reduksjonsperioden. Se eksempel under:
Skulle ha fått disse periodene: 
|---før---|---utbetaling med reduksjon---|--etter--|
Men vi får:
|---------------------utbetaling-------------------|
TIdligere så vi kun på om en person ble borte, og om en person ikke hadde utbetaling i forrige periode. Vi ønsker egentlig å se på om det er en spesifikk utbetaling for en person som er …
=> Håndtere reduksjon fra forrige iverksatte behandling for småbarnstillegg

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeMedBegrunnelser.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9027
Fikk ikke lov til å legge til fritekst når man hadde eøs-begrunnelse. Dette var fordi funksjonen som så om det var valgt en begrunnelse kun så på vanlige begrunnelser. 
Nei
Vet ikke om det er nødvendig?
=> Ta hensyn også til eøs begrunnelser når man validerer fritekst

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingHentOgPersisterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/InternPeriodeOvergangsstønad.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/InternPeriodeOvergangsstønadTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/småbarnstillegg/PeriodeOvergangsstønadGrunnlag.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/BehandleSmåbarnstilleggTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9148
**Hvorfor:**
Vi har en feil der vi ikke klarer å finne hvilken periode som får småbarnstillegg. Dette skjer fordi en overgangsstønad-periode utvides. Til nå har vi antatt av dersom det blir mer overgangsstønad vil dette komme som en ny periode.
**Hva endres i denne PRen:**
Dersom vi i en behandling har overgangsstønad i tre måneder:
`|OOO-----|`
som fører til småbarnstillegg.
Og så utvides overgangsstønadsperioden i neste behandling til fem måneder:
`|OOOOO---|`
som fører til småbarnstillegg i alle månedene.
Ønsker vi å kunne begrunne de to siste månedene med småbarnstillegg.
Splitter derfor opp overgangsstønadsperioden slik at vi kan begrunne endringen for søker i riktig periode. …
=> Håndter forlenget overgangsstønadsperiode

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtilsTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9136
Vi har en autobrev task som feiler fordi man får behandlingsresultatet endret og opphørt når man egentlig forventer å få fortsatt innvilget (evt. i dette tilfellet fortsatt opphørt). Grunnen til at det blir endret og opphørt er fordi hvis alt opphører, og det ikke opphører på samme tid, samt at det ikke kun er fremstilt krav i inneværende behandling så legger vi til ENDRET_UTBETALING som et resultat. Derfor blir behandlingsresultatet endret og opphørt. 
Tanken bak denne PRen er at det ikke gir mening å legge til endret utbetaling som resultat hvis alle personresultatene er fortsatt opphørt. Dette vil gjør at man til slutt ender opp med fortsatt opphørt som resultat.
Vil dette funke for …
=> Hvis det kun er fortsatt opphørt resultater ønsker vi ikke å legge til endret-resultat

src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceEnhetstest.kt
Koden ville ikke la seg kompilere på Windows. Fjernet dobbeltfnutt og erstattet med enkeltfnutt.
=> Fjernet dobbeltfnutter fra metodenavn. Ville ikke kompilere på Windows.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtils.kt, src/test/resources/behandlingsresultatPersoner/RV18_OPPHØRT_OG_FORTSATT_OPPHØRT.json
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9130
Vi har et case der et barn får resultat opphørt og et annet barn får resultatet fortsatt opphørt. Dette er ikke støttet i løsningen i dag. Vi ønsker at behandlingsresultatet skal bli "opphørt". 
Endrer så behandlingsresultatet blir "opphørt" ved personresultater "opphørt" og "fortsatt opphørt"
=> Gi behandlingsresultat opphørt dersom personresultatene er opphørt og fortsatt opphørt

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/sanity/SanityKlient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/sanity/sanityQueries.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BegrunnelseUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BegrunnelseMedTriggere.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevperiodeData.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/SanityBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/StandardbegrunnelseUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/TriggesAv.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/domene/MinimertPerson.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/dataGenerator/behandling/kjørRevurdering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/dataGenerator/brev/MinimertPerson.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevBegrunnelseTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeUtilTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevperiodeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevBegrunnelserTestKlasser.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/StandardbegrunnelseTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceUtilsTest.kt
Avhengig av [endring](https://github.com/navikt/familie-sanity-brev/pull/236) i `familie-sanity-brev`
Lenke til Favro: [TEA-8911](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8911)
Begrunnelsestekster knyttet til reduksjon eller opphør når et barn dør, dukket ikke opp som et valg i behandling med dødsfall dersom "Delt bosted" var valgt som utdypende vurdering i vilkårsvurderingen.
Logikken for om dødsfall-begrunnelser skulle dukke opp, var knyttet til at saksbehandler hadde satt en tom-dato på vilkåret "Bor med søker" og valgt den utdypende vurderingen "Vurdering annet grunnlag". Dersom "Delt bosted" var valgt i tillegg eller istedenfor som utdypende vurdering, "overkjørte" begrunnelsesregelen for delt bosted regelen for dødsfall.
For å løse …
=> Endret logikk for barn død begrunnelse

pom.xml
sentry-logback 6.3.1 brakk deploy. Reverter tilbake til 5.7.4
=> Revert sentry-logback tilbake til 5.7.4

src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggServiceTest.kt
Dagens lærdom er at ved sortering på fleire felt i Spring-SQL-Query må ein definere om det er stigande eller synkande for kvart felt.
Rettar også duplikate innslag og feil tekst.
Dette er rettingar av feil frå førre PR på [Tea-7453](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7453), oppdaga under test. Logghendingane kom no i feil rekkjefølgje (skal vera nyaste øverst).
=> Tea-7453: Rettar sortering av logghendingar, samt tekst og duplikate fnr i logginnslaget ved fleirlingar

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/InternPeriodeOvergangsstønad.kt
Vi har en sendAutobrevVed6og18År task som feiler pga "Antar overgangsstønad for kun søker, men fant overgangsstønad for mer enn en person.". Siden vi ikke har lagt på så mye logging er det vanskelig å vite hvilke perioder og hvilke personer den har funnet. Legger derfor på bedre logging slik at vi enklere kan debugge.
Nei
Kun debug
=> Bedre logging når vi får feil med flere personer som får overgangsstønad

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtilsTest.kt
Dette gir i dag feilmelding, ref https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9191 , men er et legitimt scenario.
Årsaken til at vi skiller på disse er at endring med utbetaling skal trigge iverksetting til økonomi, mens endring uten utbetaling ikke gjør dette. Siden det her er minst en endring som fører til endring i utbetaling så bør denne få presidens.
Her bør vi derfor sette resultatttypen til endra utbetaling.
=> Tea-9191: Viss vi har ytelsepersonresultat som både er endra utbetaling og endra ikkje utbetaling, så skal vi bruke resultat for endra utbetaling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/InternPeriodeOvergangsstønad.kt
Etter å ha tatt i bruk loggingen jeg la på i går oppdaget jeg at hver person blir listet ut flere ganger. Dette er unødvendig. Endrer derfor til å bruke set også for det som logges.
Nei
Bare logging
=> Logg hver person med overgangsstønad kun 1 gang

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/Autobrev6og18ÅrFortsattOpphørtTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9136
Får feilen "Håndtering av stegtype 'BEHANDLINGSRESULTAT' feilet på behandling" ved omregningsbehandling (autobrev 6 og 18 år) når ytelsen opphører samme/neste måned, selv om dette er gjort i tidligere behandlinger. Dette er fordi resultatet blir fortsatt opphørt og ikke fortsatt innvilget. Legger derfor til fortsatt opphørt som gyldig resultat for å sende en omregningsbehandling rett fra behandlingresultat til iverksetting.
Er litt usikker på om dette løser oppgaven, men tror det!
=> Håndter forsatt opphørt som resultat på omregningsbehandlinger

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonClient.kt
Dersom en søker får fortrolig adresse skal de behandles av en egen enhet for kode 6 og 7 brukere. Vi har krav om å kunne tilpasse oss disse endringene innen en time. Kodeverk-chachen er på 24 timer. 
Endrer chachen for `hentBehandlendeEnhet` til short cache som er den vi bruker på data fra PDL.
burde ikke trenge test
=> Bruker short chache for behandlene enhet

src/main/resources/db/migration/V219__fjerner_fagsak_eier.sql
Siste del av fjerning av fagsak.eier
Ble gjort i 2 steg for å unngå å minste bakoverkompatibilitet under deploy.
=> dropper fagsak.eier

src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggService.kt
Justerer tekst som dukker opp i loggene når man angrer korrigert etterbetaling
=> Tea-9063: Justert tekst ved angring av korrigert etterbetaling i loggene

src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/ArbeidsfordelingIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/AutomatiskVilkårsvurderingIntegrasjonTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/AutobrevSmåbarnstilleggOpphørTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/BehandleSmåbarnstilleggTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/BehandlingSatsendringTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/EndretUtbetalingAndelTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/task/FerdigstillBehandlingTaskTest.kt
Det ble tidligere påstått i kommentarene at @DirtiesContext måtte bli brukt fordi `every` ble brukt som `endret funksjonalliteten for alle klasser.`. Jeg så dog at man uansett unmocker og setter opp mockene på nytt for hver test, så jeg forsøkte å fjerne @DirtiesContext og det har vist seg til å fungere.
Vi får uansett ikke så mye gevinst på dette, da spring context'n må settes opp på nytt for mange av våre tester. (mest gevinst på verdikjedetest?)
Dette er pågrunn av at mange av testene kjører med forskjellig antall @ActiveProfiles (burde sees på i en annen sak)
Litt usikker på hvor stabilt dette er. Har tidligere fått beskjed om at det testene sporadisk feiler hvis man ikke har DirtiesContext, men jeg har ikke opplevd dette.
_Jeg har ikke skrevet …
=> Tea-6031: Fjerner dirtiescontext på alle tester som skal fungere etter man begynte å cleare mocks

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestRegistrerInstitusjonOgVerge.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/UtvidetBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/verge/Verge.kt, src/main/resources/db/migration/V221__drop_verge_navn_adresse_og_unique_index_verge_ident.sql, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrerInstitusjonOgVergeStegTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/verge/VergeServiceTest.kt
Navn og adresse kan fjernes fra verge da det er overflødig informasjon som ikke trengs videre ved distribusjon av brev via Dokdist-API. 
=> Fjerner overflødige felter, navn og adresse, fra Verge

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsvurderingTidslinjer.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsvurderingTidslinjerTest.kt
For vilkåret bor med søker skal vi tillate at periodar overlappar. Det typiske eksempelet her er at du søker for delt bosted, men foreldra bur saman, så vi avslår det, og innvilger heller fullt. Da skal delt bosted-vilkåret vera avslått, gjerne med udefinert fom og tom, medan fullt-vilkåret skal vera innvilga.
Favro:
- https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8868
- https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9253
Det er mogleg denne PR-en ikkje løyser alle problema, men det her må uansett gjerast. Tenkjer å leite etter moglege andre ting som må oppdaterast i preprod etter denne er merga.
_Er det noe du er usikker på eller ønsker å diskutere? Beskriv det gjerne her eller kommenter koden det …
=> Tea-8868: Unngår å gruppere saman bor med søker-vilkår til samme tidslinje

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilpassDifferanseberegningService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilkjentYtelseRepositoryOppdaterTilkjentYtelseTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/TilkjentYtelseBuilder.kt
Sikkerhetsnettet rundt EØS og endring av andeler tilkjent ytelse, sjekker nå for duplikater hos barna. Denne sjekker også for duplikater hos søker. Her må ytelsestype være med fordi utvidet barnetrygd og småbarnstillegg kan overlappe i tid.
Nei
_Jeg har ikke skrevet tester fordi:_  Det _burde_ være dekket av tidligere tester.
=> Utvider sikkerhetsnettet til også å sjekke søkers andeler for duplikater

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilkjentYtelseDifferanseberegningTest.kt
Vi får trøbbel tilknyttet EØS fordi det ikke tas hensyn til endringsperioder i vurderingen om to andeler tilkjent ytelse er like. Forsøker å quickfix'e det med å legge inn id'ene til endringene i hashcode og equals i AndelTilkjentYtelse
Vet jo at dette er litt dirty. Bør løses ordentlig med å frikoble andeler og endringer
_Jeg har ikke skrevet tester fordi:_ de eksisterende testene _burde_ sjekke dette
=> Legger til id'ene til endringsperioder i hashcode og equals på andel tilkjent ytelse

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonopplysningGrunnlag.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/domene/PersonResultat.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/VilkårVurderingTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonoGrunnlagServiceTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9625
Noe må gjøres med hva som lagres i persongrunnlaget på institusjon/enslig_mindreårig-saker for at vilkårene på barnet skal dukke opp under vilkårsvurderingen i frontend. Default oppførsel er å lagre hovedaktøren på saken som SØKER, som blir feil når det dreier seg om et barn, siden det er denne persontypen som da blir gjeldene, og man får ikke sett vilkårene som gjelder for barn. Har gjort følgende:
- Legger til "aktør" som BARN istedenfor SØKER ved opprettelse av  personopplysningGrunnlag på institusjon/enslig_mindreårig-saker.
- Returnerer barnet når "persongrunnlag.søker" kalles på en institusjon/enslig_mindreårig-sak istedenfor å kaste feil, siden det er barnet som da er aktøren man er ute …
=> Persongrunnlag på institusjon- og enslig mindreårig saker

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringService.kt
Valideringen er for streng og stopper behandlinger som ikke burde stoppes.
=> Ignorer offsetandeler som er null i validering

.dockerignore
No køyrer vi docker build på heile mappa vi køyrer frå. Med dockerignore sørger vi for at docker berre kopierer inn akkurat dei filene vi bryr oss om. Sia vi køyrer maven-bygg først, og bygger ein fat-jar, er det nok berre denne jar-fila vi faktisk treng å ha med inn.
Favro: [Tea-9681](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9681)
Er det andre filer som må med? Har ikkje sett teikn til det, men kan jo vera noko godt gøymt
=> Tea-9681: Trur ikkje vi treng meir enn sjølve jar-fila når vi skal køyre docker-bygget, så da er det unødvendig å bygge inn mykje meir

pom.xml
Oppgraderer til nyaste minor-version av Spring Boot. Kjekt å halde oss fortløpande oppdatert.
Ryddar med det samme bort to apache-http-bibliotek vi ikkje bruker lenger, og samlar all versjonsstyring i properties
Nei
=> Oppgraderer til nyaste Spring Boot, og fjernar ubrukte http-avhengnadar

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/UtvidetBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/behandlingstema/BehandlingstemaService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/EndringstidspunktService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilpassDifferanseberegningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/utenlandskperiodebeløp/UtenlandskPeriodebeløpController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/ValutakursController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/EøsSkjemaerForNyBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtbetalingsperiodeMedBegrunnelser/UtbetalingsperiodeMedBegrunnelserService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/LagreMigreringsdatoTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/behandlingstema/BehandlingstemaServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingStegTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/VedtakServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/utenlandskperiodebeløp/UtenlandskPeriodebeløpControllerTest.kt
Fjerner funksjonsbryteren  KAN_BEHANDLE_EØS fordi den nå skal gjøres tilgjengelig for alle
Nei
_Jeg har ikke skrevet tester fordi:_ endringen eer dekke av testene
=> Fjerner bruken av funksjonsbryteren KAN_BEHANDLE_EØS

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilpassDifferanseberegningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseController.kt
Sekundærland-funksjonaliteten er nå permanent skrudd på. Fjerner toggle og tilhørende kode.
Nei
_Jeg har ikke skrevet tester fordi:_ det ikke endrer funksjonalitet 🤞
=> Fjerner funksjonsbryteren KAN_BEHANDLE_EØS_SEKUNDERLAND

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/UtgåendeJournalføringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/domene/PersonResultat.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceEnhetstest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/OppdaterVilkårsvurderingTest.kt
Legger til støtte for institusjon som mottaker ved sending av brev via høyremenyen:
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9441
Forsøker samtidig å løse problemet med at opplysningspliktvilkåret ikke alltid legges til etter utsending av brev:
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9377
- Initierer vilkårsvurderingen for behandlingen hvis den ikke finnes
- Tar vare på andreVurderinger når vilkårsvurderingen oppdateres senere.
Problemet med opplysningspliktvilkåret som ikke vises, er at det blir forsøkt lagret på vilkårsvurderingen, som først blir opprettet når man kommer til det steget, vanligvis. Det ser likevel ut som det skal gå bra å initiere vilkårsvurderingen tidligere etter behov. …
=> TEA-9441 Tea-9377 Oppdaterer sendManueltBrev i DokumentService

src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/BehandleSmåbarnstilleggTest.kt
Ref [dokumentasjonen](https://www.postgresql.org/docs/current/queries-order.html)
Stabiliserer test
Favro: [Tea-9777](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9777)
=> Tea-9777: Rekkjefølgja på select i postgres er ikkje-deterministisk, så når vi assertert på første innslag, må vi sortere for at det skal bli rett

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/domene/VilkårRegelverkResultat.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsresultatMånedTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/Periode.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/TidslinjerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsresultatMånedTidslinjeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/rest/RestTidslinjerTest.kt
EØS-perioder blir én måned for lange fordi eksisterende kode ikke sjekker om perioden avsluttes siste dag i måneden. Da skal EØS-perioden også stoppe den måneden. Dette endrer oppførselen til en del tester, som da må ha vært feil hele tiden. 
MERK at det er tilsvarende kode i `PersonResultat`. Det må sjekkes om ikke også den bør skrives om. Det blir i så fall en egen PR.
Nei
- [] Nei
=> Fikser konvertering av vilkårsresultat fra dagsnivå til månedsnivå

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/domene/Vilkår.kt
Lenke til Favro: [TEA-9712](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9712)
Vilkår av typen `UTVIDET_BARNETRYGD` har fått feltet `vurderesEtter` satt til `NASJONALE_REGLER` dersom behandlingskategori er "Nasjonal" og `EØS_FORORDNINGEN` dersom kategori er "EØS". Problemet oppstår i revurderingen dersom man skal behandle i henhold til annet regelverk enn i førstegangsbehandlingen. Saksbehandler får regelverks-mismatch da det ikke går an å sette `vurderesEtter` på vilkåret `UTVIDET_BARNETRYGD` i frontend. 
Løsningen er å alltid sette `vurderesEtter` til null for `UTVIDET_BARNETRYGD`, slik det allerede er gjort for `UNDER_18_ÅR` og `GIFT_PARNTERSKAP`.
Eivind nullstiller `vurderesEtter` for `UTVIDET_BARNETRYGD`  i databasen for alle eksisterende …
=> Fjernet default verdi for vurderesEtter for utvidet barnetrygd vilkår

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt
Andeler i endre migreringsdato behandlinger skal få ny offset, selv om de er like som i forrige behandling. Må derfor filtrere de ut så vi ikke oppdaterer feil på flere behandlinger.
Nei
=> Filtrer ut Endre migreringsdato-behandlinger ved offset-retting

src/main/resources/db/migration/V226__vurderes_etter_null_for_utvidet.sql
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9712
I en kommentar så sier Eivind at man skal kjøre denne sql for å oppdatere gamle saker slik at det står "null" i vurderes_etter for UTVIDET_BARNETRYGD
@EAamli 
Kjørte
select count(*) from vilkar_resultat where vilkar='UTVIDET_BARNETRYGD' AND vurderes_etter is not null;
Som ga 159526 i prod og 1194 i preprod. Stemmer dettte? Synes det er rart at jeg fikk så mange i preprod når du hadde alt kjørt det der
=> Sql for å rydde opp TEA-9712 for utvidet barnetrygd med vurder_etter ikke null

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevOpphørSmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt
BA-sak har fått overført overgangsstønad med splitt i perioder, d.v.s. to perioder med full overgangsstønad ligger back to back, og det er ingen endring i utbetalt overgangsstønad.
Småbarnstillegget er difor innvilget for begge perioder, men ba-sak har alikavel sendt autobrev om opphør.
Fiksen skal hindre at autobrev om opphør av småbarnstillegg blir sendt ut, sidan ytelsen fortsatt er løpende.
=> Ikkje send autobrev opphør småbarnstillegg, når småbarnstillegget fortsatt er løpende neste måned

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/OffsetOppdatering.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsperiodeMal.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/NyUtbetalingsoppdragGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/UtbetalingsoppdragService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/RettOffsetIAndelTilkjentYtelseTask.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/IverksettMotOppdrag.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/PeriodeOffsetIntegrasjonTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/UtbetalingsoppdragServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiIntegrasjonTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiUtilsTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/NyUtbetalingsoppdragGeneratorTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragIntegrasjonTest.kt
Vi har i dag en knyttet til generering av utbetalingsoppdrag. Ved simulering skal ikke andelene oppdateres med periodeOffset, men det skjer uansett pga at andelene hentes ut i en transaksjon under JPA, og offset-verdiene endres på andel entitetene
Jeg forsøker med dette å lage to ulike wrappere rundt andelene som brukes i generering av utbetalingsoppdrag. Hvis det er simulering, vil wrapper-implementasjonen ikke oppdatere offset-verdiene på andel-entitetene. 
Målet vare å gjøre så lite endringer som mulig. Det har ikke lykkes helt.
_Greiest å lese commit for commit_
_Jeg har ikke skrevet tester fordi:_ det ikke skal introdusere funksjonelle endrringer
=> Lager en wrapper-klasse for andel tilkjent ytelse som brukes ved generering av utbetalingsoppdrag

src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggService.kt
Fjerner overstyrende tittel med liten forbokstav. Korrekt tittel vil da settes fra Loggtype.visningsnavn istedet.
Verifisert manuelt i frontend
Før:
Nå:
=> Fjerner overstyrende tittel for LoggType.INSTITUSJON_REGISTRERT

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/Brev.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceEnhetstest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevTypeTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10069
- logikk for å sette behandlingen på vent og trigge opplysningspliktvilkåret etter brevet er sendt.
- venteårsak
- ventefristDager
=> Legger til samme logikk for "innhente opplysninger"-brevet tilpasset institusjon som ellers

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsresultatDagTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsvurderingTidslinjer.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/domene/VilkårResultat.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsvurderingTidslinjerTest.kt
Får dann og vann TidslinjeException fordi det er funksjonelt mulig å legge inn IKKE_OPPFYLTE vilkårresultater som overlapper med OPPFYLT vilkårrsresultat for samme vilkår og aktør. BOR_MED_SØKER er et sånt tilfelle, der vilkåret som sådan er OPPFYLT, mens undervilkåret DELT_BOSTED ikke er oppfylt. Saksbehandler oppretter da to vilkårsresultater for BOR_MED_SØKER for et barn, ett OPPFYLT og ett IKKE_OPPFYLT. Antakelsen er at IKKE_OPPFYLTE vilkår av denne typen kan ignoreres i beregning fordi de bare skal brukes i brev-generering. Det er OPPFYLTE vilkår som sammenstilles til EØS-perioder, og fravær av perioder oppfører seg likt som perioder som er IKKE_OPPFYLT.
Tusenkronersspørsmålet er om antakelsen holder.  …
=> Fjerner vilkårsresultater som er IKKE_OPPFYLT ifm beregning av EØS-perioder

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsresultatMånedTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/MapTidslinje.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/VilkårVurderingBuilder.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/TidslinjerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsresultatMånedTidslinjeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/TidspunktClosedRangeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/eksperimentelt/TidspunktClosedRangeUtvidelser.kt
Gjeldende tolkning er at regelverket som skal benyttes er det som gjaldt forrige måned. Det stemmer _ikke_; det er regelverket som gjelder for _inneværende_ måned som skal benyttes. 
Regelverket ved månedsskifte ble også feil hvis tom-datoen var null, dvs uendelig. Fkser det ved å sjekke tidsrommet én måned før og etter hhv fom og ttom
Nei
=> Bugfix feil regelverk ved månedsskifte

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/AvstemmingService.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyController.kt, src/main/kotlin/no/nav/familie/ba/sak/task/KonsistensavstemMotOppdragStartTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/AvstemmingServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/KonsistensavstemMotOppdragStartTaskTest.kt
Optimalisering av konsistensavstemming start tasken
I stedet for å hente 500 per query, så henter man nå 10000 av gangen, og heller chunker ved bruk av kode.
Hvor den gamle brukte 3 minutter på 20000 behandlinger, så brukte den nye måten 11 sekunder
=> henter større bolker med behandlinger i konsistensavstemming, og heller bruker chunked for å sikre data størrelsen

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/AvstemmingService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/KonsistensavstemMotOppdragStartTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/AvstemmingServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/KonsistensavstemMotOppdragStartTaskTest.kt
- Konsistensavstemming task kjøres kun 1 gang og settes til manuell oppfølging hvis feil
- Bruker dagens dato som avstemmingsdato slik at den kan rekjøres ved feil
- dryRun gjør litt mere nå
=> Konsistensavstemming manuell oppfølging

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt
Til nå har feilmeldingen frontend vært "En feil har oppstått" hvis man prøver å generere svartidsbrev uten å ha satt antall uker svarfrist. Jeg endrer så feilmeldingen "Antall uker svarfrist er ikke satt" blir vist frontend så saksbehandler kan se hva som er galt. 
Avklart med Gunn.
Det er bare teksten på en feilmelding
Før:
Etter:
=> Vis bedre frontendfeilmelding hvis antall uker svarfrist ikke er satt ved svartidsbrev

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/felles/PeriodeOgBarnSkjema.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/felles/beregning/JusteringAvOppdatering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseServiceTest.kt
Legger på mulighet for å forkorte til-og-med, ref [denne](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9728) 
Nei
=> Legger på mulighet til å forkorte til-og-med på EØS-skjemaer

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiService.kt
Valideringen i prod tar ikke hensyn til nullperioder pga sekundærland/EØS. Funksjonaliteten er allerede skrevet, men nøyer meg med å ta i bruk valideringen i denne PRen.
Byttet ut med en ny funksjonsbryter. Det betyr at TO funksjonsbrytere må skrus på for å ta i bruk hele den nye implementasjonen av utbetalingsoppdrag.
_Jeg har ikke skrevet tester fordi:_ testene allerede fantes.
=> Tar i bruk ny validering av utbetalingsoppdrag for å håndtere nullperioder på EØS

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestUtvidetBehandling.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestVisningBehandling.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/SøknadDTO.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/UtvidetBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/behandlingstema/BehandlingstemaService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrereSøknad.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/VilkårsvurderingForNyBehandlingUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkService.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/søknad/SøknadGrunnlagTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/JournalførOgBehandleFørstegangssøknadNasjonalTest.kt
Så at en ny konstant ("Institusjon") i BehandlingUnderkategori ikke førte til kompileringsfeil, enda den brukes i mange integrasjonspunkter. Denne PRen tar i bruk `when` uten else for å tvinge frem håndtering alle steder. 
Overgangen til YtelseType gjør vi på to forskjellige måter. 
- VilkårsvurderingForNyBehandlingUtils.lagPersonResultaterForMigreringsbehandling
- TilkjentYtelseUtils.finnYtelseType
I tillegg innføres en DTO-type for kommunikasjon med frontend, for å fange opp endringer der også. Usikker på om det er nødvendig/ønskelig
_Jeg har ikke skrevet tester fordi:_ det _burde_ værre sjekket av andre tester. 
- [] Nei
=> Skriver om til å utnytte kompilatoren til å tvinge frem håndtering når BehandlingUnderkategori-enum'en får ny konstant

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/Brev.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/VarselbrevÅrlegKontrollEØS.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevTypeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequestTest.kt
Lagt til støtte for 2 nye varselbrev i forbindelse med revurdering årleg kontroll av EØS-saker. Begge breva bruker nytt flettefelt mottakerlandSED, og eine brevet skal ha med liste over dokumenter.
Begge breva fører til at behandling skal settes på vent.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9340
=> TEA-9340 2 nye varselbrev for årleg kontroll EØS-saker

.deploy/nais/app-preprod.yaml, .deploy/nais/app-prod.yaml
Nginx har automatisk retry for GET kall som tar tid. Vi har skatteetaten-api som kan ta lengre tid enn retryintervallet på 1 minutt. Så for å unngå at nginx spammer oss med tunge kall, så settes denne parameteren.
Testet i miljø
=> Setter ned antall autoretry til 1 ved GET fra nginx

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsresultatMånedTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/EndreTid.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/MånedFraMånedsskifteTest.kt
Legger til en ny tidslinje-funksjon som lar en generere en månedstidslinje fra siste dag i forrige måned og første dag i inneværende måned, og tar den i bruk for å generere vilkårsresultat-tidslinjer. 
Nei
=> Legger inn extension-funksjon for å mappe dager ved månedsskiftet

src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/komposisjon/TidslinjeFraTidspunkt.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/komposisjon/TidslinjeKombinator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/BeskjæreTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/EndreTid.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/BeskjæreTidslinjeTest.kt
`TidslinjeSomStykkerOppTiden` er foreldet og denne PRen fjerrner bruken et par steder. Beskjæring av tidslinjer blir da litt enklere og riktigere, og et par tester må endres til å reflektere det. 
Nei
_Jeg har ikke skrevet tester fordi:_ dette er dekket av tester fra før
=> Svitsjer et par tislinjeomformere til å bruke tidslinjeFraTidspunkt og benytter anledningen til å forenkle

src/main/kotlin/no/nav/familie/ba/sak/ekstern/tilbakekreving/FagsystemsbehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonClient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/ArbeidsfordelingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/UtvidetBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/JournalførVedtaksbrev.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingService.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/IntegrasjonClientMock.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/ekstern/tilbakekreving/HentFagsystemsbehandlingRequestConsumerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/ArbeidsfordelingIntegrationTest.kt
- Fikser feil ved at man ikke kan bytte enhet hvis man har mappe satt, siden den nye mappen ikke har tilgang til mappen.
- Fikser også feil om at endringen ikke ble rullet tilbake ved feil, men i stedet ble commit i ba-sak basen, slik at det ble usynk mellom ba og oppgave, og at man ikke sendte saksstatistikkmelding.
- Skrivefeil på hentArbeidsfordelingPåBehandling
Testet ok i preprod
=> fix: oppdater enhet for behandlig tar i bruk nytt endepunkt

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/Opphørsperiode.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/OpphørsperiodeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceEnhetstest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceTest.kt
Favro: [https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9895](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9895)
Ekskluderer perioder datert før endringstidspunktet fra sammenslåingen av opphørsperioder, da perioder fra tidligere vedtak uten en fastsatt tom-dato dekket over nye, siden de regnes som gjeldende til ubestemt tid, og det førte til feil begrunnelse for opphør i vedtaksbrevet.
=> Fix: Feil barn hentes inn i begrunnelse ved opphør

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PersonopplysningerService.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkService.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PersonopplysningerServiceTest.kt, src/test/resources/pdl/PdlIntegrasjon/utenlandskAdresseResponse.json
PDL sin landkode er alpha3, mens man kontrakten til statistikk er alpha2. Nå som man migrerer over EØS så fikk vi valideringsfeil i ba-statistikk om at landkode var for lang.
=> Gjør om landkode alpha3 til alpha2 for statistikk for utenlandsk adresse

src/main/kotlin/no/nav/familie/ba/sak/task/KonsistensavstemMotOppdragAvsluttTask.kt
Etter optimalisering av løypa, så blir 3 retries litt knapt, siden den må vente på noen tusen tasker skal kjøre ferdig før den blir grønn. Hver retry er 15 min. Utvidet antall retries slik at tasken har 2.5t å kjøre ferdig på.
=> Utvider tiden på konsistensavstemming avslutttask fra 45min til 2.5timer

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/AndelTilkjentYtelseTidslinjeUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/Differanseberegning.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilpassDifferanseberegningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/komposisjon/TidslinjeFraTidspunkt.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/komposisjon/TidslinjeJoin.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/komposisjon/TidslinjeKombinator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/tidsrom/Tidsrom.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningSøkersYtelserTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/TilkjentYtelseDsl.kt
Hvis differanseberegningen av barns ordinære barnetrygd blir negativ, så skal resten kunne komme til fratrekk i utvidet barnetrygd og eventuelt småbarnstillegg. Logikken er beskrevet i [dette Favro-kortet](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8958).
*Bør leses commit for commit*
Det er en del dupliseing i selve logikken. Landet på å la det bli sånn fordi det opplevdes som hakket lettere å lese, synes jeg.
=> Feature/differanseberegning søkers ytelser

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt
Endringer i flere løpende saker sjekken etter diskusjon med Tore
Har sett litt på dette. Problemet er nok at vi har hatt en feil i Infotrygd, hvor det IKKE er satt opphørsgrunn.
Spesielt i august 2020; det finnes 2.020 tilfeller hvor Opphørsdato (B20_OPPHOERT_VFOM) er satt, men ikke B20_OPPHORSGRUNN.
I tillegg har vi 12 andre slengere med samme problem.
I det konkrete eksemplet er det sak A07 du finner ekstra på grunn av dette. Både B20_OPPHOERT_VFOM og B20_OPPHOERT_IVER  inneholder ‘092020’, men B20_OPPHORSGRUNN er altså feilaktig 0.
Er det mulig for deg å endre testen, slik at du kun sjekker på B20_OPPHOERT_VFOM, IKKE på B20_OPPHORSGRUNN???
I så fall tror jeg mange flere kan migreres maskinelt uten problemer.
=> Tillatt migrering av saker med opphørsgrunn 0, men hvor opphørtFom er satt

src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelController.kt
Trenger å manuelt kjøre tilbakestillBehandlingTilBehandlingsresultat på en sak uten utvidetBehandlingService                   .lagRestUtvidetBehandling(behandlingId = behandling.id) kalles for en saken rett etterpå for å rette opp en sak manuelt
=> Eksponerer tilbakestillBehandlingTilBehandlingsresultatService

src/main/kotlin/no/nav/familie/ba/sak/ekstern/tilbakekreving/FagsystemsbehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingUtil.kt
Dersom saksbehandler velger å opprette tilbakekrevingsbehandling manuelt (frå menyvalget  "Opprett behandling" med type "Tilbakekreving" i ba-sak) før denne oppgåven er gjort, så vil behandlingen opprettast som ein behandling på bruker og ikkje institusjon.
Dersom kravgrunnlaget, som vart opprettet når revurdering med feilutbetaling vart vedtatt, har ligget i "innboksen" i familie-tilbake i 8 veker, så blir kravgrunnlaget automatisk lest inn og tilbakekrevingsbehandling oppretta, og behandling vil bli opprettet feil, som beskrivet over.
=> Inkludere institusjon-informasjon i responsen HentFagsystemsbehandlingRespons når ba-sak mottar ein HentFagsystemsbehandlingRequest

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/Differanseberegning.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningsUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningSøkersYtelserTest.kt
Hvis søkers ytelser allerede er differanseberegnet, kan det oppstå feil når vi skal beregne på nytt. Denne fiksen gjør to ting:
* Fjerner eventuelt eksisterende differanseberegning før beregning
* Gjennomfører differanseberegningen uansett
_Bør leses commit for commit_
Endringen betyr at alle søkers ytelser vil gå gjennom denne koden og få nye andeler (ofte identiske med de som ble sendt inn) underveis, tilsvarende som for barnas ytelse. Det innebærer en større risiko enn forrige versjon (med feil).
Riskoen som introduseres skyldes at `TilkjentYtelse` er under kontroll av JPA, og at manipulering av andelene kan skape uheldige sideeffekter. _Kan_ jo ta en ny runde på om det er mulig å unngå å treffe denne koden hvis differanseberegning ikke er relevant. Utfordringen jeg har, er at vi må …
=> Bugfix/korrekt opprydding i differanseberegning av søkers ytelser

.github/workflows/build-pr.yml
GitHub har no støtte for å avbryte samtidig pågåande bygg for samme grein, som vi kan ta i bruk heller enn å bruke eit tredjepartsbibliotek for det.
Det kjens både tryggare frå eit vedlikehaldsperspektiv og frå eit tryggleiksperspektiv
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9791)
=> Bruker GitHub Actions sin innebygde mekanisme for å avbryte pågåande jobbar heller enn å bruke tredjeparten vi bruker no

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakServiceTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9841
Lager et endepunkt som finner fagsakId+aktørId for alle fagsaker hvor personen man sender inn enten mottar løpende utvidet eller løpende ordinær.
Nei
=> Endepunkt: finn fagsaker hvor person har løpende utvidet eller løpende ordinær

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt
Rydde PR: Fjerner toggles for migrering som man ikke trenger lenger
=> Sletter toggles for migrering som ikke er nødvendig lenger

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/domene/Kompetanse.kt
Autobrev opphør 6 og 18 feiler for migrerte sakers av eøs primærland fordi komeptanseskjemaet er opprettet uten verdier. Filtrerer bort disse ved oppretting av brevperioder
Testet i preprod med sak:
https://barnetrygd.dev.intern.nav.no/fagsak/200008723/saksoversikt
=> Filtrerer bort tom kompetanse ved migrering primærland ved autobrev

src/test/resources/hentMiljøvariabler.sh
Passer på at vi ikke henter miljøvariablene fra podder som ikke kjører. I dette tilfellet 👇 prøvde jeg å hente fra den øverste podden som ga meg feilmeldingen `error: cannot exec into a container in a completed pod;`
=> Hent kun løpende podder

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeService.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10696
Kun ta med kompetanser som er utfylte når brev skal genereres ved automatiske behandlinger, og forrige behandling var en EØS-migrering. Grunnen til dette er fordi ved automatiske EØS-migreringer så blir kompetansen tom. Dette skaper problemer i autobrev-behandlinger fordi man drar med seg den tomme kompetansen, som det blir kastet feil for (se bilde av feil under).
Problemet ble opprinnelig prøvd løst her: https://github.com/navikt/familie-ba-sak/pull/3129, men måtte reverteres her: https://github.com/navikt/familie-ba-sak/pull/3136.
Nei ikke egentlig.
Koster mye og gir minimalt med verdi.
=> Bug: EØS-migreringer skaper problemer pga tomme kompetanser

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/ForsattInnvilget.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/Førstegangsvedtak.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceEnhetstest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9732)
Legger til Informasjon om årlig kontroll som en mulig delmal for vedtaksbrevene Førstegangsvedtak og FortsattInnvilget, og utvider sjekken som trigger delmalen til å inkludere tom-dato blant vedtaksperiodene som ikke er utløpt, ved siden av tom-dato som er null.
=> Fikser visning av delmal 1 for årlig kontroll EØS

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BegrunnelseMedTriggere.kt
Kaster en Feil hvis man ikke finner en begrunnelse med gitt apiNavn. Dette er for å unngå nullpointers som dette:
Nei
Unødvendig imo
=> Kast Feil hvis begrunnelse med apiNavn ikke finnes i listen med begrunnelser

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/småbarnstillegg/AutovedtakSmåbarnstilleggService.kt
Knyttet til denne feilen: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10669
Retter opp årsaken til at feilen i saken over har oppstått. Årsaken til feilen er at autovedtak for småbarnstillegg setter status til "iverksetter vedtak" på slutten av behandlingsresultat-steget. Når man da skal begrunne vedtaket etterpå, og dette feiler av en eller annen grunn, så er fortsatt status "iverksetter vedtak" når behandligen blir gjort om til manuell. Her tilbakestiller jeg status til "utredes" om behandlingen blir omgjort til manuell behandling. 
Syns måten det er løst på med å sette status = "iverksetter vedtak" i behandlingsresultat-steget virker litt rart, og jeg kunne gjerne tenke meg å skrive om dette. Men det blir en større omskriving, fordi det kan …
=> Tilbakestiller status på behandling til UTREDES ved omgjøring til manuell behandling for småbarnstillegg

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/Differanseberegning.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningsUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilpassDifferanseberegningService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningSøkersYtelserTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/TilkjentYtelseBuilder.kt
Det var en mangel i forrige implementasjon: Kravet er at søkers ytelser først differanseberegnes i perioder der alle andeler tilkjente ytelser  for relevante barn er differanseberegnet, dvs kompetansen er vurdert til at Norge er sekundærland. 
Jeg løser (delvis) tre andre svakheter:
* Splitter i andeler forårsaket av differanseberegning ble ikke slått sammen hvis differanseberegning på barna ble fjernet. Det er delvis løst her
* Hvis søkers ytelse deles på et antall barn som ikke gir heltallsresultat, kan differanseberegningen bli flere kroner feil. Også delvis løst med overgang til BigDecimal. Avvik kan fortsatt forekomme, men det blir sjeldnere. 
* Fjernet en funksjonsbryter som bare var en duplikat
_Kan leses commit for commit, men funker nok også å se alt under ett._ 
* De to siste …
=> Ny implementasjon av differanseberegning av søkers ytelser

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/VilkårsvurderingForNyBehandlingService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceEnhetstest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/VilkårVurderingTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårServiceTest.kt
Hvis saksbehandler revurderer pga av søknad og sender ut et brev i registrer-søknad-steget, så er ikke vilkårsvurderingen opprettet ennå. Hvis brevet utløser opplysningsplikt, vil vilkårsvurderingen opprettes. Denne fiksen sørger for at vilkårsvurderingen fra eventuell vedtatt behandling blir kopiert. Fjerner null-default-verdien på forrige-behandling-parameteren, slik at fremtidige utviklere må ta stilling til den. 
Nei
=> Bugfix/manglende kopiering av vilkårsvurdering ved manglende opplysninger

.deploy/nais/app-prod.yaml
da POST-request til api/oppgave/hent-frister-for-apne-utvidet-barnetrygd-behandlinger også ble brutt etter 1 minutt på lik linje med GET
=> Forsøker å sette nginx proxy timeout verdier til 3 minutter

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceIntegrasjonTest.kt
Støtte for å migrere saker fra infotrygd hvor barnet har historisk ident
Det er kun testene med sammenlingBarnInfotrygdMedBarnBAsak som er nye. De andre så har jeg bare separert enhetstest og integrasjonstest
Jeg har testet lokalt mot q1 på en sak
=> Åpner opp for å migrere saker med historisk ident på barna

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestUtvidetBehandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/UtvidetBehandlingService.kt
Jobbet med å overføre feilutbetaltValuta logikken fra ba-sak til ks-sak.
Oppdaget trekkILøpendeUtbetaling som senere ble renamet til feilutbetaltValuta, men ikke fjernet fra behandlingresponsen enda. Frontend bruker heller ikke feltet, så tenkte det er greit å bli kvitt det nå.
=> Fjerner ubrukt felt fra utvidet behandling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt
Etterbetaling korrigering må også tillate verdi === 0 i tillegg til positive heltall.
Endringer må også gjøres i frontend. Se: https://github.com/navikt/familie-ba-sak-frontend/pull/2490
Før:
https://user-images.githubusercontent.com/110383605/214021777-b2124a31-1976-4bd3-ba69-2e876a1e535e.mov
Etter:
https://user-images.githubusercontent.com/110383605/214021792-11302bdd-fab0-4046-8f4b-9bb87ff4f0c4.mov
=> Tillat 0 som verdi i etterbetaling korrigering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt
Liten bugfix. Vi ønsker ikke å bruke verdien 0 hvis det kommer fra simulering, bare hvis det kommer fra korrigert etterbetaling.
=> Fikser bug som bruker verdien 0 hvis det kommer fra simulering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt
Vi går tilbake til å skjule etterbetaling tekst-snutt dersom beløp er 0 eller mindre uansett grunn.
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-11005
=> Vi skjuler etterbetaling uansett dersom beløp er 0 eller mindre

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/domene/ØkonomiSimuleringPostering.kt, src/main/resources/db/migration/V235__okonomi_simulering_mottaker_legg_til_er_feilutbetaling.sql, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/ØkonomiTestConfig.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringUtilTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/VurderTilbakekrevingStegTest.kt
Legger til felt som lar oss skille på om en feilutbetaling er reel eller ikke. Dersom nøs har laget en manuell postering etter at betalingen har gått ut fra venteregisteret(eller noe i den duren, jeg er ikke helt stødig på når det skjer) får vi feilutbetaling tilsvarende den manuelle posteringen. 
Siden den de feilutbetalingene ikke er reelle ønsker vi å se bort fra dem. Vi har en antagelse om at "erFeilkonto" er false når feilutbetalingene ikke er reelle, og at vi dermed kan se bort fra dem
=> Legg til "erFeilkonto" på ØkonomiSimuleringPostering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringUtilTest.kt
Korrigert resulat skal være lik resultat i dette tilfellet ☝️, ikke 0
=> La korrigert resultat være mindre enn 0

.github/workflows/build-and-deploy-preprod.yml, .github/workflows/build-and-deploy-prod.yml
For ba-sak går vi tilbake til vanlig ubuntu-runner siden det ikke finnes mange runners for 8 cores samt at det ikke ga oss gevinst i integrasjonstestene. Vi lar det stå for ks foreløpig da ks har fått stor gevinst av å bytte.
=> Vi går tilbake til vanlig runners siden det finnes færre runners for 8 cores og det ga oss ikke gevinst

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/AndelTilkjentYtelseTidslinjeUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SatsService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggBarnetrygdGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseRepositoryUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/Differanseberegning.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningsUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilpassDifferanseberegningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/småbarnstilleggkorrigering/SmåbarnstilleggKorrigeringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/komposisjon/TidslinjeKombinator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/komposisjon/TomTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/domene/PersonResultat.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilkjentYtelseRepositoryOppdaterTilkjentYtelseTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/TilkjentYtelseBuilder.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/småbarnstilleggkorrigering/SmåbarnstilleggKorrigeringServiceTest.kt
`SatsService.hentGyldigSats` tillater ikke å finne satsen for en periode i fremtiden. Det kan skape trøbbel, og virker som en unødvendig begrensning. I stedet bruker jeg `satstypeTidslinje` og skriver generelt om til å bruke tidslinjer mer.
_Les gjerne commit for commit_
Fikler (som vanlig) med TilkjentYtelse.andelerTilkjentYtelse, som historisk sett ikke er lurt. Oppførselen er litt endret mtp hvilke andeler som fjernes og legges til. Men det _bør_ gå bra 🤞 
_Jeg har ikke skrevet tester fordi:_ koden allerede hadde tester. Har justert dem litt til å stemme overens med ny virkelighet, men de bør være funksjonelt like.
=> Fjerner avhengighet til SatsService.hentGyldigSats og skriver om til tidslinjer

src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringUtilTest.kt, src/test/resources/kjerne.simulering/simulering_med_manuell_postering.json, src/test/resources/kjerne.simulering/simulering_med_mottrekk.json
Vi har et testcase med en "fremtidig" debit-postering ikke som ikke har en tilsvarende kredit-postering. Siden vi har passert januar er den ikke lenger fremtidig, og den gir feil. Fjerner derfor posteringer for januar 2023 i to tester
=> Fjern fremtidige posteringer testcase

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/AndelTilkjentYtelseMedEndreteUtbetalingerTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/AndelTilkjentYtelseTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggBarnetrygdGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/småbarnstilleggkorrigering/SmåbarnstilleggKorrigeringService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggUtilsTest.kt
Gjør to ting:
- Endrer måten vi henter ut endret utbetaling andel for en gitt måned. Før var vi avhengig av listen med endringer som lå på andelen, men nå lager vi heller en endretUtbetalingAndelTidslinje som vi kombinerer sammen med de to Aty-tidslinjene
- Bruker AndelTilkjentYtelse direkte i stedet for å få gjennom wrapper-klassen AndelTilkjentYtelseMedEndreteUtbetalinger
Nei
Endrer ikke på logikken så eksisterende tester burde fortsatt kjøre grønt 💚
=> Behandlingsresultat: endre måten vi henter ut endret utbetaling andel for aty

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSøknadUtils.kt
Tok å gjennomgikk uregistrert barn logikken med Anna.
Dersom det eksisterer uregistrerte barn i søknadsgrunnlaget så skal vi automatisk legge til AVSLAG i listen av søknadsresultater. 
Eksempel case:
Man har 2 barn, 1 uregistrert og registrert. Begge er søkt barnetrygd om.
Hvis man får innvilget på det registrerte barnet så blir søknadsresultatet delvis innvilget.
Hvis ikke blir det avslått.
=> Legg til AVSLÅTT i listen av søknadsresultat dersom det finnes uregistrerte barn

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendringTest.kt
Endepunkt for å trigge satsendring basert på en liste med personidenter i input. Den henter alle fagsaker for en aktør, sjekker om siste iverksatte behandling har oppdatert sats. Hvis den ikke har oppdatert sats så opprettes det en ny entry i satskjøring-tabellen og en SatsendringTask, som utfører selve satsendringen
=> Endepunkt for å trigge satsendring for en liste med identer

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevOpphørSmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt, src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevOpphørSmåbarnstilleggServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTaskTest.kt
Vi ønsker å kjøre autovedtak-taskene for småbarnstillegg og 6/18 år, men de stopper opp fordi det ikke er kjørt satsendring.
Lagt til samme logikk som for fødselshendelse. Altså at man sjekker om fagsaken har seneste sats. Hvis den har seneste sats, så trigges det en satsendring før tasken prøver igjen om en liten stund
=> Legger til sjekk om det er kjørt satsendring før autovedtak for småbarnstillegg og 6/18 år

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevOpphørSmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt
Funksjon returnerer ikke om den har opprettet satsendring, sikrer at hver metode har Transaction med Propagation_required_new.
Utvid rekjørintervall ved satsendring for autobrev til 1 time, siden mange tasker stoppet opp på venter på iverksett behandling
=> Funksjon returnerer ikke om den har opprettet satsendring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceEnhetstest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-11361)
Endrer valideringen for helmanuell migrering i stegService.håndterNyBehandling slik at den godtar ny migrering på fagsak med vedtak fra før, så lenge siste vedtatte behandling var en teknisk endring med opphør.
=> Endrer valideringen for helmanuell migrering i stegService

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatEndringUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatEndringUtilsTest.kt
Ønsker ikke å sette resultat ENDRING hvis eneste endring er å sette opphørsdato på vilkår. Grunnen til at det har skjedd nå er fordi man sammenligner fom og tom på vilkåret i forrige behandling og nåværende behandling. Løsningen er å kun sammenligne tom hvis den ikke fører til opphør.
Eksempel:
- Behandling 1: vilkår oppfylt fra 01.01.22-null ("uendelig")
- Behandling 2: vilkår oppfylt fra 01.01.22-15.10.22
Opphørsdato er da november 22 (fordi andelene strekker seg til og med oktober, som gjør at opphøret starter i november).
Når opphørsdato er november så er tom-dato satt i oktober en gang på vilkårene. 
Derfor sammenligner vi kun tom-dato hvis den er FØR oktober.
Ikke sikkert dette er beste løsningen, men syns det gir mening. Og det bevarer funksjonaliteten med at splitter ellers fører …
=> Behandlingsresultat: Ikke returnere ENDRING hvis eneste endring er å sette opphørsdato på vilkår

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendringTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-11385
Vi ønsker at saksbehandlerene skal kunne starte en satsendringsbehandling på en fagsak manuelt slik at de kan gjøre revurderinger på siste sats. 
=> Legger til mulighet for å trigge satsendringsbehandling manuelt fra endepunkt

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/AutovedtakFødselshendelseService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt
I forbindelse med en feil med fødselshendelser på saker hvor det ikke var kjørt satsendring på, så ble det gjort slik at alle tasker feilet hvis det manglet henleggbegrunnelser. Reverterer denne feilhåndteringen og utvider rekjør senere tidspunktet til 60min ved evt satsendring
=> Fjerner midlertidig feiling av fødselshendelsetask ved manglende satsendring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt
Hopper over IVERKSET_MOT_OPPDRAG for satsendringer ved FORTSATT_INNVILGET på EØS. Dette for å støtte satsendringtasker med 0 utbetaling, som blir FORTSATT_INNVILGET
=> Satsendring tillater FORTSATT_INNVILGET for EØS-behandlinger

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10856
Vi har en behandling som ikke blir simulert siden den har resultat innvilget og opphørt og treffer koden som ble laget her:
https://github.com/navikt/familie-ba-sak/pull/2234
Tekst fra https://github.com/navikt/familie-ba-sak/pull/2234
> Hvis alle innvilgede perioder i en søknad er endret til å ikke utbetale for noen periode så skal ikke simulering kjøre. Steget Iverksett mot økonomi skal bypasses til journalfør vedtaksbrevet.
Endrer koden fra https://github.com/navikt/familie-ba-sak/pull/2234 til å trigges dersom alle utbetalinger er endret til 0 kroner, enten gjennom endret utbetaling, eller på grunn av differanseberegning. Dette gjelder kun om vi ikke har noen forrige behandling, …
=> Endrer navn på innvilgetSøknadUtenUtbetalingsperioderGrunnetEndringsPerioder og all logikken i funksjonen

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentService.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10089
Bug per i dag:
Setter man antall uker svarfrist til 10 i frontend, så forlenges fristen bare med 10 dager.
Dette er fordi at vi ikke ganger tallet med 7 før vi setter det videre i backend.
=> Tea-10089: Antall uker må ganges med 7 før vi forlenger fristen

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/UtgåendeJournalføringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/mottaker/BrevmottakerService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/JournalførVedtaksbrev.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/domene/JournalførVedtaksbrevDTO.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceEnhetstest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/mottaker/BrevmottakerServiceTest.kt
Nå er det mulig for SB å legge til manuell brev mottakere på barnetrygd. Derfor trenges det å gjøre endringer på journalføring og distribuering av brev ved manuelt utsendelse slik at brev kan også sendes til manuell mottakere. PR-en inneholder endringer som støtter dette.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10504
=> Støtte for å sende manuelt brev til manuell mottakere

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentDistribueringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/DistribuerVedtaksbrev.kt, src/main/kotlin/no/nav/familie/ba/sak/task/DistribuerDokumentPåFagsakTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/DistribuerDokumentTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/DistribuerVedtaksbrevTilInstitusjonVergeEllerManuellBrevMottakerTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentDistribueringServiceEnhetstest.kt
Når vi distribuerer et dokument fra en behandling og brukeren er død uten dødsboadresse, skal vi fullføre behandlingen som vanlig med en logg om at vi ikke fikk distribuert dokumentet. I tillegg skal vi prøve å sende dokumentet fra fagsaknivå en gang i uken. Dersom brukeren ikke har fått dødsboadresse etter 6 måneder gir vi opp. 
Vi hadde en feil der tasken som sender dokumentet fra fagsaken opprettet seg selv.
Splitter opp logikken for å distribuere dokument slik at enklere kan skille mellom det som skal skje fra fagsak-nivå og det som skal skje fra behandling-nivå
=> Splitt ut koden for å distribuere brev slik at vi er sikker på at logikken som kun skal skje på behandlingsnivå kun brukes fra behandling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendringTest.kt
Tar vare på ignorerte satsendringer i minne, slik at man slipper å sjekke de flere enn en gang på podden. Denne vil bli bygget opp hver gang en ny pod blir leader, men det er greit.
Vinduet for når man kjører satsendring har blitt utvidet
=> Skipp sjekk av fagsak hvis den alt er ignorert

src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceIntegrasjonTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/MigrerFraInfotrygdTest.kt
Migrering fungerer ikke etter satsendring fra kjøredató i februar, og det er i dag. Så disabler de til oppgaven om migrering og satsendring er ferdig utviklet
=> Disabler migreringstester som feiler pga satsendring

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestBrevmottaker.kt
I dag feiler brev distribuering på dokdist hvis postnummer har en mellomrom på slutten. Fjerner det ved lagring av brevmottaker.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10504
=> fjernet mellomrom i poststed og postnummer som forårsaket feilen i brev distribuering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/HenleggBehandling.kt, src/main/kotlin/no/nav/familie/ba/sak/task/HenleggBehandlingTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/HenleggBehandlingTaskTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt
[Favro:](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10784)
Legger til et endepunkt det kan sendes en liste med behandlinger til, basert på tidligere uttrekk, som oppretter en HenleggBehandlingTask med årsak TEKNISK_VEDLIKEHOLD og begrunnelse "Satsendring" for hver behandling i listen.
Tasken validerer at behandlingen som skal henlegges fortsatt er åpen og har frist etter 1. april 2023. 
La i tillegg til en sjekk i HenleggBehandling-steget som dropper å ferdigstille behandleSak-oppgaven dersom årsak og begrunnelse matcher kombinasjonen over.
=> Håndtere åpne behandlinger som skal ha satsendring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeUtilTest.kt
Favro: [Tea-11365](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-11365)
Vi får `flettefeltet barnasFodselsdatoer mangler for begrunnelse`-feil i tilfeller der EØS-søknad kun inneholder uregistrerte barn og man setter en avslagsbegrunnelse på søkers vilkår. Sender derfor med fødselsdatoer også for manuelt registrerte barn, på samme måte som vi gjør for nasjonale begrunnelser (se [koden her](https://github.com/navikt/familie-ba-sak/blob/master/src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevBegrunnelseGrunnlagMedPersoner.kt#L49))
_Er det noe du er usikker på …
=> Ta med uregistrerte barn i EØS-begrunnelsesdata for avslag

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingStegTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/RevurderingMedEndredeUtbetalingandelerTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-11444
Etter Jobi sine endringer som ikke lagrer ned koblingen mellom andeler og endringer i databasen så har vi fått en feil på revurderinger hvor vi har kopiert med oss endret utbetaling andelene fra forrige behandling uten å oppdatere andelene med disse endringene.
- Etter vilkårsvurderingen genereres andeler tilkjent ytelse. Her ønsker vi kun å ta med endringsandeler som er validert riktig (endret utbetaling andel har gyldig årsak og overlapper med andel tilkjent ytelse). Problemet er den siste biten der, første gang vi skal oppdatere beregning så finnes det ingen tilkjent ytelse og dermed er ingen endringer gyldige heller. Altså blir ikke endringen tatt hensyn til og andelen blir generert …
=> Bug: endret andeler oppdaterer ikke aty ved kopiering fra forrige behandling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValideringTest.kt
Vi har en validering som jeg trodde vi hadde fjernet for lenge siden. 
Det kan se ut som funkjsonen for valideringen ikke ble fjernet og at valideringen tatt med på nytt i denne PRen: https://github.com/navikt/familie-ba-sak/commit/cfafdd1c188f4fd530bdd616de66a468a4190590
Fjerner den nå. Har testa det og alt ser riktig ut, men det er ikke helt lett å se konsekvensen av dette. Ser ut som valideringen kun har blitt kjørt når "toggleFrikobleAndelerOgEndringer" er på
=> Fjern validering på at delt bosted endringer ikke krysser utvidet ytelse

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceIntegrasjonTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/MigrerFraInfotrygdTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-11433
Maskinell migrering/migreringsknappen skal fungere etter satsendring. Man sammenligner summen i sak i ba med summen i infotrygd, mens summen i BA har ny sats, så har den ikke det i infotrygd. For å få lik sum, så oversetter man satsene i saken i ba til satser man har i infotrygd.
Har også enablet igjen alle de gamle testene som var avslått
=> Støtte for maskinell migrering selv om satsendring ikke er kjørt i infotrygd

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/domene/Satskjøring.kt, src/main/resources/db/migration/V238__satskjoering_feiltype.sql, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendringTest.kt
Vi la til logikk i scheduleren for å filtrere bort de med utbetalinger på barn på flere fagsaker. Dette gjorden at antall saker man klarte å gjøre  hver dag gikk ned til 24k. Flytter nå denne logikke til tasken, og oppdaterer oversikten om satskjøringen med feiltype for å kunne identifisere de.
=> Flytter logikken for å sjekke om det er dupliserte utbetalinger på barn til selve AutovedtakTjenesten.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/SatsendringTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendringTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/BehandlingSatsendringTest.kt
Dersom vi starter satsendringen manuelt fra saksoversikten og det løper mer enn 100% utbetaling på barnet får vi nå en feil i iverksett tasken, og saken må teknisk henlegges.
Endrer så saksbehandler får en feilmelding når de prøver å trykke på knappen i stedet
=> Stans manuell satsendring dersom det løper mer enn 100% utbetaling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringStatistikk.kt
Øker antall satsendringer
Statistikk for satsendring oppdateres ikke før det har gått minst en halv time etter deploy, og etter det så blir den ikke oppdatert før neste deploy. Legger til initial delay slik at den kjøres rett etter oppstart, og fjerner leader-sjekken, siden det er relativt billige spørringer, og utvider til timelige oppdateringer, siden den nå kjører på flere poder.
=> Endringer i hvordan man oppdaterer satsendring-statistikk, og økning i antall satsendringer

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSøknadUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatValideringUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSøknadUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatValideringUtilsTest.kt
Det skal alltid være lov til å sette eksplisitt avslag på søker, noe vi ikke støttet. Legger til at det skal være lov til å legge på eksplisitt avslag på søker, og at det skal føre til avslag på samme måte som eksplisitt avslag for person fremstilt krav for.
Nei
=> Behandlingsresultat: eksplisitt avslag på søker skal være lov uansett om det er utvidet eller ordinær

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeUtil.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-11384
Dersom det er ugyldige kompetanser i siste behandling slik som det er [i denne saken](https://barnetrygd.intern.nav.no/fagsak/1919322/2190804/tilkjent-ytelse) vil autovedtak feile. Fikser det ved å filtrere bort ugyldige kompetanser før vi genererer brev.
=> Fjern alle ugyldige kompetanseperioder for brev

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/Behandlingutils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/EndringstidspunktService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-11439
I dag beregner ba-sak endringstidspunkt basert på endringer mellom nåværende behandling og siste iverksatt behandling. Men det gir av og til feil endringstidspunkt fordi alle behandlinger som gjør endringer i utbetaling ikke er iverksatt, f.eks. migreringsbehandling med årsak ENDRE_MIGRERINGS_DATO som kan endre utbetalingsperiode uten å sende data til økonomi. 
For å fikse denne endrer jeg logikken slik at beregningen skjer basert på siste vedtatt behandling og nåværende behandling for å finne ut endringstidspunkt. …
=> fikset bug slik at endringstidspunkt er beregnet basert på siste vedtatt behandling istendenfor siste iverksatt behandling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt
Før har vi hatt:
- Fortsatt innvilget (klassisk, uten perioder): genererer én periode (utenfor funksjonen som er endret her)
- Fortsatt innvilget (med perioder): det er noe saksbehandler kan overstyre i løsningen, og da ønsker man å få med alle vedtaksperioder, selv om resultatet er fortsatt innvilget
Dette skal delvis erstattes av et nytt resultat: "endret og fortsatt innvilget"
Ønsket løsning:
- Fortsatt innvilget: genererer én periode
- Endret og fortsatt innvilget: genererer flere perioder
Dette gjør at saksbehandler ikke skal få mulighet til å justere på om de ønsker én eller flere perioder hvis behandlingsresultatet var "fortsatt innvilget".
- Hvis resultatet var "endret og fortsatt innvilget" så ble ingen vedtaksperioder generert
- Grunnen til det var at man prøvde å utlede …
=> Behandlingsresultat bug: ingen vedtaksperioder ble generert ved resultat "endret og fortsatt innvilget"

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatStegTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt
Vi ønsker bare å forholde oss til 1 feature toggle når det gjelder funksjonalitet for ny behandlingsresultat.
=> fjerner BRUK_ANDELER_FOR_IVERKSETTELSE_SJEKK toggle og bruker NY_MÅTE Å_BEREGNE_BEHANDLINGSRESULTAT istedenfor da disse skal ut i prod samtidig

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/Behandlingutils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt
Liten forbedring på denne: https://github.com/navikt/familie-ba-sak/pull/3366
Det er ikke kun vedtatte behandlinger som sendes inn (henlagte behandlinger kalles ikke vedtatt), så renamer parameter til alleBehandlingerPåFagsak. I tillegg legger jeg til en sjekk som sjekker at behandlingen som returneres faktisk er avsluttet. Alternativt kan jeg rename parameteret til alleAvsluttedeBehandlingerPåFagsak, men føler den løsningen jeg har kommet med her er hakket tryggere 🤷‍♂️
Kom gjerne med tilbakemeldinger på det jeg skrev rett over her.
Bare småendringer 😊
=> Chore: renaming i funksjon som henter siste vedtatte behandling

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/domene/Kompetanse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?onShow=mycards&card=Tea-11399
Det er ønskelig å kunne velge Utsendt arbeidstaker i nedtrekksmenyen for annen forelders aktivitet.
Ny verdi er lagt til i enumn AnnenForeldersAktivitet.
PS:
Testene feiler siden vi må bruke ny versjon av familie-eksterne-kontrakter der utsendt arbeidstaker er lagt til.
PR på det ligger her: https://github.com/navikt/familie-eksterne-kontrakter/pull/132
=> Legger til utsendt arbeidstaker i annen forelders aktivitet

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/AvstemmingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingHentOgPersisterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/KonsistensavstemmingTest.kt
Ved sending av oppdrag av Institusjon-saker så settes utbetalesTil til tss ident for Organisasjonen, men ved konsistensavstemming så ble fnr sendt som utbetalesTil.  Dette fordi oppdrag overskriver med siste aktive fødselsnummer ved konsistensavstemming. Slik at gamle oppdrag får riktig fnr
For å støtte at man ikke overskriver utbetalesTil til fødselsnummer for institusjonsaker, så har man lagt til et felt i kontrakten mot oppdrag hvor man spesifikt kan sette utbetalesTil på institusjons-sakene
https://github.com/navikt/familie-oppdrag/pull/537
=> Overstyrer utbetalesTil ved konsistensavstemming for å støtte institusjon

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendringTest.kt
Slacktråd: https://nav-it.slack.com/archives/GU4MVCGCD/p1677245395624259
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-11757
Vi har et case der tilkjent ytelse i en behandling ikke er lik beløpet vi har sendt til økonomi. Det er fordi vi aldri iverksetter mot økonomi ved endre migreringbehandlinger, men enkelte endre migreringbehandlinger har endret på tilkjent ytelse, blant annet ved satsendring og dødsfall. 
Får å unngå dette stopper vi saksbehandlerene fra å gjøre en “endre migreringsdato”-behandling dersom siste behandling ikke er oppdatert med siste sats.
Det skaper problemer i de sakene der det løper over 100% utbetaling fordi vi må endre migreringsdato for å løse dem, men vi får ikke endret migreringsdato fordi da må vi gjøre …
=> Gjør det mulig å kjøre satsendring selv om det løper over 100% utbetaling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatEndringUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/EndringstidspunktService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIVilkårsvurderingUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatEndringUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIVilkårsvurderingUtilTest.kt
Observasjon fra test:
- Forrige behandling: bosatt i riket oppfylt fra 1987 til uendelig
- Nåværende behandling: bosatt i riket oppfylt fra 1987 til november 2022, og fra november 2022 til uendelig
Forventer da å få endringstidspunkt = november (eller skal det være desember??). Men ender opp med å få 1987. Dette er fordi man sammenlignet både fom og tom for å reflektere splitter i vilkårsvurderingen.
Det skal bli samme resultat om vi i stedet sammenligner kun på stønadFom. 
=> Bug: utleder endring i vilkårsvurdering feil

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSøknadUtils.kt
Forbedrer feilmeldingen. Man kan havne i den tilstanden også hvis man ikke har krysset av for noen barn, så legger til det i feilmeldingen.
Kan også vurdere å sende inn listen med personer fremstilt krav for, og heller lage to forskjellige feilmeldinger avhengig av om listen med personer fremstilt krav for er tom. Hva tenker du/dere?
Kun feilmeldingstekst
=> Forbedre feilmelding ved ingen søknadsresultat ved utledning av behandlingsresultat

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt
Trigging av satskjøring manuelt må også opprette en rad i satskjøring. Denne ble fjernet i forrige endring i manuell satsendring
=> Må opprette satskjøring rad ved manuell start av satsendring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSøknadUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatValideringUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSøknadUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatValideringUtilsTest.kt
Har endret noen feilmeldinger i forbindelse med behandlingsresultat fra Feil til FunksjonellFeil. Disse feilene skyldes saksbehandler som har gjort feil, og vi trenger derfor ikke få logginnslag på sentry.
Nei
Finnes allerede tester
=> Chore: Kast funksjonell feil i stedet for feil, slik at vi slipper så mange feil i sentry

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt
Satsendring oppretter satskjøringrad hvis den ikke eksisterer, eller gjenbruker eksisterende satskjøring rad
Dette for å tillate rekjøring av satsendring for manuell rute selv om det alt eksisterer en rad
=> Satsendring oppretter satskjøringrad hvis den ikke eksisterer, eller gjenbruker eksisterendee

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevBegrunnelseGrunnlagMedPersoner.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/IVedtakBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-11745
Når et barn er lagt til med kun fødselsdato i registrer søknad steget, og det er sendt innhentingsbrev til bruker, går dette barnet direkte til avslag. 
I dag er det kun lagt til begrunnelsestekst for dette som er tilpasset behandlingstema nasjonal ordinær/utvidet.
Det er nå lagt til en egen tekst som er tilpasset EØS saker som brukes dersom kategori er EØS.
Se bilder:
Tekst som brukes ved nasjonale saker:
Tekst som brukes ved eøs saker:
=> Legger til valg av eøs avslags tekst for uregistrerte barn dersom kategori er EØS

src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkServiceTest.kt
Ignorerer tomme kompetanser ved sending av stønadsstatistikk, siden de får task til å feile og de ikke er relevant.
=> Ignorerer tomme kompetanser ved stønadsstatistikk

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/domene/OppgaveRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/VurderTilbakekrevingStegTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceIntegrasjonTest.kt
Tar en liste som input, kaller integrasjon sin ferdigstill endepunkt og rydder i DbOppgave. Tenkt brukt til å rydde opp i oppgaver som ble opprettet med en feil
Tenkt brukt for å rydde opp i oppgaver som ble opprettet av feilen i RestartAvSmåbarnstilleggService som opprettet 2382 oppgavers om ikke skulle vært opprettet
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-11891
=> Forvalterendepunkt for å ferdigstille en liste med oppgaver basert på oppgaveid/gsakId

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/InternKonsistendsavstemming/InternKonsistensavstemmingService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/InternKonsistendsavstemming/InternKonsistensavstemmingUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyController.kt, src/main/kotlin/no/nav/familie/ba/sak/task/InternKonsistensavstemmingTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettInternKonsistensavstemmingTaskerTask.kt
Som en del av denne favrooppgaven: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-11936
Taskene kjøres fortere i Ba-sak enn familie oppdrag klarer å ta imot requests, så venter litt mellom hver task slik at vi har litt mer slack. 
Det var også en feil i sammenligningen mellom oppdrag og tilkjent ytelse. I enkelte tilfeller er andelene delt opp i revurderingen uten at det fører til endring i beløp. Da er fom og tom ulik. Vi må derfor se om utbetalingen over tid er lik og ikke om fom + tom + utbetaling er lik.
=> Fiks sammenligning mellom oppdrag og tilkjent ytelse og delay taskene med 60 sekunder

.deploy/nais/app-prod.yaml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt
Hoveddelen av satsendring er ferdig, og man trenger ikke å kjøre like ofte og med like mye ressurser
- Kjør scheduler kun 2 ganger om dagen
- Reduser antall podder til før satsendring
=> Nedskalering etter satsendring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/metrikker/TeamStatistikkService.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-11477)
aty.stonad_tom lagres som YearMonth. I databasen oversettes dette til en timestamp på første dato i måneden. Om til og med måneden er mars 2023 lagres det som 2023-03-01 i databasen. 
Vi må derfor se på første dato i måneden når vi prøver å finne hvilke andeler som løper til en måned. 
Databasespørringen:
Dersom datoen er 2. mars vil vi ikke få med andelene som slutter i mars siden `2023-03-02>2023-03-01`. Det så derfor ut som vi utbetalte 0 krones i mars, siden alle andeler ble avsluttet den måneden på grunn av satsendring.
=> Fiks sammenligning av måned

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingServiceTest.kt
Lenke til Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-11855
Vil sende videre manuelle brevmottakere som er lagret i ba-sak til familie-tilbake når vi oppretter tilbakekrevinger. 
Hvorvidt testen heller skulle vært en på annen form og om det er nødvendig at den dekker alle casene. Gjorde et forsøk med Junit.parameterizedTest, men da får jeg trøbbel med at testene går i beina på hverandre (alle funker hver for seg, men ikke hvis de kjøres samtidig). 
=> sende med manuelleBrevmottakere ved tilbakekreving

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/metrikker/TeamStatistikkService.kt
ref https://github.com/navikt/familie-ba-sak/pull/3445
Må enten ha LocalDateTime eller legge til Cast i query.
Den feiler nå med
ERROR: operator does not exist: timestamp without time zone <= bytea
Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
=> Query i TeamStatistikk trenger LocalDateTime og ikke Yearmonth

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BegrunnelseMedTriggere.kt
Vi har en del feil som skyldes at saksbehandlerene har valgt en annen begrunnelse enn de burde. 
I en perfekt verden burde de ikke ha mulighet til å velge feil begrunnelse, men enn så lenge gi vi dem en feilmelding. 
Gjør slik at ikke vi får varsel dersom feil begrunnelse er valgt
=> Gjør om til funksjonell feil

pom.xml
Fikser en sikkerhetsoppdatering som er markert som kritisk
=> Bump spring-boot-starter-parent 2.7.6 -> 2.7.10

.deploy/nais/app-preprod.yaml, .deploy/nais/app-prod.yaml
Kall mot Unleash, PDL og andre applikasjoner utenfor dev-gcp feilet etter en justering av egress-policy i NAIS.
Har nå lagt til alle disse eksterne appene i `accessPolicy.outbound.external` i henholdsvis `app-preprod.yaml` og `app-prod.yaml`
Endringene er testet i pre-prod og applikasjonen kommuniserer nå med de eksterne tjenestene uten problem.
=> Lagt til alle eksterne tjenester utenfor dev-gcp i external hosts

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/domene/ØkonomiSimuleringPostering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringUtilTest.kt
Lagt inn støtte for manuelle posteringer på fagområdeKode MBA (Barnetrygd Manuelt)
NØS utfører nå manuelle korigeringer på fagområdekode MBA, vi må ha støtte for å ta med disse når vi beregner tidligere utbetalt beløp.
=> Lagt inn støtte for manuelle posteringer på fagområdeKode MBA

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/Vedtaksperiode.kt
Reverterer sletting av dekprekert enum, siden vi har mange av denne enumsverdien i databasen. Slik at  blant annet autobrev-tasker ender opp som manuell
=> Reverterer sletting av dekprikert enum, siden vi har mange av denne enumsverdien i databasen

.deploy/nais/app-preprod.yaml, .deploy/nais/app-prod.yaml
Setter rolling update strategi for å få deploy til å gå fortere.  Se [Nais doc](https://doc.nais.io/nais-application/application/#strategyrollingupdate) og [slacktråd](https://nav-it.slack.com/archives/C01DE3M9YBV/p1680273231054969) for mer info
Setter maxSurge til 100% og maxUnavailable til 99%.
Gitt 4 replicas, maxSurge: 100% og maxUnavailable: 99% så vil følgende skje ved utrulling av en ny deploy:
* Det spinnes opp 4 nye podder samtidig
* Det tas ned 3 gamle podder samtidig (i.e. Math.floor(0.99*10))
* Minst 1 pod vil være kjørende til enhver tid under utrullingen
=> Sett rollingUpdate strategi

src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt
Knyttet til feil på sentry. F.eks. denne: https://sentry.gc.nav.no/organizations/nav/issues/421297/?environment=prod&project=112&query=is%3Aunresolved&referrer=issue-stream
Det er saksbehandler som har puttet inn feil fom-dato på barnas vilkår. Burde være funksjonell feil og ikke feil. Skulle egentlig ha vært stoppet av validering frontend. Jeg har rettet opp valideringen frontend her: https://github.com/navikt/familie-ba-sak-frontend/pull/2635
Nei
bare endret feiltype
=> Kast funksjonell feil i stedet for feil når saksbehandler har puttet inn feil dato i vilkår

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/feilutbetaltValuta/FeilutbetaltValutaController.kt
Vi oppdaget under utvikling av #3553 at tilgangene som kreves for feilutbetalt valuta er feil. Nå krever vi VEILEDER for alle handlingene, men det bør være SAKSBEHANDLER for alle handlinger som legger til eller endrer data. Vi beholder VEILEDER for å kun lese ut data. 
Har tatt avsjekk med Eivind om dette.
=> Krev saksbehandlertilgang for å legge til eller endre feilutbetalt valuta

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/InternPeriodeOvergangsstønad.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForPerson.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForVedtaksperioder.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/VedtaksperiodeProdusent.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceEnhetstest.kt
Vi bruker overgangsstønadsperiodene slik som vi får dem fra EF. De har flere splitter enn det vi trenger, og vi har allerede funskjonalitet for å slå de sammen og splitte på diff fra forrige behandling. 
Deler opp koden for å slå sammen og splitte overgangsstønadsperiodene slik at vi kan gjenbruke den og bruker dette i ny vedtakspreiode løsning. 
=> Bruk InternPeriodeOvergangsstønad som er splittet opp og slått sammen slik som vi vil ha det

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeMedBegrunnelser.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/Utbetalingsperiode.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/domene/UtvidetVedtaksperiodeMedBegrunnelser.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/dataGenerator/behandling/KjørRevurdering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtvidetVedtaksperiodeMedBegrunnelserTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/RevurderingMedEndredeUtbetalingandelerTest.kt
Med den nye vedtaksperiodeløsningen slår vi sammen perioder med lik data. Det betyr at perioder med lik utbetaling kan bli slått sammen. Dette skaper trøbbel når vi senere skal se hvilken utbetalingsperiodedetalj som perioden hører til ettersom vi nå kan ha to andeler som hører til én periode. 
For å løse dette slår vi sammen like utbetalingsperiodedetaljer slik at det ikke kan være to utbetalingsperiodedetaljer for en vedtaksperiode. 
=> Slå sammen like utbetalingsdetaljer for ny vedtaksperiodeløsning

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggService.kt
Favro: NAV-11404 og NAV-12397
Historikkinnslagene må vise at beløpet gjelder "kr/mnd", tilsvarende skjemafeltene og andre steder vi omtaler beløpene.
For feilutbetalt valuta er dette en endring i en lansert feature, derfor legges det bak feature toggle. Den kommer til å bli aktivert sammen med flere endringer som kommer for feilutbetalt valuta i forbindelse med at beløpet skal gjelde per måned.
Refusjon EØS er ennå ikke lansert, men der er beløpet allerede omtalt som "kr/mnd" alle andre steder enn her. 
=> Spesifiser at beløp er månedlig for feilutbetalt valuta og refusjon EØS

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlIdentRestClient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlRestClient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/domene/PdlBaseResponse.kt
Favrokort: [NAV-12403](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12403) 
Dersom man henter ut noe fra pdl sendes det med en warning i extensions-objektet i responsen fordi behandlingsnummer ikke blir sendt med i header. Denne PR'en legger til denne headeren. Dette nummeret er knyttet opp mot [behandlingskatalogen](https://behandlingskatalog.nais.adeo.no/process/purpose/BARNETRYGD/9f5fa38c-c6d3-415f-967e-9f961ab8413d). Da får man også en warning dersom man mangler noen opplysningstyper i behandlingskatalogen. 
Det er også lagt til at vi logger dersom man får denne …
=> Legger ved behandlingsnummer i header til kall mot pdl

src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringUtilTest.kt
Sum av manuelle posteringer vises med motsatt fortegn av det som faktisk er postert manuelt. Når det posteres et negativt beløp (KREDIT) viser vi det som et postitivt beløp og når det posteres et positivt beløp (DEBIT) viser vi det som et negativt beløp. Denne PR'en sørger for at fortegnet vi viser for manuelle posteringer stemmer overens med de faktiske posteringene.
Jeg har ikke skrevet tester fordi: Har ikke endret logikk ut over endring av fortegn på manuelle posteringer. Eksisterende tester er fortsatt dekkende. Forventet beløp på manuelle posteringer i testene er justert ved å endre fortegn.
=> Riktig fortegn på sum av manuelle posteringer

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt
Skrivefeil i dato for migreringer med potensiell feil. Mars ble til januar.
=> Endrer migreringsdato med potensiell feil til mars

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt, src/main/resources/db/migration/V241__oppdater_behandlinger_satt_på_vent.sql, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentServiceTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12540
For å enklere kunne validere en behandling, så gjøres dette. I stegService trenger man ikke et kall til på-vent-service men kan sjekke behandlingen direkte. 
En behandling kan kun settes på vent hvis den har status `UTREDES`
En behandling kan kun tas av vent hvis den har status `SATT_PÅ_VENT`, for å unngå at man prøver å gjennoppta en behandling som senere kan ha status `SATT_PÅ_MASKINELL_VENT` som settes når man sniker i køen.
=> Sett på vent skal oppdatere behandlingsstatus for å enklere kunne validere behandlingsstate

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingForskyvningUtils.kt
Her har saksbehandler mest sannsynlig gjort feil og ønsker å avslå fra barnet blir 18 og ikke på generelt grunnlag. Nå får saksbehandleren kun en diffus feilmelding "Noe har gått galt". 
Endrer så hen får "Finner ikke fra og med dato på 'under 18 år'-vilkåret. Det gjør også så utviklerene ikke får varsel
=> Kast funksjonell feil om saksbehandler ikke har satt fra og med dato for under 18 vilkåret

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSteg.kt
Vi får NoSuchElementException i valideringen til endre migreringsdato-behandlinger der det ikke er noen andeler i forrige behandling. 
Legger til nullhåndtering
=> Legg til nullhåndtering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt
Favro: [NAV-12692](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12692)
Vi sjekket tidligere både om forrige behandling var en "Teknisk endring"-behandling og at resultatet var et opphør for å avgjøre om saksbehandler skal få opprette en "Manuell migrering". Nå sjekker vi kun om den forrige behandlingen var et opphør. Dette vil redusere behovet for at våre fagressurser må inn for å fikse opp ting saksbehandlerne selv skal kunne gjøre.
=> Kan opprette manuell migrering dersom forrige behandling var et opphør

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForGjeldendeOgForrigeBehandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/VedtaksperiodeProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/vedtaksperiode_sammenlign_mot_forrige_behandling.feature
I gammel løsning har vi en egen vedtakstype som gir opphav til noen egne begrunnelser. I mellomfasen med ny vedtaksperioede-løsning og gammel begrunnelseløsning må vi fremdeles ha disse, men tanken er dette skal løses når vi genererer begrunnelsene senere
Gjør så vedtakstypen blir UTBETALING_MED_REDUKSJON_FRA_SIST_IVERKSATTE_BEHANDLING når vi har barn som mister en andel samtidig som vi har barn med utbetaling
=> Reduksjon der barn mister andel starten av periode

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt
Oppretting av endre migreringsdato med simulering stoppet opp med:
no.nav.familie.ba.sak.common.FunksjonellFeil: Simuleringen har ikke en feilutbetaling, men restTilbakekreving var ikke null
Som jo høres greit resultat ut. Var en av de tingene som var vanskelig å teste lokalt siden det der mockes alltid til å ha feilutbetaling. Så fjernet RestTilbakekreving
=> Ikke send med tilbakekreving for Simuleringen for nav-12506 fiks

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceIntegrationTest.kt
Favro: [NAV-12827](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12827)
Man får ikke henlagt en behandling som har kommet til `FERDIGSTILLE_BEHANDLING`-steget. Dette skyldes at `HENLEGG_BEHANDLING`-steget også kjører `FERDIGSTILLE_BEHANDLING`-steget og vi får kluss med rekkefølgen på stegene i `behandlingStegTilstand`. 
Før henleggelse ligger steget `FERDIGSTILLE_BEHANDLING` allerede i `behandlingStegTilstand` som `IKKE_UTFØRT`. Når vi så kjører henleggelse legger vi til steget `HENLEGG_BEHANDLING` i `behandlingStegTilstand`, og når vi deretter forsøker å kjøre `FERDIGSTILLE_BEHANDLING` legges ikke steget til i `behandlingStegTilstand` fordi det finnes fra før. For å finne ut nåværende steg brukes siste steg i `behandlingStegTilstand`, så når vi …
=> Fix: Får ikke henlagt behandling som har kommet til FERDIGSTILLE_BEHANDLING steg

src/main/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/PensjonService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/PensjonServiceIntegrationTest.kt
* finnAndelerTilkjentYtelseForAktør risikerer å hente veldig mange andeler og mye data generellt
Ønsker å fjerne Behandling fra TilkjentYtelse for å unngå å hente så mye når man i mange tilfeller kun skal hente TilkjentYtelse/AndelTilkjentYtelse
=> Forbedring: finner fagsaker som har andeler for aktør

src/main/kotlin/no/nav/familie/ba/sak/config/ApiExceptionHandler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/ArbeidsfordelingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt
Filtrerer vekk barn hvor id ikke lenger eksisterer ved revurdering, slik at man kan teknisk revurdere.
NAV-12734
Behandling har en ident som ikke lenger eksisterer. Ved revurdering kastets det PdlPersonKanIkkeBehandlesIFagsystem fordi foedsels objekt ikke eksisterer lenger på fnr, siden forrige behandling har dette fødselsnummeret
Dette vil kun funke for teknisk revurdering av en behandling slik at man kan få løst den saken i kortet, mens det er lagd en generell kort for å løse det generelle problemet.
=> Filtrerer vekk barn hvor id ikke lenger eksisterer ved revurdering, slik at man kan teknisk revurdere.

src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyService.kt
Når man trykker på "Fyll ut vilkårsvurdering"-knappen i preprod endrer vi nå alle som ikke er oppfylt og uten fom-dato. 
Gjør så vi kun endrer vilkårene som ikke er vurdert. I tillegg endrer jeg så vi setter begrunnelsesteksten til vilkårene.
=> Endre logikken på "Fyll ut vilkårsvurdering"-knappen i preprod

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/AutovedtakStegService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/AutovedtakFødselshendelseService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/småbarnstillegg/AutovedtakSmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettOppgaveTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/dto/OpprettOppgaveTaskDTO.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/AutobrevStegServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/BehandleSmåbarnstilleggTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FødselshendelseHenleggelseTest.kt
NAV-12761
Opprettet manuell oppgave for med en manuell oppgave type, som styrer om det skal sendes med behandlesAvApplikasjon. Brukes på de steder hvor det opprettes manuelle vurder livshendelse oppgaver.
Småbarnstillegg skal ha behandles av applikasjon
fødselsehendeler skal ikke ha behandles av applikasjon
dødsfall, sivilstand, utflytting behandles i baks-mottak og setter ikke behandlesAvApplikasjon
Lar åpne behandlinger fortsatt ha behandles av applikasjon, for der opprettes oppgaven på den åpne oppgaven, og bevarer dermed autolukking av disse
oppgaver som ikke er VurderLivshendelse skal oppføre seg som før.
_Jeg har ikke skrevet …
=> Opprett manuell oppgave for med en manuell oppgave type, som styrer om det skal sendes med behandlesAvApplikasjon.

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/internkonsistensavstemming/InternKonsistensavstemmingService.kt
Kast feil og ikke bare log dersom det er en feil i den interne konsistensavstemmingen slik at vi blir tvunget til å kjøre taskene som feiler på nytt
=> Kast feil dersom det er noe galt med den interne konsistensavstemmingen

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingValidering.kt
Validering av 18års-vilkåret feiler for alle behandlinger hvor barnets fødselsdato ikke stemmer overens med fom i vilkåret. Dette skaper issues for automatiske behandlinger. 
Løsning på dette er foreløpig å ikke feile på denne valideringen dersom behandlingsårsak er satsendring eller autobrev. Feilen logges med warn slik at vi kan lage en liste over fagsaker med denne feilen.
=> Logger ut mismatch mellom fødselsdato og fom i 18års-vilkåret for satsendring og autobrev

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendringTest.kt
Henter kun fagsakId fra spørring for å unngå at man henter hele fagsaken og allt koblet til den
Sjekker ikke om den er oppdatert med siste satsen, som gjøres i `AutovedtakSatsendringService::kjørBehandling` som då hver task kan være ansvarlig for
Plusser også på 200 på hver side for å prøve å hente alle behandlinger på første siden
=> Småforbedringer i satsendring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonopplysningGrunnlag.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/PersonopplysningGrunnlagForNyBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/VilkårsvurderingForNyBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/domene/PersonResultat.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/domene/Vilkårsvurdering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/PersonopplysningGrunnlagForNyBehandlingServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/VilkårsvurderingForNyBehandlingServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonopplysningGrunnlagForNyBehandlingServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingForNyBehandlingServiceTest.kt
Saker med VilkårResultater som har status `IKKE_OPPFYLT` kopieres over og skaper problemer i Behandlingsresultat. Vi kopierer også over personer som ikke har tilkjent ytelse i forrige behandling til ny behandling.
Nå sjekker vi personer fra forrige behandling og filtrerer ut barn som ikke har tilkjent ytelse i forrige behandling ved kopiering. Når vi senere kopierer over vilkår, kopierer vi kun over oppfylte vilkår for personer som finnes i Personopplysningsgrunnlaget.
=> Kopierer ikke over personopplysninger og personresultater for barn uten tilkjent ytelse fra forrige behandling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/VilkårsvurderingForNyBehandlingService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/VilkårsvurderingForNyBehandlingServiceTest.kt
Vi kopierer ikke over `EndretUtebetalingAndel` fra forrige vedtatte behandling når vi kjører satsendring. Dette fører til at fagsaker hvor den forrige vedtatte behandlingen har `EndretUtbetalingAndel` får feil behandlingsresultat/andelt-tilkjent-ytelse.
Sørger nå for at vi kopierer over disse!
=> Sørger for at vi kopierer over endrede utbetalingsandeler fra forrige vedtatte behandling

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt
Ca 1000 fagsaker har kjørt gjennom satsendring og ikke fått med seg endrede utbetalingsandeler fra forrige behandling. Dette endepunktet tar inn fagsaker med feil og forsøker å kopiere over de endrede utbetalingsandelene til siste behandling. Planen er å trigge en manuell satsendring på disse sakene til slutt for å få rettet opp i dem.
=> Laget forvalter-endepunkt for å kunne kjøre kopiering av endretUtbetalingAndel for fagsaker med feil

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt
Sletter et par tjenester man ikke trenger etter NAV-12506 fiksen. Gjør del 3 av den mer generell, slik at man kan manuelt trigge en satsendring uten validering. For å kunne rekjøre satsendringer som ble feil i juli satskjøring som Brage jobber med, som ikke har fått med endret_utbetal_andel.
=> Rydder i forvaltere controller, sletter et par metoder og gjør satskjøring endepunktet mer generell

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/AutovedtakFødselshendelseService.kt
Henla en fødselshendelsebehandling som var opprettet med feil data, og skulle rekjøre, men da ble den ignorert fordi det barnet fantes på en henlagt behandling
=> Fødselshendelser ignorerer barn hvis de finnes på en henlagt behandling.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/tidspunkt/TidspunktKonvertering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeMedBegrunnelser.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/EndringsTidspunktUtil.kt
`tilYearMonth` støtter ikke uendelighet, så vi vår feil ved avlag uten dato. 
Lager funksjon tilYearMonthEllerUendeligFortid og tar den i bruk
=> Fikser håndtering av uendelighet

src/main/kotlin/no/nav/familie/ba/sak/task/GrensesnittavstemMotOppdrag.kt, src/main/kotlin/no/nav/familie/ba/sak/task/TaskUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/GrensesnittavstemMotOppdragTest.kt
Det opprettes ikke tasker for å kjøre grensesnittavstemming på en fredag. Når torsdagens jobb er ferdig og ny task lages, så ble neste triggertid mandag.
=> Fikser bug om at grensesnitt avstemming ikke opprettet tasker til å kjøre på fredag

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BegrunnelseUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/UtgjørendeVilkårUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BegrunnelseMedTriggere.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/StandardbegrunnelseUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/UtgjørendePersonerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceUtilsTest.kt
Vi har et case der to personer har forskjellige avslagsbegrunnelser på samme vilkår på i samme periode. Det er derfor ikke nok å se hvem som har avslag på vilkåret i perioden for å se hvem vi skal ha med i begrunnelsen, vi må også dobbeltsjekke at den spesifikke begrunnelsen er den samme. 
Drar med begrunnelsen hele veien ned i funksjonskallene slik at vi kun tar med personene som har avslag på samme begrunnelse. 
=> Ta høyde for begrunnelsene som er satt i vilkåret når vi ser på personene vi skal ha med i begrunnelser for eksplisitte avslag

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/IverksettMotOppdrag.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/SendVedtakTilInfotrygdTaskTest.kt
Manuelle migreringer som tidligere har vært migrert, men flyttet tilbake til infotrygd, har ikke blitt sendt til feed.  Lagt til sjekk om at det er manuell migrering, og hvis det er det så sendes det til feed.
=> Sender vedtak til feed hvis sak har vært migrert, flyttet tilbake til Infotrygd og så migrert igjen

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/AutomatiskBeslutningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/SendTilBeslutter.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/AutomatiskBeslutningServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/LagreMigreringsdatoTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt
Favro: [NAV-13778](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-13778)
Etter at totrinnskontroll gikk fra å være manuell til å bli automatisk for "Endre migreringsdato"-behandlinger ble det fortsatt opprettet manuell "GodkjennVedtak"-oppgave. 
Denne PR'en sørger for at "GodkjennVedtak"-oppgave ikke opprettes for "Endre migreringsdato"-behandlinger. Har også flyttet kode som bestemmer om en behandling skal automatisk besluttes eller ikke inn i den nye servicen`AutomatiskBeslutningService` slik at vi slipper duplisert kode for dette som kan være vanskelig å huske på å oppdatere ved fremtidige endringer i logikk. Koden for dette ble ikke lagt i en allerede eksisterende service da jeg fikk en del problemer med sirkulære avhengigheter da jeg …
=> "Endre migreringsdato"-behandlinger skal ikke opprette GodkjenneVedtak-oppgaver

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt
Vi ser to feilede autovedtak av fødselshendelser den siste uka, der mor har en fagsak med status avsluttet. Allikevel blir behandlingen som opprettes av autovedtakprosessen en førstegangsbehandling. Det blir feil, korrekt behandlingstype vil være revurdering. 
=> Autovedtak fødselshendelse: behandlingstype kan ikke være førstegangsbehandling dersom fagsak har status avsluttet

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/ValiderBrevmottakerService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/mottaker/BrevmottakerService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/ValiderBrevmottakerServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/mottaker/BrevmottakerServiceTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-13868
Det er lagt til validering ved oppretting av manuell brevmottaker, på at det ikke er tillatt med manuelle brevmottakere dersom det fins fortrolige brukere i behandlingen (personer med adressebeskyttelse STRENGT_FORTROLIG / STRENGT_FORTROLIG_UTLAND). 
* Visning av feilmelding i frontend er allerede merget i familie-ba-sak-frontend PR https://github.com/navikt/familie-ba-sak-frontend/pull/2714
=> NAV-13868 - Validering ved oppretting av ny manuell brevmottaker

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/AutovedtakFødselshendelseService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/FødselshendelseServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatStegTest.kt
Fra vakt ser vi at enkelte fødselshendelser feiler:
- Mor har et barn fra tidligere, som ikke bor med mor. Siste behandling er et opphør og fagsaken er avsluttet
- Fødselshendelsen gir behandlingsresultat INNVILGET_OG_ENDRET, som ikke passerer sjekken i `skalRettFraBehandlingsresultatTilIverksetting`
- Vi får feilmelding `Steg 'Iverksett mot oppdrag' kan ikke settes på behandling i kombinasjon med status UTREDES`
Fjerner sjekken av behandlingsresultat for fødselshendelser i `skalRettFraBehandlingsresultatTilIverksetting`, da vi kontrollerer at resultat ble `INNVILGET` når vi går videre med behandlingen i `AutovedtakFødselshendelseService` (se [kode](https://github.com/navikt/familie-ba-sak/blob/master/src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/f%C3%B8dselshendelse/AutovedtakF% …
=> Autovedtak: gå rett fra behandlingsresultat til iverksetting for alle fødselshendelser

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForVedtaksperioder.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/VedtaksperiodeProdusent.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeMedBegrunnelserStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/domeneparser/VedtaksperiodeMedBegrunnelserParser.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/uregistrerte_barn.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-13886)
Dersom vi har et uregistrert barn skal vi få en avslagsperiode uten fom-
eller tomdato med begrunnelsen `AVSLAG_UREGISTRERT_BARN`
Endrer så avslagsperioden kommer med sammen med begrunnelsen
🕵️
deploy til miljø for å verifisere endringene.
=> Lag avslagsperiode ved uregistrerte barn

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringService.kt
Forvalterendepunkt som itererer gjennom alle løpende fagsaker og validerer om det er mer enn 100% utbetaling på barna. Dette logges til securelogs
Tjenesten er fire and forget. Man får umiddelbart tilbake en callId som man kan taile loggene med. 
Videre kjøres det async i chunker på 10000. Det vil logges slik til securelogs
=> Forvalter endepunkt over 100% utbetaling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/Fagsak.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/EndringsTidspunktUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForVedtaksperioder.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/VedtaksperiodeProdusent.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeMedBegrunnelserStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/domeneparser/DomeneparserUtil.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/enslig_mindreårig.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-14061)
Når fagsaktypen er barn enslig mindreårig fungerer barnet som både søker og barn. Dette skaper krøll for vedtaksprodusenten. Splitter opp vilkårene til barnet slik at vi vurderer barnet førs som søker og så som barn. 
=> Legg til støtte for enslig barn for vedtaksperioder

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatEndringUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/endringstidspunkt/EndringstidspunktService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIVilkårsvurderingUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingForskyvningUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatEndringUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIVilkårsvurderingUtilTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingForskyvningUtilsTest.kt
Ser at kode jeg trodde lå bak toggle og skulle bort brukes flere steder enn jeg antok. Vi må derfor sende fødselsdagen til personene ned til funksjonen. 
Endrer så vi sender med fødselsdagen til funksjonen som forskyver vilkårene slik at vi kan beskjære vilkårene etter 18-årsdagen basert på fødselsdagen og ikke vilkårene. 
=> Bruk fødselsdato for å finne endring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/FellesDelmaler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/ForsattInnvilget.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/Førstegangsvedtak.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/OpphørMedEndring.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/VedtakEndring.kt
Til nå har vi manglet støtte for å sende inn flettefeltene som blokker i delmalene i [familie-brev](https://github.com/navikt/familie-brev). Det betyr at det egentlig ikke skal gå å bruke flettefelter som lister i en delmal slik som vi gjør i Refusjon EØS-delmalen 👇. 
Av en eller annen magisk grunn kicker serializeren til hoveddokumentet inn i dette tilfellet og gjør at det er mulig likevel, men dette krever at vi sender med flettefeltene med hoveddokumentet og ikke delmalen. 
Dette støttes ikke av den nye versjonen til `@portabletext/react`. 
For å få det til å fungere må vi:
1. Sende med flettefeltene både global i hoveddokumentet og lokalt i delmalen (denne PRen)
1. Legge til støtte for å bruke flettetelt som blokk i lokalt i delmalen (https://github.com/navikt/familie-brev/pull/501) …
=> Send med flettefeltene til delmal med delmalen

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingServiceEnhetstest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/LagreMigreringsdatoTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/VedtakServiceTest.kt
Saksbehandler får ikke opprettet manuell migrering dersom det finnes en tidligere behandling og denne ikke har resultat `OPPHØRT`, `FORTSATT_OPPHØRT` eller `ENDRET_OG_OPPHØRT`. Det kan forekomme tilfeller av behandlinger som er opphørt men får ytterligere endringer i en behandling etter opphøret, med et resultat som ikke matcher et av opphør-resultatene. Dette til tross for at det ikke finnes noen løpende andeler i behandlingen.
Har derfor justert valideringen til å kun sjekke om andelene til siste vedtatte behandling er løpende: `tom` > dagens dato. Er den løpende kan man ikke opprette en manuell migreringsbehandling.
=> Justert validering ved opprettelse av manuell migrering behandling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIVilkårsvurderingUtil.kt
[Feilmelding i sentry](https://sentry.gc.nav.no/organizations/nav/issues/487793/events/9133addae4664f369e99f63299fbd8b8/?project=112&referrer=events-table%2F%3Fproject%3D112#exception)
Dersom vi har en person som var i forrige behandling, men som ikke er med i denne får vi nå en feil ved en `.single{}`. 
Endrer den til `.singleOrNull`
=> Støtt mulighet for at person ikke er med i behandling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/GrunnlagForPerson.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/VedtaksperiodeProdusent.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/domeneparser/VedtaksperiodeMedBegrunnelserParser.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/endret_utbetaling.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-13242)
Hvorfor:
Vi har enkelte scenarier som i dag blir rare. Dette gjelder f.eks saker der bruker kun oppfyller vilkårene tilbake i tid for en periode som var mer enn 3 år tilbake i tid. I dag får vi vedtaksbrevet "Du får barnetrygd", men ønsket er at vi her skal avslå ytelsen fordi de i realiteten ikke får barnetrygd. 
Hva: 
Endrer så perioder med endret utbetaling 0% med alle årsaker utenom "Delt bosted", skal gi vedtakperiode av typen "Ingen utbetaling"
=> Lag ikke-utbetalings-perioder når det andelene er endret til 0% og det ikke er delt bosted

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/VedtaksperiodeProdusent.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeMedBegrunnelserStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/endringstidspunkt.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/vedtaksperiode_endrede_utbetalinger.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/vedtaksperiode_sammenlign_mot_forrige_behandling.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/vedtaksperiode_sammenlign_mot_forrige_behandling_etterfølgende_ikke_oppfylt.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/vedtaksperiode_vilkår.feature
Nå som vi bruker samme data for å generere vedtaksperiode og endringstidspunkt kan vi ha det i samme utledning slik at vi enklere kan teste på det
=> Utled endringsperiode i vedtaksperiodeprodusenten

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelerTilkjentYtelseOgEndreteUtbetalingerService.kt
- Rydder vekk et par metoder i forvalter som man ikke lenger trenger.
- assert funker kun når man starter familie-ba-sak med -ea, så å ha dette i koden gjør ingenting uten denne kompiler-parameteren. Endrer til check, som funker uten kompilerparameter
=> Sletter ubrukt kode og bytter ut assert med check

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt
Favro: NAV-14060
Oppdaterer spørring så man kun henter ut behandlinger hvor beslutte vedtak-steget er **steget behandlingen er på (dvs. siste steg i behandling-steg-listen)** og dette steget ikke er utført. Vi hadde en bug hvor beslutte vedtak-steget kunne ligge i steg-listen som "ikke utført" hvis behandlingen hadde blitt henlagt når den sto på beslutte vedtak-steget, og da fanget denne spørringen opp det som en relevant behandling. Vi er kun på jakt etter behandlinger hvor dette er **siste/aktivt** steg.
Fjerner også logging som ikke er nødvendig lenger (det samme logges i funksjonen ett hakk ut).
Nei ikke egentlig.
Jeg har testet manuelt i konsollen med prodsaken, og da får vi opp forventet resultat med den …
=> Bug/Oppdater spørring for å hente behandlinger som ligger til godkjenning

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/Dødsfall.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/domeneparser/VedtaksperiodeMedBegrunnelserParser.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/brevbegrunnelse_vilkår.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/hendelser.feature
Favro: NAV-13721
Vi ønsker å filtrere begrunnelsene slik at satsendring-, dødsfall og seksårsbegrunnelsene kommer opp ved de hendelsene. 
Legger til filtreringsregler for satsendring, dødsfall og reduksjon 6 år.  
=> Legg til filter på hendelser for begrunnelser

src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/Periode.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/brevbegrunnelse_vilkår.feature
Personene sine begrunnelse-grunnlag er ikke nødvendigvis splittet opp samtidig som vedtaksperiodene. 
For eksempel er det i testen som blir lagt til i PRen kun én periode for søker siden søker ikke har noen endringer. 
Denne PRen sørger for å lage en splitt samtidig som vedtaksperioden slik at vi kan sammenligne hva vi hadde rettfør vedtaksperioden og det vi har i vedtaksperioden. 
=> Splitt opp begrunnelsegrunnlag på vedtaksperiode

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/SanityBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/SanityEØSBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/VedtaksperiodeGrunnlagForPerson.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/brevbegrunnelse_vilkår.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/hendelser.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/restSanityBegrunnelser.json, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/utdypende_vilkårsvurdering_utbetaling.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-13718)
Slik koden er nå skiller vi ikke mellom begrunnelsene som er knyttet til de forskjellige perioderesultatene innvilget, redukjson og ingen endring. 
Gjør så reduksjonsbegrunnelsene kun kommer om det er reduksjon, innvilgetbegrunnelsene kommer når det er økning og "ingen endring"-begrunnelsene kommer når det ikke er noen endring. 
=> Skiller på perioderesultatet er innvilget, redukjson og ingen endring i begrunnelse

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/SanityBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/SanityEØSBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/VilkårFilterUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/domeneparser/BrevBegrunnelseParser.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/kompetanser.feature
EØS-begrunnelser må filtreres på kompetanse.
Har nå lagt inn en ekstra metode for å filtrere på vilkår som tar med begrunnelser som ikke skal vurderes på vilkår. Denne brukes foreløpig kun for EØS-begrunnelser. Gjorde det slik siden EØS-begrunnelser sjeldent vurderes på vilkår.
=> Feat/filtrer begrunnelser på kompetanser

pom.xml
Reverts navikt/familie-ba-sak#3846
CodeQL Støtter ikke Kotlin 1.9.10 enda. Se https://github.com/navikt/familie-ba-sak/actions/runs/5962112501
=> Revert "Bump kotlin.version from 1.9.0 to 1.9.10"

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/TilkjentYtelseRepository.kt
Etter at vi rullet ut kode knyttet til sisteAndelPerKjede (https://github.com/navikt/familie-ba-sak/commit/3a1992a2ae788eb20ef2ed7cef1fd6ab2b6e0703) så ble også kode knyttet til opphør noe endret. Det vi ikke innså var at vi der var avhengig av en sortering av andelTilkjentYtelse på `stønadFom` for å fungere. Sorteringen ble fjernet og vi har kjørt ett døgn i prod med denne feilen. Feilen skal nå være rettet, men vil mest sannsynlig kreve litt opprydningsarbeid for å fikse saker som er iverksatt mot økonomi med feil opphørsdato.
Med denne PR'en ønsker jeg å få ut kode som kan hjelpe oss med å se hvor mange behandlinger som har blitt påvirket av feilen. Forsøker her å sammenligne opphørsdato vi har brukt i utbetalingsoppdraget mot det som burde ha blitt sendt. 
Jeg har ikke skrevet tester …
=> Identifisere behandlinger med feil opphørsdato i utbetalingsoppdrag

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt
Saker som har vært migrert kan mangle kompetanse fordi vi ikke har data om det fra Infotrygd. Når man da revurderer saken må vi legge til kompetansen. Dette fører til at systemet tror det er en endring og endringstidspunktet blir satt til starten av kompetansen. Dermed kommer det med flere vedtaksperioder enn det egentlig skal. 
Vi har en validering på at det kun er én periode som skal begrunnes for opphørsbrev. Siden det er mange vedtaksperioder som kommer med har saksbehandler mulighet til å begrunne flere. Dette gjelder for revurderinger som kommer etter migreringer og vil ikke skje når vi ikke har migreringssaker lenger. 
En workaround er at saksbehandlerene ikke begrunner periodene som ikke er opphørsperiodene. Legger ved en feilmelding som gjør det lettere for saksbehandlerene å …
=> Endre feil til funksjonell feil når SB har begrunnet flere perioder ved opphør

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/KontrollerNyUtbetalingsgeneratorService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/simulering/KontrollerNyUtbetalingsgeneratorServiceTest.kt
Sammenligning mellom gammel og ny utbetalingsgenerator feiler i de tilfellene vi ikke har noen utbetalingsperioder. Typisk EØS-saker med 0 kr i `kalkulertUtbetalingsbeløp`.
Feiler også med `nullPointerException` i saker hvor alt opphører og vi får et tomt resultat tilbake fra Oppdrag.
* Legger inn sjekk før simulering, som sørger for at vi kun kjører simulering dersom det finnes utbetalingsperioder i utbetalingsoppdraget.
* Legger inn sjekk etter simulering som validere at resultatet ikke er tomt før vi går videre til sammenligning.
=> Fix: ikke kjøre simulering uten utbetalingsperioder og ikke sammenligne dersom resultat er tomt for ny og gammel

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt
Filtrerer bort ytterligere behandlinger som ikke er påvirket av opphørsdatofeil. Behandlinger etter en ENDRET_MIGRERINGSDATO behandling bruker migreringsdato som opphørsdato.
=> Sjekker om endret migreringsdato skal brukes som opphørsdato

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt
Returnerer alle utbetalingsoppdrag som har feil opphørsdato i perioden med bug i prod. I tillegg returneres informasjon om hvilke utbetalingsperioder som har feil, og hvordan det oppdaterte utbetalingsoppdrag vil se ut etter korrigering.
=> Finner og returnerer utbetalingsoppdrag med feil opphørsdato, sammen med korrigert utbetalingsoppdrag

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/rolle.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/utdypende_vilkårsvurdering_utbetaling.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-14647)
Vi ønsker at begrunnelser knyttet til rolle kun skal dukke opp for den relevante rollen. 
Gjør så vi filtrerer bort begrunnelsen for personer som ikke er i rollelisten til behandlingen. NB: Tar alltid med begrunnelsen dersom den ikke er knyttet til noen rolle. Dersom rollelisten er tom blir begrunnelsen alltid tatt med i dette filteret. 
=> Filtrer begrunnelser på rolle

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/avslag.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-14518)
Dersom vi får en avslagsperiode uten datoer kan den strekke seg over flere splitter i personene sine data. Dette skapte litt krøll da får forskjellige perioder med data på person.
Lager en egen løype for avslagsperioder som kun tar med begrunnelsene fra vilkårsvurderingen. Legger også til begrunnelsene fra vilkårsvurderingen for de andre periodetypene
=> Legg til støtte for avslag

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt
Fikser bug som førte til at vi kun sendte perioden med endringen og ikke alle periodene i samme kjede som kom etter. Noe usikkert om det har noe å si eller ikke, men her er ihvertfall endringen som sørger for at vi sender alle perioder i den endrede kjeden.
=> Sørger for at vi sender alle kjedeelementer knyttet til kjeden med oppdatert opphørsdato

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestVedtak.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/UtvidetBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeMedBegrunnelserController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/AndelTilkjentYtelseOffsetTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/AutobrevSmåbarnstilleggOpphørTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/BehandleSmåbarnstilleggTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/Datagenerator.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FamilieBaSakKlient.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/JournalførOgBehandleFørstegangssøknadNasjonalTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/OpplysningspliktTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/ReduksjonFraForrigeIverksatteBehandlingTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/RestartAvSmåbarnstilleggTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/TriggingAvAutobrev6og18ÅrTest.kt
Hører til https://github.com/navikt/familie-ba-sak/pull/3869 og https://github.com/navikt/familie-ba-sak-frontend/pull/2751 og må bli merget etter dem.
[Denne behandlingen](https://barnetrygd.intern.nav.no/fagsak/1921845/3780399) stopper helt opp fordi vi ikke klarer å utlede vedtaksperiodene. Det er ikke mulig å se på noe annet data siden all data i behandlingen som sendes til frontend finnes på samme objekt som vi nå ikke klarer å lage. 
Gjør så vi splitter ut vedtaksperiodene fra `IBehandling` (`RestUtvidetBehandling` backend). 
* Første steg er å gi med vedtaksperiodene i både `RestUtvidetBehandling` og eget endtepunkt. https://github.com/navikt/familie-ba-sak/pull/3869
* Så må frontend gå over til å ta imot fra det nye endepunktet. …
=> Fjern vedtaksperioder fra RestUtvidetBehandling

src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyService.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/begrunnelser/LagGyldigeBegrunnelserTestUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/kompetanser.feature
I saken beskrevet [i dette favrokortet](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15079) viser vi kompetansebegrunnelser når alt som har skjedd er at det er en satsendring. 
Endrer så vi kun viser kompetansebegrunnelser dersom det er endring i kompetanse
=> Kun vis kompetansebegrunnelser dersom det er endring i kompetanse

src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/tidsrom/Tidsrom.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/TidslinjeTest.kt
Når vi skal kombinere to tidslinjer gjør vi lager i først en liste som inneholder alle tidspunktene i begge tidslinjene, før vi kjører kombineringsfunkjsonen på tidslinjene sine verdier i hvert av tidspunktene. 
Dersom en av periodene i tidslinjene er uendelig brukes fremdeles den endelige verdien. Dette skaper trøbbel når den endelige verdien kommer før andre tidspunkter i tidslinen fordi vi da ikke ser på periodene vi ville trodd at vi skulle se på. 
Endre så periodene vi henter ut til å kjøre kombineringsfunkjsonen på går fra det minste av fom og til til den første perioden og det største av fom og tom til den siste perioden. 
Det av vi må mappe over alle verdiene som finnes mellom det første og det seneste tidspunktet i tidslinjene er i seg selv litt iffy. I framtiden burde vi vurdere …
=> Fiks uendelighetfeil i tidslinjene

src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/begrunnelser/LagGyldigeBegrunnelserTestUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BegrunnelseGrunnlagForPersonIPeriode.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/endret_utbetaling.feature
Nå får vi mer enn én periode som kan knyttes til vedtasperioden siden vi ikke slår sammen periodene som ikke har utbetaling dersom det skyldes at det er en endret utbetaling. 
Endrer så vi slår sammen alle perioder som ikke har utbetaling (med unntak av delt-bosted periodene)
=> Fiks feil i begrunnelser når siste periode er endret til nullutbetaling
