navikt/familie-ba-sak

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt, src/test/resources/brevperiodeCaser/ENDRET_UTBETALING.json
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12311)
Fjerner begrunnelser som ikke skal brukes lenger.
Jeg har kjørt
```
select *
from vedtaksbegrunnelse vb
join vedtaksperiode vp on vb.fk_vedtaksperiode_id = vp.id
join vedtak v on vp.fk_vedtak_id = v.id
join behandling b on v.fk_behandling_id = b.id
where b.status != 'AVSLUTTET'
and vb.vedtak_begrunnelse_spesifikasjon = 'ENDRET_UTBETALING_DELT_BOSTED_INGEN_UTBETALING';
```
For hver av begrunnelsene og det er ingen slike rader i databasen. begrunnelsene er altså ikke i bruk.
=> Fjern ubrukte begrunnelser

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt, src/test/resources/brevperiodeCaser/ENDRET_UTBETALING.json
This reverts commit 2e51aa257a5714ca54c306de80ca0fc72e94da01.
Kontekst: 
https://nav-it.slack.com/archives/C036C6VAWH3/p1693866881601519
=> Revert "Fjern ubrukte begrunnelser (#3910)"

src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/AutovedtakStegService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/AutovedtakFødselshendelseService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevOpphørSmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutovedtakBrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/småbarnstillegg/AutovedtakSmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/VedtakOmOvergangsstønadTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/AutobrevStegServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/FødselshendelseServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/BehandleSmåbarnstilleggTest.kt
For de automatiske behandlingene har vi `AutovedtakStegService` som har en felles funksjon `kjørBehandling` som gjør logging og annet diverse i tillegg til å kjøre gjennom de respektive behandlingene. Den har til nå hatt behandlingsdata som en generisk parameter, noe som er helt unødvendig ettersom vi vet typen på behandlingsdataene ved kompileringstid. 
Endrer så vi bruker et sealed interface i stedet for en generisk variabel. 
Ingen ny funksjonalitet
=> Endre generic til sealed interface

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringService.kt
Satssjekken bør alltid bruke sisteVedtatteBehandling for å sjekke om saken har siste sats. Dette for å få korrekt satssjekk der hvor behandling har en iverksatt med gammel sats, men har vedtatte etterpå som ikke gjør en iverksett mot oppdrag. Samme gjelder også ved satskjøring. Den burde bruke vedtatte, siden den er mest rett.
=> Tar i bruk sisteVedtatteBehandlig for å sjekke og utføre satsendring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/KontrollerNyUtbetalingsgeneratorService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/simulering/KontrollerNyUtbetalingsgeneratorServiceTest.kt
Det hender at det kastes en feil i metoden `kontrollerNyUtbetalingsgenerator` som hindrer saksbehandling. Wrapper derfor hele metoden i en try-catch slik at vi fanger opp feilen.
=> Wrappet kontrollerNyUtbetalingsgenerator i try-catch

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringTest.kt
Favro: [NAV-14467](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-14467)
Koden som validerer at en aktør ikke får utbetalinger som overstiger 100% feilet dersom en aktør hadde andeler i flere enn 2 fagsaker. Vi fikk en tidslinje-feil om etterfølgende overlappende perioder.
Har nå justert koden slik at den vil fungere uavhengig av hvor mange fagsaker en aktør har andeler i.
=> NAV-14467: Sammenligning av andeler fra fler enn 2 fagsaker skal være mulig

src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/begrunnelser/LagGyldigeBegrunnelserTestUtil.kt
Legger til \<pre>-tag rundt testene som vi genererer fra endepunkt slik at nettleseren skjønner at den ikke skal formatere teksten.
=> Legg til pre så vi kan lese testen rett ut fra nettleseren

src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/KontrollerNyUtbetalingsgeneratorService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/simulering/KontrollerNyUtbetalingsgeneratorServiceTest.kt
Det er viktig at andelene som returneres av ny utbetalingsgenerator inneholder alle andeler med `kalkulertUtbetalingsbeløp > 0`, slik at vi får oppdatert alle relevante andeler med korrekt `periodeId` og `forrigePeriodeId`.
Legger her inn validering av andelene i `KontrollerNyUtbetalingsgeneratorService`
=> Lagt til validering av andeler returnert fra ny generator

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeMedBegrunnelserController.kt
Favrokort: 
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543
Vi har en bug der vi ikke oppdaterer state korrekt etter at vi splittet ut vedtaksperioder fra behandling responsen.
Endrer til at i returnerer bare det relevante ved oppdatering av fritekst og oppdater state i henhold til dette i frontend.
Frontend PR: https://github.com/navikt/familie-ba-sak-frontend/pull/2769
=> Gå bort fra å returnere hele behandlingen ved oppdatering av fritekster

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentServiceTest.kt
Omskrivning av merge av identer, siden antakelsen gjort ikke ser ut til å stemme.
En merget ident vil ha både gammel og ny aktørId og fnr som en del av alle historiske identer. En av aktørene blir aktiv, og den andre blir ikke det.
Relevant PR i baks-mottak for å hindre duplikate meldinger https://github.com/navikt/familie-baks-mottak/pull/934
=> Omskrivning av merge av identer, siden antakelsen gjort ikke ser ut til å stemme.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Etter prat med Eivind så sletter vi denne ubrukte begrunnelsen
=> Slett ubrukt endret utbetaling begrunnelse

.deploy/nais/app-preprod.yaml
Fjerner deprecated ingress som nå førte til feil ved deploy:
Nei
=> Fjern deprecated ingress som ikke lenger er støttet

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/AutovedtakStegService.kt
Fikser at behandleFødselsehendelseTask feiler med UnexpectedRollbackException ved FunksjonellFeil
Når det kastes en FunksjonellFeil i kjørBehandling for AutovedtakBehandlingService, så vil behandlingen bli markert som rollback av transaksjonsmangeren, men siden vi catcher FunksjonellFeil i tasken for å opprette oppgave i stedet for å feile tasken, så vil det bli en conflikt når transaksjonsmanageren prøver å commite riktig status på tasken
Dette kan løses ved å kjøre  kjørBehandlingFødselshendelse i egen tråd. Da vil behandlingen rulles tilbake, men og tasken kan kjøres FERDIG.
Man kunne ha automatisk henlagt denne behandlingen i stedet, som man gjør når det slår ut ved filtreringsregler, men den behandlingen vil mest sannsynlig ikke være til hjel for saksbehandler. Så synes det er greit …
=> Fikser at behandleFødselsehendelseTask feiler med UnexpectedRollbackException

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/SanityBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/SanityEØSBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/produsent/VedtaksperiodeGrunnlagForPerson.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/domeneparser/BrevBegrunnelseParser.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/kompetanser.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/tema.feature
Favrokort: [NAV-13724](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-13724)
Vi ønsker å kunne filtrere bort EØS begrunnelser for en periode (per person) dersom perioden er vurdert etter nasjonale regler, og vi ønsker å kunne filtrere bort nasjonale begrunnelser dersom en periode er vurdert etter EØS regler.
Dette er satt på feltet tema i sanity.
Dersom det er begrunnelser med tema felles som har blitt trigget i enten nasjonal eller eøs, så ønsker vi også å ta med disse.
Logikken er dersom som følges:
- Dersom man har en kompetanse i nåværende grunnlagperiode så sier man at perioden er vurdert etter eøs.
- Dersom man har hatt en kompetanse periode i forrige periode, men har mistet den, så må man se på nærmere på det:
- Hvis det fortsatt …
=> Filtrer begrunnelser basert på tema og regelverk periode er vurdert etter

.deploy/nais/app-preprod.yaml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingForskyvningUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdUtilTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-14453) 
Beregner prosenten utvidet andel søker skal ha ut i fra største prosent blant andelene til barna som har oppfylt "bor med søker", uten utdypende vilkårsvurdering som tilsier at de bor hos den andre forelderen.
=> Fix: Kombinasjon EØS og nasjonal sak med utvidet delt BA

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeMedBegrunnelser.kt
Denne oppgaven løser 2 favrokort:
Favrokort: 
- https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15512
- https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15077
Det er nå tillatt å begrunne opphørsperioder med endret utbetalingsbegrunnelser.
Eksisterende logikk som gjør dette bruker andelene for å gjøre det, men siden vi for opphørsperioder har tom som kan være uendelig, så fungerer ikke dette.
Jeg endrer det derfor til at for opphørsperioder, så er det bare relevant å se på fom i vedtaksperioden er lik fom i andel. 
Deretter vil overlapping av perioden + endretutbetaling og beløp bli gjort senere i løpet.
=> Vi ønsker å bare se på fom dato på andelene når vi henter relevante utbetalingsperioder relevant for opphørsperiode

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevPeriodeProdusent/BrevPeriodeProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/Vedtaksbrev.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/brevperioder/BrevPeriode.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15513
Vi oppretter 4 nye brevperiodetyper som erstatter de gamle.
Vi sender også mer data nå til familie-sanity-brev, slik at vi kan skille mellom institusjon og du istedenfor å ha egen brevperiodetype for hver av dem.
PR i familie-sanity-brev: https://github.com/navikt/familie-sanity-brev/pull/442
Nye brevperioder: https://familie-brev.sanity.studio/ba-brev/desk/periode;523a9377-af63-4192-892c-ea31706da7ee
=> Legg til logikk for nye brevperiode typer

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/AbstractMockkSpringRunner.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/config/UnleashServiceMockConfig.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningIntegrasjonTest.kt, src/test/resources/application-integrasjonstest.yaml
I alle tester vil nå `unleashService.isEnabled()` gi `false` og vi får ikke testet at koden som ligger bak togglene fungerer som tiltenkt. Med "gammel" Unleash `FeatureToggleService` ble alle toggler skrudd på i alle enhetstester og integrasjonstester også ble alle verdikjedetester kjørt med toggler både på og av.
Har her lagt til tilsvarende logikk for toggles i tester for `UnleashService` som for `FeatureToggleService`.
> Vil ikke kunne merge denne før eksisterende "UnleashNext"-toggles ikke feiler tester dersom de er skrudd på.
=> Legger til mock av UnleashService på samme måte som for FeatureToggleService

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/EndringsTidspunktUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/BehandlingsGrunnlagForVedtaksperioder.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/endringstidspunkt.feature
Fiks etter muntlig prat rundt [denne behandlingen](https://barnetrygd.intern.dev.nav.no/fagsak/200058751/100177351/vedtak). 
I behandlingen ovenfor ☝️ er det ingen endringer, men det er lagt inn et avslag på utvidet barnetrygd. Da ønsker vi ikke at alle perioder skal dukke opp. Det skjer nå siden avslagsvilkåret påvirker endringstidspunktet som settes til starten av avslagsvilkåret (tidenes morgen). 
Før:
Endrer så vi kun ser på vilkår som beholdes mellom behandlinger når vi utleder endringstidspunktet. 
Etter endring:
=> Kun se på vilkår som beholdes mellom behandlinger når vi utleder endringstidspunktet

pom.xml
Saksbehandler blir hindret pga en `UnexpectedRollbackException` som stammer fra en `NoSuchElementException` fra den nye utbetalingsoppdrag-generatoren ved sammenligning av gammel vs ny.
Har fikset feilen i `familie-utbetalingsoppdrag` så bumper derfor versjonen her.
Må fikse issue med at vi får `UnexpectedRollbackException`, men gjør det i en egen PR etter at denne er ute.
=> Bumper familie-utbetalingsgenerator for å fikse NoSuchElementException ved simulering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsvurderingTidslinjeService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsvurderingTidslinjeServiceTest.kt
Favro: [NAV-15579](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15579)
Periodene i tidslinja "AnnenForelderOmfattetAvNorskLovgivningTidslinje" blir 1 mnd for lange. `fom` blir satt korrekt til neste mnd, men `tom` blir også satt til neste mnd og det blir feil. 
Sørger her for at `fom` blir satt til neste mnd og `tom` til inneværende mnd.
=> Korrigerer periodene hvor vi innvilger selvstendig rett

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsvurderingTidslinjeService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsvurderingTidslinjeServiceTest.kt
Hadde en bug i koden hvor man fikk tidslinje-feil hvis vilkår kun var oppfylt innenfor en måned, feks 01.12-31.12. Dette gir ingen rett til utbetaling. Koden i prod nå forskjøv dette feil så man fikk fom=01.01 og tom=31.12. Retter opp dette i denne PRen ved å bruke metoden for forskyvning som også brukes ved generering av andeler.
Nei
=> Bug: praksisendring EØS

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/VedtakBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/innvilget_ved_ingen_endring.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15575
Ref favrokort:
```
Gitt at resultatet er "Ingen endring" 
Når det finnes person som er EØS
Så vis alle begrunnelser av typen Resultat: Innvilget eller økning og Tema: EØS
```
Merk at filtreringen på Tema og om det er EØS person skjer videre i løpet og allerede er på plass.
=> Legg til filtrering basert på perioderesultat for eøsbegrunnelser

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragGeneratorService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelseRepository.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragGeneratorServiceTest.kt
Etter gjennomgang av implementasjon mot `familie-utbetalingsgenerator` ble det foreslått noen små endringer av metodenavn og feltnavn.
Har bumpet versjonen til `familie-utbetalingsgenerator` for å få et mer presist feltnavn enn `opphørFra`. I ny versjon er `opphørFra` endret til `opphørAlleKjederFra`.
Jeg har ikke skrevet tester fordi:
Ikke gjort noen endringer som påvirker logikk
=> Bumpet familie-utbetalingsgenerator og justert noen metodenavn

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/VedtakBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/opphør_fra_forrige_behandling.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/reduksjon_fra_forrige_behandling.feature
Favro: NAV-15524
Vi får opp en begrunnelse som kun skal gjelde opphør fra forrige behandling, i en sak med normalt opphør.
Tidligere hadde vi filtrert vekk begrunnelsene for reduksjon/opphør fra forrige behandling, men det har forsvunnet i omskriving. Legger tilbake at vi filtrerer dem vekk og lager tester som bekrefter filteret
=> Unngå å se på begrunnelser for opphør/reduksjon fra forrige behandling i de andre triggerfiltrene

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/VilkårFilterUtil.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/utvidet.feature
Favro: NAV-15813
Vi har en begrunnelsestekst `innvilgetBorAleneMedBarn` som skal være tilgjengelig i den første innvilgede vedtaksperioden  etter at utvidet blir oppfylt. Utvidet kan være oppfylt flere måneder før behandlingen gir innvilgede perioder, så vilkåret vil ikke nødvendigvis bli oppdaget som utgjørende med den eksisterende logikken vi har.
Begrunnelsen skiller seg fra andre utvidet-begrunnelser ved at den ikke fletter inn måned og år for når utvidet ble oppfylt. Vi ønsker ikke at triggeret for denne begrunnelsen også skal trigge andre utvidet-begrunnelser.
Vi har kun én begrunnelse som skal opptre på denne måten. Vi har diskutert om vi bør skrive logikk som takler at flere tekster skal opptre likt, men prioriterer det ned nå. Hvis man allikevel i fremtiden vil gjøre det er mitt …
=> Begrunn første innvilgede periode etter at utvidet ble oppfylt

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/TilbakestillBehandlingService.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12477
Når vi har fått en behandlingsresultat, og gjør endringer i vilkårsvurderingen så resettes steget tilbake til vilkårsvurdering, og data som har blitt generert senere i løypa slettes (vedtaksperioder og tilbakekreving). Vi setter derimot ikke behandlingsresultatet tilbake til Ikke Vurdert, noe som forvirrer saksbehandler da det ikke er umiddelbart forståelig at man må videre til simuleringssteget igjen for å få oppdatert behandlingsresultatet.
Vi setter derfor resultatet til ikke vurdert når steget settes tilbake til vilkårsvurderingen.
=> Vi ønsker å sette behandlingsresultat tilbake til IKKE_VURDERT dersom det skjer endringer i vilkårsvurderingen

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/sanity/SanityService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/sanity/SanityServiceTest.kt
Bruker EØS-praksisendring toggle for å hindre at vi viser EØS-praksisendring begrunnelser før det er klart i prod.
=> Sørger for at vi ikke viser EØS praksisendring begrunnelser i prod

src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BrevperiodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/domeneparser/BrevPeriodeParser.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/innvilgete-vilkår.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/kompetanser.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/vilkår.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/brevPerioder/brevperiodetype.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/brevPerioder/vilkår.feature
Oppfølging av #4028 
Brevperioder og brevbegrunnelser har begrepsbruk som er nesten lik men har ulik betydning eller bruksområde.
For å unngå forvirring når vi skriver og leser tester bør vi adskille dem slik at hvert begrep kan bli korrekt for sitt bruksområde
- **Antall barn**: i brevperiodene ønsker vi kun å ta inn dataen for antall barn med utbetaling, men i brevbegrunnelsene trenger vi å vite antall barn begrunnelsen gjelder
- **Barnas fødselsdager/fødselsdatoer**: restobjektene vi sender til familie-brev er ulike for brevperioder og brevbegrunnelser, de bruker hver sin variant av denne verdien
=> Separer domenebegrepene for testing av brevperioder og brevbegrunnelser

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt
* Lagt til nytt endepunkt for å hente ut alle fagsaker som er migrert flere ganger og som løper i ba-sak.
* For å enklere kunne finne igjen saker i Infotrygd og Oppdrag legger vi til fnr i respons på endepunktene `/finnÅpneFagsakerMedFlereMigreringsbehandlingerOgLøpendeSakIInfotrygd` og `/finnÅpneFagsakerMedFlereMigreringsbehandlinger`
=> Lagt til nytt endepunkt i ForvalterController og lagt til fnr i respons

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/BehandlingsGrunnlagForVedtaksperioder.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/uregistrerte_barn.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-14370
Vi har en feil der vi ikke kan begrunne avslag på de ordinære vilkårene til søker dersom det bare eksisterer uregistrert barn.
Før:
Etter:
=> Vi ønsker å kunne begrunne avslagsperiode for søker selvom det bare finnes uregistrert barn og ingen andre på søknad

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/UtgjørendeVilkårUtils.kt
Får feil i finnForeliggende() hvis periodeFom == null
Setter til å returnere false siden det ikke skal finnes noen foreliggende periode hvis fom == null
=> håndter fom == null i finnForeliggende()

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/Utbetalingsperiode.kt
[Feil](https://sentry.gc.nav.no/organizations/nav/issues/513217/?environment=prod&query=is:unresolved)
`søkerOgBarn` inneholder ikke alle personene. 
Endrer til å se på `.personer`
=> Bruk `personer` og ikke `søkerOgBarn` når vi ser på andeler på personer

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevPeriodeProdusent/BrevPeriodeProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevPerioder/brevperiodetype.feature
Der vi ikke fletter inn barn med nullutbetaling EØS i periodeteksten. 
☝️ Her skulle vi fått "Du får 0 kroner for 1 barn født ..."
Fikser så vi ikke filtrerer ut barn med 0 kroner pga sekundærland
=> Ta med barn med nullutbetaling pga sekundærland i periodetekst

src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/begrunnelser/LagGyldigeBegrunnelserTestUtil.kt
Nå er det en manuell jobb å anonymisere aktørid, behandling og fagsak ved henting av begrunnelsestester. Vi ønsker å automatisere dette for å unngå å hente ned og lagre disse dataene i testene våre
<details>
<summary>Før</summary>
<pre>
Egenskap: Plassholdertekst for egenskap - xQWffRfg80
Bakgrunn:
Gitt følgende fagsaker for begrunnelse
| FagsakId | Fagsaktype |
| 999952   | NORMAL     |
Gitt følgende behandling
| BehandlingId | FagsakId | ForrigeBehandlingId | Behandlingsresultat  | Behandlingsårsak | Skal behandles automatisk |
| 999952       | 999952   |                     | INNVILGET_OG_OPPHØRT | SØKNAD           | Nei                       |
| 1000001      | 999952   | 999952              | ENDRET_UTBETALING    | NYE_OPPLYSNINGER | Nei                       |
Og følgende …
=> Anonymiser aktørid, behandling og fagsak ved henting av begrunnelsestester

src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt
Nå henter vi inn mock for begrunnelsestestene for hver test vi kjører. Det tar ~40ms for begge testene, så dette blir litt om vi nok tester. 
Endrer så vi kun henter dette én gang
=> Flytt henting av mockobjekter ut av testsyklus så vi bare gjør det én gang

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/VedtaksperiodeGrunnlagForPerson.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/opphør.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15352)
Når vi opphører på søker legger vi med alle barna som er på behandlingen i begrunnelsen. Det blir feil når vi har barn som er opphørt på et tidligere tidspunkt. 
Endrer så vi kun fletter inn barn som hadde andeler i forrige periode for begrunnelser som gjelder opphør for søker.
=> Kun flett inn barna som hadde andeler forrige periode når vi opphører på søker

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/task/FinnSakerMedFlereMigreringsbehandlingerTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/internal/ForvalterSchedulerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/FinnSakerMedFlereMigreringsbehandlingerTaskTest.kt
Månedlig uttrekk av saker som er migrert til BA-sak flere ganger
En schedulert jobb som kjører hver måned, som oppretter en task som leter etter løpende fagsaker med flere enn 1 migrering. Hvis den finner slike saker, så feiler tasken og må avvikhåndteres etter at listen er sendt til Anna.
NAV-16095
=> Månedlig uttrekk av saker som er migrert til BA-sak flere ganger

.github/workflows/build-and-deploy-prod.yml
Dersom vi starter to deploys til prod samtidig ønsker vi kun at det siste skal deployes. 
Endrer så vi stopper alle tidligere deploys dersom de ikke har kjørt ferdig når vi starter en ny deploy
=> Gjør så vi stopper tidligere prodbygg som kjører dersom vi starter flere deploys samtidig

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/VilkårFilterUtil.kt
Denne logikken ble lagt til i #4026 for å kunne begrunne utvidet i alle tilfeller der søker begynner å få utvidet-andeler, uavhengig av om det var utvidet-vilkåret som var utgjørende for at andelen begynte. 
I #4104 ble det lagt til et eget trigger som gjør denne begrunnelsen tilgjengelig i alle perioder der utvidet er innvilget. Dette gjør at vi ikke trenger logikken fra #4026 lengre.
Fjerner logikken men beholder testen som bekrefter ønsket oppførsel
=> Fjern spesiallogikk for å begrunne utvidet som nå dekkes av eget trigger

.github/workflows/build-and-deploy-prod.yml
Ref [slacktråd](https://nav-it.slack.com/archives/C01G9BA8JKZ/p1697809402319029)
Nå som vi kjører testene som det siste vi gjør før vi merger en PR til main er det unødvendig å kjøre testene på nytt i deploy-steget.
Fjerner testene fra deploysteget
Merk dette er et forslag. Det er lov å være uenig i at dette er ok.
=> Fjern tester i byggesteg når for bygg som trigges av at en PR committes

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Dersom man velger avslagBosattIRiket for søker vil man få en feil siden den begrunnelsen prøver å flette inn barn. Legger til en ny begrunnelse med en annen formulering for tilfellene der vi skal begrunne for søker. 
=> Legg til avslagIkkebosattINorgeSoker i Standardbegrunnelse.kt

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutovedtakBrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevOpphørSmåbarnstilleggServiceTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16314
Når vi kjører autobehandling ved 6 og 18 år sjekker vi om vi ikke allerede har begrunnet reduksjonen allerede. Måten vi gjør det på er at vi henter alle begrunnelsene i fagsaken og sjekker om én av dem er samme begrunnelse som vi ønsker å bruke og at den ble begrunnet denne måneden. Dersom vi har brukt en begrunnelse som vi har fjernet, vil dette feile. 
Endrer så vi kun henter begrunnelsene som strenger først og ignorerer dem dersom de ikke finnes i kodebasen lenger.
=> Gjør så vi ikke får feil når vi henter begrunnelser på vedtaksperioder begrunnet med utgåtte begrunnelser

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/FerdigstillBehandling.kt
En fortsettelse på oppdatering av løpende flagg for fagsaker, der hvor 0-utbetalinger ikke ble avsluttet. Der fjernet man sjekken om behandling skulle ha utbetalingsoppdrag, og populerte stønad_tom for disse behandlingene, slik at de skulle bli avsluttet riktig. 
Dette støttet ikke tilfeller med løpende fagsaker hvor siste vedtak var AVSLÅTT, men hvor de hadde iverksette behandlinger. De har heller ingen stønad_fom eller stønad_tom populert.
Ved å filterere bort AVSLÅTT bort disse behandlingene så vil man få plukket ut disse slik at de får oppdatert flagg.
Jeg har testet query. Den plukker opp 3 saker som ikke er avsluttet, men som skulle vært avsluttet
=> Ignorerer behandlinger med AVSLÅTT i query for å finne fagsaker som skal avsluttes

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/VedtaksperiodeProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/fortsatt_innvilget.feature
Favro: NAV-16239
Søker har fått innvilget barnetrygd ved automatisk behandling av fødselshendelse, men sender også søknad kort tid etterpå. Revurdering med årsak søknad gir endring i mors vilkår (tidligere FOM-datoer) men påvirker ikke utfallet av behandlingen. Behandlingsresultatet blir `ENDRET_OG_FORTSATT_INNVILGET` pga endring i vilkår. Dette skal vi kunne begrunne med tekstene for fortsatt innvilget.
Tidligere har vi kun opprettet vedtaksperiode for fortsatt innvilget dersom behandlingsresultatet ble `FORTSATT_INNVILGET`. Tipper at vi har glemt at vi har flere varianter av fortsatt innvilget? Hører gjerne motargumenter om dere vet om noen grunn til å forskjellsbehandle disse
=> Gi fortsatt innvilget-periode ved beh.res. endret og fortsatt innvilget

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ISanityBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/RestSanityBegrunnelse.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16222)
[Favro2](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16225)
Ønsker å rename en del av feltene i sanity. Legger derfor til navnet på de nye feltene slik at vi kan migrere til de, før vi sletter de gamle. 
Ønsker også å ta i bruk begrunnelseType så legger til navnet på det nye feltet i kontrakten (begrunnelseTypeForPerson)
Er navnene bra nok?
Tema -> Regelverk: Er litt i tvil siden Tema strengt talt inneholder "Felles" for øyeblikket
begrunnelseType -> begrunnelseTypeForPerson : litt langt navn, burde vi heller kalle det noe annet?
=> legg til begrunnelseType i kontrakt for SanityBegrunnelse og legg til støtte for felter med nytt navn

src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrereSøknad.kt
Det er ikke gitt at person har vilkår dersom person har blitt fjernet som person framstilt krav for.
Ideelt så burde også EndretUtbetalingAndel koblet til person også fjernes når personen ikke lenger er framstilt krav for, men tenker at dette er en fin første steg.
=> Kan ikke anta at det person har noe vilkårsvurdering (mtp at person kan bli fjernet som person framstilt krav for)

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/sanity/SanityQueries.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/SanityEØSBegrunnelse.kt
oppdatere RestSanityEØSBegrunnelse til å ta i bruk nye felter
Får feil fordi vi ikke får hentet ut begrunnelser som har eøs i regelverk etter at vi har slettet 'tema'-feltet fra sanity.
La også til bruk av nye felter i restSanityEØSBegrunnelser siden det også vil gi feil dersom de nye ikke blir tatt i bruk. 
=> endre SanityQueries.kt slik at vi bruker regelverk og ikke tema

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/opphør.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/opphør_samme_måned.feature
Favro: NAV-14024
Når vi opphører og begrunnelsen gjelder søker må vi ta stilling til **antall barn som også har opphør på samme vilkår** i perioden når vi skal bestemme om vi skal si "du"/"du og barnet"/"du og barna". I dag teller vi med alle barna som har andeler i forrige periode, men om det kun er søker som har opphørende vilkår blir det feil å begrunne med at "du og barna ikke lenger er bosatt i Norge".
Har prøvd å stykke det opp så det gir mening å lese commit for commit.
Fjerner også en funksjon som ikke var i bruk - den er en duplikat av en metode som ligger i `IVedtakBegrunnelse.kt`, og det er den andre metoden som kalles på.
=> Valgfelt du og barna: tell antall barn med opphør på samme vilkår som søker

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/avslag.feature
Favro: NAV-16813
Oppdaget i forbindelse med #4139 at vi for avslagsbegrunnelser alltid velger "du" i valgfeltet "du og eller barnet barna" dersom søker er blant personene begrunnelsen gjelder. Sjekket med Anna, og det er ikke korrekt 
=> Valgfelt du og barna: tell antall med avslag på samme vilkår som søker

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestFeilutbetaltValuta.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/sanity/SanityService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/KontrollerNyUtbetalingsgeneratorService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/feilutbetaltValuta/FeilutbetaltValutaService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/sanity/SanityServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringServiceEnhetTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringUtilTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/VurderTilbakekrevingStegTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceTest.kt
Fjerner toggler som har vært på lenge: 
EØS_PRAKSISENDRING_SEPTEMBER2023 har vært på siden 01.10.2023
FEILUTBETALT_VALUTA_PR_MND har vært på siden 22.06.2023
ER_MANUEL_POSTERING_TOGGLE_PÅ har vært på siden 05.06.2023:
EØS_INFORMASJON_OM_ÅRLIG_KONTROLL har vært på siden 13.01.2023:
=> Fjern toggler

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtakPeriodeValidering.kt
Vi hadde lenge et håp om å ha en strengere validering på begrunnelsene. Det har ikke blitt noe av, men vi logger der vi ville kasta feil for å se behovet. Der trenger vi ikke å logge warn. Det forvirrer lett den som har vakt. Endrer fra warning til info
=> Endrer logging fra warn til info, slik at vi ikke skal tro noe er galt

src/main/kotlin/no/nav/familie/ba/sak/config/ApiExceptionHandler.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyController.kt
- Exceptionhåndtering for NumberFormatException. Som skjer ofte når noen vil til fagsak/1000151/saksoversikt men skriver fagsak/1000151saksoversikt
- Ikke logge feil ved redirect av behandling når behandling ikke finnes
- Bedre feilmelding til frontend for datetimeparse exception
=> Reduser feillogging til sentry

src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/vedtaksperioder/LagVedtaksperiodeTestUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/tidsrom/Tidsrom.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/TidslinjeTest.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/kompetanser.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/brevPerioder/selvstendig_rett.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16908)
Vi har hatt feil som kun dukker opp i når testene kjøres i github actions. Grunnen til dette er todelt.
`YearMonth.now()` gir annet svar i GA.  I localhost får vi nov 2023, mens i github actions gir det nov 2022. Hvorfor dette skjer vet jeg ikke, men det burde egentlig ikke ha noe å si for testene. De burde fungere uavhengig av dagens dato, men på grunn av den andre feilen beskrevet under gjorde de ikke de. 
`Tidslinje.tidsrom()` ga feil ved uendelige datoer. Når vi har en periode med uendelig fom- eller tomdato setter vi likevel en skjult dato som ikke brude brukes som selve datoen til tidspunktet. Vanligvis settes dette bare til dagens dato/måned. 
Når vi skulle finne tidsrommet som …
=> Skru på test igjen

src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/begrunnelser/LagGyldigeBegrunnelserTestUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevEøsBegrunnelseProdusent.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BrevbegrunnelseUtil.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/begrunnelsetekster/kompetanser.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16824)
Når vi har flere kompetanser i samme tidsrom som gjelder for samme begrunnelse skal begrunnelsen deles opp etter kompetansene. Da skal dataene fra de respektive kompetansene komme med i begrunnelsene.
Vi har hatt et problem med at barna fra alle kompetansene kom med i alle begrunnelsene. For eksempel hadde vi et case der en begrunnelse som ble dekket av to kompetanser med ett barn hver ble begrunnelsen delt i to, men begge barna kom med i begge begrunnelsene, selv om bare ett barn skulle med. 
Fikser så kun barna fra den respektive kompetansen kommer med i begrunnelsene
=> Send med riktige barn når det er flere kompetanser som gjelder for en begrunnelse

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveController.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/domene/DataForManuellJournalføring.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16037
Det skal ikke være mulig at en journalføringsoppgave ikke har en journalpost knyttet til seg. I dag er det en mismatch fordi frontend forventer at journalpost alltid eksisterer på journalføringsoppgave, men backend håndterer at den er null. Sørger derfor for at det blir kastet en feil backend hvis det ikke er knyttet en journalpost til oppgaven.
Nei
Tenker det gir lite verdi her
=> Kast feil hvis journalføringsoppgave ikke har en journalpost knyttet til seg

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/VedtaksperiodeProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/automatisk_behandling.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-16984)
Når vi skal finne stopptidspunktet for vedtakseperioden til omregning  6- og 18år-behandlinger ser vi bruker vi neste endring i tilkjent ytelse. 
Vi har en bug der vi ikke tar høyde for nye andeler som starter, bare andeler som slutter. 
Endrer så vi også tar høyde for andelene som starter
=> Ta høyde for nye andeler når vi skal finne tom-dato for vedtaksperiode ved omregning

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatEndringUtils.kt
[Denne](https://familie-prosessering.intern.nav.no/service/familie-ba-sak/task/762132151) tasken på `sendAutobrevVed6og18År` feiler fordi det er en endring. Siden hele behandlingen rulles tilbake når det er en feil er det vanskelig å se hva som er endret. 
Legger til en debuglog ved endring
=> Logg endringer

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatEndringUtils.kt
Når vi har feil på personresultat og behandlingen som kaster feilen blir slettet er det vanskelig å vite nøyaktig hva som er endret. Logger derfor ut de endrede dataene i securelogger.
=> logg ut nye verdier når noe er endret slik at endringer er synlige selv om behandling er slettet

pom.xml
Dependabot greier ikke å oppdatere versjonen for denne ene pakken så oppdaterer den manuelt.
=> bumpet token-validation-spring-versjon

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringServiceTest.kt
Får mange av [denne](https://sentry.gc.nav.no/organizations/nav/issues/520499/?project=112) feilen i Sentry. Skyldes at saksbehandler kommer inn på behandlingsresultat-siden når det ikke finnes tilkjent ytelse - feks ved henlagt behandling. Sørger for at tilkjent ytelse kan være optional. Hvis det ikke finnes tilkjent ytelse så sender vi bare inn en tom liste med andeler.
Nei
Tenker det er unødvendig
=> Chore: optional andel tilkjent ytelse for å unngå mange logginnslag i sentry

src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/begrunnelser/LagGyldigeBegrunnelserTestUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/vedtaksperioder/LagVedtaksperiodeTestUtil.kt
Vurderes etter kommer ikke automatisk med når vi generer tester for begrunnelser og vedtaksperioder. Med endringene som kommer i https://github.com/navikt/familie-ba-sak/pull/4192 blir vi mer avhengige av å ha riktig regelverk for at testene ikke skal feile. Må derfor ta med vurderes etter i testgeneratoren
=> legg til vurderes etter i testendepunkter for begrunnelse- og vedtaksperiodetester

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevEøsBegrunnelseProdusent.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/gyldigeBegrunnelser/kompetanser.feature
Når man velger en standardbegrunnelse for vilkår som gjelder eøs, f.eks. avslagSelvstendigRettStandardAvslag vil ikke begrunnelsen dukke opp og føre til at man får feil flettefelt. Endrer slik at vi faktisk parser riktig felt. 
=> Bruk 'StandardBegrunnelser' når vi parser begrunnelser valg i vilkårsvurderingen slik at eøs-begrunnelser kommer med

src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevKlient.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeMedBegrunnelserController.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/BrevKlientMock.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevServiceTest.kt
Ønsker bedre logging slik at det er lettere å håndtere feil rundt brevbegrunnelser. 
Legger til autogenererte tester i loggene slik at vi kan se staten til behandlingen i det feilen inntreffer. 
Burde testene logges i securelogger? Dataene er obfuskerte, men datoene og antall barn vil fortsatt være til stede
=> Bedre logging brevbegrunnelsefeil

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17453
Delmalen om årlig kontroll dukker opp i flere saker enn den skal. Dette er fordi eksisterende kode ser på om behandlingstema er EØS og om det finnes noen løpende vedtaksperioder. Dette gjør at saker som har hatt EØS i fortiden, men nå er nasjonale, også får med seg delmalen, fordi man ikke sjekker om det er løpende EØS. Jeg mener at vi kan endre til å kun sjekke om det finnes kompetanser i fremtiden, fordi det finnes alltid kompetanser i perioder som er vurdert etter EØS. Og man ønsker delmalen i EØS-perioder uansett om de fører til utbetaling eller nullutbetaling.
Egentlig ikke
=> Bug: årlig kontroll delmal

src/main/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/PensjonService.kt
Filtrerer vekk periodene med småbarnstillegg og utvidet barnetrygd for å unngå problemene med IllegalArgumentException ved håndtering av overlapp, etter avklaring med Pensjon, da de uansett kun trenger å forholde seg til periodene med ordinær barnetrygd.
Fikser feilene som oppstod i preprod ved å bruke barnas identer til å maskere personidentene fra infotrygd-Q, istedenfor bare aktør.aktivtFødseslnummer på tvers av alle periodene tilhørerende ulike barn.
=> Pensjon: Fikser overlapp-exception som oppstod i preprod, og for ikke-ordinære perioder i prod

src/main/kotlin/no/nav/familie/ba/sak/sikkerhet/TilgangService.kt
NAV-12516 
Auditlogging skjer inne i en cachet metode, så man får dermed ikke med auditlogging ved endring av event. 
Skrur av caching for validerTilgangTilBehandling slik at man alltid auditlogger
Selve tilgangsjekken er cachet inne i harTilgangTilPersoner()
Fikser bug med manglende auditlogg i fagsak-metoden
Dette vil gi mer auditlogging, men mener dette er bedre enn manglende auditlogging som det er nå.
=> Alltid auditlogg tilgang på behandling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/VedtakBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/delt_bosted_og_reduksjon_6år.feature
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17433
Hvis det kun er reduksjon pga sats i periode skal person også få resultat "innvilget/økning". Dette er fordi i perioder hvor barnet blir 6 år samtidig som man har avtale om delt bosted så får man ikke med seg barnet i innvilget-tekster (siden det er reduksjon av beløp pga under 6 år).
Nei
=> Bug: fletting av barn i innvilget tekst når det er reduksjon pga 6 år i samme periode

.deploy/nais/app-prod.yaml, src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt
Endringer i scheduler jobben for å kjøre satsendring januar 2024
- Lagt tilbake scheduler-jobbene vi brukte for juni 2023 satsendring, men togglet de, slik at man kan starte med lavt volum, ikke utenom arbeidstid og helg. Alle toggler av for tidspunktet
- Endret søk etter ikke utførte satsendringer til å søke etter satstidspunkt 2024-01
PR kan gå inn før, men ikke testbar før https://github.com/navikt/familie-ba-sak/pull/4267 
=> Tilrettelegging for å kjøre satsendring januar 2024

src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringStatistikk.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt
Det er per nå ikke mulig å opprette en endre migreringsdato behandling dersom det finnes nye satser og forrige vedtatte behandling ikke har de nye satsene på plass. 
Denne endringen oppretter automatisk satsendring når man prøver å endre migreringsdato og satsen ikke er på plass.
https://nav-it.slack.com/archives/C01G9BA8JKZ/p1704456100569059
=> Oppretter satsendring hvis endre migreringsdato feiler pga manglende sats

src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/begrunnelser/LagGyldigeBegrunnelserTestUtil.kt
Vi må defaulte til tomstreng istedenfor å ha det som null hvis dødsfall dato ikke finnes.
=> Default til tomstreng istedenfor null

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsvurderingTidslinjer.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17560
Hvis søkers vilkår vurderes etter nasjonale regler, og det finnes minst ett barn som har vilkår vurdert etter eøs-regler skal validering feile. 
Nei
Har testet manuelt. Usikker på om det er verdt å lage en testrigg rundt dette 🤷
=> Validering: søker kan ikke vurderes etter nasjonal om det finnes barn vurdert etter EØS

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendringTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt
Saksbehandlerene liker å klikke mange ganger når ting ikke funker første gang, så ved endre migreringsbehandling så har vi hatt tilfeller hvor de har trigget 14 satsendringer på rad. Som generer 14 rader i satskjøringstabellen, hvor man forventer kun 1, og da blir det manuell opprydding og lengre tid for saksbehandleren å vente.
- Kun opprette rad hvis det ikke eksisterer
- melding til saksbehandler at de må vente til satsendring er ferdig kjørt.
=> Opprett kun 1 rad i satsendring ved oppretting av task

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassKompetanserService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/TilpassKompetanserTilRegelverkTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/TidslinjerTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17059
Del 1 av denne oppgaven ☝️ 
Når vi genererer kompetansene setter vi alltid siste periode til å være uendelig fram i tid. Dette skaper krøll når vi setter endret utbetaling til null kroner på grunn av endret mottaker ut behandlingen. Da vil vi få en kompetanse som starter etter at 18-årsdagen når den endrede utbetalingen avsluttes.  Se tegning.
Endrer så vi fjerner kompetansen når vi ikke har noen andeler på personen, så slipper vi dette problemet.
Dette fikser ikke at vi får feil farger i utbetalingstidslinjen på behandlingsresultatssiden når vi både har en nullutbetaling og endret utbetaling som er endret til null.
=> Klipp kompetanse til andelene

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsvurderingTidslinjer.kt
Valideringen sjekker om det finnes nasjonal på søker og eøs på barn generelt, men skulle ha vært i en spesifikk periode. Har en fiks på det andre klart, men fjerne fordi det tar litt tid å teste at det andre er riktig. Stopper opp noen saker.
Revert av #4279 
Nei
=> Bug: Fjern validering som jeg la til feil

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/Batch.kt
Fjerner rollestyring fra batch-tabellen. Siden den blokker for å opprette konsistensavstemming gjennom forvaltertjenesten med forvalter som rolle, og tabellen ikke er i bruk i saksbehandlerkontext.
=> Fjerner rollestyring fra batch-tabellen

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassKompetanserService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/TilpassKompetanserTilRegelverkTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/TidslinjerTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17059
Oppfølging for: https://github.com/navikt/familie-ba-sak/pull/4281
Når vi genererer kompetansene setter vi alltid siste periode til å være uendelig fram i tid dersom til-og-med-datoen er etter dagens dato. Når vi setter en endret utbetalingsperiode som stanser utbetalingen fjerner vi kompetansen i den perioden. 
Tidligere har vi satt kompetansene til å være uendelige før vi har fjernet kompetansene for endrede utbetalingsperioder som stanser utbetalingen. Da får vi problemet som er vist i bildet under, at den uendelige kompetansene starter opp etter de endrede utbetalingsperiodene. 
Endrer så vi fjerner kompetansene i periodene med endret utbetalingsperiode som stanser utbetalingen før …
=> Fiks kompetanseperioder ved stans av ytelse pga endret utbetaling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsvurderingTidslinjer.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingValideringTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17560
Ny fiks som sørger for at validering kicker inn hvis søker har nasjonal i en periode minst ett barn har EØS. Hadde tidligere en fiks på problemet, som skapte feil, fordi jeg sjekket om søker hadde nasjonal og det fantes barn med EØS. Problemet var at jeg ikke sjekket I EN PERIODE, men generelt 😅 revertet endringene for å sørge for at det ikke var feil i produksjon så lenge, men denne PRen er egentlig bare en bugfix på det
Nei
Har testet manuelt at det funker og at det ikke brekker det som ble feil sist
=> Valider at søker ikke har nasjonal i en periode minst ett barn har eøs

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestTilkjentYtelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtilsTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17059
Vi har et case der andelene i behandlingsresultatet vises feil siden vi ikke slår sammen periodene riktig. 
Endrer til å bruke tidslinjerammeverket til å slå sammen like perioder, så slipper vi å deale med dette selv. 
Leses enklest commit for commit.
=> Slå sammen andeler til rest ytelse perioder riktig

.deploy/nais/app-prod.yaml, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/task/GrensesnittavstemMotOppdrag.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/GrensesnittavstemMotOppdragTest.kt
Huritgtiltak for å få bedre grensesnittavstemming ved satsendring.
- Sørger for at man kjører fast med 5 podder. Her skal man skalere ned til 2/4 når satsendring er ferdig
- Ikke automatisk rekjør tasken 3 ganger ved feil for å forhindre at man trigger flere grensesnittavstemminger ved nettverksfeil o.l.
- endepunkt for å opprette neste grensesnittavstemming som kan brukes når man må avvikhåndtere en avstemMotOppdrag task
=> Ikke nedskaler podder ved satsendring, feil grensesnittavstemming på første forsøk og forvalterendepunkt for å oppprette ny grensesnitt-task

src/main/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIVilkårsvurderingUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/BeskjæreTidslinje.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIVilkårsvurderingUtilTest.kt
Fikser en bug i prod som oppstår fordi vi forsøker å beskjære tidslinje sin tom på 18 års vilkår.
Dette ble opprinnelig gjort fordi det å sette TIDENES_ENDE førte til en evig lang tidslinje som tok evigheter å prosessere i ba-sak.
Lager derfor en extension metode for tidslinje som bare beskjærer fomdato og lar tomdato være as-is.
=> Vi beskjærer bare fom dato

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelerTilkjentYtelseOgEndreteUtbetalingerService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceTest.kt
Vi har noen satsendringer som ikke går gjennom fordi de endrede utbetalingene ikke lenger passerer valideringene. Vi har gått gjennom sakene det gjelder og ser at andelene og brevene har blitt riktige. 
Endrer så behandlingen ikke stopper på valideringene for endret utbetaling dersom vi er på en satsendringssak.
=> Ikke valider andeler på endret utbetaling ved satsendring 

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/PatchFomPåVilkårTilFødselsdato.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/internal/ForvalterServiceTest.kt
legg til forvalterEndepunkt som endrer fomdato til vilkårResultat til persons fødselsdato dersom fomdato er før fødselsdato innenfor samme måned
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17837)
Ønsker et forvalterendepunkt vi kan bruke for å rette opp vilkårresultater der periodefom er før barns fødselsdato. 
=> endepunkt for å endre periodeFom på vilkårResultat dersom det er før barns fødselsdato

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/internal/ForvalterServiceTest.kt
Når vi endrer fom på vilkårresultater som begynner før personens fødselsdato ønsker vi ikke å flytte på fom på under-18-vilkår siden vi da og må flytte på tom-verdien også og det kan føre til problemer. Dette gjelder gjerne en annen type feil enn den vi jobber med. 
Videre arbeid på [denne](https://github.com/navikt/familie-ba-sak/pull/4312) PR-en :)
=> fjern UNDER-18 vilkår fra vilkår man flytter fom på

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelseRepository.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragIntegrasjonTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceIntegrationTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17858
I saken lenket til på favro får vi feil forrigePeriodeOffset i utbetalingsoppdraget på en av personene. Grunnen til dette er at funksjonen som finner siste offset i kjede per person finner feil siste offset for denne personen. I denne saken så har første behandling (søknad) kun 0-utbetalinger, men det er laget andeler som har lagret ned offset i databasen og det finnes et utbetalingsoppdrag, men dette har en tom liste med utbetalingsperioder. Sørger derfor i denne PRen for at vi ikke ser på behandlinger hvor utbetalingsoppdraget har en tom liste med perioder sendt til økonomi, fordi da er egentlig ingen av offsetene i den behandlingen relevante å ta med.
Lurer litt på om spørringen også …
=> Bug: feil offset i utbetalingsoppdrag

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/AvstemmingService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiKlient.kt, src/main/kotlin/no/nav/familie/ba/sak/task/GrensesnittavstemMotOppdrag.kt, src/main/kotlin/no/nav/familie/ba/sak/task/dto/GrensesnittavstemmingTaskDTO.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/GrensesnittavstemMotOppdragTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17773
Når vi kjører grensesnittavstemming i ba-sak henter det at avstemmingen timer ut før den er ferdig, selv om det går bra mot oppdrag. I de tilfellene har vi ikke lyst til å kjøre grensesnittavstemmingen på nytt.
Endrer så vi sender med en avstemmingId som vil bli lagret i familie-oppdrag. Dersom vi prøver å rekjøre en grenseavsnittsavstemming på samme avstemmingId vil den bli ignorert dersom forrige avstemming gikk ok.
=> Send med avstemmingId med Grensesnittavstemming

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/AvstemmingService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiKlient.kt, src/main/kotlin/no/nav/familie/ba/sak/task/dto/GrensesnittavstemmingTaskDTO.kt
Ønser at avstemmingId er nullable slik som det er i api-et til oppdrag. Vi har tasker som feiler på dette.
=> avstemmingId skal være nullable

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/SendTilBeslutter.kt, src/main/kotlin/no/nav/familie/ba/sak/task/FerdigstillLagVedtakOppgaver.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17857
Når vi har sendt behandling til godkjenning har vi tidligere hentet alle behandlingene av type BehandleSak, BehandleUnderkjentVedtak eller VurderLivshendelse på behandlingen og ferdigstilt dem. I tilfellet i favrooppgavnen var saksbehandler så rask at behandleSak-oppgavenikke var opprettet enda, og den ble derfor ikke ferdigstilt. 
Endrer så vi kaster en feil dersom vi ikke har en oppgave av typen BehandleSak, BehandleUnderkjentVedtak eller VurderLivshendelse når vi godkjenner vedtak og legger det inn i en task slik at det kan rekjøres senere.
_Har du husket alle punktene i …
=> Flytt ferdigstilling av oppgave inn i task

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt
Knyttet til https://github.com/navikt/familie-ba-sak/pull/4329
Vi validerer at vi får lukket oppgaven for å lage vedtak når vi sender til godkjenner. Disse oppgavene finnes ikke på migreringer eller tekniske behandlinger. Tar bort valideringen i de tilfellene
=> Ikke valider at vi har en oppgave på migrering eller teknisk behandling

pom.xml, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/internal/ForvalterSchedulerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/behandlingstema/BehandlingstemaServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatOpphørUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggBarnetrygdGeneratorTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValideringTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/TaskUtilsTest.kt
Når vi mocker statiske metoder, som feks `YearMonth.now()`, endrer vi dette globalt for _*alle*_ tester. Testene som kjører etter vil derfor returnere det samme som `YearMonth.now()` er mocka til når de kjører `YearMonth.now()`. 
Endrer så vi rytter opp der vi mocker statikste metoder. Endrer også så rekkefølgen på testene er random, slik at vi kan oppdage slike feil raskere i fremtiden.
=> Gjør så tester ikke er avhengige av rekkefølge

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/avslag.feature
Gjelder denne feilen i sentry: https://sentry.gc.nav.no/organizations/nav/issues/545586/?environment=prod&project=112&query=is:unresolved#exception
På denne behanldingen: https://barnetrygd.intern.nav.no/fagsak/2220279/4651738/vedtak
Vi fletter ikke inn barna når det er avslag på søker som ikke har en startdato. 
Endrer slik at vi fletter inn alle barna på behandlingen selv om avslaget ikke er generelt.
=> Fiks feil der barna ikke blir flettet inn når vi har avslag på søker

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt
Logger andel ved valideringsfeil av andel ved satsendring. For å enklere feilsøke
=> Lagt til mer logging for å kunne feilsøke valideringsfeil for tilkjent ytelse ved satsendring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/EndreTid.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/VedtakBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingForskyvningUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingForskyvningUtilsTest.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/avslag.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/opphør.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/avslag.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-17842)
Når en behandling har et eksplisitt avslag dukker ikke avslagsbegrunnelsene opp. Dette er fordi vi når vi har forskjøvet perioder som starter og stopper innenfor samme måned har satt perioden til å være tom (Fordi innholdSisteDagForrigeMåned eller innholdFørsteDagDenneMåned vil være null. Se dokumentasjonen til EndreTid.tilMånedFraMånedsskifteIkkeNull() ).
Ønsket oppførsel for eksplisitt avslag er:
* Vilkårsresultat som slutter innenfor samme måned, f.eks. 16. jan - 31. jan skal gi periode 1. feb - 28. feb
* Vilkårsresultat som varer lengre, f.eks. 16.jan - 30. april skal gi periode 1. feb - 30 april
* Dersom vi har en innvilget periode etter avslaget altså avslag 16. jan - 30. april, …
=> forskyv eksplisitte avslag dersom de begynner og opphører innenfor samme måned

src/main/kotlin/no/nav/familie/ba/sak/config/LeaderClientService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/skyggesak/SkyggesakScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/internkonsistensavstemming/InternKonsistensavstemmingScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/småbarnstillegg/RestartAvSmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakStatusScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/metrikker/TeamStatistikkService.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkScheduler.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/MockLeaderClientService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/internal/ForvalterSchedulerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/småbarnstillegg/RestartAvSmåbarnstilleggServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/skyggesak/SkyggesakSchedulerTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18021)
Ønsker å skrive oss vekk fra statisk mocking av metoder siden det kan skape ustabile tester.
Wrapper felles sin LeaderClient.isLeader() i et interface som kan mockes når det trengs, f.eks. i integrasjonstester. 
Kunne dette gjøres på en lurere måte? 
=> wrap fells.LeaderClient.isLeader() i eget interface

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/PatchMergetIdentTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/PatchMergetIdentTaskTest.kt
NAV-18269
Tillater patching av ident for Søker.
=> Mulighet til å kunne patche søkers ident for en fagsak

.deploy/nais/app-preprod.yaml
I følge [dokumenteringen til Nais](https://doc.nais.io/explanation/good-practices/?h=cp#set-reasonable-resource-requests-and-limits) skal man sette cpu-requests til hva applikasjonen bruker ved normal last. Ved å se på historisk data kan det se ut som dette ligger på rundt 7% av hva vi ber om i dag i preprod, se [nais console](https://console.nav.cloud.nais.io/team/teamfamilie/dev-gcp/app/familie-ba-sak/utilization?from=2023-10-17&to=2024-02-29) og bilde under. Endrer derfor cpu-request til 10% av det vi har i dag.
=> Reduser cpu-request

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingMetrikker.kt
Oppdaget at vi logger noen tusen linjer med stacktrace (ett innslag per linje i stacktrace...!) jenvlig, for å si ifra om at metrikken `eøs-begrunnelse` har ugyldig navn. Endrer til å unngå ø. Metrikken leses i grafana, men vi har ingen skjermer ennå som trenger å oppdateres med nytt metrikknavn
```
[otel.javaagent 2024-03-04 10:07:39:940 +0100] [TaskWorker-1] WARN io.opentelemetry.sdk.metrics.SdkMeter - Instrument name "eøs-begrunnelse" is invalid, returning noop instrument. Instrument names must consist of 255 or fewer characters including alphanumeric, _, ., -, and start with a letter.
```
=> Unngå Ø i metrikknavn

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/VedtaksperiodeProdusent.kt
[Codeql klager på at vi har to funksjoner med samme navn, men med forskjellig kapitalisering](https://github.com/navikt/familie-ba-sak/security/code-scanning/46). Funksjonene opererer på forskjellige klasser, så tenker vi beholder de som de er, men endrer navn slik at ikke codeql skal klage.
=> Endre navn slåSammenSammenhengendeOpphørsPerioder -> slåSammenSammenhengendeOpphørsperioder

src/main/kotlin/no/nav/familie/ba/sak/common/TekstSaniteringUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestFagsakSøk.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestHentFagsakForPerson.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestHentFagsakerForPerson.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestManuellDødsfall.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestNyttVilkår.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestOppdaterJournalpost.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestPersonResultat.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestSlettVilkår.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/SøknadDTO.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/småbarnstillegg/VedtakOmOvergangsstønadController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/søknad/GrunnlagController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/IdentController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårController.kt, src/main/kotlin/no/nav/familie/ba/sak/sikkerhet/TilgangController.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/TekstSaniteringUtilTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/ArbeidsfordelingIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakControllerTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/SøkFagsakNegativeTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/søknad/SøknadGrunnlagTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingServiceTest.kt
[Codeql klager på at vi saniterer dataene før vi bruker det i logger](https://github.com/navikt/familie-ba-sak/security/code-scanning/52). 
Endrer så vi saniterer den variabelen. 
Egentlig burde vi validere disse dataene tidligere, både syntaktisk og semantisk. Se [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html). Endrer også så vi kjører valideringer på personidentene vi får i endepunktene våre.
=> Valider person ident

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatEndringUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatEndringUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/MockAutovedtakSmåbarnstilleggService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/domeneparser/DomeneparserUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceIntegrationTest.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/autovedtak_småbarnstillegg.feature
Leses lettest commit for commit
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18278)
Fortsettelse av https://github.com/navikt/familie-ba-sak/pull/4398
I forrige PR gjorde vi at endringer i overgangstønad som kun endret andeler etter neste måned kunne kjøre automatisk. Dersom det også fører til en endring tilbake i tid, skal vi ikke kjøre disse automatisk. 
Endrer så vi kun behandler automatisk dersom behandlingsresultatet blir fortsatt innvilget. 
Utvider også på testrammeverket
=> Fiks autovedtak småbarnstillegg fram i tid

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/Differanseberegning.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilpassDifferanseberegningService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningSøkersYtelserTest.kt
Utvidede regler for differanseberegning er tatt i bruk i prod. Fjerner derfor bruk av toggle.
=> Fjernet bruk av differanseberegning-toggle

src/main/kotlin/no/nav/familie/ba/sak/common/TekstSaniteringUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/TekstSaniteringUtilTest.kt
Ønsker at valideringen skal være gyldig ved tom streng
=> Støtt tom streng i validering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSteg.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatStegTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/MockAutovedtakSmåbarnstilleggService.kt
Favro: [NAV-18723](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18723)
Ved satsendring i juni og i januar har vi fullført behandlingsresultat-steget med tilfeller av UtenlandsPeriodebeløp- og Valutakurs -perioder som ikke har vært utfylt. Legger nå inn en validering som vil stanse saksbehandling dersom alle perioder ikke er utfylt.
Dette er kun en validering som hindrer videre saksbehandling og ikke en fix av selve feilen som skaper problemet. Kode som retter feilen kommer i egen PR.
=> Validerer at UtenlandskPeriodebeløp og Valutakurs er utfylt ved kjøring av BehandlingsresultatSteg

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/domene/Datagenerator.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceIntegrationTest.kt
Favro: [NAV-18723](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18723)
Som en del av satsendring, kjører vi gjennom VilkårsvurderingSteg på samme måte som for manuelle behandlinger. Vi genererer blant annet andeler og tilpasser skjemaer for kompetanse, utenlandsk periode beløp og valutakurs. I logikken som tilpasser kompetanse-skjemaene blir det opprettet en splitt dersom dagens dato er etter siste EØS-periode for ett av barna. Typisk at ett av barna har fylt 18 år. Når dette skjer opprettes også nye perioder med utenlandsk periodebeløp og valutakurs. I og med at vi ikke har noen måte å fylle ut disse periodene på ved satsendring blir ikke differanseberegning gjennomført og søker får utbetalt full norsk sats.
I og med at vi ikke ønsker å gjøre …
=> Sørger for at vi ikke genererer nye kompetanser ved satsendring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Vi fikk en del feilmeldinger i loggene som sa at vi hentet en EØS begrunnelse fra Sanity som vi ikke hadde definert i koden. `Finner ikke EØSStandardbegrunnelse for avslagDeltBostedBeggeForeldreIkkeOmfattetNorskLovvalg`
Har nå lagt inn støtte for denne begrunnelsen.
Jeg har ikke skrevet tester fordi:
Ingen funksjonell endring.
=> Lagt til manglende EØS-avslagsbegrunnelse

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Vi kaster feil ved henting av begrunnelser for hver begrunnelse vi forventer at skal finnes i Sanity. Det var nå 4 begrunnelser som var avpublisert og merket som 'Utgått' i Sanity, men som fortsatt lå inne begrunnelse-enumene våre. Disse skaper mye støy i loggene.
Fjerner her de 4 utgåtte begrunnelsene. Har verifisert at de kan fjernes med Anna.
De utgåtte begrunnelsene i Sanity:
* [[Utgått] Etterbetaling tre år tilbake i tid kun utvidet del](https://familie-brev.sanity.studio/ba-brev/structure/__edit__7ca99085-f7ef-4d37-9a82-28bc7a83b8cb%2Ctype%3Dbegrunnelse)
* [[Utgått] Etterbetaling tre år tilbake i tid](https://familie-brev.sanity.studio/ba-brev/structure/__edit__090a065e-b055-44bf-b974-950037ecd944%2Ctype%3Dbegrunnelse)
* [[Utgått] Etterbetaling tre år tilbake i tid …
=> Fjernet begrunnelser som er avpublisert i Sanity og merket som 'Utgått'

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/task/MånedligValutajusteringTask.kt
Oppgave: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18511
I forbindelse med at vi lager månedlig valutajusteringen har vi ikke koblet sammen scheduleren og selve koden for valutajustering. Fikser det i denne PRen. 
I tillegg trenger vi å kunne teste det vi lager. Legger også til et testendepunkt for å starte koden manuelt
=> Gjør det mulig å starte valutajustering scheduleren

src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
For å finne dato injiserer vi en LocalDateProvider i servicene våre. For prod bruker vi RealDateProvider som alltid gir dagens dato, men i testene ønsker vi å mocke dette til en dato vi setter selv. Endrer fra å bruke RealDateProvider til mockedDateProvider
=> Fiks feilende tester. Bruk MockedDateProvider

pom.xml
Får advarsel i oppstart av app at man bruker feil versjon av sentry. Så bytter til den man bør bruke for Spring boot 3
https://docs.sentry.io/platforms/java/guides/spring-boot/
=> For Spring Boot 3 så bør man bruke jakartaversjonen av Sentry

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/sanity/SanityService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingMetrikker.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/sanity/SanityServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-20240
Jeg refaktorer skruddAvIProduksjon logikken slik at filtreringen skjer i sanityService.
Dette fordi det blir mye kode duplikat dersom hver service selv skal gjøre denne filtreringen.
Legger til mulighet for filtrering slik at steder som BehandlingMetrikker der vi ønsker alle begrunnelser uavhengig av skruddAvIProduksjon skal komme med.
=> Refaktorerererer filtrering av sanity begrunnelser basert på miljø

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/Brev.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/HenleggBehandling.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-20289
Denne PR'n gjør to ting
1.  Vi har en bug der henleggelse av søknad som tilhører institusjon blir sendt til barn. PR'n retter opp dette.
2. Ved utsendelse av brev relatert til henlegge av søknad som tilhører institusjon så bruker vi nå egen brevmal
=> Legg til egen brevmal for henlagte søknad institusjon og fiks bug

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSøknadUtils.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-20244
Bytter til å kaste en funksjonell feilmelding med en bedre feilmeldingstekst for saksbehandler, slik at saksbehandler skjønner at det er hen som må gjøre en endring for å komme videre. Hvis en 0-andel ikke er knyttet til endret utbetaling eller skyldes differanseberegning er det fordi saksbehandler ikke har lagt inn endret utbetaling på søkers andeler, men "etterbetaling 3 år" på alle barna. I dette scenariet dannes det utvidet-andel med 0kr uten endret utbetaling, men med denne feilmeldingen får vi forhåpentligvis …
=> Bedre feilmelding ved andel på 0kr som ikke skyldes differanseberegning eller endret utbetaling

src/main/resources/db/migration/V258__slett_samlet_resultat_vilkaarsvurdering.sql
Sletter enda ubrukt kolonne i db i vilkårsvurdering tabellen.
Ingen referanser til kolonna i koden, så antar at man på et tidspunkt fjernet feltet fra klassen, men glemte å slette kolonna.
=> Sletter enda ubrukt kolonne i db

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ISanityBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/RestSanityBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/eøs/RestSanityEØSBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/IVedtakBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/domene/EØSBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/domene/RestUtvidetVedtaksperiodeMedBegrunnelser.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/domene/RestVedtaksbegrunnelse.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
Favro: [NAV-20229](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-20229)
Utvider ISanityBegrunnelse med feltet stotterFritekst og eksponerer feltet til frontend via RestVedtaksbegrunnelse.
=> Utvider ISanityBegrunnelse med feltet stotterFritekst og eksponerer feltet til frontend via RestVedtaksbegrunnelse

src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/vedtaksperioder/LagVedtaksperiodeTestUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/EndringsTidspunktUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/VedtaksperiodeGrunnlagForPerson.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/endringstidspunkt.feature
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-20060
Vi har en sak der endringen fra forrige behandling er at utvidet barnetrygd avsluttes og starter opp igjen innenfor samme måned. Dette fører ikke til noen endring i utbetaling. Tidligere har vi kun sammenlignet vilkårene måned for måned når vi har sett etter endringer mellom behandlingene. Det gjør at vi ikke oppdager noen endring per i dag, men vi ønsker at systemet skal tolke dette som en endring.
Endrer så vi også sjekker om fra-og-med-datoen på vilkårene er den samme. Dersom den er ulik anser vi det som en endring.
Leses enklest commit for commit. 
=> Sett endringstidspunk dersom det er en splitt i vilkårene 

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/HenleggBehandling.kt
Vi har en bug i dag som fører til dette:
Dette oppstår fordi mottakerNavn ikke blir populert ved institusjon.
Fikser dette.
=> Populer mottakernavn ved institusjon

src/main/kotlin/no/nav/familie/ba/sak/config/ApiExceptionHandler.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestOppdaterJournalpost.kt
Hvis en saksbehandler prøver å skrive en ident som ikke validerer i avsendermottaker, så får ikke saksbehandler noen god feilmelding i frontend. Og vil gjøre igjen og igjen og skape støy i sentry
**Fø**r:
**Etter**:
=> Legger til en frontendfeilmelding for Ugyldig ident

src/test/resources/application-dev-postgres-preprod.yaml
Endrer over til intern.dev ingress for familie-integrasjoner
=> Bytter dev-url til integrasjoner vekk fra en deprekert en

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt
Ref [denne](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-19991) oppgaven. Etter å ha oppdatert tilkjentYtelse.stønadTom ønsker vi å oppdatere fagsakstatus på fagsakene det gjelder for å kunne sjekke at fiksen funker (og kunne rydde vekk taskene i familie-prossessering før det glemmes). 
Bør dette endepunktet fjernes eller beholdes etter at vi er ferdig med denne fiksen?
=> legg til endepunkt for å oppdatere løpende flagg på fagsaker slik at man ikke må vente til første dag i måneden

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt
Endepunktet slik det var skrevet tidligere var avhengig av at kallet tilfeldigvis ble gjort til poden som er leder. Det er uheldig.
=> oppdaterLøpendeFlaggtask er ikke avhengig av å bli kjørt i lederpod

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestUtvidetBehandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/UtvidetBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/ValutakursController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/VurderingsstrategiForValutakurser.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/VurderingsstrategiForValutakurserRepository.kt, src/main/resources/db/migration/V260__lag_vurderingsstrategi_for_valutakurser.sql, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-20661
For å være på den sikre siden ønsker vi å kunne skur av at valutakursene genereres automatisk. I så fall skal det være mulig å redigere de automatiske valutakursene og endringer i behandlingen skal ikke lenger føre til at vi henter kurser og lager perioder for kursene atuomatisk. 
Legger til en tabell for VurderingsstrategiForValutakurser som er koblet til behandlingen i tillegg til en controller for å opprette rader i tabellen. 
Dersom vi har satt strategien på en behandling til manuell vil ikke løypa for automatisk valutajustering kjøres.
=> Legg til vurderingsstrategi for valutakursene

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/config/KafkaAivenConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/IdenthendelseV2Consumer.kt, src/main/resources/avro/AktorV2.avdl
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-20711
Siden vi nå leser direkte fra køen i ks-sak istedenfor å få hendelsene sendt gjennom REST fra baks-mottak, så ønsker vi å gjøre tilsvarende for ba-sak. Dette betyr også da at vi kan slette kode fra baks-mottak når det er ferdiggjort.
Endepunktet som baks-mottak benytter seg av tenker jeg å ta i en annen PR som kommer etter denne.
=> Les fra identhendelse kafka kø

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragGeneratorService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatOpphørUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/domene/EndretUtbetalingAndel.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OppdaterStønadTomPåTilkjentYtelseTask.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-19991)
Når vi finner behandlinger for å sjekke om stønadTom burde settes tidligere så vi tidligere på behandlinger som er iverksatt. Det blir feil når vi har fagsaker uten iverksatte behandlinger eller når behandlingen vi vil ente stønadTom fra ikke er iverksatt. Bytter derfor til å se etter siste behandling som er avsluttet i stedet.
=> resterende behandlinger med feil tilkjent ytelse tom

pom.xml
Swagger funker ikke. Ser ut til å være en transitive dependency som kommer inn i gammel versjon pga confluent jackson, så overstyrer
=> Fikser brukket swagger etter transitive dependencies

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursService.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-20661
Sjekk om vi har en tidligere behandling når vi resetter valutakursene. Om vi har en tidligere behandling skal kursene settes slik de var før vi genererer automatiske, om ikke genererer vi bare de automatiske
=> Ikke resett valutakurser til forrige behandling dersom vi er på en førstegangsbehandling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/FellesDelmaler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/InnhenteOpplysningerBrev.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/InnhenteOpplysningerOmBarn.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-20702
Vi ønsker å legge til muligheten for å legge til et avsnitt der man kan skrive fritekst i.
Forskjellen mellom denne og kulepunkt funksjonaliteten er at teksten som skrives her ikke skal være bundet til noe kulepunkt
Frontend PR:   https://github.com/navikt/familie-ba-sak-frontend/pull/3155
=> Legg til fritekst avsnitt delmal logikk

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/domene/Kompetanse.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/domene/Datagenerator.kt
Brev-generering feiler i EØS-saker dersom man kan har 1 kompetanse og denne begynner før endringstidspunktet. 
Bruker her tidslinjer for å sørge for at vi får med oss alle gjeldende kompetanser fra endringstidspunktet og utover.
=> Fix: Finne alle kompetanser etter endringstidspunkt

src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/IntegrasjonClientMock.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/MockPersonopplysningerService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/InfotrygdBarnetrygdClientTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/ArbeidsfordelingIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/SnikeIKøenIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/AutomatiskVilkårsvurderingIntegrasjonTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/VelgFagsystemIntegrasjonTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakControllerTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/RestFagsakTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/søknad/SøknadGrunnlagTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingFlyttResultaterTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/sikkerhet/TilgangControllerTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/task/FerdigstillBehandlingTaskTest.kt
En fortsettelse av arbeidet med å redusere testenes avhengigheter til ClientMocks https://github.com/navikt/familie-ba-sak/pull/4536
Går vekk fra bruken av mockk med felles testverdier på tvers, sånn at testene vanskeligere skal gå i beina på hverandre.
Relativt stor pr, men mye av det er repeterende mønstre, og totalt sett er det flere linjer som fjernes enn det som legges til
=> Ny "mock-pdl"-profil som erstatter ClientMocks-oppsettet for personinfo

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/domene/Kompetanse.kt
Får overlapp i tidslinjer når vi lager 1 tidslinje for alle kompetansene etter endringstidspunkt i en behandling. Dette fører til at tidslinjefeil kastes.
Endrer til å lage 1 tidslinje per aktør og heller slå disse sammen igjen etter tidslinje-manipulering.
=> Finner utfylte kompetanser per barn for å unngå tidslinje overlapp på tvers av barn

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingStegController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevmalService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonopplysningGrunnlagUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkServiceTest.kt
Etter en diskusjon på kontoret har vi blitt enige å fjerne teknisk opphør enum verdien.
Den må migreres i db i preprod og prod.
Ingen behandlinger i preprod som hadde denne typen.
3 i prod.
=> Vi fjerner teknisk opphør

.github/workflows/build-pr.yml
Lagt til -Dsurefire.rerunFailingTestsCount=2 for integrasjonstester for å rekjøre flaky tester
Flaky tester vil bli markert som
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Flakes: 1
men blir grønn
=> Lagt til -Dsurefire.rerunFailingTestsCount=2 for integrasjonstester for å rekjøre flaky tester

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtilsTest.kt
Vi har en feil når vi prøver å sammenligne tidslinjer etter at det har blitt beskjært fra og med tidenes ende.
Vi returnerer derfor bare false med engang i `skalHenteUtbetalingerEøs` dersom endringstidspunktet er tidenes ende, da det uansett ikke finnes noe valutakurs etter det tidspunktet.
Opprinnelig feil:
```
Caused by: java.time.DateTimeException: Invalid value for Year (valid values -999999999 - 999999999): 1000000000
at java.base/java.time.temporal.ValueRange.checkValidIntValue(Unknown Source)
at java.base/java.time.temporal.ChronoField.checkValidIntValue(Unknown Source)
at java.base/java.time.YearMonth.plusMonths(Unknown Source)
at no.nav.familie.ba.sak.kjerne.tidslinje.tidspunkt.MånedTidspunkt.flytt(MånedTidspunkt.kt:25)
at …
```
=> Returnerer false i skalHenteUtbetalingerEøs dersom endringstidspunktet er satt til tidenes ende.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/VilkårFilterUtil.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/opphør/endring_etter_opphør.feature
Favro: NAV-21008
I et scenario der to barn fyller 18 samme måned, og ene barnet er opphørt tidligere, ble begge barna tatt med i begrunnelse. Forventer egentlig bare det barnet som ikke var opphørt.
Endrer så vi kun drar inn barn i begrunnelse som har innvilgede vilkår fra forrige periode eller samme periode forrige behandling
=> Kun flette inn barn i begrunnelse som ikke allerede er opphørt

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursService.kt
Bugfix etter tilbakemelding fra saksbehandlere.
Vi skal ikke lage automatikse valutakurser dersom det er en migreringsbehandling.
=> Ikke lag automatiske valutakurser i migreringsbehandligner

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/AutovedtakFødselshendelseService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/FødselshendelseServiceTest.kt
NAV-21071
Forventet oppførsel:  Det skal ikke opprettes automatiske oppgaver for oppfølging med årsak "kontroller gyldig opphold" når mor er utenlandsk statsborger.
Ida skrevi kortet: Avklart med Anna: Vi tror aldri dette har blitt skrudd av, så ønsket for denne oppgaven er at funksjonaliteten skal bli lagt bak en feature toggle, og eventuelt fjernet på sikt hvis vi ikke trenger det lenger
Denne PR legger denne funksjonaliteten som oppretter oppgaver med "Kontroller gyldig opphold" bak en toggle.
=> Flytter oppretteFremleggsoppgaveDersomEØSMedlem bak toggle og skrur den av i miljøene

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonClient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveController.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/HenleggBehandling.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/IntegrasjonClientMock.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveIntegrationTest.kt
Fjerner ubrukt endepunkt fjern-behandles-av-applikasjon. Denne er alt slettet i integrasjoner.
=> Fjern ubrukt endepunkt fjern-behandles-av-applikasjon

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceIntegrationTest.kt
Favro: NAV-21205
En behandling som ligger lenge til godkjenning vil ikke få oppdatert valutakurser i perioden den ligger til godkjenning.
Endrer derfor slik at vi oppdaterer valutakurser når beslutter godkjenner/underkjenner behandlingen
Oppdatering av valutakurser er allerede testet. Virker unødvendig å kun teste at funksjonen blir kjørt
=> Oppdater valutakurs i beslutte vedtak-steg

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/internkonsistensavstemming/InternKonsistensavstemmingUtil.kt
Dersom det er feil i intern konsistensavstemming ønsker vi å ha litt med data i feilmedlingen. Endrer så vi sender med andelene som ble brukt i avstemmingen
=> Logg andelene som blir bruk i intern konsistensavstemming ved feil

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligvalutajustering/MånedligValutajusteringScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/task/MånedligValutajusteringFinnFagsakerTask.kt
Koden for månedlig valutajustering skal kjøres første virkedag per måned, som er fikset her. Har gjort det likt som `opprettAutobrevTask`, som allerede hadde lignende funksjonalitet.
Kan/bør vi skrive tester for scheduled tasks?
=> Endret i scheduler for månedling valutajustering, endrer til første virkedag

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtilsTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21245
Vi har per i dag en liten bug når vi oppretter utbetalingstabellen.
Per nå inkluderer den andeler som er satt til 0 pga endret utbetaling andeler. Disse ønsker vi ikke å ha med.
Jeg tenker derfor det er greit at vi filtrerer bort andelene tidlig i løpet.
=> Filtrer bort andeler som er satt til 0 pga endret utbetalingsandeler før vi fortsetter å hente utbetalingsinfo

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligvalutajustering/MånedligValutajusteringScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingHentOgPersisterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/task/MånedligValutajusteringFinnFagsakerTask.kt
Funksjonen som starter månedlig valutajustering tillater enn så lenge kun av vi starter det første virkedag i måneden. 
Endrer så vi starter månedlig valutajustering umiddelbart dersom vi starter det fra endepunkt.
=> Legg til mulighet for å kunne kjøre MånedligValutajustering utenom første virkedag i måned

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21377
Dette er begrunnelser tilknyttet EØS selvstendig rett som mangler, og som er etterspurt i produksjon
=> Vi legger til to nye begrunnelser for eøs to primærland som etterspørres i produksjon

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21380
Vi henter endringstidspunkt i denne koden ved å hente alle sorterte vedtaksperioder (ved å bruke fom), og deretter så tar vi den tidligste fommen. Problemet med dette er at hvis fom er null i et vedtaksperiode som f.eks ved avslag, så vil den bli plassert først i lista. (se https://pl.kotl.in/EI5fbYvTC)
Henter derfor første som faktisk har fom.
=> Hent første vedtaksperiode som faktisk har en fom dato før vi sjekker etter endringstidspunkt

src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/begrunnelser/LagGyldigeBegrunnelserTestUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatValideringUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/MånedligValutajusteringFinnFagsakerTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/MånedligValutajusteringTask.kt
Automatisk valutajustering tar utgangspunkt i siste iverksatte behandling. Dette blir feil for saker med nullutbetaling.
Fikser problemet ved å bruke siste vedtatte behandling i stedet for.
Vanskelig å teste fordi vi bruker en annen SQL spørring
=> Fikse validering av valutajustering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligvalutajustering/AutovedtakMånedligValutajusteringService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/MockAutovedtakMånedligValutajusteringService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/komponentMocks/MockSimuleringService.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21237)
Automatisk valutajustering skal ikke gjøres dersom det fører til en etterutbetaling eller feilutbetaling
Feilutbetaling og etterutbetaling hentes fra økonomi, så dette måtte i så fall måtte blitt mocket i en test, og vi hadde dermed endt opp med å teste at mocken funker
=> Ikke kjør automatisk valutajustering som fører til etterutbetaling eller feilutbetaling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingValidering.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21410)
Vi har en validering som stopper saker fra å ha forskjellig regelverk på søker og barn. Denne valideringen har ikke alltid vært på, og vi har noen saker med blandet regelverk. I de sakene blir resultatet det samme som om begge partene har nasjonalt regelverk. 
Siden vi nå har fått en validering stoppes disse sakene ved månedlig valutajustering. 
Endrer så vi hopper over valideringen ved månedlig valutajustering.
=> Ikke kast feil ved blandet regelverk dersom det er månedlig valutajustering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligvalutajustering/MånedligValutajusteringScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/task/MånedligValutajusteringFinnFagsakerTask.kt
Skrur på funksjonalitet for å starte månedlig valutajustering første virkedag hver måned. Tidligere har dette ligget bak en toggle og kun kjørt et mindretall av sakene i en startfase. 
=> Kjør automatisk månedlig valutajustering på alle saker

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligvalutajustering/AutovedtakMånedligValutajusteringService.kt
I automatisk valutajustering kaster vi en feil dersom det er en etterutbetaling eller feilutbetaling.
For at disse skal bli korrekt oppdaterer vi simuleringen før vi henter verdiene
Ville bare endt opp med å teste mockingen
=> Oppdater simulering ved behov før vi henter etter- og feilutbetaling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/EndringsTidspunktUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/endringstidspunkt/endringstidspunkt.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/test.feature
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21290
Vi oppdaget en prodfeil hvor en sak fikk automatisk valutajustering lenger tilbake i tid enn forventet. Grunnen til dette var at endringstidspunktet var feil. Det eneste som hadde skjedd i behandlingen var opphør på et vilkår. Når den gamle koden da sammenlignet om alle vilkår var like før og nå for perioden 02.23-05.23 (som var ikke oppfylt for personen), fikk den feil svar, fordi tom-dato var forskjellig på vilkår som strakk seg over denne perioden. Sørger nå for at vi ser bort i fra tom-datoene når vi …
=> Bugfix: endringstidspunkt ved opphør

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/utenlandskperiodebeløp/UtenlandskPeriodebeløpRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/task/KorrigerUtenlandskePeriodebeløpTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/internal/ForvalterServiceTest.kt
Ca 2500 utenlandske periodebeløp har feil verdi i feltet `utbetalingsland`. Enten er det satt til `NO` eller så er det satt til `null`, og begge disse skal ikke være mulig.
Legger her inn funksjonalitet for å finne og korrigere de utenlandske periodebeløpene med feil. Starter med noen få og justerer opp dersom det ser bra ut. Har testet ok i preprod.
Dette må kjøres før vi kan skru på nye regler for utledning av utbetalingsland.
=> Forvalter-endepunkter for patching av upb med feil utbetalingsland

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingValidering.kt
Månedlig valutajustering stoppes dersom barnets fødselsdato ikke stemmer overens med 18-års vilkåret. Legger her inn at vi ikke stopper behandlingen dersom opprettetÅrsak er månedlig valutajustering, slik vi også gjør for satsendring og omregninger.
Dette gjør vi fordi vi allikevel ønsker å korrigere utbetalingsbeløpet for neste måned for å unngå feilutbetalinger. Vi har andre valideringer i senere i løypa som passer på at vi ikke endrer noe annet enn beløpet for inneværende måned. Endring/oppdatering av 18-års vilkåret kan rettes ved neste revurdering/årlig kontroll. Vi logger fortsatt ut at fødselsdato ikke stemmer overens med 18-års vilkåret.
=> Hopp over validering av 18 års vilkåret for månedlig valutajustering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingValidering.kt
I https://github.com/navikt/familie-ba-sak/pull/4630 , hoppet vi over validering av 18-årsvilkåret for månedlig valutajusterings-behandlinger. Litt senere valideres det samme uansett på nytt. Trodde i utgangspunktet at vi også hoppet over alle disse valideringene for satsendring, men ser nå at vi validerer vilkårene også for satsendring, så da reverserer jeg endringene her.
=> Reverterer at vi hopper over validering av 18-års vilkåret dersom det er månedlig valutajustering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/månedlig_valutajustering/Automatiske_valutakurser_ved_oppdatert_periode.feature
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21538
Dersom vi har to barn som har forskjellig utenlandsk periodebeløp men med samme valutakode i en periode skal de samles i samme rad i valutakurstabellen. 
Slik koden var lagde vi en egen oppdatering for valutakurs per utenlandsk periodebeløp. Det vil si at vi kun sende inn ett og ett barn dersom de var på forskjellige periodebeløp. Slik koden tolket det ble barnet som ikke ble sendt med slettet fra valutakursen siden det ikke var sendt med.
Endrer så vi samler barn med lik valutakode i samme periode før vi genererer de automatiske valutakursene. 
☝️ Alt ettersom hva leser av PRen ønsker
=> Fiks feil i oppretting av automatiske valutakurser

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/VedtakRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkController.kt
Relatert til: [NAV-21536](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21536)
Vi får feilen 
```
Argument [2024-06-16] of type [java.time.LocalDate] did not match parameter type [java.time.LocalDateTime (n/a)]
```
Dette fordi vedtaksdato er av typen `LocalDateTime` og vi forsøker å sammenligne denne med innsendt `LocalDate`. Endrer derfor dato-parameter til `LocalDateTime`.
Tidligere PR denne retter: https://github.com/navikt/familie-ba-sak/pull/4636
=> Fix: Bruke LocalDateTime som parameter fremfor LocalDate

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/ValutakursController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/main/kotlin/no/nav/familie/ba/sak/sikkerhet/TilgangService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
NAV-21578
Vi ønsker å oppdatere valutakurser i behandlingsresultatsteget når beslutter ser på behandling, slik at beslutter blir oppmerksom på om automatisk valutajustering fører til en feilutbetling som saksbehandler ikke har tatt stilling til
- Legger til endepunkt for å kunne automatisk oppdatere valutakurser og simulering som kalles når beslutter går inn på behandlingsresultatsteget
- Legger til validering i BeslutteVedtak-steg som kaster en feil dersom det er en feilutbetaling uten at det er en tilbakekreving
Funksjoner som kalles er allerede testet
=> Oppdater valutakurs for beslutter i behandlingsresultatsteg

src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkController.kt
Fordi jeg aldri lagrer tasken ned i databasen skjer det nødvendigvis heller ingenting. 
Sørger her for at vi kjører `taskRepository.save()` for den nye tasken `OpprettTaskerForVedtakEtterVedtaksdatoTask`.
Fikser: https://github.com/navikt/familie-ba-sak/pull/4645
=> Fix: Må faktisk lagre opprettet task for at noe skal skje

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingStegTest.kt
NAV-21383
Behandlinger med omregningsårsak skal ikke føre til endring i utbetaling
Løser problemet ved å kaste feil etter behandlingsresultatsteg dersom det et endring i utbetaling
✅ Checklist
Har du husket alle punktene i listen?
[x] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
[ ] Jeg har config- eller sql-endringer. I så fall, husk manuell deploy til miljø for å verifisere endringene.
[x] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇
=> Kast feil ved endret utbetaling for omregningsårsak

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatValideringUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/TilkjentYtelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtbetalingsperiodeMedBegrunnelser/UtbetalingsperiodeUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/BehandlingsGrunnlagForVedtaksperioder.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/VedtaksperiodeProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/SendVedtakTilInfotrygdTask.kt
I valideringene som sjekker at andelene ikke har endret seg tilbake i tid fra forrige behandling for måndelig valutajustering lager vi en boolsk tidslinje som returner om det er endring. Dersom det er en endring logger vi ut hvilken periode det er endring i og alle andelene for begge behandlingene. 
Forenkler slik at vi også sender med andelene som har endret seg dersom det er en uforventet endring, slik at vi kan bruke de direkte i loggene. Gjenbruker også loggefunksjonen som logger ut andelene med endring
Renamer også `tilTidslinjerPerAktørOgType`-funksjonen til `tilAndelForVedtaksperiodeTidslinjerPerAktørOgType` slik at det blir eksplisitt at den ikke lager en tidslinje av vanlige andeler
=> Forenkle valideringskode som sjekker at det ikke er noen endringer i andeler

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/Valutakurs.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursUtilTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/domeneparser/BasisDomeneParser.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/automatisk_valutajustering/utenlandsk_periodebeløp_er_0_kroner.feature
Favro: NAV-21649
Det er en saksbehandler som prøver å oppdatere valutakurser når utenlandsk periodebeløp er 0.
Normalt ville vi tenkt at vi lager automatisk valutakurser tilbake til første endring i valutakursene.
Koden vi bruker nå for å finne første endringstidspunkt ser kun på andelene.
Siden endringen i valutakursene ikke synes på andelene, påvirker det heller ikke endringstidspunktet.
Lager kode som også oppdager endringer i valutakurser når vi avgjør hvor langt tilbake i tid vi skal automatisk generere valutakurser.
=> Finn første endringstidspunkt for automatisk valutajustering

src/main/resources/db/migration/V266__drop_index_oppdrag_not_null.sql
NAV-21667
Utbetalingsoppdrag er text og skalerer ikke med indextype btree. Som gjør at task feiler fordi oppdraget er for stort til å bygge index. Så dropper index, og sjekker hvordan ytelsen blir på de tunge spørrringene, siden vi er usikker på om den faktiske indeksen gjør noe for ytelsen.
Legger evt på senere indeks av annen type hvis det likevel skulle være behov
=> Drop index drop index tilkjent_ytelse_utbetalingsoppdrag_not_null_idx

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/VedtakBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/avslag.feature
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21644
Bugen går ut på at man tar med alle barn som har begrunnelsen delvis overlappende med perioden. I prodsaken er det to vedtaksperioder av typen avslag: a) 01.06.2020 - uendelig og b) 01.12.2021 - uendelig. To av barna har avslått i tidsrom a, og ett barn i tidsrom b. Siden koden frem til nå bare har sjekket hvem som delvis overlapper med vedtaksperioden så har alle tre barna kommet med i begrunnelsen i begge periodene (fordi b er et subsett av a). 
Endrer nå til at man kun anser det som en gyldig begrunnelse for …
=> Bug: feil barn flettes inn i overlappende avslagsbegrunnelser

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/ecb/ECBService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/ecb/domene/ECBValutakursCacheRepository.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/ecb/ECBServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/ecb/ECBIntegrationTest.kt
Ved månedlig valutajustering 01.07 ble enkelte valutaer hentet fra ECB klienten og lagret til ECB cachen flere ganger.
Dette førte til at alle tasker som brukte disse valutaene feilet fordi det ikke ble returnert et unikt resultat fra cachen.
Midlertidig løsning på problemet er å hente ut valutakursene med lik valutakursdato og valutakode som en liste, og hente første valutakurs fra listen.
=> Hent liste med valutakurser fra ECB cache

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/uregistrerte_barn.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21668
Vi skal ikke inkludere uregistrerte barn ved ikke innvilget perioder. De skal bare inkluderes når begrunnelsen AVSLAG_UREGISTRERT_BARN blir brukt.
=> Tar ikke med uregistrerte barn dersom det ikke er AVSLAG_UREGISTERT_BARN

src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyService.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/begrunnelser/LagGyldigeBegrunnelserTestUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/vedtaksperioder/LagVedtaksperiodeTestUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/søknad/SøknadGrunnlagService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/BehandlingsGrunnlagForVedtaksperioder.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/VedtaksperiodeGrunnlagForPerson.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/VedtaksperiodeProdusent.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/søknad/SøknadGrunnlagServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeMedBegrunnelserStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/komponentMocks/MockSøknadGrunnlagRepository.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/avslag.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/opphør/opphør-eøs.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/opphør/opphør.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/gyldigeBegrunnelser/avslag.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/gyldigeBegrunnelser/opphør_fra_forrige_behandling.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/avslag.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/endringstidspunkt.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/enslig_mindreårig.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/filtrer_vekk_ikke_innvilgete_perioder.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/uregistrerte_barn.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/vilkår.feature
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21646
Vi ønsker ikke å regne et eksplisitt avslag på søker som et eksplisitt avslag for barnet med mindre det barnet er fremstilt krav for (= søkt for i en behandling av type søknad). Dette skapte feil i en sak hvor vi hadde ett barn (som tidligere hadde barnetrygd) som ikke var søkt for, og tre nye barn det ble søkt for. Siden barn 1 tidligere hadde barnetrygd som nå ble opphørt pga avslag på søker fikk vi veldig rare vedtaksperioder (pga endring i utbetaling siden forrige behandling). 
Til info så skal man egentlig kun …
=> Bug: ikke se på eksplisitte avslag for barn det ikke er fremstilt krav for ved vedtaksperiode-generering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/EndringsTidspunktUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/BehandlingsGrunnlagForVedtaksperioder.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/VedtaksperiodeGrunnlagForPerson.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/VedtaksperiodeProdusent.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BegrunnelseTeksterStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/valutajustering.feature
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21773
Gjør hovedsakelig to ting:
1. Sletter toggle for å ikke splitte vedtaksperioder på valutakurs da den har vært i prod i to uker og nå er testet ok av Birgitte
2. Endrer logikk sånn at endringstidspunkt fortsatt tar hensyn til endring i valutakurser (det er kun selve vedtaksperiodene som genereres som ikke skal splittes). 
Syns ikke løsningen på problem 2 her ble spesielt sexy. Men, det skal ganske mye omskriving til for å gjøre det mer lekkert så jeg kan akseptere at det ikke er top notch for øyeblikket:) tar veldig …
=> Bug: endringstidspunkt må ta hensyn til endring i valutakurs

.deploy/nais/app-prod.yaml
Mange av kallene mot Sanity feiler med `SSLHandshakeException  Remote host terminated the handshake`. Dette har vært et problem lenge og saksbehandler blir som regel ikke veldig påvirket av feilen, da den kun oppstår av og til. Kanalen baks-sentry blir derimot spammet av disse feilene, så tenker det kan være fint å gjøre noe med.
Det kan virke som at feilen oppstår på bakgrunn av en svakhet i plattformen og plattform-teamet ser på hvordan det kan løses https://nav-it.slack.com/archives/C5KUST8N6/p1719994144462539. I mellomtiden er det foreslått en midlertidig løsning hvor vi legger til Sanity sine ['customer facing IPs'](https://storage.googleapis.com/sanity-customer-facing-ips/all-ips) i `outbound.external` configen. 
Når feilen er rettet burd denne endringen reverseres.
Endringen …
=> Legger til Sanity sine 'customer facing IPs' i outbound.external

src/main/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIUtbetalingUtil.kt
Logger ut ytelsetype og endring i beløp for å få litt bedre innsikt i feil som har oppstått i omregningsbehandlinger.
=> Logging av endringer i beløp

src/main/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIUtbetalingUtil.kt
Ser ikke ut til at loggingen jeg la inn for å debugge endringer mellom nye og gamle andeler fungerer. Dukker i hvertfall ikke opp i loggene. Velger derfor å fjerne det igjen.
=> Fjerner logging av endringer mellom nye og gamle andeler

src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/VedtaksperioderOgBegrunnelserTestUtil.kt
Linjer ble separert med komma pga default behaviour til `joinToString`
=> Fiks feil i Cucumber util

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatEndringUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatEndringUtilsTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21810
Når man går fra å ikke ha andeler i en periode til å få andeler som er 0kr-andeler ønsker vi å gi resultatet "Endret" så lenge det ikke er fremstilt krav for personen. Resten av logikken for å detektere endringer for å gi "endret" som behandlingsresultat ser kun på perioder hvor det fantes noe før og det finnes noe nå - så dette er det eneste stedet hvor man ønsker å se på hvor det er lagt til eller fjernet noe. Uten denne endringen får revurderinger som har lagt til 0-kr andeler resultatet "fortsatt innvilget", men …
=> Bug: behandlingsresultat når ingen andeler til nullutbetaling

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperioderOgBegrunnelserStepDefinition.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/steg/vilkårsvurderingsteg.feature
Favro: NAV-21691
Automatiske valutaperioder skal genereres for behandlinger som er teknisk endring når saksbehandler går fra vilkårsvurderingssteget til behandlingsresultatsteget.
Det skal være mulig å overstyre dette i tekniske endringer, se [frontend-PR](https://github.com/navikt/familie-ba-sak-frontend/pull/3267)
=> Automatisk valutajustering for teknisk endring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt
Barn som er manuelt registrert i førstegangsbehandlinger blir ikke tatt med i avslagsbegrunnelse. Det er et problem dersom det kun eksisterer manuelt registrerte barn og man tar med begrunnelse for eksplisitt avslag på søker, fordi brevbegrunnelsen trenger barnas fødselsdato.
Løser problemet ved å ta med uregistrerte barn i brevbegrunnelse som er avslag på søker
=> Inkluder uregistrerte barn i brevbegrunnelse for avslag på søker

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevPeriodeProdusent/BrevPeriodeProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/endret_utbetaling.feature
Favro: NAV-21263
Forhåndsvisning av brevbegrunnelse feiler fordi `antallBarn = 0` når barn ikke har utbetaling pga allerede utbetalt i behandlinger med utvidet barnetrygd
- Forelder har krav på utvidet og har ett barn som allerede har utbetalt $\rightarrow$ inkluder barn i brevbegrunnelse
- Forelder har krav på utvidet og har ett barn med utbetaling og ett barn som allerede har utbetalt $\rightarrow$ inkluder barn med utbetaling i brevbegrunnelse
**Før**
**Etter**
=> Inkluder barn med allerede utbetalt i brevbegrunnelse og brevperiode

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/VedtaksperiodeProdusent.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/opphør_ved_lik_tom_alle_vilkår.feature
Favro: [NAV-21881](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21881)
Når alle vilkår har samme `tom`, eller `tom` faller innenfor samme år og måned, får vi ingen vedtaksperioder og saksbehandler får ikke mulighet til å begrunne hvorfor ytelsen opphører. 
Dette kommer av at logikken vår for reduksjon ikke håndterer tilfellet når `grunnlagTidslinjeForPerson` i nåværende behandling sitt grunnlag er `null` i perioden reduksjonen/opphøret inntreffer. Når vi ikke oppdager reduksjonen/opphøret og dette er den eneste endringen i behandlingen finner vi ikke noen perioder som skal begrunnes.
Fikser dette ved å spesifikt håndtere tilfellet når grunnlaget i nåværende behandling er `null`. Da sjekker jeg kun om samme periode i forrige behandling har en …
=> Fix: Oppdage reduksjon fra forrige behandling når alle vilkår har tom-dato innenfor samme år og måned

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favro: [NAV-22051](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22051)
Begrunnelse dukket ikke opp selv om den var lagt inn
Hadde lagt inn begrunnelsen i `Standardbegrunnelse` fremfor `EØSStandardbegrunnelse` og brukt `VedtakBegrunnelseType.OPPHØR` fremfor `VedtakBegrunnelse.EØS_OPPHØR`
PR retter opp dette ☝️
=> Korrigert EØS-opphørsbegrunnelse og flyttet den til rett plass

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevServiceTest.kt
Favro: NAV-22065
Ved behandlingsårsak årlig kontroll skal utbetalingstabellen vise utbetalinger tilbake i tid med fom etter disse reglene:
- Hvis det er gjort endringer tidligere enn 1. januar i fjor $\rightarrow$ Endringstidspunkt
- Hvis det er gjort endring senere enn 1. januar i fjor $\rightarrow$ Seneste av 1. januar i fjor og første utbetaling i fjor
- Hvis det ikke er gjort noen endring $\rightarrow$ Seneste av 1. januar i fjor og første utbetaling i fjor
=> Spesifiser starttidspunkt for utbetalingstabell ved årlig kontroll

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligvalutajustering/AutovedtakMånedligValutajusteringService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/MånedligValutajusteringTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligValutajustering/AutovedtakMånedligValutajusteringServiceTest.kt
Tidligere måneder har månedlig valutajustering blitt satt til manuell oppfølging for alle behandlinger som ikke har blit suksessfulle på første forsøk. Dette har oversvømt prosessering med feilede tasks.
Løser problemet ved å kaste forskjellige exception avhengig av hvordan tasken feiler:
Hvis status på åpen behandling er `IVERKSETTER_VEDTAK` eller `SATT_PÅ MASKINELL_VENT` kjøres valutajustering igjen om en time
Hvis status på åpen behandling er `FATTER_VEDTAK` kjøres valutajustering igjen klokken 6 morgenen etter
Hvis åpen behandlingen har blitt endret siste 4 timene kjøres valutajustering igjen klokken 6 morgenen etter
Månedlig valutajustering-tasker kjører 3 ganger før de settes til manuell oppfølging
=> Rekjøring av månedlig valutajustering-task

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/domene/Kompetanse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/Valutakurs.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/ValutakursService.kt
Når det lages en kopi av et `Valutakurs`-objekt skal det lages en kopi av `barnAktører`-settet, slik at det ikke eksisterer to `Valutakurs`-objekter med referanse til samme `barnAktører`-sett. Dette gjelder for `Kompetanse` også.
Legger også på `@Transactional` i metoder i `ValutakursService`, da mangel på dette gjorde debugging endel vanskeligere
=> Unngå duplikat av barnAktører i Valutakurs

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSøknadUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/domene/EndretUtbetalingAndel.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/EndretUtbetalingAndelTidslinjeService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdUtilTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValideringTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
Favro: NAV-22314 NAV-21612
Legger til årsak ETTERBETALING_3_MND for endret utbetaling.
Endrer feilmelding til å passe til etterbetaling 3 måneder i stedet for 3 år.
Feilmeldinger og funksjon som kalles fra frontend via endepunkt ligger bak [feature toggle](https://teamfamilie-unleash-web.iap.nav.cloud.nais.io/projects/default/features/familie-ba-sak.etterbetaling-3-mnd)
=> Legg til endret utbetaling-årsak ETTERBETALING_3_MND

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligvalutajustering/AutovedtakMånedligValutajusteringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/Valutakurs.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligValutajustering/AutovedtakMånedligValutajusteringServiceTest.kt
Bytter rekkefølge på validering, så MånedligValutajusteringTasks fra forrige måned kan rekjøres og hopper ut uten å feile, dersom det allerede finnes en valutakurs for gjeldende måned
Endre `erAlleValutakurserOppdaterteIMåned` til å returnere false dersom listen er tom (det eksisterer ingen valutakurser)
=> Bytt rekkefølge på validering i utførMånedligValutajustering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeHentOgPersisterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeMedBegrunnelserController.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeHentOgPersisterServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeRepositoryTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21924
Feilen oppstår på følgende hvis:
Oppstår når man har to faner oppe.
Fane 1: Vedtakssiden
Fane 2: Behandlingsresultat.
Når man går videre fra behandlingsresultat, så vil vedtaksperiodene genereres på nytt. Det vil si at fane 1 blir utdatert, og prøver man å legge til nye begrunnelser så vil det feile.  Feilmeldingen er ikke veldig beskrivende, og i tillegg skaper det støy i loggene. Kaster derfor funksjonell feil som ber saksbehandler oppdatere siden på nytt (slik at frontend kan hente nye periode id) og forsøke igjen.
Før - Skapte støy i logger:
Etter - skaper ikke støy i logger:
=> Kast funksjonell feil ved regenererte vedtaksperioder

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentService.kt
[Task som feiler](https://familie-prosessering.intern.nav.no/service/familie-ba-sak/task/1269153301)
Når vi ser etter unike fagsak-ider filtrerer vi ikke bort null. Det gjør at vi i enkelte tilfeller kaster en exception selv om det bare er én fagsak
=> fjern fagsaker som er null slik at ikke null-fagsaker gjør at vi ikke patcher identer

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/felles/beregning/JusteringAvOppdatering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/SlettKompetanserTask.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22230)
Hvis en behandling ligger inne med kompetanser som fører til at vi kaster feilmelding og så blir satt tilbake til vilkårsvurderingssteget er det ingen mulighet for å komme tilbake til behandlingsresultat og ordne opp i kompetansene funksjonelt. 
Legger til et endepunkt man kan bruke for å slette alle kompetanser på en behandling som utredes slik at man kan komme seg videre i et slikt tilfelle. I praksis vil da også alle utenlandske periodebeløp og valutakurser også slettes. 
=> legg til endepunkt for å slette alle kompetanser på en behandling som utredes

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentService.kt
dersom vi ikke skal merge ident ønsker vi ikke å hente fagsaker iom at dette kan føre til at vi kaster en feil vi ikke hadde trengt å kaste.
=> ikke hentAktuellFagsakId med mindre vi skal merge Ident

src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingStegTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperioderOgBegrunnelserStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/domeneparser/BasisDomeneParser.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/automatisk_valutajustering/ingen_endringer_fra_forrige_behandling.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/steg/vilkårsvurderingsteg.feature
I behandlinger der det ikke er noen endringer i kompetanse eller utenlandsk periodebeløp, blir valutakurser fra forrige behandling kopiert over, men andelene blir ikke oppdatert. Dette fører til at saksbehandler kan gå forbi behandlingsresultatsteget med andeler som ikke er valutajustert.
Fikser dette ved å oppdatere andeler med valutakurser på slutten av vikårsvurderingsteget.
Les commit for commit
La også til noen snacks Cucumber-funksjoner, som krevde litt refaktorering
=> Tving oppdatering av andeler i vilkårsvurderingsteget

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/utenlandskperiodebeløp/UtenlandskPeriodebeløpService.kt
Endringer i utenlandsk periodebeløp fører til at valutakurser blir oppdatert.
Dersom noe galt skjer under oppdatering av valutakurser blir utenlandsk periodebeløp slettet uten at nye perioder genereres.
Gjør oppdateringen `@Transactional` slik at alt rulles tilbake hvis noe feiler
=> Gjør oppdatering av utenlandsk periodebeløp transactional

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/task/MaskineltUnderkjennVedtakTask.kt
Favro: NAV-22580
På grunn av en bug i automatisk valutajustering, som treffer når man går inn på behandlingsresultatsiden, har en behandling blitt låst i `BESLUTTE_VEDTAK`, og kan verken godkjennes eller underkjennes av beslutter eller saksbehandler.
Lager et endepunkt som oppretter en `MaskineltUnderkjennVedtakTask`, som prøver å underkjenne vedtak, uten å ha sett på alle sidene i behandlingen. `BeslutteVedtak::utførStegOgAngiNeste` tar seg av valideringen av at behandlingen er i en tilstand det er mulig å underkjenne fra.
Ingen ny logikk innført og `BeslutteVedtak`-steg er allerede testet
=> Lag task og endepunkt for å maskinelt underkjenne vedtak

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentServiceTest.kt
Har identhendelsetasker som feiler pga constraint på aktørid. Dette kommer at vi ikke sender ikke lagre = false når vi oppretter personident
renamer lagre -> lagreNyAktør
sender lagre = false når vi kaller fra en kontekst der vi vet at det eksisterer en aktør
=> ikke lagre ny aktør når aktør allerede eksisterer for personident

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligvalutajustering/AutovedtakMånedligValutajusteringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/Valutakurs.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligValutajustering/AutovedtakMånedligValutajusteringServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/ValutakursTest.kt
Dersom det ikke eksisterer valutaer på forrige behandling er det ingen valutakurser å oppdatere, så tasken avsluttes.
=> Avbryt månedlig valutajustering dersom det ikke eksisterer valutakurser i forrige behandling

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlageService.kt
har behov for at klagebehandlinger inneholder informasjon om behandlingsårsak for behandlingen
Enslig Forsørger har behov for å markere klagebehandlinger med en behandlingsårsak. Oppdaterer derfor kontrakter og gjør det slik at dere i BAKS alltid sender inn Klagebehandlingsårsaken: Ordinær. 
Den andre årsaken som ble lagt til i kontrakter er _henvendelse fra kabal_. I dette tilfellet ønsker kabal, av ulike grunner, at våre saksbehandlere oppretter en klagebehandling og opprettholder denne slik at den sendes med til kabal. I dette tilfellet skal det ikke sendes noe brev ut mot sluttbruker.
En klagebehandling med årsak _henvendelse_fra_kabal_ vil derfor skille seg fra en ordinær klagebehandling ved at det ikke sendes ut et brev til sluttbruker.
=> Marker klagebehandlinger med klagebehandlingsårsak

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentServiceTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22663)
Vi har en del identhendelsetasker som feiler fordi vi lagrer ned aktør dobbelt. Går derfra vekk fra å lagre ned aktør to ganger i PersonidentService. 
Bruker hentFagsakerPåPerson() i stedet for hentFagsakDeltager() siden sistnevnte gjør veldig mye mer enn å bare hente fagsakene som er gjeldende for personen.
=> Fix identhendelser som feiler på dobbel lagring av aktør

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt
slik at vi ikke får problemer med unike id-er.
Vi fjernet tidligere default lagring av aktør siden vi tenkte at dette kom til å løse en bug i enkelte identhåndteringstasker. Dette viste seg å skape mer problemer for andre caser og må reverteres.
=> reverter endringer på lagring av aktør

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentServiceTest.kt
tillat patching av identer når fødselsdato endrer seg mindre enn én måned eller det er søkers fødselsdato og fagsak ikke er enslig mindreårig
Når fødselsdatoen endrer seg mindre enn én måned eller det er søkers fødselsdato som endrer seg (og det ikke er en enslig-mindreårig-sak) så vil ikke endringen i fødselsdato påvirke saken. Vi ønsker derfor å tillate automatisk patching av identer i disse tilfellene.
=> tillat patching av identer når fødselsdato endrer seg mindre enn én måned

src/main/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/TilpassArbeidsfordelingService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/TilpassArbeidsfordelingServiceTest.kt
Fikser bug i forbindelse med fødselshendelser og oppslag på enheter `NavIdent` har tilgang på. Dersom `NavIdent` er SYSTEM_FORKORTELSE feiler kall mot Axsys. Sørger her for at vi aldri gjør oppslag mot Axsys dersom `NavIdent` er SYSTEM_FORKORTELSE.
Lagt inn to enkle tester som validerer dette.
=> Fix: Sørger for at vi aldri gjør oppslag mot Axsys dersom navIdent er SYSTEM_FORKORTELSE

.github/workflows/build-pr.yml, .github/workflows/sonar.yml, pom.xml
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22720
Hensikten med endringene er analysere prosjektet med sonar med test coverage. I PRene skal man få en kommentar fra SonarCloud som sier hvilket (om noen) issue koden her, samt metrikker som test coverage og code duplications. Kommentar skal se ut som noe ala dette:
Obs! Er ingen ekspert på maven så dette er bare slik jeg har forstått det. Om noe er galt er det bare å si ifra. 😁 
Siden vi ikke benytter av oss [Maven Failsafe Plugin](https://maven.apache.org/surefire/maven-failsafe-plugin/) for å kjøre integrasjonstester vil man ikke kunne kjøre JaCoCo på standard måte. Hadde vi benyttet oss av de kunne integrasjonstestene kjørt under `pre-integration-test`, `integration-test` og …
=> NAV-22720: Legger til JaCoCo og Sonar

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseRepositoryUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelerTilkjentYtelseOgEndreteUtbetalingerService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/tidspunkt/DagTidspunkt.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/tidspunkt/MånedTidspunkt.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/tidspunkt/Tidspunkt.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeMedBegrunnelser.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/Vedtaksperiodetype.kt, src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilkjentYtelseRepositoryOppdaterTilkjentYtelseTest.kt
- Fikser warning Data class copy function to have the same visibility as constructor
Fra kotlin 2.1 så blir denne kompiler warningen en error. Endringer i copy funksjonalitet slik at copy har samme visibility som konstruktor. Det er 2 nye  annoteringer for dette. ConsistentCopyVisibility og ExposedCopyVisibility. I stedet valgte vi å skrive oss vekk fra å bruker internal constructor.
- Skjuler deprecation warnings for å hente fødselsdato fra fnr
- Sletter deprecated metode sjekkForDuplikater
- Skjuler deprecation warning for ENDRET_UTBETALING som ikke kan slettes
sikkert lettest commit for commit
=> Fikser noen compiler-warnings

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonClient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/IntegrasjonClientMock.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/ArbeidsfordelingIntegrationTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22778
Patch-endepunktet fungere ikke som tenkt i `familie-integrasjoner`. Det vil ikke nullstille `mappeId` og `tilordnetRessurs` når de er satt til `null` da koden er satt opp til å ingorere `null` felt. 
Bytter om til metoden som ble brukt tidligre for å "patch" oppgaven, men utvider det nå til å også nullstill `tilordnetRessurs` 
Nei
Hotfix for et problem, skal endres i med en gang etter merge
=> NAV-22778: Korrigerer kall til integrasjoner ved endring av behandlede enhet

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/JournalføringController.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/JournalføringControllerTest.kt
Vi har endret returtype ved henting av journalposter for bruker. I overgangen til ny type brukte vi en toggle for å bestemme om vi skulle bruke gammel eller ny type. Nå er vi helt over på den nye typen `TilgangsstyrteJournalposter` og kan trygt fjerne toggle.
Ingen nye tester da jeg bare har fjernet kode.
=> Chore: Fjerner bruk av toggle ved henting av journalposter for bruker

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22880
Når vi oppretter en ny behandling så deaktiverer vi den gamle behandlingen, og deretter sender sakstatistikk på den gamle.
Dette fører til problemer fordi ved sending av sakstatistikk så sender vi alt relatert til behandlingen.
Dette inkluderer vedtaksperioder med begrunnelser som vi kan ha slettet fra kodebasen.
Dette kan skje potensielt 1+ år etter at en begrunnelse er slettet, avhengig av når ny behandling blir opprettet.
Har tatt en prat med @stigebil og med tanke på at vi allerede har sendt over siste tilstand til behandling ved ferdigstillelse, så tenker vi at å fjerne denne kodelinjen skal gå fint.
=> Ikke send statistikk ved deaktivering av gammel behandlign

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonClient.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/IntergrasjonTjenesteTest.kt
Tar i bruk nye endepunkter for henting av journalpost og dokument. De nye endepunktene kjører tilgangskontroll dersom journalposten inneholder eller dokumentet er en digital søknad. Har ikke saksbehandler tilgang til personene i søknaden får vi en 403 - forbidden respons. Grunnen til at vi går over til dette er for å hindre at saksbehandlere som ikke har kode 6, 7 eller 19 tilgang får tilgang til å journalføre innkommende søknader.
=> Nye endepunkter for henting av journalpost og dokument

.github/workflows/sonar.yml
Når dependabot lager PR-er feiler alltid sonar-sjekken fordi dependabot ikke har tilgang til secrets.SONAR_TOKEN . Fjerner derfor sjekken for dependabot.
Burde dette vært løst på en annen måte? Mister vi noe av verdi dersom vi ikke kjører sonar-sjekkene for dependabot?
=> fjern sonar-workflow for dependabot-PRer

src/main/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/ArbeidsfordelingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelerTilkjentYtelseOgEndreteUtbetalingerService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/PersonopplysningGrunnlagForNyBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/VilkårsvurderingForNyBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingValidering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatStegTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/AndelerTilkjentYtelseOgEndreteUtbetalingerServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/PersonopplysningGrunnlagForNyBehandlingServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingValideringTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
Favro: NAV-22581
Månedlig valutajustering-tasker feiler oftere enn ønsket, som følge av for mye validering.
For satsendringer blir enkelte valideringer hoppet over, da vi heller ønsker at noen type feil skal bli korrigert i en manuell revurdering på et senere tidspunkt. Vi ønsker også dette for månedlig valutajustering, så fikser så det enkelte steder brukes satsendring sin løype i stedet for den manuelle behandlingsløypen.
Vær gjerne litt kritisk der månedlig valutajustering har fått ny løype <|:^)
=> Månedlig valutajustering skal følge satsendring sin behandlingsløype

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestJournalføring.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/InnkommendeJournalføringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/mottaker/MottakerInfo.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/RestJournalføringTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22897
Ved alle typer journalføring fra BA i dag vil vi konvertere hva enn som var avsendermottakeridtype til FNR.
Dette er feil, og ikke ønskelig når det gjelder behandle sed oppgavene.
Har avklart med Anna at for alle behandle sed oppgaver, så ønsker vi å bruke UTL_ORG.
=> Vi bruker UTL_ORG på avsendermottaker ved behandle sed oppgaver

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestJournalføring.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/InnkommendeJournalføringService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/IntegrasjonClientMock.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/Datagenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/RestJournalføringTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/IntergrasjonTjenesteTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22897
Det må sjekkes på kanal EESSI istedenfor BEH_SED når man skal se om man skal videreføre AvsenderMottakerIdType originalt på journalpost.
=> Endre fra sjekk på behandle sed til kanal EESSI

src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/RestartAvSmåbarnstilleggTest.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/autovedtak_småbarnstillegg.feature
Fikser enhetstest som feiler på grunn av ny måned. Testen tester fortsatt det den skal teste.
=> Fiks enhetstest som feiler pga ny måned

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23140
Står EØS i oppgaven, men begrunnelsen ønskes å benyttes i periode med nasjonale begrunnelser. 
Flyttes derfor.
=> Flytt eøs reduksjon begrunnelse til nasjonal

src/main/kotlin/no/nav/familie/ba/sak/common/ClockProvider.kt, src/main/kotlin/no/nav/familie/ba/sak/config/ClockProviderConfig.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/TestClockProvider.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/ClockProviderConfigTest.kt
Favro: [NAV-22995](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22995)
ClockProvider oppretter en ny instanse av Clock hver gang det kalles. Dette sikrer at sommertid/vintertid vil fungere.
Nei
=> NAV-22995: Endrer fra Clock til ClockProvider for å sikre at sommertid/vintertid fungerer korrekt

src/main/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/PensjonService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/tidsrom/Tidsrom.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/PensjonServiceIntegrationTest.kt
På løpende fagsaker operere infotrydg med til datoer som er 999999999-12 dette håndterer ikke tidslinjerammeverket når det forsøker å lage perioder med en slik dato som sluttdato.
Har lagt inn spesialhåndtering av denne datoen slik at tidsrom håndterer denne datoen
=> Håndterer infotrygd perioder med tidslinje rammeverk

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassValutakurserTilUtenlandskePeriodebeløpService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/TestClockProvider.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/TilpassValutakursTilUtenlandskePeridebeløpTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/ValutakursServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
Favro: NAV-22931
Som en følge av en tidligere bug, der saksbehandler kunne legge inn kompetanse frem i tid, er det flere behandlinger som har fått valutakurser frem i tid som saksbehandler ikke har tilgang til å endre.
Fikser problemet ved å:
- Filtrere bort valutakurser som har fom senere enn inneværende måned
- Sette `tom = null` i valutakurser som har tom lik eller senere inneværende måned
=> Filtrer bort valutakurser med fremtidig fom eller tom

src/main/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/PensjonService.kt
For noen grunner så får vi duplikate infotrygd perioder i preprod.
Tar derfor distinct før vi forsøker å gjøre om til tidslinje (som gir overlapp på perioder som er duplikate)
=> Tidslinje fiks

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/mottaker/BrevmottakerService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/mottaker/BrevmottakerValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23182
Vi har lagt på validering på brevmottakere i frontend, men dette fjerner jo ikke brevmottakerne som allerede er lagt inn feil i databasen. Legger derfor på validering på utsending av brev og iverksetting av vedtak (som jo også sender brev)
Er koden god nok? Pirk gjerne! Jeg er også usikker på om sjekken på `BeslutteVedtak.kt` er god nok. Det gir for meg og Ole Kristian mening at man kun skal kjøre valideringen når vedtaket er godkjent. Siden man skal underkjenne når brevmottakerne ikke er gyldige.
=> Validerer brevmottakere ved sending av brev og iverksetting av vedtak

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakServiceTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23401
Dersom man har en avsluttet institusjon fagsak, og man prøver å opprette ny institusjon fagsak på person med samme org nummer, så vil det kastes SQL feil i dag. Dette fordi at det ikke skal være mulig å opprette ny institusjon fagsak på person med samme org nummer, det ønskes at den avsluttede fagsaken benyttes i dag.
Sånn ser det ut:
Det er heller ønskelig å gi saksbehandler en ordentlig melding her.
Da slipper vi støy i loggene, og saksbehandler får beskjed at det allerede finnes institusjon fagsak m/ samme orgnummer på person:
Man kunne også bare returnert fagsaken, men dette skjer når SB aktivt prøver å opprette ny institusjon fagsak med samme org nummer, så tenkte det er best å …
=> Vi kaster funksjonell feil ved forsøk på å opprette ny institusjon med samme org nummer på person.

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/EØSForordningen883Hjemler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/EØSForordningen987Hjemler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/FolketrygdlovenHjemler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/ForvaltningsloverHjemler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/HjemlerKombinator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/HjemmeltekstUtleder.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/OrdinæreHjemler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/SeparasjonsavtaleStorbritanniaHjemler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/refusjonEøs/RefusjonEøsService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/domene/Vilkårsvurdering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/EØSForordningen883HjemlerKtTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/EØSForordningen987HjemlerKtTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/FolketrygdlovenHjemlerKtTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/ForvaltningsloverHjemlerKtTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/HjemlerKombinatorKtTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/HjemmeltekstUtlederTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/OrdinæreHjemlerKtTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/hjemler/SeparasjonsavtaleStorbritanniaHjemlerKtTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/refusjonEøs/RefusjonEøsServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/domene/VilkårsvurderingTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/refusjonEøs/RefusjonEøsServiceIT.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23449
Forenkler logikken ved å trekke ut hjemler i en egen pakke. Fordeler logikken ut over flere filer. Skriver enhetstester for den "nye" logikken. Den "nye" logikken skal i teorien produsere samme resultat som den forrige. Hensikten her er utelukkende å gjøre koden mer oversiktlig og lettere å teste. 
Toggle for å skru av/på refaktorert logikk slik at det kan merges uten å testes først. 
Toggle: https://teamfamilie-unleash-web.iap.nav.cloud.nais.io/projects/default/features/familie-ba-sak.bruk_omskriving_av_hjemler_i_brev
Når toggle fjernes kan man fjerne mye "gammel" kode. 
Nei
=> NAV-23449: Refaktorer logikk for hjemler til en egen pakke. Forenkler logikken og skriver enhetstester.

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/ArbeidsfordelingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/MidlertidigEnhetIAutomatiskBehandlingFeil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/TilpassArbeidsfordelingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/domene/ArbeidsfordelingPåBehandlingRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/OpprettVurderFødselshendelseKonsekvensForYtelseOppgave.kt, src/main/kotlin/no/nav/familie/ba/sak/task/dto/OpprettVurderFødselshendelseKonsekvensForYtelseOppgaveTaskDTO.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/ArbeidsfordelingServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/TilpassArbeidsfordelingServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/domene/ArbeidsfordelingPåBehandlingRepositoryTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FødselshendelseFørstegangsbehandlingTest.kt
Favro: NAV-23353
Reverserer tidligere endringer som aggressivt kastet feil hvis man ikke kan fastsette behandlende enhet. Tidligere sjekket den forrige behandling, men nå sjekker den alle tidligere behandlinger på gitt fagsak.
=> Sjekk tidligere behandlinger på fagsak ved fastsettelse av behandlene enhet

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlRestClient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/domene/PdlDødfødtBarnResponse.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/domene/PdlDødtfødtBarnResponse.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/domene/PdlHentPersonResponse.kt, src/main/resources/pdl/hentperson-med-relasjoner-og-registerinformasjon.graphql, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlGraphqlTest.kt, src/test/resources/pdl/pdlDoedfoedtBarnOkResponse.json
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23491
Dersom aktør ikke har fødselsnummer, så sjekker vi om aktør har dødfødt objektet med dato på seg.
Hvis så, så betyr det at det er et dødfødt barn, og vi ønsker å bruke datoen barnet døde som fødselsdato.
Verdikjedetester feiler grunnet:
https://github.com/navikt/familie-mock-server/pull/147
=> Vi bruker dødfødt datoen på barn dersom det finnes

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/FerdigstillBehandling.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23573
Dette oppstår fordi:
1. Ved henleggelse av en behandling så ønsker man å sette forrige vedtatte behandling til aktiv. (Dette er fordi at den settes til ikke aktiv når man lager ny behandling, men når ny behandling henlegges ønsker man å gjøre forrige vedtatte behandling tilbake til den aktive)
2. Ved oppdatering av en behandling ( i dette tilfellet, oppdaterer man gammel behandling fordi man har gjort den aktiv) så sender man ny behandlingsstilstand til dvh.
3. Ved sending av behandlingsstilstand forsøker man å hente begrunnelser brukt, og dersom det har blitt brukt eldgamle begrunnelser som nå er fjernet, så kastes det en feil.
Vi fikser dette ved å ikke sende oppdatering av …
=> Ikke send saksstatistikk ved reaktivering av gammel behandling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/ArbeidsfordelingServiceTest.kt
Behandlinger med årsak `OPPDATER_UTVIDET_KLASSEKODE` faller inn i kategorien av automatiske behandlinger med tidligere behandlinger. Altså skal vi også her bruke enhet fra tidligere behandling ulik 4863 dersom denne finnes.
=> Håndtere arbeidsfordeling i `OPPDATER_UTVIDET_KLASSEKODE`-behandlinger

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/oppdaterutvidetklassekode/AutovedtakOppdaterUtvidetKlassekodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/oppdaterutvidetklassekode/OppdaterUtvidetKlassekodeScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/oppdaterutvidetklassekode/OppdaterUtvidetKlassekodeTask.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/oppdaterutvidetklassekode/domene/OppdaterUtvidetKlassekodeKjøring.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/oppdaterutvidetklassekode/domene/OppdaterUtvidetKlassekodeKjøringRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/FerdigstillBehandling.kt, src/main/resources/db/migration/V269__status_kolonne_utvidet_klassekode_kjoring.sql, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/komponentMocks/MockOppdaterUtvidetKlassekodeKjøringRepository.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/oppdaterutvidetklassekode/domene/OppdaterUtvidetKlassekodeKjøringRepositoryTest.kt
Dersom `OppdaterUtvidetKlassekodeTask` feiler eller må vente lenge på å motta status fra oppdrag, risikerer vi at det opprettes duplikate tasker. Altså at vi får flere `opprettUtvidetKlassekodeTask` per fagsak som bruker gammel klassekode. Dette er uheldig og bør ikke skje.
Legger derfor til en `status`-kolonne i tabellen som skal fortelle om tasken er `IKKE_UTFØRT`, `UTFØRES` eller `UTFØRT`, og bruker denne kolonnen til å bestemme hvilke fagsaker vi skal opprette task for.
=> Status-kolonne i OppdaterUtvidetKlassekodeKjøring-tabell

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/gyldigeBegrunnelser/etter_endret_utbetaling_som_ikke_gjelder_søker.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23677
For begrunnelser som ikke gjelder søker og ikke gjelder allerede utbetalt så er det ikke ønskelig å inkludere alle barn.
Dette gjelder f.eks ved etterbetaling 3 mnd, der vi bare ønsker å begrunne barn som får utbetalt etter perioden.
=> Skal ikke ta med barn som ikke får utbetalt ved etter endret utbetaling periode som ikke gjelder søker og ikke er allerede utbetalt

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingValidering.kt
Vi skipper allerede denne valideringen for satsendringer og månedlige valutajusteringer. Legger nå også til at vi skipper den ved oppdatering av utvidet klassekode.
=> Skipper blandet regelverk validering for behandling med årsak OPPDATER_UTVIDET_KLASSEKODE

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingValidering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingValideringTest.kt
Hopper over validering av 18års-vilkåret når behandlingsårsak er `OPPDATER_UTVIDET_KLASSEKODE` på samme måte som får satsendringer og månedlige valutajusteringer.
=> Hopper over validering av 18års-vilkåret når behandlingsårsak er OPPDATER_UTVIDET_KLASSEKODE

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/AndelDataForOppdaterUtvidetKlassekodeBehandlingUtleder.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/AndelDataForOppdaterUtvidetKlassekodeBehandlingUtlederTest.kt
Vi splitter opp "nye"-andeler før generering av utbetalingsoppdrag. I den forbindelse må vi sette en kunstig id på den ene andelen. Tidligere satte vi id = (id til andel + antall andeler), men dette fører noen ganger til at vi får duplikate id'er. Sørger her for at vi tar i litt når vi setter id til denne kunstige andelen. Id'en brukes ikke til noe spesielt, men kan altså ikke være lik en av de andre andelene vi sender inn til generatoren.
=> Sørger for å ta i litt når vi setter id på 'fiktiv/kunstig' andel.

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/BehandlingsinformasjonUtleder.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/UtbetalingsoppdragGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/TilkjentYtelseRepository.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/BehandlingsinformasjonUtlederTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/UtbetalingsoppdragGeneratorTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/OppdragSteg.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/komponentMocks/MockTilkjentYtelseRepository.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/oppdrag/opphoerEtterOppdaterUtvidetKlassekodeBehandling.feature
Favro: [NAV-23733](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23733)
I revurderinger i fagsaker vi har kjørt `OppdaterUtvidetKlassekodeTask` for, kommer ikke saksbehandler seg videre fra vilkårsvurdering pga feilende simulering mot Oppdrag. Dette skyldes hvordan vi utleder `sisteAndelPerKjede` og at vi etter `OppdaterUtvidetKlassekodeTask` ikke lenger har ett 1-1 forhold mellom andeler og kjedeelementer for utvidet barnetrygd. 
Andelen i en utvidet barnetrygd behandling strekker seg eksempelvis fra 01.07.23 -> 01.07.33, mens det siste kjedeelementet vi faktisk sendte til Oppdrag i autovedtaket strakk seg fra 01.01.25 -> 01.07.33. Oppdrag klager da når vi forsøker å opphøre (som vi alltid gjør i simulering) på at den ikke kjenner igjen …
=> Overstyre sisteAndelPerKjede for utvidet barnetrygd dersom fagsak er over på ny klassekode

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentService.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23748
Når man forlenger frist i dag skjer følgende:
Man finner forskjellX som er dagens dato fram til ny frist.
Man plusser gammelfrist med forskjellX.
Kommer vi da i en situasjon der dagensdato er 30 desember, ny frist er 21 januar, og gammelfrist er 20 desember så vil fristen bli satt til 11 januar. (20 des + 21 dager) selvom ønsket frist er 21 jan.
=> Fiks frist feil

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassKompetanserService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/TilpassKompetanserTilRegelverkTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/TidslinjerTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
Favro: NAV-23729
I noen scenarioer blir kompetanseskjemaene generert med fremtidig tom. Dette skjer fordi tidslinjene for regelverk kan strekke seg langt frem i tid, og splittes opp i perioder som kan ha fremdtidig tom.
Løser problemet ved å beskjære tidslinjene til nåværende måned, og sette siste periode som uendelig.
=> Ikke sett fremtidig tom i skjemaer

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentServiceTest.kt
Identhendelser på en aktør hvor aktøren har en Fagsak, men ikke en behandling har blitt ignorert. Siden query for å finne fagsaker gjør en join på behandling, men man ønsker å patche aktøren selv om den kun har en behandling. Legger til logikk hvor man også søker etter fagsaker som aktøren eier. Og kombinerer resultatet av disse.
- **Endrer kotlinkodestil til 2.1**
- **Støtte for å patche ident på fagsaker som ikke har behandling**
=> Bug: Patch ident på fagsak som ikke har behandllinger

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevEøsBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/BrevbegrunnelseUtil.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/kompetanser.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/reduksjon.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/brevPerioder/selvstendig_rett.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/gyldigeBegrunnelser/kompetanser.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/gyldigeBegrunnelser/opphør_selvstendig_rett_eøs.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23732
Begrunnelser med og uten kompetanse krever feltet gjelder søker, så inkluderer derfor dette.
=> Uavhengig om barn har kompetanse eller ikke så må vi inkludere gjelder søker da det er begrunnelser som er avhengig av dette

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/gyldigeBegrunnelser/vilkår_delt_bosted.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23749
Tok en prat med Anna, og når det gjelder barn som har delt bosted, men ytelsen ikke skal deles, så er det ikke relevant å ha dem med i begrunnelsene som gjelder delt bosted.
=> Ikke inkluder barn med delt bosted som ikke skal deles i begrunnelser

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassKompetanserService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassUtenlandskePeriodebeløpTilKompetanserService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassValutakurserTilUtenlandskePeriodebeløpService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/BeskjæreTidslinje.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/utenlandskperiodebeløp/TilpassUtenlandskePeriodebeløpTilKompetanserTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/utenlandskperiodebeløp/UtenlandskPeriodebeløpServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/TilpassValutakursTilUtenlandskePeridebeløpTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/komponentMocks/MockEcbService.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/eøs/tilpass_eøs_skjema.feature
Favro: NAV-23752
Når behandlinger kopierer EØS-skjemaer fra forrige behandling, der noen av periodene har fom eller tom senere enn inneværende måned, prøver systemet å hente valutakurser med fremtidig dato.
Løser problemet ved å beskjære tidslinjene for kompetanse, utenlandsk periodebeløp og valutakurser på inneværende måned, og sette siste måned som uendelig.
=> Fjern fremtidige perioder i EØS-skjemaer

src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/AbstractVerdikjedetest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FødselshendelseHenleggelseTest.kt
Vi ser sjansen for at denne testen plukker opp noe som liten og det forenkler oppsettet av verdikjedetestene.
=> Fjerner den ene verdikjedetestene som bruker familie-ba-infotrygd

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/internal/ForvalterServiceTest.kt
Sørger for at vi filtrerer bort henlagte behandlinger når vi skal finne behandling før `OPPDATER_UTVIDET_KLASSEKODE`-behandling.
Legger også til ekstra logging for å enklere kunne feilsøke.
=> Fix for patch av utvidet barnetrygd fagsaker

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/internal/ForvalterServiceTest.kt
Ved kjøring av dry-run for korrigering av andeler ble returobjektet `AndelTilkjentYtelse` alt for stort da vi fikk med alle entiteter `AndelTilkjentYtelse` har relasjoner til. Introduserer her et eget returobjekt for kjøringen.
=> Eeget returobjekt for korrigerte AndelTilkjentYtelse

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/SendTilBeslutter.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/SendTilBeslutterTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23989
Fyller ut saksbehandler sitt navn i beskrivelsen til godkjenne vedtak-oppgaven hvis toggle er på. Dette er i dag en manuell prosess som saksbehandlerne bruker mye tid på, men som er en veldig liten fiks. Legger bak toggle så Dorota kan teste før vi prodsetter.
Nei
Syns ikke det gir mening å bruke tid på, finnes ingen eksisterende tester som tester task. Men kom med innspill om noen er uenig!
=> Feat: saksbehandlers navn i beskrivelsen til godkjenne vedtak-oppgave

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/internal/ForvalterServiceTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23968
Etter en feil i dokdist så her flere behandlinger kjørt seg ferdig, men uten å ha distibuert dokumentene. Dette endepunkt skal rette opp de feilaktige behandlingene.
=> Opprett forvalter-endepunkt for å distribuere dokumenter for ferdigstilte behandlinger

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/ForvaltningRedistribuerBrevTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/internal/ForvalterServiceTest.kt
Kjør resend brev som systembruker, slik at det ikke står utviklers navn i brevet som resendes
=> Kjør resend brev som systembruker, slik at det ikke står utviklers navn i brevet som resendes

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt
Problemer med patching av andeler. Får StaleObjectStateException ved lagring av oppdatert `TilkjentYtelse`. Klarte å gjenskape problemet lokalt og ser at `tilkjentYtelse.andelerTilkjentYtelse.remove(andel)` ikke fjernet andelen. Mest sannsynlig pga problem med `equals/hashCode`. Når vi senere la til oppdatertOgNyAndel i lista over andeler lå både gammel og ny versjon av entitet i lista og vi fikk feil. 
Erstatter her `remove()` med `removeAll{}`.
=> Fix: StaleObjectStateException ved patching av andeler 

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/internal/ForvalterServiceTest.kt
Fortsatt et problem med `StaleObjectStateException` ved lagring av endrede andeler i TilkjentYtelse. Forsøker å fjerne eksisterende og legge til 2 nye andeler fremfor å oppdatere 1 og legge til 1 ny.
=> Forsøker å opprette ny andel fremfor å oppdatere eksisterende

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/domene/PdlHentIdenterResponse.kt
Når vi ikke finner noen ident logges det ikke hva det er søkt etter. Det gjør det vanskelig å feilsøke. Legger ved logging i securelogging av tilhørende identer.
[Feil i sentry](https://sentry.gc.nav.no/organizations/nav/issues/603545/?environment=prod&project=112&query=is%3Aunresolved&referrer=issue-stream)
=> bedre logging når vi ikke finner en ident

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringService.kt
Vi har noen `OPPDATER_UTVIDET_KLASSEKODE`-behandlinger som feiler med:
```
Vi finner utbetalinger som overstiger 100%
```
Som ved satsendringer legger jeg inn at OPPDATER_UTVIDET_KLASSEKODE-behandlinger også skipper denne valideringen.
=> Skipper utbetalinger over 100 prosent validering for OPPDATER_UTVIDET_KLASSEKODE-behandlinger

src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringServiceEnhetTest.kt
Saksbehandlere opplever at de ikke får godkjent behandlinger der det er endring i utbetaling inneværende måned.
Dette skyldes en validering av at dersom det eksisterer automatiske valutakurser på behandlingen og det er en feilutbetaling, må det eksistere en tilbakekrevingssak. I tilfellene det er snakk om er ikke utbetalingen skjedd ennå, og det bør være mulig å godkjenne behandlingen med feilutbetaling, selv om det ikke eksisterer en tilbakekrevingssak.
Løser problemet ved å bare validere feilutbetalinger til og med forrige måned.
=> Ekskluder inneværende måned i validering av feilutbetaling i BeslutteVedtak-steget

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/PensjonService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/KlassifiseringKorrigerer.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/UtbetalingsoppdragGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/AutovedtakFødselshendelseService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/oppdaterutvidetklassekode/OppdaterUtvidetKlassekodeScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/oppdaterutvidetklassekode/OppdaterUtvidetKlassekodeTask.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendring.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingStegController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/SendTilBeslutter.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/sammensattKontrollsak/SammensattKontrollsakController.kt, src/main/kotlin/no/nav/familie/ba/sak/task/HentAlleIdenterTilPsysTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/KlassifiseringKorrigererTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/UtbetalingsoppdragGeneratorTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/StartSatsendringTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingStegControllerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/OppdragSteg.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/JournalførOgBehandleFørstegangssøknadNasjonalTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/TekniskEndringAvFødselshendelseTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23170
Refaktorerer FeatureToggleConfig fra klasse med companion object til enum for bedre typesikring. Fremover kan enums parses direkte i Cucumber-tester, slik at testene kan bruke enum-navnene på samme måte som i koden ellers.
Det ble lagt inn en kommentar på kortet om å fikse defaulting til true/false. Det finnes allerede funksjon i UnleashConfig.kt for å sette default verdi når isEnable() blir kalt. Om ingen verdi bli satt, blir default false - trengs det mer enn dette? 
Finnes eksisterende tester
=> Legg til enum-klasse for FeatureToggle

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/main/kotlin/no/nav/familie/ba/sak/task/FinnSakerMedFlereMigreringsbehandlingerTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/internal/ForvalterServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/FinnSakerMedFlereMigreringsbehandlingerTaskTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/sikkerhet/RolletilgangTest.kt
- **Slett forvalter-endepunkt /start-manuell-restart-av-smaabarnstillegg-jobb/skalOppretteOppgaver/{skalOppretteOppgaver}**
- **Slett forvalter-endepunkt for forenklet satsendring**
- **Slett forvalter-endpunkt /finnÅpneFagsakerMedFlereMigreringsbehandlingerOgLøpendeSakIInfotrygd/{fraÅrMåned}**
- **Slett forvalter-endepunkt finnÅpneFagsakerMedFlereMigreringsbehandlinger/{fraÅrMåned}**
=> Sletter forvalter-endepunkt som ikke har vært i bruk på en stund, som jeg tror man ikke trenger lenger

src/main/kotlin/no/nav/familie/ba/sak/task/IverksettMotOppdragTask.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
Vi hadde en forskjell mellom utbetalingsoppdraget i familie-oppdrag og utbetalingsoppdraget i tilkjent_ytelse. Dette skjedde fordi PDL var nede da man forsøkte å lage neste task. Dette skjedde etter at oppdraget var iverksatt. Da feilet tasken og når den ble rekjørt, så forsøkte den å iverksette på nytt. Dette utbetalingsoppdraget hadde forskjellig oppbygging av periodeId. Så neste revurdering på fagsaken feilet mot oppdrag
Denne oppgaven er en del av favro NAV-24177 for robustgjøring av tasken, siden man ikke trenger å gjøre kall mot PDL her.
Dette for å unngå at iverksettingstasken feiler hvis PDL er nede.
_Jeg har ikke skrevet tester …
=> Unngå kall mot PDL etter iverksetting mot oppdrag

src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagService.kt
[NAV-24208](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24208)
På lik linje som for satsendringer og månedlige valutajusteringer henter vi kun "enkel" PersonInfo for personer i behandling i `OPPDATER_UTVIDET_KLASSEKODE`-behandlinger.  
https://familie-prosessering.intern.nav.no/service/familie-ba-sak/task/1332204501
=> Henter kun enkel personInfo i OPPDATER_UTVIDET_KLASSEKODE-behandlinger.

src/main/kotlin/no/nav/familie/ba/sak/common/CollectionUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/TilpassArbeidsfordelingService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/CollectionUtilsKtTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/TilpassArbeidsfordelingServiceTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24196
Når saksbehandler kun har tilgang til enheten Vikafossen skal det være lovt å opprette behandlinger på Vikafossen enheten. Saksbehandler med Vikafossen tilgang har ofte (alltid?) kun tilgang til Vikafossen.
Har omdøpt de gamle metodene med en "Gammel" suffix. De nye metodene her omtrent lik, men endringer relatert til det som er nevnt over.
Har lagt de nye endringene bak en toggle. 
Nei
=> NAV-24196: Tillatter å sette Vikafossen hvis det er eneste tilgang saksbehandler har

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlRestClient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/domene/PdlHentPersonResponse.kt, src/main/resources/pdl/hentperson-enkel.graphql, src/main/resources/pdl/hentperson-med-relasjoner-og-registerinformasjon.graphql, src/main/resources/pdl/hentperson-navn-og-adresse.graphql, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlGraphqlTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/scenario/StubsForVerdikjedetester.kt, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForBarn.json, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForBarnMedAdressebeskyttelse.json, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForBarnMedOpphørtStatus.json, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForBarnUtenFødselsdato.json, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForDødMor.json, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForMor3Barn1Opphørt1UtenFødselsdato.json, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForMorMedTomtStatsborgerskap.json, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForMorMedUkjentStatsborgerskap.json, src/test/resources/pdl/PdlIntegrasjon/personinfoResponseForMorMedXXXStatsborgerskap.json, src/test/resources/pdl/pdlDoedfoedtBarnOkResponse.json, src/test/resources/pdl/pdlManglerFoedselResponse.json, src/test/resources/pdl/pdlMatrikkelAdresseOkResponse.json, src/test/resources/pdl/pdlMedToNavnMedIngenFraPdl.json, src/test/resources/pdl/pdlMedToNavnOgToKjonn.json, src/test/resources/pdl/pdlOkResponse.json, src/test/resources/pdl/pdlOkResponseEnkel.json, src/test/resources/pdl/pdlTomAdresseOkResponse.json, src/test/resources/pdl/pdlUkjentBostedAdresseOkResponse.json
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24082)
Ref [pdl-doc](https://pdl-docs.ansatt.nav.no/ekstern/index.html#_navn) så ønsker vi å bruke PDL som master og ikke Freg når vi får verdier fra begge. 
Velger derfor å ta med metadata, master og historisk for å kunne filtrere ut når det er flere kilder til navn/kjønn. 
[Dokumentasjon om metadata og kilder](https://pdl-docs.ansatt.nav.no/ekstern/index.html#felles)
=> prioriter navn og kjønn som kommer fra PDL og ikke Freg

src/main/kotlin/no/nav/familie/ba/sak/config/ApplicationConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/config/RestTemplateConfig.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/vedtak/VedtaksperioderOgBegrunnelserTestUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/småbarnstillegg/AutovedtakSmåbarnstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentService.kt, src/main/resources/application.yaml, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/RestTemplateTestConfig.kt
- Endret beskrivelse på hva man må gjøre for å håndtere en endring av fødselsdato for et barn ved identhendelse
- Bytter vekk fra deprikerte metodene setReadtimeout og setConnectTimout
- Fjerner warning: PostgreSQLDialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
- Fikser warning  og skrur på metadataaccess for å slippe å ha dialect
- Fikser warning med registrering av prometheus metric behandling, fordi den allerede eksisterer og er ulike keys. Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'behandling' containing tag keys [saksbehandling, smaabarnstillegg]. The meter you are attempting to register has keys [aarsak, …
=> Rydding av warnings ved bygg og oppstart og annet småsnacks

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/komposisjon/TidslinjeJoin.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/komposisjon/TidslinjeKombinator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/komposisjon/TidslinjeUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/matematikk/BigDecimalTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/matematikk/SammenliknbarTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/transformasjon/BeskjæreTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/transformasjon/EndreTid.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/transformasjon/FiltrerTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/transformasjon/MapTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/transformasjon/Zip.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/utbetaling/UtbetalingTidslinjeServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/TidslinjeKombinasjonTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/komposisjon/TidslinjeJoinTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/komposisjon/TidslinjeKombinatorTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/komposisjon/TidslinjeUtilTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/matematikk/BigDecimalTidslinjeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/matematikk/SammenliknbarTidslinjeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/transformasjon/BeskjæreTidslinjeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/transformasjon/EndreTid.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/transformasjon/FiltrerTidslinjeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/transformasjon/MapTidslinjeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/transformasjon/MånedFraMånedsskifteTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/transformasjon/ZipTidslinjeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/util/BooleanCharTidslinje.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/util/CharTidslinje.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/util/CharTidslinjeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/util/StringTidslinje.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/util/Tid.kt
Favro: NAV-23270
Vi ønsker å ta i bruk tidslinjebiblioteket fra familie-felles i ba-sak.
Starter migreringen med å importere biblioteket, og oversette hjelpefunksjonene fra det gamle tidlsinjebiblioteket til det nye.
Kopierer og oversetter testene av de gamle funksjonene, for å sjekke at funksjonaliteten er lik.
Sammenlikn gjerne nye og gamle funksjoner, for å sjekke at logikken er den samme.
=> Legg til hjelpefunksjoner for tidslinje fra familie-felles

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24302
Ved utleding av `barnSomHaddeDeltBostedIForrigePeriodeMenIkkeDenne` så må vi filtrere bort alt som ikke er BARN fra `hentPersonerMedDeltBostedIForrigePeriodeMenIkkeDenne`
=> Vi må filtrere ut søker ved sjekk av barnSomHaddeDeltBostedIForrigePeriodeMenIkkeDenne

src/main/kotlin/no/nav/familie/ba/sak/ekstern/pensjon/README.md, src/test/resources/application-dev-postgres-preprod.yaml
Bytter over til intern.dev.nav.no ingressen for familie-ba-infotrygd
=> Endrer til intern.dev.nav.no for familie-ba-infotrygd

src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagService.kt
Ingen favrokort bundet til denne - Vi rydder opp i steder der vi logger aktørId i vanlige logger.
=> Gå over til bruk av securelogger ved logging av persongrunnlag, da denne kan inneholde aktørId

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/AndelTilkjentYtelseTidslinjeUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SatsService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/Differanseberegning.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningsUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassKompetanserService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassUtenlandskePeriodebeløpTilKompetanserService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassValutakurserTilUtenlandskePeriodebeløpService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/felles/beregning/SkjemaTidslinjer.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingForskyvningUtils.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdTest.kt
Favro: NAV-23270
Fortsettelse av #5083 
Bytter ut tidslinje fra ba-sak med tidslinje fra familie-felles enkelte steder.
Holder PR'ene små, så de skal være lette å lese.
Bør leses commit for commit.
Det er noe duplikatkode, men dette vil fjernes i neste PR
=> Bytt til tidslinjebibliotek fra familie-felles

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassKompetanserService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/transformasjon/BeskjæreTidslinje.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/TilpassKompetanserTilRegelverkTest.kt
Favro: NAV-23270
Som en følge av bytte til tidslinjebibliotek fra familie-felles ble det introdusert en bug der man prøver å hente siste element i en tom liste. Dersom listen med perioder er tom returneres `tomTidslinje`.
Fjerner også kode som ikke lenger er nødvendig
=> Bug i generering av kompetanser

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/behandlingstema/BehandlingstemaService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatValideringUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/AndelTilkjentYtelseMedEndretUtbetalingGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/Differanseberegning.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassKompetanserService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassUtenlandskePeriodebeløpTilKompetanserService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/endringsabonnement/TilpassValutakurserTilUtenlandskePeriodebeløpService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsvurderingTidslinjeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/rest/RestTidslinjer.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/komposisjon/TidslinjeJoin.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/komposisjon/TidslinjeKombinator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/komposisjon/TidslinjeUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/matematikk/BigDecimalTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/transformasjon/BeskjæreTidslinje.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/transformasjon/EndreTid.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/vilkårsvurdering/VilkårsresultatMånedTidslinjeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/komposisjon/TidslinjeJoinTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/util/BooleanCharTidslinje.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/util/CharTidslinjeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinjefamiliefelles/util/StringTilTidslinje.kt
Favro: NAV-23270
Bumper tidslinje fra familie-felles og erstatter metoder i ba-sak med metoder fra familie-felles
=> Bump familie-felles

.github/dependabot.yml
Legger til gruppering av dependabotPR-er slik at det blir lettere å ha oversikt og å gjøre oppdateringer som hører sammen (f.eks. spring-boot).
=> legg til gruppering av dependabot-PRer

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/common/Feil.kt, src/main/kotlin/no/nav/familie/ba/sak/common/RessursUtils.kt
Favorkort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24416
Vi legger til nytt felt callId i Feil, som da propageres videre opp til frontend.
=> Legger til callId når vi kaster feil

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsTidslinjeService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsTidslinjeServiceTest.kt
Etter litt testing i prod oppdaget jeg at `UtbetalingsTidslinjeService` ikke håndterer opphør ved overskriving av tidligere periode.
Gitt en periode som løper fra 01.09.24 -> 01.09.35, skal en ny periode 01.09.24 -> 28.02.25 føre til at det det ikke løper noe fra og med 01.03.25.
=> Håndterer opphør gjennom overskriving av tidligere periode

Dockerfile, src/test/integrasjonstester/kotlin/DevLauncherPostgresPreprod.kt, src/test/resources/hentMiljøvariabler.sh
Fjerner busybox fra docker og skrevet om scriptet for å starte ba-sak mot preprod til å fungere uten printenv. Dette betyr at man ikke lenger kan bruke  kubectl exec for å hente ut secrets. Dette for å gjøre distroless-imaget tryggere.
I stedet for å kjøre printenv, så bruker scriptet
```kubectl -n teamfamilie get secrets```
For å finnne navn på secret og så
```
kubectl -n teamfamilie get secret navn-på-secret -o json | jq '.data | map_values(@base64d)' 
```
kubectl get secret azure-familie-ba-sak-* secreten for å hente det samme.
Utvidet skriptet til å sjekke om naisdevice og gcloud er logget inn. Hvis det ikke er det så vil det komme en melding i terminalvinduet
=> Fjerner busybox fra docker og skrevet om scriptet for å starte  ba-sak mot preprod til å fungere uten printeenv

src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingForskyvningUtilsTest.kt
Test som feiler pga månedskifte. Fikser testen som sjekker på en måned frem i tid og ikke siste dag i måneden en måned frem i tid
=> Fikser test som sjekker på en måned frem i tid og ikke siste dag i måneden

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/skyggesak/SkyggesakScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/skyggesak/SkyggesakService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/AutovedtakSatsendringScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkScheduler.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/skyggesak/SkyggesakServiceTest.kt
Tiltak for å minske antall errors når leader-sidecaren blir tatt ned før appen. Hentet fra familie-prosessering-backend, som ikke kjører nye tasker når man får SIGTERM. På samme måte sjekker man ikke leader for de Scheduled jobbene som kjører ofte det er sendt en melding om at appen stenger ned.
Også flytte noe kode fra skyggesak-scheduler til serviceklassen siden at Transactional-proxien ikke funker om det er i samme klasse.
ref: https://nav-it.slack.com/archives/C01G9BA8JKZ/p1740747402744669
=> Graceful shutdown på skyggesak, satsendring og saksstatistikkscheduler

src/test/resources/hentMiljøvariabler.sh
Fikser dev-script for å hente variabler når preprod har mer enn 1 pod kjørende
=> Fikser dev-script for å hente variabler når preprod har mer enn 1 pod kjørende

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsTidslinjeService.kt
I noen fagsaker feiler generering av utbetalingstidslinjer pga overlapp i periodeId. Legger her til litt logging for å kunne feilsøke hvorfor dette skjer.
=> Logger ut periodeId som finnes i flere kjeder samt alle utbetalingsperioder i fagsak

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24502
Vi har fått en sak i produksjon der det eksisterte feilutbetaling på brukeren når saken ble sendt til godkjenning.
Men i mellomtiden så har det feilutbetalte beløpet blitt slettet hos økonomi, også har beslutter godkjent vedtaket.
Dette fører til en ugyldig state for behandlingen, og vi ønsker å forhindre dette.
Jeg har derfor:
- Lagt til en ekstra validering når det besluttes at hvis det feilutbetalte beløpet er 0, og man har aktivt valgt å opprette en tilbakekrevingssak så skal det nå kastes en feil som ber SB1 å gå tilbake til behandlingsresultatet og gå videre.
- Fjernet kravet om at det må være månedlig valutajustering før man validerer tilbakekrevingsvalget
- Lagt til tester på …
=> Valider tilbakekrevingsvalg når det besluttes

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestTotrinnskontroll.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24574
Når vi nå sjekker om saksbehandler er på sitt vedtak så sammenligner vi displayname (Etternavn, Fornavn), med det som ligger i vedtaksbrevet som signatur (Fornavn Mellomnavn Etternavn). Denne sjekken feiler etter at vi endret signatur på vedtaksbrevet.
Jeg synes uansett at denne sjekken bør sjekke på NAVIdent istedenfor, som er mer sikkert mtp at flere kan ha samme navn. Endrer det derfor til SB ident. Tilbakemeldinger tas imot med glede! :D
FrontendPR for å sjekke på SB ID: https://github.com/navikt/familie-ba-sak-frontend/pull/3591
=> Send med saksbehandler id til frontend

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestFerdigstillOppgaveKnyttJournalpost.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestJournalføring.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/InnkommendeJournalføringService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/domene/Journalføringsbehandlingstype.kt, src/test/testdata/kotlin/no/nav/familie/ba/sak/datagenerator/JournalpostGenerator.kt
Favro: [NAV-24505](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24505)
Har behvor for å sende inn "Klage"  ved journalføring. Legger det ikke til i `BehandlingType` da klager ikke skal behandles i ba-sak, men i familie-klage. Lager derfor en egen enum som inneholder både "Klage" (og "Tilbakekreving" for senere) slik at vi kan bruke den enumen til å rute til oppretting av klagebehandlinger i familie-klage senere i løypen. 
Har kjørt opp løsningen lokalt og ser ut til å fungere fint.
Relatert PR: https://github.com/navikt/familie-ba-sak/pull/5154
Måtte også legge det til i `RestFerdigstillOppgaveKnyttJournalpost`, valgte derfor å flytte enumen `Journalføringsbehandlingstype` til `domene` pakken. 
Nei.
_Jeg …
=> NAV-24505: Legger til Journalføringsbehandlingstype til RestFerdigstillOppgaveKnyttJournalpost, flytter også enumen til domene pakken

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevPeriodeProdusent/BrevPeriodeProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/delt_bosted_og_endret_utb_ikke_alle_barn_har_utb.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24592
Nasjonal sak, revurdering. 
Bruker har to barn. For perioden som starter 01.02.25 skal det utbetales delt barnetrygd for barn født 29.08.11, og full barnetrygd for barn født 30.01.10.
Begge barna hentes inn i begrunnelsen, når egentlig bare barn 29.08.11 skal inn.
Dette fordi at det bare er andelene til barn  29.08.11 som har endret på seg siden siste periode.
Sjekker derfor at sum på andelene har endret på seg siden sist periode for å bli inkludert i begrunnelse.
Tar også en sjekk på at hvis søker har fått utbetalt delt utvidet i periode, så skal barn uavhengig av den nye sjekken jeg har lagt på bli inkludert. Dette pga at man kan bli etterbetalt utvidet, men den andelen legges på …
=> Fiks delt bosted begrunnelse ved å bare inkludere barn som har hatt en endring siden sist periode.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlageClient.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24650
Bytter til POST fra GET ved henting av personer.
Da unngår vi å måtte legge personident i header, men heller i body mtp sensitiv info i headers.
Frontend PR: https://github.com/navikt/familie-ba-sak-frontend/pull/3611
=> Legger til nye endepunkter som tar imot ident i requestbody istedenfor

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevKlient.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevmalService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentGenereringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeMedBegrunnelserController.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevmalServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceTest.kt
Kaste funksjonelle feil i stedet for Illegalstate/Feil slik at det blir mindre støy for vakt når saksbehandler bare har valgt feil begrunnelse. 
La til flere roller som funksjonelle, er det riktig? 
Testet lokalt
=> kast funksjonell feil når det er feil med brevbegrunnelser

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SatsService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SatsServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/YtelseTypeTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/util/SatserForTester.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/BehandleSmåbarnstilleggTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FødselshendelseFørstegangsbehandlingTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FødselshendelseHenleggelseTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FødselshendelseRevurderingTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/JournalførOgBehandleFørstegangssøknadNasjonalTest.kt
NAV-22043
Satt riktig sluttdato på SatsType TILLEGG_ORBA. Oppdatert kode og tester til å ta hensyn til dette.
Verden ble veldig merkelig hvor satstidspunktet ble rart mocket i kombinasjon med utvidelsen i AndelTilkjentYtelse. Som var et $%#&!! å finne ut av. Løsningen var frustrende enkel å spole frem satstidspunket til siste satsendring.
Noe jeg kan ha glemt?
=> Satt sluttdato på tilleggsorba i SatsService og skrevet tester

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/AvregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/domene/Simulering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/AvregningServiceTest.kt
Favro: NAV-22661
Vi må utlede hvilke perioder det er avregning i behandlinger. Løser dette ved å se på endringer i andeler per person og ytelsetype mellom forrige iverksatte og inneværende behandling. Avklart med fag at vi bare trenger å se på måneder til og med forrige måned.
Ettersom avregningsperiodene skal brukes i simuleringssteget, og det på en måte er en del av simuleringen, wrappes det sammen med simuleringsdataen, for å minimere hvor ofte vi trenger å utlede og hente dataen.
=> Service for å utlede avregning i behandlinger

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsTidslinjeService.kt
Favro: [NAV-24387](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24387)
Dersom man har mottatt barnetrygd av en bestemt ytelsetype (Ordinær, utvidet eller småbarnstillegg) tidligere, og deretter mistet retten til alle utbetalinger av den bestemte ytelsetypen vil vi ved generering av alle utbetalingstidslinjer for en fagsak få en tom utbetalingstidslinje for den ytelsetypen. Dette skaper nå feil ved patching av enkelte fagsaker.
Legger her inn filtrering av alle tomme utbetalingstidslinjer.
=> Fix: Fjerner tomme utbetalingstidslinjer

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/domene/EØSBegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/domene/RestUtvidetVedtaksperiodeMedBegrunnelser.kt
Favro: [NAV-24773](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24773)
Sørger for at saksbehandler kan legge til fritekst på alle begrunnelser uavhengig av type for alle revurderinger med `opprettetÅrsak` = `KLAGE`.
=> NAV-24773: Fritekst på alle begrunnelser i revurderinger med årsak klage

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlageService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlagebehandlingHenter.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/RelatertBehandling.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/RelatertBehandlingUtleder.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlageServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlagebehandlingHenterTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/RelatertBehandlingUtlederTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkServiceTest.kt, src/test/testdata/kotlin/no/nav/familie/ba/sak/datagenerator/KlageGenerator.kt
Favro: [NAV-24658](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24658)
Ønsker å sende over `relatertBehandlingId` og `relatertBehandlingFagsystem` til DVH for statistikk. `relatertBehandlingId` må kunne peke på både barnetrygdbehandlinger og klagebehandlinger. Hvis man har en behandling av type `REVURDERING` med årsak `KLAGE` eller `IVERKSETTE_VA_VEDTAK` skal man bruke den siste vedtatte klagebehandlingen. I andre tilfeller skal man bruke, om det finnes, den siste vedtatte barnetrygdbehandlingen. Den siste vedtatte barnetrygdbehandlingen må være av type `REVURDERING` eller `TEKNISK_ENDRING` for å bli tatt med som en relatert behandling. Om man har en behandling av type `REVURDERING` med årsak `KLAGE` eller `IVERKSETTE_VA_VEDTAK` og det ikke …
=> NAV-24658: Utivder logikken for relatert behandling id for å ta hensyn til klage, samt legger til relatert behandling fagsystem

src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringServiceEnhetTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24806
Vi trenger å se inkludere feilutbetaling i inneværende måned når vi validerer feilutbetaling. Saksbehandler ender opp med å få feil i valideringen når de ikke skulle det, fordi vi dropper å se på inneværende måned. Eksempel:
- SB 1 er på simulering og ser at det er feilutbetaling i inneværende måned. Må da ta stilling til tilbakekreving
- SB 2 skal godkjenne vedtak og vi skal da validere tilbakekrevingen. Nåværende validering ser kun på om det er feilutbetaling før inneværende måned, og da vil ikke tilbakekrevingsvalg og feilutbetaling stemme overens siden det kun er feilutbetaling i inneværende måned. 
Reverterer endringer gjort her i januar: …
=> Fix: validering av feilutbetaling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlageService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlagebehandlingHenter.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/RelatertBehandlingUtleder.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlageServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlagebehandlingHenterTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/RelatertBehandlingUtlederTest.kt
Favro: [NAV-24658](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24658)
Ønsker kun å se på klagebehandlinger som er vedtatt før behandlingen ble opprettet.  
Eksempel:
Klage 2: - Kl. 12.02
Revurdering Klage - Kl. 12.01
Klage 1 - Kl. 12:00  <-- Velg denne når man sender inne revurdering klage behandlingen
Nei
=> NAV-24658: Henter ut forrige vedtatte klagebehandling basert på innsendt behandling

pom.xml, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/standardbegrunnelser-ingen-utbetaling-tomme-perioder-mellom-oppfylte.feature
Favro: [NAV-24606](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24606)
I noen tilfeller får ikke saksbehandler mulighet til å velge begrunnelser for vedtaksperioder av typen `INGEN_UTBETALING`/`OPPHØR`. Dette kan skje når det er "hull" i vilkår-resultatene mellom oppfylte perioder. Altså at man har "hull" fremfor en "ikke-oppfylt"-periode.
Feilen skyldes en bug i metoden `trim()` i tidslinje-biblioteket vårt som i noen tilfeller fjernet litt flere perioder enn bare de i hver ende av tidslinja. [Bugfix](https://github.com/navikt/familie-felles/pull/874)
Legger her inn en test som gjenskaper problemet og bumper `familie-felles` for å få med bug-fix som fikser problemet.
=> NAV-24606: Vedtaksperioder med `INGEN_UTBETALING`/`OPPHØR` skal også kunne begrunnes

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestFagsak.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24831
Siste del av oppgaven. Fjerner tilbakekrevingsbehandlinger fra minimal fagsak nå som dette hentes fra eget endepunkt i stedet. Fjerner også tilbakekrevingsbehandlinger fra RestFagsak-objektet som kun brukes i baks-mottak og der er ikke tilbakekrevingsbehandlinger typet opp en gang. Egentlig virker det helt tullete å ha både et RestFagsak og RestMinimalFagsak-objekt da RestFagsak kun brukes i baks-mottak og eneste grunnen til at man ikke kan bytte over til RestMinimalFagsak er fordi behandlingene på fagsaken ikke inneholder steg-property på RestMinimalFagsak... dette er noe vi kan se på senere kanskje? Hadde vært litt spennende å se om vi kunne ha beholdt kun RestMinimalFagsak og da …
=> Tilbake: fjern tilbakekrevingsbehandlinger fra minimal fagsak og rest fagsak

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValideringService.kt
Det er en iverksettMotOppdrag-task som feilet for valutajustering. Etter samtale med Anna så skipper man sjekken for mer enn 100% utbetaling for valutajustering. Slik man gjør med blant annet satsendring
=> Skipper validering av mer enn 100% utbetalinger for månedlig valutajustering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentServiceTest.kt
Fikk inn en identhendelse på en fagsak hvor barnet hadde endret fødselsdato. Saken var gammel og barnet var blitt voksen. Lagt til funksjonalitet for å skippe disse casene
=> Tillater patching av ident hvis gammel og ny fødselsdato begge er over 18

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/VedtakBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/hentBegrunnelser/HentEØSStandardBegrunnelser.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/hentBegrunnelser/HentStandardBegrunnelser.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringUtilTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/YtelseTypeTest.kt
Mange fødselshendelsetasker feiler nå pga satsendring. Buggen kommer av at vi får feil satstype når vi prøver å kontrollere at andelene har riktig satstype. 
Dette oppstår siden andelene ikke splittes opp på sluttdatoen for tilleggsorba og dermed i prinsippet har både tillegsorba og orba samtidig. 
tilSatstype() tar når høyde for sluttdatoen på tilleggsorba og gir dermed begge satstypene når det kan være begge. 
=> Ta høyde for at perioder kan overlappe sluttdato for TILLEGGS_ORBA og satsendring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentServiceTest.kt
NAV-24914
Vi har hatt en sjekk ved patching av fagsaker på at det er kun 1 fagsak og de casene som har mer enn 1 har måtte blitt tatt manuelt. Nå har vi patchet flere titalls manuelt og er ganske sikre på at patchescriptet fungere selv om ident finnes på flere fagsaker.
Så denne PR fjerner denne begrensningen og lar de automatisk patches.
https://github.com/navikt/familie-ks-sak/pull/1226
=> Tillatt patching av identer som finnes på flere fagsaker så lenge fødesldato er riktig på alle fagsakene

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestVisningBehandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingHentOgPersisterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Visningsbehandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestVisningBehandlingTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingHentOgPersisterServiceEnhetstest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingHentOgPersisterServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/VisningsbehandlingTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingHentOgPersisterServiceIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingServiceIntegrationTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakServiceIntegrationTest.kt, src/test/testdata/kotlin/no/nav/familie/ba/sak/datagenerator/BehandlingGenerator.kt
Favro: [NAV-24909](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24909)
Har lyst til å hente ut barnetrygdbehandlinger fra et eget endepunkt når vi ser på react-query. Introduserer dermed dette endepunkt for å muliggjøre det.
Valgte å introdusere en egen klasse `Visningsbehandling` slik at `BehandlingHentOgPersisterService` ikke trenger å bruke `RestVisningBehandling`. Tanken er at man kan holde domene-laget og api-laget litt adskilt, syns det ble ryddigst slik. `Visningsbehandling` inneholder `vedtaksdato` som ikke et standard `behandling`-objekt gjør. 
Relatert frontend PR: https://github.com/navikt/familie-ba-sak-frontend/pull/3663
Nei
Droppet tester på controller da …
=> NAV-24909: Legger til endepunkt for å hente ut barnetrygdbehandlinger

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/ForenkletTilbakekrevingsvedtakBrev.kt
Favro: NAV-24929
Saksbehandler skal fylle inn en fritekst som skal legges til i brevet for `ForenkletTilbakekrevingsvedtakBrev`. Brevet var laget med et flettefelt `forenkletTilbakekrevingsvedtakTekst`, men endrer måten det sendes til familie-brev så det er likere fritekstfelter i andre brev
=> Endre hvordan fritekst blir sendt med i ForenkletTilbakekrevingsvedtakBrev

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentUtils.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentServiceTest.kt
Favro: NAV-24918
Frist skal være 14 dager, ikke 5 dager
=> Endre frist for å vente på samtykke for ulovfestet motregning til 14 dager

src/main/kotlin/no/nav/familie/ba/sak/statistikk/producer/KafkaProducer.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkTest.kt
NAV-24912
Alle meldinger som sendes på kafka i forbindelse med saksstatistikk mellomlagres til en tabell. Det er en scheduled jobb som henter alle meldinger som ikke er sendt og sender de. Raden i tabellen fikk satt sendt_tid og ble liggende til noen™ gadd å manuelt rydd vekk melding
Grunnen til at det er en mellomlagringstabell er at man ønsket å sende de i riktig rekkefølge, og kun sende meldinger på fagsaker og behandlinger som faktisk var committet til basen. Tasker kan ikke garantere rekkefølgen. Samtidig var det nyttig i oppstarten med muligheten til å kunne patche gamle meldinger og da trengte man orginalen.
Det var 2 måter å løse denne på. En med å slette alle meldinger eldre enn en valgt dato med en scheduled jobb,  Den andre er å slette meldingen med engang den er sendt. Tenker …
=> Slett melding fra saksstatistikk_mellomlagring etter at den er sendt

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevPeriodeProdusent/BrevPeriodeProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/delt_bosted_og_endret_utb_ikke_alle_barn_har_utb.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24783
Når søker får etterbetalt delt utvidet barnetrygd så ønskes vi at barna flettes inn i begrunnelsene som omhandler delt bosted. Dette er i scenarier når den eneste nye andelen er den utvidet andelen.
Vi har derfor hatt en sjekk på `søkerFårUtbetaltDeltUtvidetIPeriode`.
Problemet med dette er at dette slipper ALLE barn gjennom også i perioder der vi bare ønsker å inkludere et barn som faktisk har hatt overgang fra eller til delt bosted. Dette fører til bug i favrokortet der flere enn det påvirkede barnet blir trukket inn i begrunnelsen.
Jeg justerer derfor kravet `søkerFårUtbetaltDeltUtvidetIPeriode ` til å bli at det må ha vært en forskjell på delt utvidet i forrige periode vs denne …
=> Fikser delt bosted begrunnelse ved overgang til delt bosted med utbetaling av utvidet

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/BehandlingsinformasjonUtleder.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/EndretMigreringsdatoUtleder.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/EndretMigreringsdatoUtlederTest.kt
En satsendring stoppet iverksetting med Ny migreringsdato pluss 1 mnd kan ikke være etter første fom i forrige behandling. Etter samtale med Anna så ble vi enige om å ikke stoppe iverksetting av disse for Satsendring
=> Skipper sjekk av Ny migreringsdato pluss 1 mnd kan ikke være etter første fom i forrige behandling for satsendringer

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SatsService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringUtilTest.kt
NAV-24907
Saker som alt har ny sats pga revurdering, ble plukket ut til satsendring siden sjekken om siste sats også hadde med TILLEGGS_ORBA som en gyldig sats. Som førte til at sjekken sa at den ikke hadde oppdatert sats. Så filtrerer bort alle satser som ikke er aktive og sjekker kun på disse.
Omstrukturert testene litt. Hver satsstype har fått sin egen test for de vanligste testene. Har lagt på parametisert test for over og under 6 år. Slettet en del dupliserte tester.
=> Filterer bort TILLEGGS_ORBA som gyldig sats ved sjekk om man skal kjøre satsendring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeHentOgPersisterService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeMedBegrunnelserController.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeHentOgPersisterServiceTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24988
Vi ønsker å kaste funksjonell feil når det forsøkes å generere perioder + legge til fritekst på perioder som plutselig ikke lenger finnes. Dette kommer mest sannsynlig av saksbehandler har 2 faner, eller det er 2 saksbehandlere som jobber på samme behandling.
=> Kast funksjonell feil dersom det ikke finnes vedtaksperioder med gitt ID i behandlingen

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/personident/HåndterNyIdentServiceTest.kt
Tydligere beskjed om hva man må gjøre hvis en aktør endrer ident og fødselsdato. Fagressurser får ikke oppdatert saken før man har patchet identen.
Selve tasken vil nå få melding:
```
Fødselsdato er forskjellig fra forrige behandling. 
Ny fødselsdato 2024-01-23, forrige fødselsdato 2024-04-23
Fagsak: 1 
Du MÅ først patche fnr med PatchMergetIdentTask og etterpå sende saken til en fagressurs.
Info om gammel og nytt fnr finner man i loggmelding med level WARN i securelogs.
Se https://github.com/navikt/familie/blob/main/doc/ba-sak/manuellt-patche-akt%C3%B8r-sak.md#manuell-patching-av-akt%C3%B8r-for-en-behandling for mer info.
```
securelogs:
=> Tydligere feilmelding om hva man trenger å gjøre for en identhendelse med endring i fødselsdato

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/InnkommendeJournalføringServiceV2.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/InnkommendeJournalføringServiceV2Test.kt
Favro: [NAV-24943](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24943)
Etter en prat med Anna kom vi fram til at vi alltid skal opprette en fagsak på bruker.id når det journalføres. 
Nei
=> NAV-24943: Oppretter alltid fagsak ved journalføring

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/InnkommendeJournalføringServiceV2.kt
Favro: [NAV-25025](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25025)
Tidligere sendte man med informasjon fra requesten når man opprettet fagsaker, se gammel kode her:
Ved tilknytning ble ikke type og institusjon brukt. 
Har nå lagt det til ved journalføring. 
Nei
=> NAV-25025: Setter korrekt type og institusjon for fagsak ved oppretting via journalføring

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/avslag.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25022
Ved avslag på søker og det finnes barn framstilt krav for, så skal bare barnet som det framstilles krav for trekkes inn i avslagsbegrunnnelsen. Hvis det er ikke framstilt krav for noen barn, trekkes alle med som før.
=> Fiks at avslagsbegrunnelser bare skal ta med seg personer fremstilt krav for hvis det finnes

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24701
NFP skal innføre ny felles rutine for refusjon EØS, og i den anledning ber de om at vi endrer tekst i periodevisningen, til beløp per måned. Det er fordi NØS vil ha beløp oppgitt per måned i den manuelle oppgaven som sendes via Gosys.
Teksten var opprinnelig satt opp som månedsbeløp. Dette ble endret når vi innførte automatisk valutajustering, fordi det ville medføre at saksbehandler må legge inn veldig mange perioder i skjema siden beløpet endrer seg for hver måned. Dette mener NFP ikke lenger blir et problem, og ønsker derfor at dette endres tilbake.
NFP venter med å lansere den nye rutinen til vi har lagt inn endringen i systemet.
=> Endre refusjoneøs tekst til å vise per mnd

src/main/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlageService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlageServiceTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24892)
Klagebehandlinger skal ha enhet tilhørende saksbehandleren som opprettet klagen i stedet for enheten med geografisk tilknytning til saken. 
Henter ut saksbehandler her og finner enhet via familie-integrasjoner. 
Har testet i dev, føler tester gir lite verdi siden vi praksis bare mocker ut svarene vi vil teste.
=> Sett enhet på klagebehandling til saksbehandler sin enhet

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/tilbakekrevingsvedtakmotregning/TilbakekrevingsvedtakMotregningBrevService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/tilbakekrevingsvedtakmotregning/TilbakekrevingsvedtakMotregningServiceTest.kt
Favro: NAV-22552
Legger til validering på at fritekstfelter er utfylt før brevet genereres
=> Tilbakekrevingsvedtak motregning validering

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursService.kt, src/main/kotlin/no/nav/familie/ba/sak/sikkerhet/SaksbehandlerContext.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/valutakurs/AutomatiskOppdaterValutakursServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/sikkerhet/SaksbehandlerContextTest.kt
Fjerner disse to togglene:
familie-ba-sak.behandling.valutajustering_dato
amilie-ba-sak.bruk-ny-saksbehandler-navn-format-i-signatur
=> Fjern gamle toggles

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevServiceTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25099
Ved avregningsperioder der fom == tom så ønsker vi at det listes ut i brevet som f.eks "januar 2025"og ikke "januar 2025 til januar 2025" som det er i dag.
=> Vi justerer på hvordan periodene blir beskrevet i tilbakekrevingsvedtak_motregning

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/EndretMigreringsdatoUtleder.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/EndretMigreringsdatoUtlederTest.kt
Legger til feilmelding for saksbehandler så de skjønner at det er migreringsdato som er feil i fagsaken og ikke prøver å gjennomføre behandling mange ganger. 
Har fått inn en del feil fordi saksbehandler prøver å klikke seg gjennom en behandling som har feil migreringsdato i fagsak. Legger til en feilmelding som forklarer problemet.
=> Feilmelding på migreringsdato

src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepositoryTest.kt
Refactor test setup to use DatabaseCleanupService
Replaced manual repository deletions with a call to `databaseCleanupService.truncate()` for cleaner and more maintainable test setup. This improves consistency and reduces duplication in test initialization.
=> Refactor test setup to use DatabaseCleanupService.

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestUtvidetBehandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/UtvidetBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/tilbakekrevingsvedtakmotregning/TilbakekrevingsvedtakMotregningController.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/tilbakekrevingsvedtakmotregning/TilbakekrevingsvedtakMotregningControllerTest.kt
Grunnet hvordan ting er satt opp i frontend og backend, så ser vi det som en bedre løsning å returnere hele behandlingen ved oppdatering og sletting av tilbakekrevingsvedtak motregning.
Dette fordi at det blir mye ekstra kall for å holde ting i sync hvis vi bare får tilbake tilbakekrevingsvedtaket.
=> Vi returnerer behandøingrespons ved oppdatering og sletting av tilbakekrevingsvedtak motregning

src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/Logg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/tilbakekrevingsvedtakmotregning/TilbakekrevingsvedtakMotregningService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/tilbakekrevingsvedtakmotregning/TilbakekrevingsvedtakMotregningServiceTest.kt
Favro: NAV-25099
Endrer logging relatert til ulovfestet motregning slik at:
- teksten er endret til _Ulovfestet motregning er benyttet/angret_
- logg om at ulovfestet motregning er benyttet opprettes når `samtykke` blir oppdatert til `true`
- logg om at ulovfestet motregning er angret opprettes når et `TilbakekrevingsvedtakMotregning` der `samtykke` er `true` slettes
=> Endre når logg for ulovfestet motregning blir oppdatert

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/TilbakestillBehandlingTilSimuleringService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/tilbakekrevingsvedtakmotregning/TilbakekrevingsvedtakMotregningService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/tilbakekrevingsvedtakmotregning/TilbakekrevingsvedtakMotregningServiceTest.kt
Favro: NAV-25099
Når `heleBeløpetSkalKrevesTilbake`oppdateres, ønsker vi å tilbakestille behandlingen til simuleringssteget, slik at man ikke havner i en uønsket state i frontend
=> Tilbakestill behandling til simuleringsteg når heleBeløpetSkalKrevesTilbake oppdateres

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/JournalførVedtaksbrev.kt, src/main/kotlin/no/nav/familie/ba/sak/task/JournalførTilbakekrevingsvedtakMotregningBrevTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/JournalførVedtaksbrevTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/JournalførTilbakekrevingsvedtakMotregningBrevTaskTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperioderOgBegrunnelserStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/komponentMocks/MockTilbakekrevingsvedtakMotregningRepository.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25099
Tidligere så forsøkte vi å gjenbruke JournalførVedtaksbrev steget til å også journalføre våre tilbakekrevingsvedtak ved motregning brev. Men dette viser seg til å ikke fungere helt optimalt fordi:
- Først journalførte man vedtaksbrevet, og deretter tilbakekrevingsvedtaket. Men hvis journalføring av tilbakekrevingsvedtaket feiler, så sliter vi da det ikke finnes noe mekanismer per i dag for å journalføre den alene.
- For å kunne journalføre tilbakekrevingsvedtaket så er man avhengig av at den ordinære vedtaksbrevet blir journalført OK.
- Ved opprettelse av tasken for å distribuere vedtaket ble alltid førstegangsvedtak brevmalen valgt
- Gitt flere brevmottakere som igjen gir flere …
=> Splitter ut journalføring av tilbakekrevingsvedtak ved motregning til egen task

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/SendTilBeslutter.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/tilbakekrevingsvedtakmotregning/TilbakekrevingsvedtakMotregning.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/SendTilBeslutterTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/tilbakekrevingsvedtakmotregning/TilbakekrevingsvedtakMotregningServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
Favro: NAV-25099
Sånn koden er nå er vi avhengig av at saksbehandler og beslutter forhåndsviser vedtaksbrevet for at det skal bli generert, men vi trenger at brevet blir generert uavhengig av om de ser på det eller ikke.
- Legger til validering på at `TilbakekrevingsvedtakMotregning` er riktig utfylt i `SendTilBeslutter::preValiderSteg`
- Legger til generering av brev i `SendTilBeslutter::utførStegOgAngiNeste`
- Legger til generering av brev i `BeslutteVedtak::utførStegOgAngiNeste`
=> Generering av PDF for tilbakekrevingsvedtak ved motregning

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevPerioder/endret_utbetaling.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25122
Når det legges på en endret utbetaling andel på et barn, og det dannes et nytt vedtaksperiode samtidig, så ønsker vi at begrunnelsene som gjelder endret utbetaling bare fletter inn barnet og ikke andre barn.
Det er noen tilfeller vi ønsker det motsatte, som er derfor denne sjekken legges til i slutten av when løkka.
=> Vi fikser flettingen av barn i endret utbetaling begrunnelser

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/hentBegrunnelser/HentStandardBegrunnelser.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtaksperiodeProdusent/IEndretUtbetalingAndelForVedtaksperiode.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/gyldigeBegrunnelser/etter_endret_utbetaling.feature
Favrokort:  https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25092
I denne barnetrygd saken har vedkommende og familien kommet til norge.
Måneden etter er de innvilget barnetrygd, men pga etterbetaling 3 måneder regelen så får de ikke utbetalt de første 3 månedene de skulle ha betaling for.
Det opprettes derfor 2 vedtaksperioder, en for den første perioden de ikke får utbetaling, og en for perioden etter.
Det er ønskelig å benytte innvilgelse begrunnelser på den siste perioden, men det er ikke mulig.
Dette er fordi at når vilkår blir utgjørende, forventer vi at man skal begrunne dem i samme periode (i dette tilfellet, i den første perioden). 
Jeg har derfor justert på koden slik at hvis man i den forrige perioden hadde endret utbetaling andeler som …
=> Fiks gyldige begrunnelser ved perioder etter endret utbetaling

.github/workflows/build-pr.yaml, .github/workflows/sonar.yaml, pom.xml
NAV-24974
Øker minne maven kan bruke på GHA for å se om det hjelper jacoco som dør. ubuntu-latest skal ha 7GB tilgjengelig og ubuntu-latest-4-cores har 16GB. 
Øker maven.artifact.threads fra default 5 til 10 tråder for å sjekke om ting går litt raskere.
=> Øker minne i Maven på GHA

src/main/kotlin/no/nav/familie/ba/sak/ekstern/bisys/BisysService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/ekstern/bisys/BisysServiceTest.kt
Bidrag kaller oss noen ganger med NPID. Da har man ikke aktiv fødselsnummer og dermed trigges det en alarm. Legger inn en sjekk om aktiv fødselsnummer og heller returnerer en tom liste hvis dette ikke finnes. Da slipper vi og Bidrag å få feil ved kun NPID ident. Dette fordi vi har ikke saker med NPID.
=> Sjekker at ident har aktiv fødselsnummer før man sjekker perioder for Bisys, slik at man ikke trigger alarm til vakta

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/vedtaksperioder/endret_utbetaling.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25174
Når vi får fletter inn barn ved endret utbetaling begrunnelser må vi validere at de faktisk har hatt en endring i endret utbetaling i den perioden. Vi kjører derfor `hentPersonerSomHarHattEndringIEndretUtbetalingAndelIDennePerioden` og filtrer bort de som ikke har hatt endring .Men dersom en endret utbetaling begrunnelse blir brukt, og det er ingen som har hatt endring, så dropper vi filtreringen.
=> Legg til default case ved ingen personer ved fletting av endret utbetaling

src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/komponentMocks/MockUnleashService.kt
I noen cucumber-tester kalles `isEnabled()` med default-verdi. Dette var ikke støttet i `MockUnleashService`, og noen få cucumber-tester feilet. Legger her inn støtte for default verdi i `isEnabled`.
=> Fikser feilende cucumber-tester

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonClient.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/BarnetrygdEnhet.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/IntegrasjonClientMock.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonClientTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/TilpassArbeidsfordelingServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlageServiceTest.kt, src/test/resources/familieintegrasjoner/json/enheterNavIdentHarTilgangTilResponse.json
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25115
Den 01.10.2025 så legges Axsys ned.
Per i dag bruker vi Axsys til å sjekke om en saksbehandler har tilgang til en enhet før vi eventuelt setter saksbehandleren som tilordnet ressurs i oppgaven som vi oppretter, f.eks BehandleSak oppgaver når behandlinger opprettes.
Ref https://nav-it.slack.com/archives/CDKEM1HC5/p1726835363824219 så har det kommet azure grupper som erstatter axsys:
0000-GA-TEMA_XXX (f.eks. 0000-GA-TEMA_PEN)
0000-GA-ENHET_XXXX (f.eks. 0000-GA-ENHET_4803)
Alle saksbehandlere som hadde fått tilgang gjennom Axsys til enhet 4803 skal nå tilhøre gruppen 0000-GA-ENHET_4803.
Jeg har lagt til et endepunkt i familie-integrasjoner som henter alle grupper til en saksbehandler. …
=> Bruk Azure AD ved sjekk av enhet sb har tilgang til

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/opphør/opphør-etter-endret-utbetaling.feature, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/opphør/opphør-eøs.feature
Favro: [NAV-24917](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24917)
Barn som har fått barnerygden stanset fra en tidligere dato pga `EndretUtbetalingAndel` dukker allikevel opp i etterfølgende vedtaksperiode med opphør. Vi ønsker kun å inkludere de barna som faktisk blir opphørt i vedtaksperioden og ikke de barna som allerede var opphørt.
Legger her inn logikk for å filtrere ut de barna som har `AndelTilkjentYtelse` i forrige vedtaksperiode med `kalkulertUtbetalingsbeløp` 0 kr i opphørs-vedtaksperioder.
=> NAV-24917: Filtrerer bort barn som ikke har utbetaling i forrige vedtaksperiode pga endret utbetaling ved opphør

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VurderTilbakekrevingSteg.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/VurderTilbakekrevingStegTest.kt
Favro: NAV-25282
Fjerner validering relatert til avregning som ikke skal brukes lenger etter at løypen for motregning er ferdig
=> Fjern kode relatert til avregning som ikke skal brukes

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/opphør/opphør-eøs.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25293
Vanligvis ønsker man ikke flette inn barn som har null utbetaling dersom man skal begrunne opphør for andre barn.
Men dersom det ikke er noen andre barn enn det barnet som har nullutbetaling, må vi flette inn det barnet.
Legges til som en liten ekstra fallback etter endringer her: https://github.com/navikt/familie-ba-sak/pull/5334
=> Trekk_inn_barn_med_nullutbetaling_hvis_det_ikke_er_noen_andre

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/AutomatiskRegistrerSøknadService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/søknad/SøknadService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/søknad/SøknadServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/søknad/SøknadGrunnlagTest.kt
Favro: NAV-25246
Legger til funksjonalitet for å automatisk gjennomføre `RegistrereSøknad`-steget, ved å hente søknaden som er knyttet til behandlingen fra `familie-integrasjoner`, og lage `RestRegistrerSøknad` med data fra søknaden. Legger all funksjonaliteten i en `try/catch`, slik at dersom et kall feiler / søknadsreferansen ikke finnes, feiler ikke hele tasken, men søknaden må registreres manuelt av saksbehandler.
=> Automatisk registrering av søknad

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/EØSStandardbegrunnelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseType.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/Vedtaksperiodetype.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25387
Når vi la inn støtte for at endret utbetaling begrunnelser også kunne trekke inn eøs flettefelter, valgte vi å gjenbruke VedtakBegrunnelseTypen endret utbetaling. Dette hadde uante konsekvenser grunnet følgende kode:
```
fun hentVilkårsbegrunnelser(): Map<VedtakBegrunnelseType, List<RestVedtakBegrunnelseTilknyttetVilkår>> =
standardbegrunnelserTilNedtrekksmenytekster(sanityService.hentSanityBegrunnelser(filtrerBortBegrunnelserSomIkkeErIBruk = true)) +
eøsStandardbegrunnelserTilNedtrekksmenytekster(sanityService.hentSanityEØSBegrunnelser(filtrerBortBegrunnelserSomIkkeErIBruk = true))
```
Problemet er at dersom endret utbetaling typen finnes i begge mapper som nøkkel, så vil de …
=> Legg til begrunnelse type eøs endret utbetaling

src/main/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/domene/ArbeidsfordelingPåBehandlingRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingStegController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevmalService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/HenleggBehandling.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/HenleggÅrsakTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepositoryTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25451
Per nå bruker vi BehandlingResultat.HENLAGT_AUTOMATISK_FØDSELSHENDELSE, til og med på småbarnstillegg som er feil. Vi legger til BehandlingResultat.HENLAGT_AUTOMATISK_SMÅBARNSTILLEGG, da dette er ønsket.
=> Legger til HENLAGT_AUTOMATISK_SMÅBARNSTILLEGG

src/main/kotlin/no/nav/familie/ba/sak/sikkerhet/TilgangService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/sikkerhet/TilgangServiceTest.kt
- **Sørger for at man tar med søkers ident i sjekk for tilgangskontroll for fagsak av typen skjermet_barn**
Tilgangskontroll for barn funker ut av boksen ved fagsaktype SKJERMET_BARN, siden man sjekker tilgangen til fagsaken basert på aktøren på fagsaken. Det samme for behandling. Det er derimot en liten case som ikke var dekket. Det er i de tilfeller hvor: 
- det er en fagsak av type SKJERMET_BARN,
- barnet ikke lenger er kode 6/19
- søker er kode 6/19
- Det er ikke opprettet persongrunnlag for søker og barn siden det ikke er opprettet en behandling
=> Utvidelse av tilgangskontroll for fagsak til å ta med søker for skjermet barn"

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/UtvidetBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/AutomatiskRegistrerSøknadService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/søknad/SøknadGrunnlagTest.kt
Favro: NAV-25246
Inkluder barn med adressebeskyttelse i søknadsgrunnlaget.
Legger også til filtrering av barn når søknadsgrunnlaget hentes til frontend, slik at saksbehandlere uten tilgang til diskresjonskode ikke får opp barn med diskresjonskode
=> Barn med adressebeskyttelse i automatisk registrering av søknad

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlRestClient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PersonopplysningerService.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/domene/PdlHentIdenterResponse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/AbstractMockkSpringRunner.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/FakePdlIdentRestClient.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/MockPdlIdentRestClient.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakServiceIntegrationTest.kt
Bedre støtte for NPID. 
- Hvis man henter inn relasjoner for en ident. Som man blant annet gjør ved søk og oppretting så feilet mappingen hvis det er en ident med kun NPID. Lagt til funksjonalitet for å filtrere bort denne identen
Utvidet MockPdlIdentRestClient til å fungere som en fake, slik at man kan gi den verdier man ønsker å få tilbake. I stedet for en hardkodet returnverdi
Dette fikser taskene i NAV-25447
=> filtrer bort identer som ikke har aktiv fødselsnummer ved søk og mapping av relasjoner

src/main/kotlin/no/nav/familie/ba/sak/ekstern/EksternKlageController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlageService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/klage/KlageServiceTest.kt
Favro: [NAV-25500](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25500)
Fjerner endepunkt som ikke er i bruk lengre. Erstatte av [dette](https://github.com/navikt/familie-ba-sak/blob/main/src/main/kotlin/no/nav/familie/ba/sak/ekstern/EksternKlageController.kt#L74) endepunktet.
Nei
Ikke relevant.
=> NAV-25500: Fjerner deprecated kode for oppretting av revurdering klage.

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/AndelTilkjentYtelseMedEndretUtbetalingGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseGenerator.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/Differanseberegning.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningsUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilpassDifferanseberegningService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/AndelTilkjentYtelseMedEndretUtbetalingGeneratorTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregnAndelerTilkjentYtelseMedGjeldendeSatserTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseGeneratorTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtilsEndretUtbetalingAndelTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdUtilTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/VilkårTilTilkjentYtelseTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningSøkersYtelserTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningsUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilkjentYtelseDifferanseberegningTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/DeltBostedBuilder.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/util/VilkårVurderingBuilder.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt
Favro: NAV-25575
Sletter toggle som har vært skrudd på i prod lenge.
Sletter også `slåSammenEtterfølgende0krAndelerPgaSammeEndretAndel` med tilhørende tester, da den ikke lenger er i bruk
=> Slett toggle

src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/domene/EndretUtbetalingAndel.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValideringTest.kt
Favro: NAV-25546
For andre årsaker enn `ENDRE_MOTTAKER` skal saksbehandler få en feilmelding dersom til og med-dato ikke er satt
=> Kast feil hvis til og med-dato er tom for andre årsaker enn ENDRE_MOTTAKER

src/main/kotlin/no/nav/familie/ba/sak/kjerne/minside/MinsideAktiveringKafkaProducer.kt
Vi logger nå `personIdent` med vanlig logger når vi sender aktivering/deaktivering-melding av minside-mikrofrontend. Dette må fikses asap. Heldigvis har vi ikke skrudd på kafka-integrasjon for prod enda, og `personIdent` har blitt sensurert i dev, men endrer her uansett vanlig logger til secureLogger.
=> Fix: Bruke secureLogger for å logge personIdent ved aktivering/deaktivering av minside-mikrofrontend

src/main/kotlin/no/nav/familie/ba/sak/kjerne/minside/MinsideAktiveringKafkaProducer.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/minside/MinsideAktiveringService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/minside/MinsideAktiveringKafkaProducerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/minside/MinsideAktiveringServiceTest.kt
Meldingene vi sendte til Kafka for aktivering av minside har ingen effekt. Etter å ha vært i kontakt med minside-teamet har vi funnet ut at det skyldes at meldingene ikke har noen key. Legger her til key på aktivering/deaktivering-meldinger.
Velger å bruke `aktørId` som key da den ikke er sensitiv og aldri vil endre seg for en person. Dette vil sørge for at alle meldinger som gjelder personen vil havne i samme partisjon. Har fått bekreftet at topicen ikke slår sammen meldinger med samme key (compaction).
=> Fix: Legger til aktørId som key på aktivering/deaktivering-meldinger for minside

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevBegrunnelseProdusent.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/brevBegrunnelser/opphør/opphør-eøs.feature
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25573
I denne pullrequesten https://github.com/navikt/familie-ba-sak/pull/5334, ble det innført ekskludering av barn som ikke har utbetaling i forrige vedtaksperiode pga endret utbetaling ved opphør begrunnelser.
Det mangler en sjekk på endret utbetaling, som fører til at i begrunnelser uten endret utbetaling også får barna ekskludert.
Fikser det + legger til test som sjekker at saken i produksjon er løst.
=> Fiks EØS opphør begrunnelse

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/SøknadDTO.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/AutomatiskRegistrerSøknadService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/søknad/SøknadGrunnlagTest.kt
Favro: NAV-25346
Lagre i `SøknadDTO` om søknaden er automatisk registrert. Default til `false`, slik at eksisterende `SøknadDTO`'er uten feltet satt blir `false`
=> Lagre i SøknadDTO om søknaden ble automatisk registrert

.nais/app-dev.yaml, .nais/app-prod.yaml, src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/minside/HentMinSideBarnetrygdDto.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/minside/MinSideBarnetrygd.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/minside/MinSideBarnetrygdController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/minside/MinSideBarnetrygdService.kt, src/main/resources/application-preprod.yaml, src/main/resources/application-prod.yaml, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/minside/HentMinSideBarnetrygdDtoTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/minside/MinSideBarnetrygdServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/minside/MinSideBarnetrygdControllerTest.kt
Favro: [NAV-24639](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24639)
Introduserer endepunkt for å hente ut informasjon om barnetrygden til den innloggede brukere fra min-side. Bruker `tokenx` og henter fnr fra tokenet. 
Nei
=> NAV-24639: Legger til MinSide endepunkt

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/preutfylling/PreutfyllVilkårService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/preutfylling/PreutfyllBosattIRiketServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/preutfylling/PreutfyllLovligOppholdServiceTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25673)
På grunn av utdypende vilkårsvurdering må vi sperre for EØS-saker igjen, da dette er komplisert å preutfylle og vi ønsker ikke å fokusere på dette nå.
=> Sperre preutfylling for EØS-saker

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/AvregningService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/domene/Simulering.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/config/SamhandlerTestConfig.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/AvregningServiceTest.kt
NAV-17161
Utvidelse av simulering. Den inneholder nå et nytt felt:
overlappendePerioderMedAndreFagsaker
I dette feltet vil det vises overlappende perioder for fagsaker hvor barnet er eier av fagsaken. Altså Institusjon, enslig mindreårig og skjermet barn.
Dette feltet er tenkt til å brukes der man må varsle saksbehandler om at det er andre fagsaker som alt har utbetaling i en periode i den behandlingen de jobber med.
Dette fordi i en sak som f.eks. INSTITUSJON. Der kan et barn flytte fra en institusjon til en annen institusjon. Disse fagsakene kan da ha overlappende perioder. Simulering vil da vise data fra begge fagsakene og utbetaling i den ene kan motregnes mot den andre (inntil utbetaling fikser sin bug). Ved å varsel så blir det lettere for en saksbehandler å se at her må noe gjøres …
=> Legger til overlappendePerioderMedAndreFagsaker til simulering

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakServiceIntegrationTest.kt
NAV-25615
Journalføringsløypa for institusjon funker slik at man må først opprette institusjonsfagsak. Så knytter man journalposten til denne fagsaken. 
Inne i kallet for journalførings så kalles hentEllerOpprettFagsak. Den skulle returnert den eksisterende fagsaken, men der hadde det kommet på en unødvedig funksjonell feil hvis det fantes en fagsak. 
Fikset det samme for skjermet barn
=> Opprett fagsak skal returnere eksisterende fagsak ved oppretting for institusjon eller skjermet barn

src/main/kotlin/no/nav/familie/ba/sak/task/FerdigstillBehandlingTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/FerdigstillLagVedtakOppgaver.kt, src/main/kotlin/no/nav/familie/ba/sak/task/IverksettMotOppdragTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/JournalførVedtaksbrevTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/PubliserVedtakV2Task.kt, src/main/kotlin/no/nav/familie/ba/sak/task/SendMeldingTilBisysTask.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25742
BehandlingId er mer riktig enn behandlingsId, i tillegg så slipper vi å enable linking i familie-prossessering-frontend for begge når vi fikser dette.
=> Behandlingsid til behandlingId fiks

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/preutfylling/PreutfyllLovligOppholdService.kt
Verdien er satt til 01.01.0000 for å ikke brekke validering mot Aareg (som kun støtter tilbake til år -4713), samtidig som at det er så langt tilbake i tid at det ikke ødelegger for noen funksjonelle krav. Hacky, og kan fint håndteres med bedre feilhåndtering, men det krever en forståelse av hva som er ønsket funksjonalitet som jeg ikke har.
=> Sett fallback verdi: LocalDate.MIN -> 01.01.0000 hvis dato for bosted er null

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligvalutajustering/AutovedtakMånedligValutajusteringService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/månedligValutajustering/AutovedtakMånedligValutajusteringServiceTest.kt
Øker tiden det tar før en månedlig valutajustering rekjøres fra én til tre dager, og øker dermed tiden før den settes til manuell oppfølging fra tre til ni virkedager.
=> Rekjøring av månedlig valutajustering ved status FATTER_VEDTAK

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/ekstern/klage/EksternKlageController.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/ekstern/EksternKlageControllerTest.kt
Favro: [NAV-25324](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25324)
Legger til endepunktet `fagsak/{fagsakId}/tilgang` i `EksternKlageController`, som sjekker om saksbehandler har tilgang til fagsak med id = `fagsakId` og returnerer et `FagsakTilgang`-objekt med info om saksbehandler har tilgang eller ikke.
Dette legges til for å sikre at saksbehandlere som har tilgang til en fagsak i `ba-sak` også skal ha tilgang til tilknyttet klage-behandling i `familie-klage`. Når en saksbehandler forsøker å åpne en klage-behandling kalles dette nye endepunktet, og responsen avgjør om saksbehandler får tilgang eller ikke.
=> NAV-25324: Nytt endepunkt i `EksternKlageController`for å kunne sjekke om saksbehandler har tilgang til fagsak

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/preutfylling/PreutfyllLovligOppholdService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/preutfylling/PreutfyllLovligOppholdServiceTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25551) 
Fjerner erBosattINorgeTidslinje da man ikke trenger å ha bostedsadresse i Norge for Lovlig opphold. Legger til beskjæring på eldste barn om bostedadresse ikke finnes.
=> Refaktorer preutfylling lovlig opphold

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/task/PorteføljejusteringTask.kt
Favro: [NAV-25881](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25881)
For å få en oversikt over alle åpne oppgaver tilordnet enhet 4817 - Steinkjær, legger jeg her til et forvalter-endepunkt som oppretter tasken `PorteføljejusteringTask`. Tasken henter alle åpne oppgaver tilordnet enhet 4817 og deretter kategoriserer og teller opp disse. Da kan vi se hvilke oppgavetyper og hvor mange oppgaver som er tilknyttet hvert fagsystem, samt hvilke oppgavetyper og hvor mange oppgaver som ikke er tilknyttet et fagsystem. 
Da får vi en oversikt som denne:
```
{
"OppgaveMedSaksreferanse": {
"familie-ba-sak": {
"BEH_SAK": 202,
"GOD_VED": 2,
"VURD_LIVS": 12,
"BEH_UND_VED": 1
},
"behandlesAvApplikasjonIkkeSatt": {
"BEH_SED": 21,
"VURD_LIVS": 99,
"FREM": 1, …
```
=> NAV-25881: Skaffe oversikt over åpne oppgaver for Steinkjær

src/main/kotlin/no/nav/familie/ba/sak/task/PorteføljejusteringTask.kt
Fikser feil hvor vi forsøker å konvertere et map til JSON og map inneholder null-keys.
`message=Null key for a Map not allowed in JSON `
=> Fix: Sørger for at ingen keys er null før vi kjører writeValueAsString

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/VilkårsvurderingForNyBehandlingUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårResultatUtils.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FødselshendelseFørstegangsbehandlingTest.kt
Bruk minByOrNull i stedet for maxBy for å finne eldste dato
Kun kutt fomdato til eldste barns fødselsdato på søker sine vilkår
To fødselshendelsetasker som feiler i prod fordi det er født tvillinger på hver sin side av midnatt ved månedsskifte. Feilen skyldes at vi kutter fom-datoer ved autogenerering av vilkår på eldste barns fødselsdato, MEN når vi finner eldste barns fødselsdato har vi egentlig funnet yngste barns fordi vi har brukt maxBy og ikke minBy. 
Endret også til å kun kutte søker sine vilkår siden det er mer lettleselig. Man unngår å bli forvirret av om >= på datoer betyr nyere eller eldre dato.
=> BUG: Fomdato på vilkårresultat

.nais/app-prod.yaml
`pgaudit.log_rows` er visstnok ikke støttet i GCP og hindrer også `pgaudit.log_parameter` i å bli skrudd på. Fjerner derfor flagget.
Slack: https://nav-it.slack.com/archives/C5KUST8N6/p1755166322544729
=> Fjerner flagget log_rows

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/domene/VilkårResultat.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperiodeUtil.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/VedtaksperioderOgBegrunnelserStepDefinition.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/domeneparser/AdresseParser.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/domeneparser/VedtaksperiodeMedBegrunnelserParser.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/komponentMocks/MockAutovedtakFinnmarkstilleggService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/komponentMocks/MockFagsakService.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/komponentMocks/MockSystemOnlyPdlRestClient.kt, src/test/resources/no/nav/familie/ba/sak/cucumber/finnmarkstillegg/finnmarkstillegg.feature
Favro: NAV-25926
Legger til funksjoner i Cucumber-riggen for å kunne:
- legge til bostedskommune for aktører
- kjøre autovedtak Finnmarkstillegg
- sjekke om vilkårresultater på en behandling er som forventet
Legger også med en enkel test for å sjekke om de nye testfunksjonene funker, og noe småplukk som ble avdekket under kjøring av test
=> Legg til støtte i Cucumber for autovedtak Finnmarkstillegg

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggBegrunnelseService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggBegrunnelseUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggBegrunnelseServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggBegrunnelseUtilTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/komponentMocks/MockAutovedtakFinnmarkstilleggService.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543
Når vi kjører gjennom en finnmarkstillegg sak, og det skal iverksettes, ønsker vi å sende ut et vedtaksbrev til bruker.
Dette brevet må inneholde vedtaksperioder med begrunnelser om innvilgelse eller reduksjon, avhengig av hva slags finnmarkstillegg andel som er gitt eller fjernet.
=> Automatisk begrunn vedtaksperioder i finnmarkstillegg saker

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt
Dersom resultat av behandling med årsak `FINNMARKSTILLEGG` er `FORTSATT_INNVILGET` eller `FORTSATT_OPPHØRT`, skal det ikke sendes brev
=> Ikke send brev hvis resultat av finnmarkstilleggbehandling er FORTSATT_INNVILGET eller FORTSATT_OPPHØRT

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatEndringUtils.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatEndringUtilsTest.kt
Når vi utleder endringsresultat for finnmarkstillegg må vi ekskludere endringer i vilkårsvurderingen, slik at endringsresultat blir `INGEN_ENDRING`
=> Ekskluder endringer i vilkårsvurdering når endringsresultat utledes for finnmarkstillegg

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/preutfylling/PreutfyllLovligOppholdService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/preutfylling/PreutfyllLovligOppholdServiceTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25552) 
Oppholdstillatelse kan ha tom dato, men om det er siste periode ønsker vi at den skal være løpende, så i de tilfellene settes tom til null
=> siste periode på oppholdstillatelse skal settes til null

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlRestClient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/domene/PdlGeografiskTilknytningResponse.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardstillegg/FinnPersonerSomBorIFinnmarkNordTromsEllerPåSvalbardTask.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/bostedsadresse/BostedsadresserOgDelteBosteder.kt, src/main/resources/pdl/geografisk-tilknytning.graphql
Favro: NAV-25970
I tillegg til å hente personer med bostedsadresse/delt bosted i Finnmark/Nord-Troms eller oppholdsadresse på Svalbard, ønsker vi å sjekke hvor mange personer med D-nummer som har geografisk tilknytning til Svalbard
=> Hent ut geografisk tilknytning for personer med D-nummer i task som henter personer i Finnmark/Nord-Troms/Svalbard

pom.xml, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt
Forvalterendepunkt som henter alle institusjoner på løpende fagsaker og sjekker om de er i finnmark. Dette fordi man ønsker en oversikt over omfanget av institusjoner som kvalifiserer for Finnmarkstillegget
Tar i bruk utvidelsen av kontrakten i
https://github.com/navikt/familie-integrasjoner/pull/1153
=> Forvalterendepunkt som henter alle institusjoner på løpende fagsaker og sjekker om de er i finnmark

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt
Favro: NAV-25970
Uthenting av personer per behandling brukte altfor mye minne, så poden klarte ikke å håndtere det.
Flytter derfor joining av behandlinger med persongrunnlag inn i en egen spørring, som returnerer personidenter.
Forhåpentligvis bruker dette lite nok minne til at systemet kan håndtere det.
Spørringen bruker ~1 min 40 sek.
Ta gjerne en ekstra titt på at spørringen gir mening
=> Lag spørring for å hente identer i løpende fagsaker

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/domene/PdlGeografiskTilknytningResponse.kt, src/main/resources/pdl/geografisk-tilknytning.graphql
Variabelnavn i spørring mot PDL og i DTO er forskjellige.
Endrer så begge heter `geografiskTilknytning`.
Gjør også feltet nullable.
=> Fiks navn på felt fra PDL

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt
Taskene må rekjøres med minst 1 min mellomrom, så legger til et endepunkt for å trigge rekjøring
=> Lag endepunkt for å rekjøre feilede tasker av typen finnPersonerSomBorIFinnmarkNordTromsEllerPåSvalbardTask

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt
Favro: NAV-25970
Pod'en hadde ikke nok minne, så reduserer det ved å bare hente ut fagsak-id'en i stedet for hele fagsaken
Legger også på mer logging
=> Hent ut id for alle løpende fagsaker i stedet for hele fagsaken

src/main/kotlin/no/nav/familie/ba/sak/task/MånedligValutajusteringTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/SendAutobrevPgaAlderTask.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/MånedligValutajusteringTaskTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/task/SendAutobrevPgaAlderTaskTest.kt
NAV-25979
- **Ignorerer autobrev-task som er for gammel og som likevel bare må avvikhåndteres**
- **Ignorerer månedlig valutajustering som er gammel og som likevel bare må avvikhåndteres**
- **Øker maks antall feil på valutajustering, slik at det tar lengre tid før task kommer i manuell feilhåndtering. F.eks ved totrinnskontroll**
=> Rekjøring av gamle tasker for Autobrev og Valutajustering ender ikke med en task i manuell oppfølging

src/main/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIEndretUtbetalingAndelUtil.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatEndringUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/forrigebehandling/EndringIEndretUtbetalingAndelUtilTest.kt, src/test/testdata/kotlin/no/nav/familie/ba/sak/datagenerator/EndretUtbetalingGenerator.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26086
Nå som vi autogenerer endret utbetaling andeler og setter søknadstidspunkt, så vil man alltid få "ENDRET" i nye behandlinger, fordi søknadstidspunktet blir oppdatert.
Dette trigger en endring i behandlingsresultatet, noe som er feil.
Endrer på logikken slik at det bare trigger en endring, dersom det ikke var satt fra før i en periode.
Dette kan skje dersom fom/tom blir justert.
=> Ikke marker det som en endring hvis søknadstidspunkt i endret utbetaling andel har blitt justert og det fantes fra før

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StatusFraOppdrag.kt, src/main/kotlin/no/nav/familie/ba/sak/task/IverksettMotOppdragTask.kt, src/main/kotlin/no/nav/familie/ba/sak/task/dto/StatusFraOppdragDTO.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/HentStatusTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/Utils.kt, src/test/testdata/kotlin/no/nav/familie/ba/sak/kjørbehandling/KjørStegprosessForBehandlingGenerator.kt
AktørId-feltet i StatusFraOppdragDTO blir ikke brukt til noe og kan fjernes nå som det ikke er noen tasker som har feltet satt lenger.
=> fjern aktørId-felt i StatusFraOppdragDTO.kt som ikke blir brukt til noe

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardstillegg/FinnPersonerSomBorPåSvalbardIFagsakerTask.kt
Favro: NAV-25970
Fagansvarlige trenger å vite hvor mange personer som har D-nummer i de forskjellige Svalbard-fagsakene
=> Finn personer som har D-nummer i Svalbard-fagsaker

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdGenerator.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdUtilTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26088
Denne feilmeldingen kastes når man har satt rett til utvidet en periode, men ikke får noen utvidet andeler i perioden.
Etter diskusjon med Anna forbedrer vi på feilmeldingen som kastes slik at det er klart at det er utvidet barnetrygd det gjelder, da SB kan ha misforstått at man ikke har rett til noe barnetrygd i det hele tatt.
=> Vi forbedrer feilmelding ved ingen rett til utvidet barnetrygd

src/main/kotlin/no/nav/familie/ba/sak/common/Feil.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/AutovedtakStegService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggTask.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrerPersongrunnlag.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrerPersongrunnlagEnhetTest.kt
Favro: NAV-26129
Autovedtak Finnmarkstillegg opprettes ved adresseendringer i PDL. Dersom behandlingen ikke har noen endringer i vilkårsvurderingen, vet vi at forrige behandling var oppdatert med siste adresser for alle personer, og ønsker ikke å fullføre behandlingen.
- Legger til ny exception-klasse `FinnmarkstilleggIngenEndringFeil`
- Legger til validering på at `Bosatt i riket`-vilkåret er endret i postvalideringen i `Registrere persongrunnlag`-steget, som kaster `FinnmarkstilleggIngenEndringFeil`
- Legger til `@Transactional(propagation = Propagation.REQUIRES_NEW)` på `AutovedtakStegService::kjørBehandlingFinnmarkstillegg`, slik at "snike i køen"-logikken også rulles tilbake hvis det kastes en feil.
- Kjører autovedtak Finnmarkstillegg inni en `try/catch`, som bare catcher …
=> Rull Finnmarkstillegg-behandling tilbake hvis 'Bosatt i riket'-vilkår ikke er endret

src/main/kotlin/no/nav/familie/ba/sak/kjerne/minside/MinsideAktiveringKafkaProducer.kt, src/main/kotlin/no/nav/familie/ba/sak/statistikk/producer/KafkaProducer.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/minside/MinsideAktiveringKafkaProducerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/minside/MinsideAktiveringServiceTest.kt, src/test/resources/application-dev-postgres-preprod.yaml, src/test/resources/logback-devlauncher.xml
- **Lagt til bryter på sending av kafkameldinger på minside, slik at den ikke forsøker å sende i utviklingsmiljø**
I DevLauncherPostgresPreprod er kafka skrudd av for at loggene ikke skal spammes ned med feil i sending av kafka eller at man må starte opp kafka lokalt. Siden dette er det kommet en ny kafkaproducer, om ikke har denne bryteren. Denne commiten legger til tilsvarende funksjonalitet som KafkaProducer. MinsideAktiveringKafkaProducer er trukket ut som interface. Hvis property funksjonsbrytere.kafka.producer.enabled=true så brukes Kafka, mens hvis false så logges kun meldingen
- **Skrur på infologging på DevLauncherPostgresPreprod**
Etter at test-loggene ble satt til WARN, så ble de også skrudd av for lokal utvikling. 
_Jeg har ikke skrevet …
=> Ikke default prøv å sende kafkameldinger for min side i DevLauncherPostgresPreprod

src/main/kotlin/no/nav/familie/ba/sak/common/RessursUtils.kt
Idag logges kun feilemeldingen til `FunksjonellFeil` når den kastes, men i noen tilfeller er det nyttig å kunne se selve stacktracen for å kunne debugge rare feil.
Sørger her for at stacktrace også logges når `FunksjonellFeil` kastes.
=> Sørger for at vi får stacktrace når vi kaster FunksjonellFeil

src/main/kotlin/no/nav/familie/ba/sak/common/TekstSaniteringUtil.kt, src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestJournalføring.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/common/TekstSaniteringUtilTest.kt
Favro: [NAV-26265](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26265)
Mellomrom og understrek kan forekomme i avsender ident ved journalføring og dette var tidligere ikke støttet.
Legger her inn støtte for det.
=> Utvider validering av avsender ident ved journalføring

src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/AutovedtakSvalbardtilleggScheduler.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/AutovedtakSvalbardtilleggTaskOppretter.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/FinnPersonerSomBorIFinnmarkNordTromsEllerPåSvalbardTask.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/FinnPersonerSomBorPåSvalbardIFagsakerTask.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/domene/SvalbardtilleggKjøring.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/domene/SvalbardtilleggKjøringRepository.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/AutovedtakSvalbardtilleggSchedulerTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/AutovedtakSvalbardtilleggTaskOppretterTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/domene/SvalbardtilleggKjøringRepositoryTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepositoryTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26201
Omdøper pakkenavn fra "svalbardstillegg" til "svalbardtillegg" (uten en ekstra "s")
Nei
Ikke relevant.
=> NAV-26201: Omdøper pakkenavn fra "svalbardstillegg" til "svalbardtillegg" (uten en ekstra "s")

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/Differanseberegning.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/DifferanseberegningsUtilsTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/differanseberegning/TilkjentYtelseDifferanseberegningTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25814
Ved differanseberegning ønsker vi først å trekke fra finnmarkstillegget før vi trekker ordinær andel, og så utvidet.
Eksempler
Uten differanseberegning:
Med differanseberegning på 200kr, finnmarkstillegg trekkes først:
Med differanseberegning på  500kr, finnmarkstillegget trekkes helt, men ordinær ikke påvirket
Med differanseberegning på 2000kr, finnmarkstillegget trekkes helt, og resten av ordinær
Med differanseberegning på 3000kr, finnmarkstillegget trekkes helt, ordinær trekkes helt, resten av utvidet
=> Vi differanseberegner finnmarkstillegget før vi differanseberegner ordinær andel

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/brevBegrunnelseProdusent/BrevEøsBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/ErGjeldendeForReduksjonFraForrigeBehandling.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/FinnBegrunnelseGrunnlagPerPerson.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/HentResultaterForPeriode.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/SkalFiltreresPåHendelser.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/TemaerForBegrunnelser.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/VedtakBegrunnelseProdusent.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/hentBegrunnelser/HentAvslagsBegrunnelserPerPerson.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/hentBegrunnelser/HentEØSStandardBegrunnelser.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/vedtakBegrunnelseProdusent/hentBegrunnelser/HentStandardBegrunnelser.kt, src/test/resources/cucumber/finnmarkstillegg/reduksjon-finnmarkstillegg.feature
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26271)
Når det blir reduksjon i finnmarkstillegg fordi søker flyttet ut fra landet får vi ikke opp riktig begrunnelse.
Dette skyldes at det ikke er noen andeler på søker og vi ser på andelene for personen for å utlede om det er reduksjon.
Sender med en variabel som ser om det er reduksjon på finnmarkstillegg som sendes med når vi utleder reduksjon.
OBS! Har også refaktorisert VedtakBegrunnelseProdusent og trukket ut noen av de større metodene i egne filer i et forsøk på å gjøre filen litt kortere og mer lesbar. 
ANBEFALER DERFOR Å LESE COMMIT FOR COMMIT! 
Tar gjerne input på om noe av refaktoriseringen burde sett annerledes ut eller lignende. Eventuelt forslag til mappestrukturer. Scopet ned …
=> Reduksjon finnmarkstillegg søker

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatSteg.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatStegTest.kt
Favro: NAV-26279
Legger til validering på behandlingsresultatsteget for svalbardbehandlinger.
Legger ikke `validerAtDetIkkeFinnesDeltBostedForBarnSomIkkeBorMedSøkerIFinnmark`, da dette ikke er relevant for Svalbardbehandlinger.
=> Legg til validering av svalbardtillegg

src/main/kotlin/no/nav/familie/ba/sak/config/featureToggle/FeatureToggle.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/OppdaterTilkjentYtelseService.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterController.kt, src/main/kotlin/no/nav/familie/ba/sak/internal/ForvalterService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/cucumber/mock/CucumberMock.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/utbetalingsoppdrag/OppdaterTilkjentYtelseServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/internal/ForvalterServiceTest.kt
Favro: [NAV-26278](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26278)
Sonar varsler om "Cognitive Complexity" for metoden `finnOgPatchAndelerTilkjentYtelseIFagsakerMedAvvik`. Denne ble brukt i forbindelse med avvik i konsistensavstemming i februar-mars 2025. Den har ikke vært i bruk siden da.
Sletter metoden og tilhørende kode fremfor å forbedre den da den ikke er i bruk. Kan legges inn igjen senere dersom vi ser behov for det.
=> NAV-26278: Fjerner forvalter funksjonalitet for å kunne korrigere andeler med feil offset

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/VilkårsvurderingForNyBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/preutfylling/PreutfyllVilkårService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/VilkårsvurderingForNyBehandlingServiceTest.kt
Navneendring, og fjern sjekk av togglen `PREUTFYLLING_VILKÅR` for preutfyll bosatt i riket for Finnmark og Svalbardstillegg behandlinger. Det er en egen sjekk `erFinnmarksTilleggEllerSvalbardtillegg()` i `VilkårsvurderingForNyBehandlingService` for behandlingen. Og det finnes en egen sjekk for toggle `SKAL_PREUTFYLLE_BOSATT_I_RIKET_I_FØDSELSHENDELSER`.
Ikke nødvendig?
=> Toggle for preutfyll bosatt i riket for Finnmarks- og Svalbardstillegg

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/VilkårsvurderingForNyBehandlingService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/preutfylling/PreutfyllBosattIRiketService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/preutfylling/PreutfyllVilkårService.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/AutovedtakSvalbardtilleggServiceTest.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/grunnlagForNyBehandling/VilkårsvurderingForNyBehandlingServiceTest.kt, src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceIntegrationTest.kt, src/test/resources/cucumber/finnmarkstillegg/finnmarkstillegg.feature, src/test/testdata/kotlin/no/nav/familie/ba/sak/datagenerator/VilkårsvurderingGenerator.kt
Favro: NAV-26374
For å unngå at Finnmarks- og Svalbardtilleggbehandlinger gjør endringer på 'Bosatt i riket'-vilkåret langt bakover i tid, som er irrelevante for tilleggene, men som kan føre til endringer ordinære/utvidet andeler, setter vi en cut off på preutfyllingen fra og med september 2025.
Splitter også inngangen til `PreutfyllBosattIRiketService` for finnmarks- og svalbardtilleggbehandlinger og fødselshendelsebehandlinger i to funksjoner
Cut off'en i preutfyllingen blir i praksis testet i de endrede Cucumber-testene
=> Sett cut off på preutfylling av bosatt i riket-vilkåret for finnmarks- og svalbardtilleggbehandlinger

src/main/kotlin/no/nav/familie/ba/sak/task/SendMeldingTilBisysTask.kt
Etter at vi utvidet listen over behandlingsresultater i tasken `SendMeldingTilBisysTask`, vurderer vi nå sending av Kafka-meldinger for flere behandlinger enn tidligere. Nå vil vi også vurdere utsending av Kafka-melding for behandlinger som ikke har noen forrige behandling, og dette fører til at tasken feiler.
Skriver derfor om logikken slik at vi ikke feiler dersom det ikke finnes noen tidligere behandling.
=> Fix: SendMeldingTilBisysTask feiler i alle tilfeller hvor det ikke finnes en tidligere behandling.

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakDeltagerService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtakTest.kt
Favro: [NAV-26278](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26278)
Sonar-issue: "Refactor this method to reduce its Cognitive Complexity from 30 to the 15 allowed" for funksjonen `utførStegOgAngiNeste` i `BeslutteVedtak`-steg.
Omstrukturerer koden for å redusere kompleksitet: 
* Trekker logikk ut i hjelpe-funksjoner
* Fjerner bruk av `lazy`
* Flytter validering til `preValiderSteg`
* Justert tester som følge av flytting av validering til `preValiderSteg`
Jeg har ikke skrevet tester fordi: Ingen ny logikk, kun omstrukturert kode.
=> NAV-26278: Cognitive complexity `BeslutteVedtak`-steg

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/finnmarkstillegg/AutovedtakFinnmarkstilleggService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/svalbardtillegg/AutovedtakSvalbardtilleggService.kt
Ekstra sjekk i `skalAutovedtakBehandles` for å stoppe automatisk innvigelse av Finnmark- og Svalbardtillegg i EØS saker
=> Ikke innvilge Finnmark- og Svalbardtillegg i EØS saker

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestRegisterhistorikk.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlRestClient.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/domene/PdlHentPersonResponse.kt, src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/domene/PersonInfo.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/Person.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagService.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/deltbosted/GrDeltBosted.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/deltbosted/GrMatrikkeladresseDeltBosted.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/deltbosted/GrUkjentBostedDeltBosted.kt, src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/deltbosted/GrVegadresseDeltBosted.kt, src/main/resources/db/migration/V295__opprett_delt_bosted_tabell.sql, src/main/resources/pdl/hentperson-med-relasjoner-og-registerinformasjon.graphql, src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/deltbosted/DeltBostedTest.kt
Favro: NAV-26415
Henter delt bosted fra PDL og lagrer i personopplysningsgrunnlaget
=> Legg til delt bosted i personopplysningsgrunnlag
