navikt/familie-ba-sak

.github/workflows/integrationTest.yaml
pom.xml

Integrert familie-ba-sak med [sonarcloud](https://sonarcloud.io/dashboard?id=navikt_familie-ba-sak)

Sonarcloud

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingslagerService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/personopplysninger/PersonopplysningGrunnlag.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/personopplysninger/PersonopplysningGrunnlagRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/vedtak/BehandlingVedtak.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/vedtak/BehandlingVedtakRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/mottak/MottakController.kt
src/main/resources/db/migration/V3__vedtak.sql
src/test/kotlin/no/nav/familie/ba/sak/BehandlingIntegrationTest.kt

Lagt til type på behandling. Skrevet tester for personGrunnlag og vedtak.

Laget enkel modell for vedtak på en behandling.

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingslagerService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/FagsakController.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/FagsakService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/personopplysninger/Person.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/personopplysninger/PersonRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/personopplysninger/PersonopplysningGrunnlag.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/vedtak/BehandlingVedtakBarn.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/vedtak/BehandlingVedtakBarnRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestBehandlingVedtak.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestBehandlingVedtakBarn.kt
src/main/kotlin/no/nav/familie/ba/sak/mottak/MottakController.kt
src/main/resources/db/migration/V6__vedtak_barn.sql
src/main/resources/db/migration/V7__vedtak_barn_belop.sql
src/test/kotlin/no/nav/familie/ba/sak/BehandlingIntegrationTest.kt

Mindre endringer etter kommentarer på siste PR etter merge.
Lagt til en tabell som kobler seg mot et vedtak.

Legger til beregning av barn på vedtaket. 

---

src/main/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiService.kt

Returnerer ingenting fra metoden.

Kaster feil hvis iverksetting mot oppdrag feiler. 

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/FagsakService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/FagsakRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/mottak/MottakController.kt
src/main/resources/db/migration/V10__unique_fagsak_for_person.sql
src/test/kotlin/no/nav/familie/ba/sak/BehandlingIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/BehandlingNegativeIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/økonomi/BeregningTest.kt
src/test/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiIntegrasjonTest.kt

Flytter logikk fra controlleren til behandlingservice og skriver om logikken litt. Legger på transactional på metoden.

Gjør personident til unique på fagsak tabellen.

---

src/main/kotlin/no/nav/familie/ba/sak/dokument/JournalførBrevTaskDTO.kt
src/main/kotlin/no/nav/familie/ba/sak/task/StatusFraOppdrag.kt

Må implementeres i journalføringstasken.

Fjerner henting av pdf fra status fra oppdrag task.

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/FagsakController.kt
src/main/kotlin/no/nav/familie/ba/sak/common/BaseService.kt
src/main/kotlin/no/nav/familie/ba/sak/dokument/JournalførBrevTaskDTO.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/IntegrasjonTjeneste.kt
src/main/kotlin/no/nav/familie/ba/sak/task/JournalførVedtaksbrev.kt
src/main/kotlin/no/nav/familie/ba/sak/task/StatusFraOppdrag.kt

+ Implementerer dokdist-funksjonen i Integrasjonstjenester

Flytter henting av PDF ut av StatusFraOppdrag

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/IntegrasjonTjeneste.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/domene/Arbeidsfordelingsenhet.kt

Dette er kun integrasjonspunktet, som skal brukes senere når vi oppretter oppgave for en innkommende fødselshendelse.
Integrasjonspunktet er testet og svarer.

Integrasjonspunkt mot arbeidsfordeling i familie-integrasjoner

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/FagsakService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/BehandlingRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/vedtak/VedtakRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestBehandling.kt
src/main/kotlin/no/nav/familie/ba/sak/task/StatusFraOppdrag.kt

Legger til migreringstype og forhindrer utsending av brev ved disse typene.

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/mottak/MottakController.kt
src/main/resources/application.yaml
src/test/kotlin/no/nav/familie/ba/sak/config/ByEnvironmentStrategyTest.kt

Vi trenger å kunne ha funksjonsbrytere på om det skal lages oppgaver eller ikke, dette er første PR i en serie på 2 deler.

Lagt inn mulighet for featureToggling

---

src/main/kotlin/no/nav/familie/ba/sak/mottak/MottakController.kt
src/main/kotlin/no/nav/familie/ba/sak/task/DistribuerVedtaksbrev.kt

...og fjerner toggle-testene i MottakController nå som de er verifisert

Kommenterer inn toggle-kontrollert kode i DistribuerVedtaksbrev

---

src/main/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiKlient.kt

Ikke send oppdrag/status som string da familie-oppdrag ikke klarer å deserialisere det

 Bugfix: Iverksetting mot Økonomi

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/FerdigstillOppgave.kt
src/main/kotlin/no/nav/familie/ba/sak/task/IverksettMotOppdrag.kt
src/test/kotlin/no/nav/familie/ba/sak/BehandlingIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/FagsakControllerTest.kt

- Fiks bug for opprettOppgave
- Koblet til ferdigstill etter iverksettelse

Koblet til ferdigstill og fiks feil i opprettOppgave

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/domene/Personinfo.kt

Forbereder endringer i eksisterende tjeneste i familie-integrasjoner som vil legge på navn og kjønn på personinfo. Legger også på @JsonIgnoreProperties slik at appen blir litt mer robust for fremtidige endringer.

Lagt til flere felter på personinfo.

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/beregning/Beregning.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/beregning/BeregningController.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/beregning/BeregningService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakController.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/Vedtak.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt
src/main/kotlin/no/nav/familie/ba/sak/common/RessursResponse.kt
src/main/kotlin/no/nav/familie/ba/sak/common/Tid.kt
src/main/kotlin/no/nav/familie/ba/sak/økonomi/Utbetalingsoppdrag.kt
src/main/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiService.kt
src/test/kotlin/no/nav/familie/ba/sak/BehandlingIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/BehandlingNegativeIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/FagsakControllerTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/beregning/BeregningNegativeIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/beregning/BeregningTest.kt
src/test/kotlin/no/nav/familie/ba/sak/common/TidTest.kt

Laget service og controller (med gamle navn for å ikke brekke frontend)

Skilt ut beregning til egen pakke under behandling. 

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/config/ApplicationConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/config/RestTemplateConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/config/WebConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/IntegrasjonClient.kt
src/test/kotlin/no/nav/familie/ba/sak/config/RestTemplateConfig.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/IntegrasjonClientTest.kt

This reverts commit dcc3949a2d0bb7b6c3234d225143a5ed01305f3f.

Revert "Oppgradert felles. (#132)"

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingController.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakController.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/StegService.kt
src/main/kotlin/no/nav/familie/ba/sak/common/RessursResponse.kt
src/main/kotlin/no/nav/familie/ba/sak/logg/Logg.kt
src/main/kotlin/no/nav/familie/ba/sak/logg/LoggController.kt
src/main/kotlin/no/nav/familie/ba/sak/logg/LoggService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/FerdigstillBehandling.kt
src/test/kotlin/no/nav/familie/ba/sak/logg/LoggServiceTest.kt

Bruker loggservice og lager loggmelding ved opprettelse av behandling.

Laget logg for opprettelse av behandling og henting av logg for behandling.

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/IntegrasjonClient.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/IntegrasjonClientTest.kt

Endret fra bidestrek til underscore på dokumentProdApp siden Dokument ikke håndterer dette.

Fix mot dokdist

---

src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårVurderingTest.kt

- Validerer at rett antall vilkår har blitt lagt til i det samlede resultatet
- Korrigerer expected- og actual-posisjon i tester

Oppdater VilkårsVurdering-test

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingController.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/søknad/SøknadDTO.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/søknad/SøknadGrunnlagController.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/BehandlingSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/RegistrereSøknad.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/StegService.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/domene/Personinfo.kt
src/main/kotlin/no/nav/familie/ba/sak/logg/Logg.kt
src/main/kotlin/no/nav/familie/ba/sak/logg/LoggService.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/BehandlingIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/steg/BehandlingStegTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/steg/StegServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/søknad/SøknadGrunnlagTest.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt

1. Opprett behandling blir enklere
2. Henting av persongrunnlag gjøres samtidig som søknaden settes - basert på hva det er søkt for.

Feature/behandling og søknad

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/PersonController.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/RestPersonInfo.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/IntegrasjonOnBehalfClient.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/domene/Personinfo.kt
src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt

Fjerner også relasjonskode EKTE som vi ikke får fra PDL.

Henter navn og fødselsdato på barn.

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/AndelTilkjentYtelse.kt
src/main/kotlin/no/nav/familie/ba/sak/beregning/BeregningService.kt
src/main/kotlin/no/nav/familie/ba/sak/beregning/TilkjentYtelseService.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/BehandlingIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/beregning/BeregningServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/beregning/VilkårTilTilkjentYtelseTest.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
src/test/resources/beregning/vilkår_til_tilkjent_ytelse/søker_med_ett_barn_inntil_to_perioder.csv
src/test/resources/beregning/vilkår_til_tilkjent_ytelse/søker_med_to_barn_inntil_to_perioder.csv

Legger til csv-tester for å teste beregning av TilkjentYtelse. Pluss litt refactoring for å isolere funksjonaliteten.
I IntelliJ så er det enklest å redigere CSV-filene med en CSV-plugin. Jeg har brukt denne: https://plugins.jetbrains.com/plugin/10037-csv-plugin

Csv tester beregning

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/StegService.kt
src/main/kotlin/no/nav/familie/ba/sak/journalføring/JournalføringService.kt
src/main/kotlin/no/nav/familie/ba/sak/journalføring/domene/Dokument.kt
src/main/kotlin/no/nav/familie/ba/sak/journalføring/domene/OppdaterJournalpostRequest.kt
src/main/kotlin/no/nav/familie/ba/sak/logg/Logg.kt
src/main/kotlin/no/nav/familie/ba/sak/logg/LoggService.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/Datagenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/journalføring/JournalføringServiceTest.kt

Returnerer også logiske vedlegg på dokumenter til frontend.

Flytter logging av mottatt dokument til ferdigstill metoden.

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/Vilkår.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårService.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/steg/StegServiceTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-1100

Legger til vilkår 'lovlig opphold' dersom søker er tredjelandsborger.

---

src/main/kotlin/no/nav/familie/ba/sak/logg/LoggService.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-1105

Bugfix: Fjerne dobbel visning av saksbehandler

---

src/main/kotlin/no/nav/familie/ba/sak/dokument/DokGenKlient.kt
src/main/kotlin/no/nav/familie/ba/sak/dokument/DokumentService.kt
src/main/kotlin/no/nav/familie/ba/sak/dokument/MalerService.kt
src/test/kotlin/no/nav/familie/ba/sak/dokument/DokGenKlientIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/dokument/MalerServiceTest.kt

...fra dokgen, der hvor dette ble brukt ved henting av markdown

Legger til "-tredjelandsborger" i malnavnet ved henting av html og pdf

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/StegService.kt
src/main/kotlin/no/nav/familie/ba/sak/common/Tid.kt
src/main/kotlin/no/nav/familie/ba/sak/common/Utils.kt
src/main/kotlin/no/nav/familie/ba/sak/dokument/DokumentService.kt
src/main/kotlin/no/nav/familie/ba/sak/dokument/MalerService.kt
src/test/kotlin/DevLauncher.kt

Fiks på hvem som blir med i behandlingen basert på input fra søknad. 

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/IntegrasjonClient.kt
src/main/kotlin/no/nav/familie/ba/sak/oppgave/OppgaveController.kt
src/main/kotlin/no/nav/familie/ba/sak/oppgave/OppgaveService.kt
src/test/kotlin/no/nav/familie/ba/sak/oppgave/OppgaveControllerTest.kt

Kaller oppgave/v2 i familie-integrasjoner, og legger på ekstra filtrering av prioritering da det ikke er støtte for dette i Oppgave.
Det nye endepunktet i ba-sak har navnet /oppgave/hentOppgaver, det bør hete noe lignende i integrasjoner når vi har gått over.

Generisk finn oppgave

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/BehandlingSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/IverksettMotOppdrag.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/SendTilBeslutter.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/StegService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/Vilkårsvurdering.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakController.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/Vilkår.kt
src/main/kotlin/no/nav/familie/ba/sak/beregning/domene/PeriodeResultat.kt
src/main/kotlin/no/nav/familie/ba/sak/common/RessursUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårServiceTest.kt

Validerer om fom er satt og at fom for vilkårene for barna er innenfor 0-18 år.

Legger til bedre validering av alle vilkårene på barna.

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/Vilkårsvurdering.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/BehandlingResultatService.kt

- Logg når hele vilkårsvurderingen sendes inn/valideres

Fiks logger

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt
src/main/kotlin/no/nav/familie/ba/sak/totrinnskontroll/TotrinnskontrollService.kt

Teknisk opphør ble stuck ved iverksetting fordi den manglet totrinnskontroll etter endringer.

Legg til totrinnskontroll med system som beslutter ved opphør

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/StegService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/BehandlingResultat.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/BehandlingResultatService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/PersonResultat.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/steg/StegServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt

- Deep copy av BehandlingResultat

Lagrer kopier behandlingsresultat når man sender til beslutter

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestOppdaterJournalpost.kt
src/main/kotlin/no/nav/familie/ba/sak/journalføring/JournalføringService.kt
src/main/kotlin/no/nav/familie/ba/sak/oppgave/OppgaveService.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/Datagenerator.kt

Oppdaterer kontrakter og navnendring på en variabel i tillegg.

Overskriver tittel på jp fra dokument tittel.

---

app-preprod.yaml
app-prod.yaml
pom.xml

Bumpet felles

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/Regler.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/Vilkår.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårsvurderingMetrics.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt

Skrevet om metrikker for vilkårsvurdering også.
Nå blir det generert tellere for hver regel på :
- opprinnelse av behandling
- persontype
- resultat
Dette vil hjelpe oss senere til å lage gode grafer i grafana

Koblet på automatisk vurdering på den manuelle saksbehandling løypa.

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/Regler.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårService.kt
src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt

Legger til begrunnelser på regler som resulterer i kanskje.

Setter resultatet til kanskje på gift vilkår dersom sivilstanden er uoppgitt.

---

src/main/kotlin/no/nav/familie/ba/sak/dokument/DokumentService.kt

Fiks metrikker for brev

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/beregning/domene/AndelTilkjentYtelse.kt
src/main/kotlin/no/nav/familie/ba/sak/stønadsstatistikk/StønadsstatistikkService.kt
src/main/kotlin/no/nav/familie/ba/sak/vedtak/producer/VedtakKafkaProducer.kt
src/main/kotlin/no/nav/familie/ba/sak/vedtak/verktøy/KafkaController.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/dokument/MalerServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/stønadsstatistikk/StønadsstatistikkServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/økonomi/UtbetalingsoppdragIntegrasjonTest.kt

Har lagt inn en 0.2 versjon av mapping. Er en del informasjon som ikke finnes i BA sak enda  + ett par felter som må jobbes mer med.
Mangler også junit test :(

Mapping til stønadsstatistikk DVH

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/FerdigstillBehandling.kt
src/main/kotlin/no/nav/familie/ba/sak/infotrygd/FeedDto.kt
src/main/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdFeedClient.kt
src/main/kotlin/no/nav/familie/ba/sak/infotrygd/domene/FeedDto.kt
src/main/kotlin/no/nav/familie/ba/sak/task/SendFeedTilInfotrygdTask.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/steg/StegServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdFeedClientMock.kt
src/test/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdFeedClientTest.kt
src/test/kotlin/no/nav/familie/ba/sak/infotrygd/SendFeedTilInfotrygdTaskTest.kt
src/test/kotlin/no/nav/familie/ba/sak/task/FerdigstillBehandlingTaskTest.kt

Vedtak (søker og vedtaksdatum) blir sendt til Infotrygd som del av ferdigstill steget i saksbehandlingen.

Send vedtak til Infotrygd

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/søknad/SøknadGrunnlag.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/søknad/SøknadGrunnlagController.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/søknad/SøknadGrunnlagMigrering.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/SøknadDTO.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/StegService.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/steg/StegServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/søknad/SøknadGrunnlagTest.kt
src/test/kotlin/no/nav/familie/ba/sak/beregning/BeregningServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt

Migrerer gammel søknad til ny. Migreringen fjerner felter vi ikke trenger lenger i databasen.

Feature/ny søknad dto kontrakt

---

pom.xml

Rullet tilbake til forrige versjon av prosessering.

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/config/RestTemplateConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/IntegrasjonClient.kt
src/main/kotlin/no/nav/familie/ba/sak/oppgave/domene/RestOppgave.kt
src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt
src/test/kotlin/no/nav/familie/ba/sak/config/RestTemplateTestConfig.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/IntergrasjonTjenesteTest.kt

Lagt til litt mock data og fikset auth mot integrasjoner.

Fikser bug for opprett oppgave.

---

src/main/kotlin/no/nav/familie/ba/sak/task/PubliserVedtakTask.kt
src/main/kotlin/no/nav/familie/ba/sak/vedtak/producer/KafkaProducer.kt
src/main/kotlin/no/nav/familie/ba/sak/vedtak/verktøy/KafkaController.kt
src/main/resources/application-dev.yaml
src/main/resources/application-e2e.yaml
src/main/resources/application.yaml
src/test/kotlin/no/nav/familie/ba/sak/task/PubliserVedtakTaskTest.kt

Utvidelse av KafkaProducer til å kunne sende saksstatistikkhendelser.

Kafka producer

---

src/main/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdFeedClient.kt

La til retry nå feed skrives til infotrygd-feed komponenten.
Retry trigges for IOException, tre forsøk gjøres med 5s intervall.

La til retry for feed infotrygd kall

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkService.kt
src/test/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkServiceTest.kt

lagt til behandlingsKategori, behandlingsUnderkategori og fikset feil med resultatBegrunnelse

Endringer i saksstastikk-kontrakt etter møte med dvh

---

.github/workflows/build-and-deploy-preprod-skip-e2e.yml
src/main/kotlin/no/nav/familie/ba/sak/arbeidsfordeling/ArbeidsfordelingController.kt
src/main/kotlin/no/nav/familie/ba/sak/arbeidsfordeling/ArbeidsfordelingService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/PersongrunnlagService.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/IntegrasjonClient.kt
src/main/kotlin/no/nav/familie/ba/sak/logg/LoggService.kt
src/main/kotlin/no/nav/familie/ba/sak/oppgave/OppgaveService.kt
src/test/kotlin/DevLauncherPostgres.kt
src/test/kotlin/no/nav/familie/ba/sak/arbeidsfordeling/ArbeidsfordelingIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/client/Norg2ClientMock.kt
src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt

Lagt til støtte for å endre behandlende enhet manuelt. 

---

src/main/kotlin/no/nav/familie/ba/sak/beregning/TilkjentYtelseUtils.kt

Tidligere kontrollerte man bare på segmentets verdi, men ved flere barn vil ikke dette stemme med satsbeløpene

Sjekk hver enkelt andel i segment i satsendring-sjekk

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/Vilkårsvurdering.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelse.kt
src/main/kotlin/no/nav/familie/ba/sak/beregning/TilkjentYtelseValidering.kt
src/main/kotlin/no/nav/familie/ba/sak/common/Feil.kt
src/main/kotlin/no/nav/familie/ba/sak/common/RessursUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/config/ApiExceptionHandler.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakBegrunnelseTest.kt
src/test/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkServiceTest.kt

Lager en egen funksjonell feil som implementerer runtime exception. På denne måten kan vi håndtere alle funksjonelle feil på samme måte.

Bruk funksjonell feil

---

src/main/kotlin/no/nav/familie/ba/sak/config/WebConfig.kt

Unntar task fra gruppetilgangs-sjekk

Unntar task fra gruppetilgangs-sjekk

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/stønadsstatistikk/StønadsstatistikkService.kt

Sender med personDVH istedenfor personident på vedtaket.
TidspunktVedtak er endret fra LocalDate til ZonedDateTime

Justeringer i format for stønadsstatistikk

---

src/main/kotlin/no/nav/familie/ba/sak/dokument/MalerService.kt

Ikke en feature, men en fix etter bughunt: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-2668

Datoformat i dufår-seksjon

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt

Legger på FNR-filter ved henting av identer på person før søket.

Fikser 500-feil mot InfotrygdBarnetrygd

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseService.kt

Ikke valider datoendringer på 18 årsvilkår ved manuell setting av reduksjonstekst

Ikke valider datoendringer på 18 årsvilkår ved manuell setting av reduksjonstekst

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/PersonResultat.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårsvurderingUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/beregning/SatsService.kt
src/main/kotlin/no/nav/familie/ba/sak/common/Tid.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårsvurderingUtilsTest.kt
src/test/kotlin/no/nav/familie/ba/sak/beregning/TilkjentYtelseUtilsTest.kt
src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt

1. Fjerner fylling av hull i vilkårsvurderingen. 
2. Fikser feil ved vilkårsvurdering akkurat når barnet fyller 6 år.

Retter 2 bugs etter bughunt.

---

src/main/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkService.kt
src/test/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkServiceTest.kt

Hentet fra FagsakPerson i dag, og det var ikke rett. Henter i stedet fra liste med personer for aktiv behandling, hvis bruker har behandling.

Henter liste med aktører for saksstatistikk fra persongrunnlag

---

src/main/kotlin/no/nav/familie/ba/sak/beregning/SatsService.kt
src/test/kotlin/no/nav/familie/ba/sak/beregning/TilkjentYtelseUtilsTest.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkServiceTest.kt

Fikser feil periode i tilkjent ytelse ved vurdering akkurat ved 6 årsalderen til barnet

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/BeslutteVedtak.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/SendTilBeslutter.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt
src/main/kotlin/no/nav/familie/ba/sak/dokument/DokumentUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/dokument/MalerService.kt
src/main/kotlin/no/nav/familie/ba/sak/totrinnskontroll/TotrinnskontrollService.kt
src/main/kotlin/no/nav/familie/ba/sak/totrinnskontroll/domene/Totrinnskontroll.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/steg/BeslutteVedtakTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/steg/StegServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/dokument/DokumentServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/dokument/DokumentUtilsTest.kt
src/test/kotlin/no/nav/familie/ba/sak/toTrinnKontroll/ToTrinnKontrollTest.kt
src/test/kotlin/no/nav/familie/ba/sak/toTrinnKontroll/ToTrinnKontrollTestConfig.kt

1. Setter steg ved underkjenning til send_til_beslutter
2. Forbedret fastsetting av sb/beslutter i vedtaksbrevet.

Underkjenning og fastsetting av sb og beslutter i brev

---

src/main/kotlin/no/nav/familie/ba/sak/common/Tid.kt
src/main/kotlin/no/nav/familie/ba/sak/dokument/MalerService.kt

https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-2781
Tror dette blir riktig, må bare få et grønt lys fra Anna også før merge :) 
Fiks bug som gjør at tom-dato kommer med i brev når ikke senere enn neste måned, men bør sjekke på inneværende

Fiks bug som gjør at tom-dato vises når løpende skal vises i brev

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakController.kt

Logger og returnerer feil, istedenfor å kaste, ved mislykket søk etter løpende saker

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/PersongrunnlagService.kt
src/main/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkService.kt
src/main/kotlin/no/nav/familie/ba/sak/stønadsstatistikk/StønadsstatistikkService.kt
src/main/kotlin/no/nav/familie/ba/sak/vedtak/producer/KafkaProducer.kt

- metrikker for produserterte meldinger
- nytt sakssevent ved oppdatering av personer
- innføring av funksjonellId for dvh

Metrikker over sendte meldinger og utvidelser i statatistikk

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/HenleggBehandling.kt
src/main/kotlin/no/nav/familie/ba/sak/dokument/MalerService.kt
src/main/kotlin/no/nav/familie/ba/sak/dokument/domene/MalMedData.kt

Endret navn/id på henleggelses brev

Endret navn/id på henleggelses brev

---

src/main/kotlin/no/nav/familie/ba/sak/dokument/domene/MalMedData.kt

Det ser ut som at familie-ba-dokgen ikke støtter ø i path navnet (lokalt i docker virker dette), derfor er ø blitt erstattet med o.
Lokalt i docker virker dette både for o og ø, derfor er det vanskelig å vete om det virker deployet.
Ikke relevant.
- [ x] Nei

Endret navn på trukket søknad til soknad

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingController.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/oppgave/OppgaveService.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/BehandlingIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakBegrunnelseTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakServiceTest.kt

Oppretter behandle sak oppgaver ved opprettelse av behandlinger (manuelle førstegangsbehandlinger og revurderinger)
Denne vil nå prøve å opprette, men hvis det allerede finnes noe så logger den warning. Det kan vi kanskje fjerne etterhvert.
Alt i ett :)

Legger inn opprettelse av behandle sak oppgaver på manuelle behandlinger

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/vedtak/producer/KafkaProducer.kt

Bumpet kontrakt for stønadsstatistikk
Nei
alt i ett
- [x ] Nei

Oppgradert stønadsstatistikkkontrakt

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/HenleggBehandling.kt
src/main/kotlin/no/nav/familie/ba/sak/dokument/DokumentService.kt
src/main/kotlin/no/nav/familie/ba/sak/dokument/domene/MalMedData.kt
src/test/kotlin/no/nav/familie/ba/sak/dokument/DokumentServiceTest.kt

For vanlig manueltbrev skal en forside bli generert men ikke for brev om trukket søknad.
- [x ] Nei

Fjernet førsteside når henleggelsesbrev er sendt

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/HenleggBehandling.kt

Oppgaver for behandling ferdigstilles når behandling henlegges.
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-3005

Ferdigstiller oppgaver på behandling når den henlegges.

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/SendTilBeslutter.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/steg/SendTilBeslutterTest.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt

Endret stegvalidering til å bli bakoverkompatibelt 
- [ X] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
- [ X] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇
- [ x] Nei

Endret stegvalidering til å bli bakoverkompatibelt

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestBehandling.kt
src/main/kotlin/no/nav/familie/ba/sak/beregning/domene/TilkjentYtelse.kt
src/main/resources/db/migration/V100__fjern_behandling_gjeldende_for_fremtidig_utbetaling.sql
src/test/kotlin/no/nav/familie/ba/sak/økonomi/KonsistensavstemmingSchedulerTest.kt

Etter omskriving av konsistensavstemming trenger vi ikke lenger gjeldene_for_fremtidig_utbetaling feltet på behandlingen.
Nope
_Jeg har ikke skrevet tester fordi:_ Jeg antar at eksisterende tester ville brukket hvis de var avhengig av feltet som fjernes.
alt i ett
Nei

Fjerner felt fra behandling (gjeldene for fremtidig utbetaling)

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakStatusScheduler.kt

Cron for å oppdatere fagsakstaus skal også sendes til datavarehus.
Funksjonalitet dekkes av eksisterende integrasjonstester

Fagsak status oppdatering via cron, også til datavarehus

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingMetrikker.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/StegService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt

Fag ønsket dels et nytt dashboard med et begrenset antall metrikker.
Og de ønsker bare, i dette dasjboardet, bare å se data fra manuell saksbehandling. 
- [ X] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
- [- ] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇
Metrikker skriver vi ikke tester for.

Endrett på metrikker etter diskusjon med Eivind

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårService.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/steg/StegServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt
src/test/kotlin/no/nav/familie/ba/sak/dokument/DokumentServiceTest.kt

For vilkårsvurdering skal det settes et default-svar på ugift-vilkår for barn avhengig av svar fra PDL.
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-2658
- [x ] Nei

Feature/default verdi på ugift vilkår

---

src/test/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdBarnetrygdClientTest.kt

Utkommenterte tester hjelper ingen
Har kjørt de 3 ganger på server. Ikke opplevd feilen beskrevet i kommentaren, som er at de feiler i AbstractRestClient. Skulle feilen dukke opp igjen, så anbefaler jeg at man fikser testen og ikke kommenterer ut.

Enablet utkommentert test

---

pom.xml

Bump kontrakter pga nødvendige endringer i Journalpost-objektet (AvsenderMottaker må tillate null-verdier)

Bump kontrakter.

---

src/main/resources/db/migration/V105__dupliser_behandlingresultat.sql

Dupliser resultat fra aktiv vilkårsvurdeing (tidligere behandlingresultat) til behandlingsnivå
Validerer i database

Dupliser resultat fra aktiv vilkårsvurdeing (tidligere behandlingresultat) til behandlingsnivå

---

pom.xml

https://github.com/navikt/familie-kontrakter/pull/238

Bump kontrakter etter bug i AvsenderMottakerType

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseIntegrasjonTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtilsTest.kt

Legger til validering av resultat, samt bedre feilmelding hvis vi ikke klarer å utlede resultat.
Greit at vi kun sjekker for manuelle behandlinger?
Alt i ett

Hindre videre vurdering ved resultater som ikke er støttet

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/YtelsePerson.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtilsTest.kt

Skiller i større grad på innvilget/annet slik at vi grupperer resultater i større grad.
Metoden jeg endrer på _kan_ vokse veldig fort. Diskuterer gjerne andre fremgangsmåter for å strukturere denne inndelingen av resultater.
Alt i ett

Forbedringer på innvilgede behandlingsresultater.

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkService.kt
src/test/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkServiceTest.kt

Utvider saksstatistikk til å ha med bostedsland for søker
Nei
alt i ett
- [ x] Nei

Lagt til bostedsland for saksstatistikk

---

src/main/kotlin/no/nav/familie/ba/sak/logg/LoggService.kt

Fikser: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-2652
Navn på historikkinnslag: "Brev mottatt" --> "Dokument mottatt"
Kun tekstendring

Liten tekstendring i logg

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestFagsakSøk.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakControllerTest.kt

...  i søkEtterPågåendeSak. Flyttet til ba-mottak.

Fjerner overflødig kall til infotrygd-barnetrygd

---

.github/workflows/build-and-deploy-preprod.yml

Fikser Failed to resolve action download info. Error: Unable to resolve action `navikt/github-app-token-generator@master`, unable to find version `master` ved bygging.

Setter versjon av github-app-token-generator til v1

---

.github/workflows/run-e2e.yml

Legg til e2e-workflow

---

.github/workflows/run-e2e.yml

Fjern duplikat linje som kom med ved uhell

---

src/main/resources/application-e2e.yaml

Vi ønsker å sette retry.backoff.delay til en lav verdi for kjappere e2e-tester.
- [ x] Nei

Sett retry.backoff.delay til 5 ms

---

src/main/resources/logback-e2e.xml

Legger til appender for securelog i e2e

---

src/main/kotlin/no/nav/familie/ba/sak/beregning/BeregningService.kt
src/main/kotlin/no/nav/familie/ba/sak/beregning/domene/AndelTilkjentYtelseRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/økonomi/AvstemmingService.kt
src/main/kotlin/no/nav/familie/ba/sak/økonomi/KonsistensavstemmingScheduler.kt

Opprydding: Fjern kommentar og legg på filter

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/common/Tid.kt
src/main/kotlin/no/nav/familie/ba/sak/dokument/MalerService.kt
src/main/kotlin/no/nav/familie/ba/sak/dokument/domene/maler/Innvilget.kt
src/test/kotlin/no/nav/familie/ba/sak/dokument/MalerServiceTest.kt

Støtte for behandlingsresultat endret og opphørt.
Løsningen er temporær for å virke sammen med nåværende vedtaksside.
På vedtakssiden er det bare mulig å begrunnel innvilgte perioder, løsningen er at opphørs begrunnelsen på en innvilget period gjelder for den etterkommende opphørt eller avslått perioden.

Feature/endring opphørt brevmal

---

src/main/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdFeedClient.kt

Reduserer feilloggingen ved posting mot infotrygd-feed for å ikke opprette unødvendig alarm.
Nei
- [ X] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
Finnes eksisterende tester
alt i ett
- [ X] Nei

Flytter logging av feil mot infotrygd-feed etter at retry er gjennomført

---

pom.xml

For å få med endringer i felles-prosessering slik at triggerTid ikke er null ved rekjøring av feila tasker

Bumper felles 

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt

Feil i valideringen av reduksjonsintrevaller
Har ingen test.

Feil i valideringen av reduksjonsintrevaller

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestJournalføring.kt
src/main/kotlin/no/nav/familie/ba/sak/journalføring/JournalføringService.kt

Manuelljournalføring: when creating a new behandling, the frontend can specify the behandling type and årsak
Minor change
alt i ett

Manuelljournalføring: Set the new behandling type and årsak

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/DistribuerVedtaksbrev.kt
src/main/kotlin/no/nav/familie/ba/sak/dokument/MalerService.kt

Legger til støtte for behandlingsresultat "endring og løpende".
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-3267 
- [x ] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
Skal se om en e2e-test kan være mest hensiktsmessig
alt i ett
- [x ] Nei

Feature/behandlingsresultat endret løpende

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/autobrev/Autobrev6og18ÅrService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/SendAutobrev6og18ÅrTask.kt
src/test/kotlin/no/nav/familie/ba/sak/beregning/UtbetalingssikkerhetTest.kt

Fikset bug, som ble fanget opp av test.

Endrett intervall til å ta med første og siste dag i måneden

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/stønadsstatistikk/StønadsstatistikkService.kt

Sende med årsak til behandling til stønadstatistikk
Nei
alt i ett

Utvider støndadstatistikk til å ha behandling årsak

---

Dockerfile
src/main/resources/logback-spring.xml

Tror at e2e feiler pga ikke tilgang til å opprette /securelogs/secure.log. Så tester med å bruke securelog over rest som man likevel skal over til.
må sjekke i preprod etter deploy om det fortsatt kommer ting i securelog. I do

Securelog over POST

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/YtelsePerson.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/DistribuerVedtaksbrev.kt
src/main/kotlin/no/nav/familie/ba/sak/dokument/MalerService.kt
src/main/resources/db/migration/V109__oppdatere_behandlingsresultat.sql
src/test/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtilsTest.kt
src/test/kotlin/no/nav/familie/ba/sak/dokument/MalerServiceTest.kt

To typer behandlingsresultat skal endre navn:
ENDRING_OG_LØPENDE -> ENDRET_OG_FORTSATT_INNVILGET
ENDRING_OG_OPPHØRT -> ENDRET_OG_OPPHØRT
Det er gjort endringer i ba-sak-frontend, og også e2e vil oppdateres ihht denne endring for å ha konsistens i navngivningen.
Kun endret på eksisterende tester.
Alt i ett
- [ x] Nei

Renamet et par av behandlingsresultatene.

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt

Når vi utleder behandlingsresultat så manglet vi støtte for et case der alle barn settes med opphør som samme tid samtidig som det gjøres endringer tilbake i tidslinjen (altså før opphøret). Dette gav resultat Opphørt, men skal nå gi resultat "Endret og opphørt".
Alt i ett
- [ x] Nei

Feature/endring og opphør v2

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakController.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt
src/test/kotlin/no/nav/familie/ba/sak/WebSpringAuthTestRunner.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/fagsak/SøkFagsakNegativeTest.kt
src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt

Mindre forbedringer på fagsaksøk. Nå returnerer vi en tom liste om PDL svarer med NOT_FOUND.
Ta gjerne en ekstra sjekk på håndteringen av not_found.
Ikke relevant da jeg bare har ryddet og forbedret håndtering av not found. Kunne laget en test for not found, men tenker dette egentlig tilhører testing av pdl-integrasjonen eventuelt som jeg ikke har tenkt til å røre i denne PRen.
Alt i ett

Forbedringer på fagsaksøk

---

src/main/resources/db/migration/V111__saksstatistikk_mellomlagring.sql

DB skript for mellomlagring av kafkameldinger. Slik at man har muligheter til å rekjøre
Kun dbscript. Kode kommer i egen PR.

Databasescript for mellomlagring av saksstiatistikk

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt

Rent opphør ble ikke satt rett mtp periode dersom minst et barn fra før var opphørt.
Kun en liten rettelse.

Bugfix/rent opphør

---

pom.xml

Felles-biblioteket er oppdatert med en version som teller antall fullførte task, gruppert på task-type. 
Ingen kodeenring

Oppdaterte felles bibliotek med endring som teller antall fullførte tasks

---

src/main/kotlin/no/nav/familie/ba/sak/common/Tid.kt

- Legger til validering for avslag
- Frontend: https://github.com/navikt/familie-ba-sak-frontend/pull/766 
Sortering av perioder uten datoer kommer i egen pr. Mulig det også kommer mer validering på disse også. 
UI
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-3662

Oppdater validerin på periode

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/BehandlingRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/internstatistikk/InternStatistikkController.kt
src/main/kotlin/no/nav/familie/ba/sak/internstatistikk/InternStatistikkService.kt

Etter ønske om å enkelt kunne aksessere nøkkeltall fra ba-sak. 
Gjort på mobdesign
Frontend: https://github.com/navikt/familie-ba-sak-frontend/pull/769
Internside uten noe særlig funksjonalitet
Alt i ett

Minimal internstatistikk

---

src/main/kotlin/no/nav/familie/ba/sak/infotrygd/InfotrygdController.kt

Forrige PR manglet dessverre riktige annotasjoner for at frontend skulle kunne koble seg på.
Legger på @Validated og @ProtectedWithClaims.

Legg til manglende annotasjoner

---

src/main/resources/db/migration/V117__bugfix_periode_resultat_fk_til_person_resultat_fk.sql

Ref:https://nav-it.slack.com/archives/C01G9BA8JKZ/p1614156479014000

Fiks reference

---

src/main/kotlin/no/nav/familie/ba/sak/journalføring/JournalføringService.kt

Oppretter kun behandle sak oppgave dersom vi oppretter ny behandling ved journalføring.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-3833

Opprett oppgave bug ved journalføring

---

src/main/kotlin/no/nav/familie/ba/sak/brev/BrevService.kt
src/main/kotlin/no/nav/familie/ba/sak/brev/BrevUtil.kt
src/main/kotlin/no/nav/familie/ba/sak/brev/domene/maler/Brev.kt
src/main/kotlin/no/nav/familie/ba/sak/brev/domene/maler/OpphørMedEndring.kt
src/test/kotlin/no/nav/familie/ba/sak/brev/BrevUtilsTest.kt

Bruk riktig vedtaksbrevtype på opphør med endring

---

src/main/kotlin/no/nav/familie/ba/sak/brev/BrevPeriodeService.kt

Reverser de sorterte vedtaksperiodene

---

src/main/resources/db/migration/V123__simulering.sql

Opprett simuleringstabeller

---

src/main/kotlin/no/nav/familie/ba/sak/brev/BrevPeriodeUtil.kt

Flytt opphørsperiodene under Utbetalingsperiode i den temporære løsningen

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseSpesifikasjon.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakUtilsTest.kt

- [Favrokort her](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-3473)
- Lagt til begrunnelsetekster for avslag: https://confluence.adeo.no/display/TFA/16.7+Avslag# 
- Ny datologikk som støtter casene til avslagsperioder. Lagt til tester for disse.
Opplysningsplikt-teksten er det mulig 
Funksjonell testing av denne vil skje med denne oppgaven https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-3636. Pga avklaringer på den har disse blitt lagt til allerede nå, før den er ferdig.  
Alt i ett

Legg til begrunnelsetekster for avslag

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/MigrerBehandlingerUtenInitialisertVedtak.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/BeslutteVedtak.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/StegService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/BehandlingIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/steg/BeslutteVedtakTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/steg/StegServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakBegrunnelseTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/task/FerdigstillBehandlingTaskTest.kt
src/test/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiIntegrasjonTest.kt

Vedtak skal bli opprettet sammen med behandlingen men det ble den ikke fra journalforing
Test gjennom journalføring.
Ser nå etterpå om det er mulig å få oppdatert eller skrevet ny test som tester den nye rekkefølgen.

Opprett vedtak også når behandling blir opprettet fra journalføring

---

src/main/kotlin/no/nav/familie/ba/sak/stønadsstatistikk/StønadsstatistikkService.kt

Ikke logg error ved ukjent landkode.

Justerer ned loglevel for ukjent landkode til datavarehus

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/BeslutteVedtak.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/Vedtak.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/steg/BeslutteVedtakTest.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4098
Tidligere ble begrunnelser nullstilt for hvert nye vedtak.
Alle begrunnelser skal nå tas med videre til neste vedtak.
Oppdatert eksisterende

Ta med vedtakbegrunnelser videre ved underkjenning

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/søknad/SøknadUregistrerteBarnMigrering.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/SøknadDTO.kt

Fyller ut nytt flagg på alle barn i søknadsgrunnlagene som finnes i løsningen. Dette flagget skal brukes til å gi automatisk avslag på barn som blir registrert manuelt og ikke har fått ident i registrer søknad skjermbildet.
Nei
Kun migrering
Alt i ett

Migrering: støtte for uregistrerte barn

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseSpesifikasjon.kt
src/main/kotlin/no/nav/familie/ba/sak/brev/BrevPeriodeService.kt
src/main/kotlin/no/nav/familie/ba/sak/brev/BrevPeriodeUtil.kt
src/main/kotlin/no/nav/familie/ba/sak/brev/domene/maler/Vedtaksbrev.kt
src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/AvslagBegrunnelseSammenslåingTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakUtilsTest.kt

- Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4035
- Legger til avslagbegrunnelser i eksisterende brev
- Sorterer og legger til test
- Oppdater periodedelmal i sanity (brukes i Innvilget ordinær barnetrygd, vedtak endring og opphør endring)
Begrunnelsene ser litt kunstige ut fordi det antas at et kommer et "_fordi_" først, men det passer ikke med "Du får ikke" uten periode. Avklarer dette med Anna og Birgitte i morgen tidlig (må nok enten justere tekst i sanity eller begrunnelse), men det påvirker ikke logikk, så pr er klar for review. 

Koble avslagstekster til eksisterende brev

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/Vedtak.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/vedtaksperiode/Vedtaksperiode.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseSpesifikasjon.kt

La til støtte for fritekst for reduksjon
Ikke endring i logikk

La til støtte for fritekst for reduksjon

---

src/main/kotlin/no/nav/familie/ba/sak/brev/BrevService.kt
src/main/kotlin/no/nav/familie/ba/sak/brev/BrevUtil.kt
src/main/kotlin/no/nav/familie/ba/sak/brev/domene/maler/Avslag.kt
src/main/kotlin/no/nav/familie/ba/sak/brev/domene/maler/Brev.kt
src/test/kotlin/no/nav/familie/ba/sak/brev/BrevUtilsTest.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-3472
Brev lagt inn i sanity med Anna og Birgitte. 

Støtt avslagsbrev ved behandlingsresultat "AVSLÅTT"

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/StegService.kt

Bugfix. Ikke kjør simuleringssteget automatisk når neste steg ikke er simulering

Ikke kjør simuleringssteget automatisk når neste steg ikke er simulering

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/beregning/domene/PeriodeResultat.kt

Fjerner validering av perioder på vilkårsvurderingen. Det skal gå fint å vurdere 2 selvstendige perioder for søker/barn eller kun søker om man har uregistrerte barn.
Nei
Alt i ett

Oppmykning av validering av vilkårsvurdering

---

src/main/kotlin/no/nav/familie/ba/sak/arbeidsfordeling/ArbeidsfordelingService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/EvaluerFiltreringsreglerForFødselshendelse.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/PersonController.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/søknad/SøknadGrunnlagController.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/DocFormat.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/RegistrereSøknad.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/Vilkårsvurdering.kt
src/main/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/KonsistensavstemMotOppdrag.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/steg/StegServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/GDPRInnhentingTest.kt
src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt
src/test/kotlin/no/nav/familie/ba/sak/økonomi/FagsakStatusOppdatererIntegrasjonTest.kt

- Fjern ubrukte loggere, funksjoner og imports
- Fiks sonar codesmell

Smårydding

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseSpesifikasjon.kt
src/main/kotlin/no/nav/familie/ba/sak/brev/BrevPeriodeService.kt
src/main/kotlin/no/nav/familie/ba/sak/brev/BrevPeriodeUtil.kt
src/main/kotlin/no/nav/familie/ba/sak/brev/BrevService.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/AvslagBegrunnelseSammenslåingTest.kt

Sortering av fritekster i brev: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4278

Fritekster i brev

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseSpesifikasjon.kt

- Fikser nynorsk duOgEllerBarnaFødt-formulering: "født"/"fødd"
- Fikser nynorsk i fraOgTil-formulering: "fra"/"frå"

Fiks nynorsk i begrunnelser

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/BeslutteVedtak.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4281
Avslag og fortsatt innvilget har ingen endringer mot økonomi og skal ikke trigges. Vi trigger brevutsending direkte i stedet.
Nei
- [ x Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇
BehandlingResultat sin nye metode.
Hvis noen vil kan jeg godt ta dette muntlig :)

Fortsatt innvilget og avslag skal ikke trigge iverksetting mot økonomi.

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseSpesifikasjon.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseUtils.kt

Ved opphør grunnet barn fyller 18år er 18år begrunnelsen ikke med som valg i brevbegrunnelse på vedtakssiden. 
Ikke endring i logikk

La til 18år vedtakbegrunnelse for opphør

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/AvslagBegrunnelseOppdateringTest.kt

@MarcusGustafson74 kan du validere at dette er ok mtp fritekster også? De bruker kun `/{fagsakId}/vedtak/fritekster`-endepunktet?

Fjern ubrukt kode

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseSpesifikasjon.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/AvslagBegrunnelseSammenslåingTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakUtilsTest.kt

- Tar i bruk utvidelsen her https://github.com/navikt/familie-ba-sak/pull/935 og endrer ordlyd i avslagsbegrunnelser
- Slår sammen reduksjonstekst REDUKSJON_FLYTTET_FORELDER med REDUKSJON_FLYTTET_BARN (https://github.com/navikt/familie-ba-sak/pull/939/files#diff-8977adc6d1a6bfa28df13bfda58d3659f69b5e38c03a17587978ff1aacefa2cdL233-L261)
- Legger til ny reduksjonstekst REDUKSJON_ENDRET_MOTTAKER

Oppdater brevtekster

---

pom.xml

Oppgraderer felles med securelogfix

Oppgraderer felles med securelogfiks

---

src/test/kotlin/no/nav/familie/ba/sak/behandling/BehandlingIntegrationTest.kt

Lagt til en ekstra test i BehandlingIntegrationTest som kontrollerer “resultat” og “resultatBegrunnelser” oppgitt i BehandlingDVH ved resultat AVSLÅTT

Tester innhold i BehandlingDVH ved avslag

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtilsTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/resultat/YtelsePersonUtilsTest.kt

Fikser bug hvor opphør på flere barn med forskjellig opphørsdato ikke ble markert som endring.
Nei
Alt i ett

Bug endring og opphørt

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakBegrunnelseTest.kt

Fjerner plusDays(1) fordi grenseverdier på vilkårResultat.tom vil feile på den logikken. Mulig logikk fra gammel oppgave.
Kan denne logikken ha ligget der for andre grunner? Ingen av testene som feilet hvertfall.
Alt i ett

Bug: reduksjon på vedtaksperiode

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringService.kt
src/test/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringServiceTest.kt

Tette hullet i utbetaling mellom opphør i infotrygd og startdato ba-sak, som ble oppdaget under test.
Samt endret litt på migreringslogikken for å unngå feil/kunstige historikkinnslag.
alt i ett

Fikser migrering startdato og feil i behandlinghistorikken

---

src/main/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringController.kt
src/main/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringService.kt
src/main/kotlin/no/nav/familie/ba/sak/infotrygd/domene/MigreringResponseDto.kt

Litt mer hendig å ha fagsak og behandling id direkte uten søk ved migrering, så man slipper å søke
Nope

Migreringstjenesten returernerer en response med fagsakId og behandlingId som kan brukes i e2e/frontend

---

src/main/resources/application-e2e.yaml

e2e config for infotrygd-barnetrygd mot mockserver

E2e mock azure scope

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/Vedtak.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt
src/main/kotlin/no/nav/familie/ba/sak/økonomi/UtbetalingsperiodeMal.kt
src/main/resources/db/migration/V128__slett_manuell_opphorsdato_fra_vedtak.sql
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/økonomi/UtbetalingsoppdragIntegrasjonTest.kt

Se post: 
https://nav-it.slack.com/archives/GU4MVCGCD/p1619429283089100?thread_ts=1619429275.089000&cid=GU4MVCGCD
Har kjørt med e2e lokalt.

Fjern opphørsdato fra oppdrag

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/RegistrereSøknad.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårService.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/søknad/SøknadGrunnlagTest.kt

Flytter sletting av TY til registrer søknad steget.
Nei
Alt i ett

Bug: sletting av barn fører til feil ved populering av restBehandling og restTY

---

src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vilkår/GDPRInnhentingTest.kt
src/test/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTaskTest.kt

[som diskutert her](https://nav-it.slack.com/archives/CK59Y6EHE/p1619688126163400)

Skrur av behandling av fødselshendelser med tilbakerulling for metrikkenes skyld

---

src/main/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiKlient.kt

I forbindelse med alarm så jeg at vi bruker deprecated endepunkt for grensesnittavstemming. Fikser feilen også :) 
Nei
Ikke relevant.
Alt i ett

Gjeld: Bruker ny kontrakt ved grensesnittavstemming.

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkService.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakControllerTest.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/søknad/SøknadGrunnlagTest.kt
src/test/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkServiceTest.kt

Skriver om til å bruke fagsak fremfor restfagsak i mapping mot DVH. Ved lagring av behandling kalles denne funksjonen og da kan det være behandlingen er i en state hvor mapping til rest utvidet behandling ikke er så heldig.
Nei
Forandret på testene som krever dette. Skrevet test for scenario som feilet.
Alt i ett

Bug: mapping til restFagsak ved statistikk til dvh

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/tilbakekreving/TilbakekrevingService.kt

+ tar med saksbehandlerident i request.
Legger ved saksbehandlerident i oppretttilbakekrevingsrequest for å få med navn i varselbrev

Ny versjon av kontrakt mot familie-tilbake 

---

src/main/kotlin/no/nav/familie/ba/sak/brev/BrevService.kt
src/main/kotlin/no/nav/familie/ba/sak/simulering/SimuleringService.kt

Hent simulering med behandlingsid, ikke vedtaksid

Hent simulering med behandlingsid

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt

Henter tilbakekreving basert på behandling.id

Henter tilbakekreving basert på behandling.id og ikke aktivtvedtak.id

---

src/main/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiService.kt

**Funksjonelt:**
Fikk feil "En feil har oppstått" da man gikk videre fra vilkårsvurderinga dersom opphøret ble gjort på en revurdering og endret eksisterende perioder
**Teknisk:**
Valideringen var for streng og tillot ikke nye økonomiperioder ved resultat OPPHØR. Hvis perioder fra forrige behandling berøres ved opphør skal man slik vi har implementert det opphøre og også sende oppdatert versjon.
Alt i ett

Mildere validering av opphørsvedtak ved generering av utbetalingsoppdrag

---

src/main/kotlin/no/nav/familie/ba/sak/simulering/SimuleringService.kt
src/main/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiService.kt

Simulering ønsker simulering på komplett utbetalingsoppdrag og ikke bare endringen i oppdraget, løsningen er å legge inn et flagg for komplett utebtalingsoppdrag.
Oppgaven er ikke mulig å teste lokalt, bruker derfor preprod til å teste ut som løsningen virker.
Tester skrives etter at vi fått teste ut i Preprod om løsningen virker.

Mulighet å generere komplett utbetalingsoppdrag for revurdering.

---

src/main/kotlin/no/nav/familie/ba/sak/tilbakekreving/TilbakekrevingService.kt
src/main/kotlin/no/nav/familie/ba/sak/tilbakekreving/TilbakekrevingUtil.kt

Legger inn tilbakekrevingsperioder og feilutbetaling på visning av varselbrev. 
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4367

Legg til tilbakekrevingsperioder og feilutbetaling på varselbrev

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseSpesifikasjon.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakUtilsTest.kt

Fikser bug https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4635

Bugfix: Formatér dato i opphørsbegrunnelse

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt

Se beskrivelse frontend: https://github.com/navikt/familie-ba-sak-frontend/pull/1018
Frontend viser rett begrunnelse, men dette trengs for å komme gjennom validering backend. 
Nå må vi passe på å holde logikk frontend og backend i sync. Bør vi prøve å holde det ett sted? F.eks prioritere å skrive om slik at periodene kommer med personer m/utgjørende vilkår fra backend. 
Finnes tester på logikken (feila da jeg la inn feil fiks først)
Alt i ett

Fiks utgjørende 18årsvilkår ved fødselsdato den 1.

---

src/main/resources/application-dev.yaml
src/main/resources/application-e2e.yaml
src/main/resources/application-preprod.yaml
src/main/resources/application-prod.yaml
src/test/resources/application-postgres.yaml

La til onbehalfof for familie-oppdrag
- [/] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️

La til onbehalfof for familie-oppdrag

---

src/main/kotlin/no/nav/familie/ba/sak/tilbakekreving/Tilbakekreving.kt

Se slack: https://nav-it.slack.com/archives/C01G9BA8JKZ/p1620746101188100
Fikser feil når man endrer vilkår på revurdering med tilbakekreving: `“ERROR: update or delete on table \“behandling\” violates foreign key constraint \“gr_personopplysninger_fk_behandling_id_fkey\” on table \“gr_personopplysninger\“\n  Detail: Key (id)=(1069451) is still referenced from table \“gr_personopplysninger\“.”`
https://nav-it.slack.com/archives/GU4MVCGCD/p1620800703174800 manytoone?

Fiks db-oppdateringsfeil 

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestPersonInfo.kt

Fjernet deprecated kode familierelasjoner

Fjernet deprecated kode familierelasjoner

---

src/main/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiService.kt

Ikke valider opphør ved simulering

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestPersonResultat.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårResultat.kt
src/main/resources/db/migration/V132__legger_til_skjønnsmessig_vurdering_på_vilkår_resultat.sql

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4702
Legger til et felt som viser om vilkårsresultatet er basert på en skjønnsmessig vurdering

Legg til skjønnsvurdering på vilkårResultat

---

src/main/kotlin/no/nav/familie/ba/sak/config/BisysConfig.kt

Dersom applikasjonen er Bisys, tillat kun kall på /api/bisys*.
Implementert som et OncePerRequestFilter.

Bisys path authorization

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/StegService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/brev/BrevService.kt
src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/økonomi/ØkonomiService.kt

Fjern hentEtterbetalingsbeløp fra økonomiservice

Fjern toggle bruk_simulering.

---

src/main/kotlin/no/nav/familie/ba/sak/stønadsstatistikk/StønadsstatistikkController.kt

Må sende stønadsstatistikk på gamle vedtak. 
Ny controller for å se hvordan en VedtakDVH vil se ut for en liste med behandlinger og for å opprette tasker som sender til stønadsstatistikk
Nope
Testet manuelt.

Legger til controller for å kjøre stønadsstatstikk på liste behandlinger

---

src/main/resources/application-preprod.yaml
src/main/resources/application.yaml

Skrur ba-sak mot q1

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseSpesifikasjon.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseUtils.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4481
Legger til begrunnelse 1A og endrer tittelen på begrunnelse 1
https://confluence.adeo.no/display/TFA/16.1+Innvilgelse#

Legg til begrunnelses tekst for innvilgelse 1A.

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestUtvidetBehandling.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestVedtaksperiodeMedBegrunnelser.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/domene/Vedtaksbegrunnelse.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/domene/VedtaksperiodeMedBegrunnelser.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/vedtaksperiode/VedtaksperiodeService.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/vedtaksperiode/VedtaksperiodeServiceTest.kt

Deprecated vedtaksperioder og legger til kun utbetalingsperioder på behandling. Mindre justeringer på apiet for å endre på vedtaksperiode.
Nei
Ikke aktuelt
Alt i ett

Mindre endringer på API for å endre på begrunnelser for vedtaksperiode

---

src/main/kotlin/no/nav/familie/ba/sak/stønadsstatistikk/StønadsstatistikkService.kt

Ved ettersending, så klarer man ikke å hente statsborgerskap og bostedsadresse på de som er så gamle at de ikke har infoen i databasen.

Hente statsborgerskap/bostedsland ved ettersending av stønadstatistikk

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårResultat.kt
src/main/resources/db/migration/V137__legger_til_medlemskapsvurdering_på_vilkår_resultat.sql

Tenker å få denne på plass før koden som skal bruke feltet kommer senere. For å unngå konklikter.

Legger til ny kolonne for vurdert medlemskap.

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseSpesifikasjon.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseUtils.kt

Gjør begrunnelse opphør og reduksjon grunnet barns dødsfall tilgjengelig frontend.
For mer info se: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4828
Konfigurasjon av eksisterende rammeverk og ikke ending i logikk,

Feature/begrunnelse reduksjon opphør barn død

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/opphold/GrOpphold.kt
src/main/resources/db/migration/V138__rename_dodsfall_enum.sql
src/test/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkServiceTest.kt

- Oppdaterer enum
- Migrerer enums i dev (tvilsomt at vi skal plukke opp disse behandlingene, men har hatt trøbbel med ukjente enums i dev før når man har gjort større oppdateringer)
- En liten forbedring i visningsnavn på opphold
Er allerede gjort frontend (https://github.com/navikt/familie-ba-sak-frontend/pull/1142)

Rename enum for behnadlingårsak dødsfall

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingResultatMedSøknadTest.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4821
- Legger til støtte for fortsatt innvilget ved søknad
- Legger til test for dette caset (finnes allerede for ikke-søknad)
Alt i ett

Legg til støtte for fortsatt innvilget med søknad 

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakController.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/PersonController.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/PersongrunnlagService.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4701
Nei
Alt i ett

Støtte for å manuelt trigge oppdatering av registeropplysninger

---

src/main/kotlin/no/nav/familie/ba/sak/brev/BrevService.kt

https://nav-it.slack.com/archives/C01G9BA8JKZ/p1622803211071300

Bugfix: brevdato

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/FerdigstillBehandling.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/HenleggBehandling.kt

Rullet tilbake endring endring at behandling deaktiveres

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingResultatMedSøknadTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4832
Systemet klarte ikke utlede INNVILGET_OG_ENDRET for case hvor 
- barn fra tidligere behandling opphører
- nytt barn i behandling får innvilget og opphører
- opphørsdatoene er forskjellige
Legger til test for case og oppdaterer utledning av behandlingsresultat til å støtte testcaset.
Nei
Alt i ett

Bugfix: Behandlingresultat 

---

src/main/resources/application.yaml

Flytter ba-infotrygd-feed til teamfamilie namespace
Nei
Testet i preprod. Logginnslag i loggene for infotrygd-feed ved vedtak i ba-sak

Flytter infotrygd feed til teamfamilie namespace

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/oppgave/domene/RestOppgave.kt

Bumper kontrakter for å kunne søke på behandlingstype mot oppgave

Bumper kontrakter for å kunne søke på behandlingstype mot oppgave

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/vedtaksperiode/Opphørsperiode.kt

Slå sammen opphørsperioder som ligger ved siden av hverandre
For mer info se: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-4803  

Slå sammen opphørsperioder som ligger ved siden av hverandre

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseSpesifikasjon.kt

I begrunnelsesteksten for død-barn får order Barnebidrag feilaktig skrevet med litet b

Fikset feil i begrunnelsestekst på død-barn

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/vedtaksperiode/Opphørsperiode.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/vedtak/vedtaksperiode/OpphørsperiodeTest.kt

La til test for å teste sammenslåing av to opphørsperioder som ligger direkte etter hverandre.

Bugfix/slåsammen intilliggende opphørsperioder

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestFagsak.kt
src/test/kotlin/no/nav/familie/ba/sak/behandling/fagsak/RestFagsakTest.kt
src/test/kotlin/no/nav/familie/ba/sak/beregning/BeregningServiceTest.kt

Legger til gjeldende utbetalinger slik at frontend kan sjekke om barna i checkboxlisten får/eller har fått utbetalinger.
Se første commitmelding
alt i ett

Feature/søknad på barn med løpende ytelse

---

src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VedtakBegrunnelseSpesifikasjon.kt

Oppdater hjemler (11 -> 2, 4 og 11) for begrunnelse reduksjon grunnet 18år

Oppdater hjemler for begrunnelse reduksjon grunnet 18år

---

src/main/kotlin/no/nav/familie/ba/sak/ekstern/bisys/BisysController.kt

revertere kode som ikke skulle vært slettet i bisys

Reverter slettet felter i kontrakt for bisys

---

src/test/kotlin/no/nav/familie/ba/sak/kjerne/automatiskVurdering/pdlDatagenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/automatiskVurdering/testTest.kt

Legger til et enkelt testcase for sommerjobberene

Legg til enkle testcaser for automatisk saksbehandling

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårResultat.kt
src/main/resources/db/migration/V142__legger_til_del_bosted_på_vilkår_resultat.sql

La til nytt attributt er_delt_bosted på vilkårsresultat
Ingen ny logikk

Utvidet vilkårsresultat med nytt attributt delt bosted

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/VedtakBegrunnelseRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt

https://nav-it.slack.com/archives/GU4MVCGCD/p1624442681212700

Bugfix: generering av vedtaksbrev ved flere vedtak

---

pom.xml
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiIntegrasjonTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakControllerTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/SøkFagsakNegativeTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/fødselshendelse/FødselshendelseIntegrasjonTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/fødselshendelse/VilkårVurderingTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/søknad/SøknadGrunnlagTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/VedtakBegrunnelseTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/AvslagBegrunnelseOppdateringTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/sikkerhet/RolletilgangTest.kt
src/test/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkTest.kt

Se slack https://nav-it.slack.com/archives/C01G9BA8JKZ/p1624285169139000

Revert "Bump spring-boot-starter-parent from 2.4.5 to 2.5.1 (#1134)"

---

src/main/kotlin/no/nav/familie/ba/sak/ekstern/bisys/BisysController.kt
src/test/kotlin/no/nav/familie/ba/sak/ekstern/bisys/BisysControllerIntegrasjonsTest.kt
src/test/resources/ekstern/bisys-gammel-periode.json
src/test/resources/ekstern/bisys-med-perioder.json

Utvidelser i bisys api til å returnere maneuelt beregnet + bedre swagger doc
nei

Utvidelse i bisys api til å støtte manuelt beregnet + swager doc

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/automatiskvurdering/AutomatiskVilkårsvurderingUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/automatiskVurdering/AutomatiskVilkårsvurderinUtilsTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/automatiskVurdering/pdlDatagenerator.kt

noen enkle tester for automatisk vilkårsvurdering.
Er det detaljert nok testing? 
alt I et, i AutomatiskVilkårsvurderingUtilsTest
- [] Ja
- [x ] Nei

Tester automatisk vilkårsvurdering

---

src/test/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTaskTest.kt

Legg til test som passer på at fødselsehendelse alltid sendes til infotrygd.

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagService.kt

Opprydning: Fjerner toggle for skjønnsmessig vurdering som nå er skrudd på i prod.

Fjerner toggle for skjønnsmessig vurdering.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/IverksettMotFamilieTilbake.kt

Oppretter ikke tilbakekreving om ignorer valg er valgt

Oppretter ikke tilbakekreving om ignorer valg er valgt

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevService.kt

Hører til denne https://github.com/navikt/familie-ba-sak-frontend/pull/1254/checks?check_run_id=2971011871
Validerer at opphørsbrevene kun får inn én periode

Kast feilmelding dersom opphørt-brev får mer enn én feilmelding

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeMedBegrunnelser.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-5582
Viser til-og-med dato kun dersom den er tilbake i tid i brevene. 

Ikke vis tom-dato dersom den er er senere enn inneværende måned.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/arbeidsfordeling/ArbeidsfordelingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkEventListener.kt
src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkEventPublisher.kt
src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkService.kt
src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkTestController.kt
src/test/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkEventPublisherFailSafe.kt
src/test/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkServiceTest.kt

Reverts navikt/familie-ba-sak#1226

Revert "Send saksstatistikk ved manuelt enhetsbytte"

---

src/main/resources/application-preprod.yaml

PDL bruker ulike scopes for dev og q1
https://nav-it.slack.com/archives/C84H68ESC/p1625830520471800

Endrer scope for PDL i q1

---

src/main/resources/application-preprod.yaml

Komplettering til https://github.com/navikt/familie-ba-sak/pull/1234
Virker nå ✅

Sender med default i scope

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt

Legger til en hjelpemetode for vilkårResulteter for å gjøre lagAutomatiskVilkårsvurdering mer oversiktlig. 
Det er ingen ny funksjonalitet
alt i ett.

legger deler av lagAutomatiskVilkårsvurdering i en hjelpemetode

---

src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt

oppretter vedtak med totrinnskontroll, og lager oppdrag-task.
Ser ut til å feile de samme testene som #1238

opprett totrinnskontroll og iverksett mot oppdrag

---

src/test/kotlin/no/nav/familie/ba/sak/kjerne/automatiskVurdering/VerdikjedeTest.kt

_Flere tester på verdikjede. Disse tester at ting stopper i vilkår._
_Det er ingenting som skal passere vilkår enda. Det er fordi vi ikke har koblet på alt som skal skje videre enda._
_VerdikjedeTest.kt_

Lagt til flere tester av verdikjedetest_av_vilkår.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/automatiskVurdering/VerdikjedeTest.kt

_Henlegger behandling etter vilkår, fordi behandlinger ikke skal avslås automatisk._
_Er HENLAGT_AUTOMATISK_AVSLÅTT et dårlig navn?_
_BehandleFødselshendelseTask.kt_

AVSLÅTT til HENLAGT_AUTOMATISK_AVSLÅTT

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt

endre toggle

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/Vilkår.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/automatiskVurdering/VerdikjedeTest.kt

_Sende riktig vilkårsbegrunnelse med i manuell oppgave. Alle vilkår som feiler blir representert nå._
_På confluence står det at vi bare skal ta med begrunnelse til det første vilkåret som feiler. Jeg antar at det ikke er negativt å vise alle vilkår som feiler istedenfor._
_BehandleFødselshendelseTask.kt_

Feature/manuell oppgave for underkjent vilkår

---

src/main/kotlin/no/nav/familie/ba/sak/common/Utils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/automatiskvurdering/FiltreringsreglerService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/automatiskvurdering/FiltreringsreglerUtil.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/HenleggBehandling.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/Vilkår.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/automatiskVurdering/Util.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/automatiskVurdering/VerdikjedeTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/fødselshendelse/VilkårVurderingTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingStegTest.kt

Forbedret håndteringen av henleggelse, samt noen forenklinger/forbedringer.
Nei
Bare fikset testene som feilet.
Alt i ett

Feature/fødselshendelse småjusteringer

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/FerdigstillBehandling.kt
src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/config/ØkonomiTestConfig.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/automatiskVurdering/VerdikjedeTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingServiceTest.kt

_Behandling og fagsak blir avsluttet før manuell oppgave lages. _
_Oppretting av manuell oppgave krever en behandling som parameter. Dersom det finnes en åpen behandling fra før kan det ikke opprettes en ny behandling, men det skal likevel opprettes manuell oppgave. Jeg har da sendt med den åpne behandlingen til oppretting av manuell oppgave. Jeg vet ikke om dette er riktig måte å gjøre dette på. Hva skjer med den nye fødselshendelsen som ikke fikk behandling? Dersom man prøver å avslutte en tidligere behandling og fagsaken har status IVERKSETTER VEDTAK så vil fagsaken fortsette som løpende og ikke avsluttes selv om behandlingen avsluttes. (dette tror jeg er riktig)_
_BehandleFødselshendelseTask og VerdikjedeTest_

Avslutt behandling etter feilet vilkår

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt

oppdaterer den første vedtaksperioden for automatiskvurderte bar 
Usikker på hvor beskrivelsen for de to neste periodene(barn under 6år og barn under 18 år) blir satt, eller om det også skal skje her.

Oppdaterer vedtak for automatisk løp

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeMedBegrunnelser.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeMedBegrunnelseTest.kt

Gjenbruker eldre funksjon for å utlede fom dato på begrunnelse basert på vedtaksperioden.
Nei
Det finnes allerede tester for denne logikken
Alt i ett

BUG: fom på begrunnelse

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/automatiskvurdering/FødselshendelseServiceNy.kt
src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt
src/test/kotlin/no/nav/familie/ba/sak/config/LocalDateServiceTestConfig.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/AbstractVerdikjedetest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FødselshendelseFørstegangsbehandlingTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FødselshendelseRevurderingTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/JournalførOgBehandleFørstegangssøknadNasjonalTest.kt

Forsøker å løse/forbedre verdikjedetestene.

Bug/verdikjedetest fødselshendelser

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt

Legger på logging for å kunne se årsak til resultat som settes på revurdering.

Legger på logging.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt

Legger på mer logging for å finne ut hvorfor andeler ikke opprettes for revurdering ifm autobrev.

Legger på mer loggging for feilsøk.

---

src/main/kotlin/no/nav/familie/ba/sak/ekstern/tilbakekreving/HentFagsystemsbehandlingRequestConsumer.kt

unngår å lytte Kafka consumer i lokal

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/kjerne/fødselshendelse/VelgFagSystemService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/statsborgerskap/GrStatsborgerskap.kt
src/main/resources/pdl/statsborgerskap.graphql
src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/StatsborgerskapServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/AbstractVerdikjedetest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/mockserver/domene/RestScenarioPerson.kt
src/test/resources/pdl/pdlStatsborgerskap.json

Legger til bekreftelsesdato på statsborgerskap og logger denne på fødselshendelser for å se om vi kan bruke den som fom.
Alt i ett

Bekreftelsesdato på statsborgerskap

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseSpesifikasjon.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt

Endrer logikk slik at vi kun ser på iverksatte behandlingere for å utlede gjeldende utbetalingsperioder.
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-5821

Bug gjeldende utbetalingsperioder

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt

Begrunnelser utledet fra søker ble ikke inkludert i listen på vedtaksbegrunnelser.
se: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-5820
Testene har fra før ikke det detaljnivået.

Begrunnelse for søker skal vises om de gjelder for perioden

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt

Validering av begrunnelser knyttet til søker feiler.

Fikset valideringsfeil av begrunnelsestekster relatert til søker

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveController.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveControllerTest.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveServiceTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-5822
Nei, men må lage PR frontend også ettersom state ikke oppdaterer seg ved plukking.
Usikker hvor kritisk det er med test på dette.
Alt i ett

Hindrer saksbehandlere å overstyre fordeling dersom den allerede er plukket.

---

pull_request_template.md
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StatusFraOppdrag.kt
src/main/kotlin/no/nav/familie/ba/sak/task/StatusFraOppdragTask.kt

Etter å ha tittet litt på loggene fra lørdag natt så virker det som triggertiden på rekjøring ikke fungerer som forventet. Prøver derfor å endre litt til å heller kaste RekjørSenereException.

Prøver å forbedre rekjøring av venter på status fra oppdrag task.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fødselshendelse/FødselshendelseService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/BehandleFødselshendelseTask.kt

Kun kjør fødselshendelsetask mellom 06-21. Logg ut fagsak og behandling ved behandling.

Forebedring fødselshendelse

---

node_modules/.yarn-integrity
src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/totrinnskontroll/TotrinnskontrollService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/totrinnskontroll/domene/Totrinnskontroll.kt
src/main/resources/db/migration/V148__totrinnskontroll_kontrollerte_sider.sql

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-5745
Dette er i hovedsak en frontend-oppgave, men for å kunne dokumentere hva saksbehandler har vært innom persisterer vi sidene i databasen. Disse blir aldri hentet opp igjen.
Logikken ligger frontend, skriver tester der.
Alt i ett

Lagre sider beslutter har sett ved totrinnskontroll

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingService.kt

Henter riktig saksbehandler ved opprettelse av tilbakekrevingsbehandling slik at varselbrev får riktig signatur
Ikke mye, annet en at vi har fallback til SikkerhetContext.hentSaksbehandler()  hvis det ikke er utført totrinnskontroll.

Henter saksbehandler fra totrinnskontrollen ved opprett tilbakekrevingsbehandling

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingService.kt

Setter default tilbakekrevingsvalg om det ikke finnes noe

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/DokumentService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/DistribuerVedtaksbrev.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/JournalførVedtaksbrev.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/DistribuerDokumentTask.kt
src/main/kotlin/no/nav/familie/ba/sak/task/DistribuerVedtaksbrevTask.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/Utils.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-5907
Gjør distribusjon av dokumenter til en generell task.
Dette gjør at man ved manuell brevutsending ikke risikerer flere like journalposter som et resultat av gjentatte forsøk på sending frontend dersom distribusjon er nede. 
Vi vil fortsatt gi saksbehandler feil ved manuell utsending om journalføring er nede, men det fører ikke til manuell oppfølging/opprydding. Kan skrive om dette også til task i egen pr om vi ser det nødvendig.
_F.eks. commit for commit, alt …

Generell dokumentdistribusjon-task

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt

Bruke begrunnelser fra sanity for alle begrunnelser av typen "innvilgelse".

Bruke begrunnelser fra sanity for alle innvilgelser

---

src/main/resources/db/migration/V149__oppdater_opphorsbegrunnelse_enum.sql

https://github.com/navikt/familie-ba-sak/pull/1354/files
https://nav-it.slack.com/archives/GS8JFPNTH/p1630317064000900

Legg til migreringsscript for oppdaterte opphørsenums

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagService.kt

Bare automatisk inkluder barn i søknad som hadde utbetaling i føregående behandling.
For mer infor se: 
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6088

Filtrer vekk bar som ikke har utbetalinger fra forrige behandling

---

src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FødselshendelseFørstegangsbehandlingTest.kt

Test avhengig av satsendring fram i tiden

Test avhengig av satsendring fram i tiden

---

src/main/kotlin/no/nav/familie/ba/sak/config/CacheConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevKlient.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/NavnTilNedtrekksmeny.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseSpesifikasjon.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingUtils.kt
src/test/kotlin/DevLauncherPostgres.kt
src/test/kotlin/no/nav/familie/ba/sak/config/BrevKlientMock.kt

Henter tekster til nedtrekksmenyer fra sanity
Det er vanskelig å vite hva som er korrekt output uten å bruke outputet fra funksjonen

Henter tekster for nedtrekksmenyer fra Sanity

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt
src/test/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkServiceTest.kt

Mer tester for å sikre stønadsstatistikkkontrakt endringer

Kontrakt og tester

---

src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FamilieBaSakKlient.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/HenleggelseTest.kt

Forhåndsvisning er mocket ut mot familie-brev, men tester logikk for å hente ut data til brevgenerering.

Flytter over henleggelsetestene fra e2e.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakServiceTest.kt

Rapportere ut til GUI at person ikke finnes ved søk heller enn at det rapporteres om oppstått feil (500-feil). 
- [x ] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇
- [ x] Nei

Bugfix/gi tom liste ved fagsaksøk på person som ikke finnes

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt

Tilbakemelding dersom man:
- forsøker å avslå behandling med årsak klage
- legger til barn som allerede finnes
- forsøker å gå videre fra vilkårsvurdering uten barn

Mer validering på legg-til-barn-funksjonalitet

---

src/main/resources/application.yaml

Avklart med Fredrik og co at vi øker denne til 5 i første omgang.

Øker antall fødselshendelser i produksjon til 5 om dagen.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StatusFraOppdrag.kt

Ref alle feilene i helga: https://nav-it.slack.com/archives/CK59Y6EHE/p1630911567049500?thread_ts=1630748623.044900&cid=CK59Y6EHE

Ikke forsøk å hente status fra os i helger

---

src/main/resources/application.yaml

nytt namespace for infotrygd-barnetrygd 
Jeg tester i miljø før merge

Infotrygd barnetrygd flytter til nytt namespace

---

src/main/resources/application-preprod.yaml

Tilbakekreving flytter til GCP

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/ekstern/tilbakekreving/FagsystemsbehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/ekstern/tilbakekreving/HentFagsystemsbehandlingRequestConsumer.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingService.kt
src/main/kotlin/no/nav/familie/ba/sak/statistikk/producer/KafkaProducer.kt
src/test/kotlin/no/nav/familie/ba/sak/ekstern/tilbakekreving/HentFagsystemsbehandlingRequestConsumerTest.kt

Håndterte HentFagsystemsbehandlingRespons kontrakt endring

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/YtelsePersonUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/søknad/SøknadGrunnlag.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/søknad/SøknadGrunnlagService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/YtelsePersonResultatTest.kt

Legg til uregistrert barn i ytelsepersoner. Lag tom avslagsperiode for å begrunne avslag på uregistrerte barn.
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6184
Nei
Alt i ett

Bug: uregistrert barn, resultat og begrunnelse

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevUtil.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6322
Ikke sorter begrunnelser etter begrunnelsestype, men kun etter fom-dato

Ikke sorter etter begrunnelsestype

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/Datagenerator.kt

1. Mocke hentJournalposterForBruker så dokumentoversikten fungerer.
2. Legge inn toggle for utvidet-flyten

Mocke hentJournalposterForBruker og legge inn toggle for utvidet-flyt

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/Behandlingutils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/domene/Vilkår.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/JournalførOgBehandleFørstegangssøknadNasjonalTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårServiceTest.kt

Lagt inn vilkår for utvidet barnetrygd.
Nei
Alt i ett

Vilkår for utvidet barnetrygd

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/Behandlingutils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrereSøknad.kt
src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt

Når SB registrerer søknad skal behandlingen sin underkategori reflektere søknaden, men med samme regler som ved fastsettelse når behandlingen opprettes.
Nei
Alt i ett

[parprogrammert] Oppdaterer behandlingunderkategori når søknad blir registrert.

---

src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt

Fjerner test som feiler sporadisk på gha. Funksjonaliteten er dekket gjennom verdikjedetester.

Fjerner test som sporadisk feiler på gha

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/fødselshendelse/Evaluering.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/fødselshendelse/FødselshendelseService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/fødselshendelse/filtreringsregler/FiltreringsreglerService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt

Bedre logging på fødselshendelseløypa. Logger også hele behandlingen flere steder for å få med fagsakId.
Nei

Bedre logging på fødselshendelser

---

src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskService.kt

https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6480

Setter unik callid på hver enkelt autobrev-task.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt

Reduserer kognetiv kompleksitet for `TilkjentYtelseUtils.beregnTilkjentYtelse` som sonar klager på.
https://sonarcloud.io/project/issues?id=navikt_familie-ba-sak&open=AXwSR1-QfHA6elUvHDIW&pullRequest=1447&resolved=false&severities=CRITICAL&types=CODE_SMELL
Flytter i hovedsak kun beregningen av beløpsperioder i egen metode.

Flytter beregning av beløpsperioder for å redusere kognetiv kompleksitet

---

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestPersonInfo.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonController.kt

https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6168
Nei
Ikke aktuelt
Alt i ett

Legger til kommunenummer opp til frontend.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/domene/EndretUtbetalingAndel.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/domene/EndretUtbetalingAndelRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt

https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6482
Sletter endringer lagt inn når man går videre fra vilkårsvurdering, i likhet med oppførsel for begrunnelser. Midlertidig løsning før man tilpasser endringsperiodene til vilkårsendringer.

Feature/wipe endringsperioder 

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/ekstern/skatteetaten/SkatteetatenController.kt

Vi ønsker at skatteetaten-api returnerer mock-response som default nå i førsteomgang,
men testing avslørte at funksjonsbryteren ikke fungerte som forventet for prod.
Derfor må vi snu på den

Flipper toggle-logikk i SkatteetatenController

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/SanityBegrunnelse.kt

Sett vilkår til NULL dersom man ikke får inn noen vilkår.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/SøkFagsakNegativeTest.kt

Legger på en ekstra test for å fange opp en normalsituasjon der søker ikke finnes i PDL, uten at dette gir feil ut til SB.

Feature/ingen logging av feil ved søk på fagsak

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt

Lage endepunkt for steget behandlingresultat. Endepunktet gjør ingenting enn så lenge, men må merges før implementasjonen er på plass for at løsningen ikke skal feile
Forslag til hva man kan kalle steget i stedet for "Behandlingresultat"? (Kort på Favro som sier noe om funksjonaliteten steget skal implementere: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6556)

Lage endepunkt for behandlingsresultat-steg (1)

---

.github/workflows/build-and-deploy-preprod.yml
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/fødselshendelse/FødselshendelseService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingresultatSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingsresultatSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/RestFagsakTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/søknad/SøknadGrunnlagTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingStegTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FamilieBaSakKlient.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/JournalførOgBehandleFørstegangssøknadNasjonalTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/TekniskOpphørAvFødselshendelseTest.kt

Legge til funksjonalitet for behandlingsresultat-steget (flyttet vekk fra vilkårsvurderingssteget): 
- Beregne behanldingsresultat
- Simulere
- Generere vedtaksperioder

Behandlingsresultat-steg (2)

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevKlient.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/BrevPeriode.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeMedBegrunnelser.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeMedBegrunnelserController.kt
src/test/kotlin/no/nav/familie/ba/sak/config/BrevKlientMock.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeMedBegrunnelseTest.kt

Fikser prodfeilen som vi har sett https://logs.adeo.no/goto/b743c043734ba941c196283d0b1492cd
Henter begrunnelsestekstene til forhåndsvisning fra sanity

Hent forhåndsvisningen av begrunnelsestekstene fra familie-brev

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/Behandlingutils.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingTest.kt

Sette gjelder til "utvidet" hvis det eksisterer en løpende utvidet-sak, hvis ikke skal gjelder settes til "ordinær".

Utled "gjelder" basert på om det eksisterer en løpende andel med utvidet barnetrygd

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtilsEndretUtbetalingAndelTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6635
Dette er nok et "special case" som håndteres spesifikt og som gjør det litt utfordrende å holde koden forståelig og enkelt lesbar. Har lagt på noen kommentarer i koden for å avhjelpe dette.

Bug/endrete perioder back2back håndteres feil

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/SanityBegrunnelse.kt

Legger til felt for begrunnelsene

Legg til trigger

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevUtil.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseSpesifikasjon.kt
src/test/kotlin/no/nav/familie/ba/sak/config/BrevKlientMock.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevUtilsTest.kt

Sorter hjemler for brevtekst og lag test for at de er sorterte

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/VedtakService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårController.kt

Resetter til behandlingsresultat-steg dersom det legges til, fjernes eller endres på utbetalingsperioder.
Nei
Kunne lagt det til på en verdikjedetest, men hadde ikke tid atm.
Alt i ett

Resette steg ved endringer på behandlingsresultatsiden

---

src/main/kotlin/no/nav/familie/ba/sak/ekstern/skatteetaten/SkatteetatenController.kt

Endret til gyldig tom måned i skattestub
Nei

Endret tommåned for skattestub

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/DokumentService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/Utbetalingsperiode.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt

https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6521
Lagt på litt informasjon om andelen er påvirket av en endring slik at dette kan filtreres frontend. Litt smårydding i filene som er berørt også.
Nei
Har bare populert litt data og trenger ikke tester.
Alt i ett

Feature/vis-skjul funksjonalitet for deltajer på utbetaling

---

src/main/kotlin/no/nav/familie/ba/sak/common/Tid.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/domene/EndretUtbetalingAndel.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeMedBegrunnelser.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceUtil.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceUtilsTest.kt

Fiks feil hvo barn med endret utbetaling ikke kom med i begrunnelse for utvidet barnetrygd

Legg til barn med endret utbetalingandel

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/domene/EndretUtbetalingAndel.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtvidetVedtaksperiodeMedBegrunnelser.kt

Case 1 og 2 fikk samme begrunnelse som skal være i case 5 og 6. Denne PRen fikser dette.

Bruk riktig begrunnelse dersom det er en endret delt bosted ytelse, men ingen utvidet ytelse

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/AndelTilkjentYtelse.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/domene/EndretUtbetalingAndel.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingsresultatSteg.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValideringTest.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7077
Legger til validering at ingen delt bosted -endringer krysser utvidet tilkjent ytelse

Legg til validering på at delbosted endring ikke krysset utvidet tilkjent ytelse

---

src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/VilkårTilTilkjentYtelseTest.kt
src/test/resources/beregning/vilkår_til_tilkjent_ytelse/søker_med_utvidet_og_ett_barn_inntil_to_perioder.csv

Koblet til denne: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6485
Nei
Alt i ett

Legger til csv tester på utvidet og småbarnstillegg.

---

.github/workflows/build-pr.yml

Deler pull request  -actionene i tre nye jobber:
* Sonar + ktlint ~ 2 minutter
* Alle tester som ligger under verdikjedetest-mappen ~ 8 minutter
* Alle tester som **ikke** ligger under verdikjedetest-mappen ~ 10 minutter
Krever at vi endrer her:
https://github.com/navikt/familie-ba-sak/settings/branch_protection_rules/12279110
Under **Require status checks to pass before merging**

Parallelliser tester

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/InfotrygdBarnetrygdClient.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/InfotrygdService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/fødselshendelse/VelgFagSystemService.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/InfotrygdBarnetrygdClientTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/fødselshendelse/VelgFagsystemIntegrasjonTest.kt

Bytter ut endepunktet vi bruker til å finne ut om bruker har saker, men ikke løpende utbetalinger, i Infotrygd
jfr. [slack-tråd i team-familie-dev](https://nav-it.slack.com/archives/CJN0STWB0/p1636391706055800?thread_ts=1636370177.052500&cid=CJN0STWB0)

Fikser filtreringsregel nr 4 for fødselshendelser

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/Behandlingutils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingsresultatSteg.kt

Systemet validere at man ikke betaler ut mer enn full sats av barnetrygden for et barn.
Valideringen er gjort mot iverksatte behandlinger, men det er et ønskemål om at man skal gjøre det mot alle behandlinger som har blitt sendt til godkjenning.
See PR: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7034
Valideringen er sterkt dataavhengig, og ettersom vi mockker dataen er det vanskelig å få et vanntett test.

Feature/validering allerede innvilget til annen søker ved godkjenning

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/InfotrygdFeedClient.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/InfotrygdFeedService.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/domene/FeedDto.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/JournalføringService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/SendStartBehandlingTilInfotrygdTask.kt
src/test/kotlin/no/nav/familie/ba/sak/config/AbstractSpringIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/InfotrygdFeedServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt

This PR is to fix the branch feature/infotrygd-feed-behandling, which has an unsigned commit.
Add a feature that ba-sak send Infortrygd feed when creating a førstgangsbehandling. Sending of the feed is feature toggled.

PR-Fix: Send Infotrygd feed når opprett en førstegangsbehandling

---

src/main/resources/db/migration/V167__opprett_person_ident_og_legg_til_kolonne_aktorid.sql

La til db-tabell personident og la til nye kolonner aktoer_id i alle tabeller som refererer person_ident.
Se: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7204
Bara db-endringer som ikke påvirker noen kode.

La til DB-tabel personident

---

src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/InfotrygdFeedServiceTest.kt

Fix InfotrygdServiceTest

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatPerson.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/YtelsePersonUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultaterTest.kt
src/test/resources/behandlingsresultatPersoner/FGB1_AVSLÅTT_UREGISTRTERT_BARN.json
src/test/resources/behandlingsresultatPersoner/FGB5_DELVIS_UREGISTRERT_BARN.json

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7239
Legger tilbake støtte for avslag på grunn av uregistrerte barn. Mulig å teste dette med json-testene.
Nei
Alt i ett

BUG: avslag på uregistrerte barn

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/søknad/GrunnlagController.kt

Fikser bug hvor det ble brukt fagsakId i stedet for behandlingId til å returnere oppdatert behandling.
Nei, men er det noe lett måte å sjekke om dette skjer andre steder også? Vi har hatt lignende issues tidligere med vedtakId også :( 
Ikke aktuelt
Alt i ett

BUG: legg til barn

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt

Counter for migrering som går ok
Nei

Counter for migrering som går ok

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevUtil.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceUtil.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevUtilsTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceUtilsTest.kt

Favro https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7406
Gjør sånn at barn fra begrunnelsene som ikke er innvilgelsesbegrunnelser ikke kommer med i innvilgelsesperioden med mindre de har en utbetaling

Filtrer bort alle barn som ikke er fra innvilgelsesbgerunnelsene eller har utbetaling i innvilgelsesperiodene

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autobrev/Autobrev6og18ÅrService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/BrevUtil.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseSpesifikasjon.kt

Favro https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7400
Legg til egne begrunnelser for autovedtak 6 og 18 år

Legg til egne begrunnelser for autovedtak 6 og 18 år

---

.deploy/nais/kafka/dev/bisys_opphoer_av_barnetrygd.yaml
.deploy/nais/kafka/dev/bisys_utvidet_barnetrygd.yaml
.deploy/nais/kafka/prod/bisys_opphoer_av_barnetrygd.yaml
.deploy/nais/kafka/prod/bisys_utvidet_barnetrygd.yaml
.github/workflows/build-and-deploy-krise-rett-i-prod.yml
.github/workflows/build-and-deploy-preprod.yml
.github/workflows/build-and-deploy-prod.yml
.github/workflows/build-pr.yml

Lager topics for bisys(avien)
Tar ibruk innebygget cache i setup-java
bruker fetch-depth: 0 for å fikse sonar på PRer
Har endret på deploy-prod pipeline, må følge med ved deploy for å se at det virker.
Ikke mulig å teste dette.

Lager topics for bisys(aiven)

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/domene/VilkårResultat.kt

fikser bug ved bruk av utdypendeVilkårsvurderinger felt. må oppdatere erDeltBosted, erSkjønnsmessigVurdert og erMedlemskapVurdert

gjør utdypende vilkårsvurdering bakoverkompatibel

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggBarnetrygdGenerator.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt
src/test/kotlin/no/nav/familie/ba/sak/config/EfSakRestClientMock.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggUtilsTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/EndretUtbetalingAndelTest.kt

Retter bug hvor småbarnstilleggandeler ble fjernet når man la inn endret andeler. Mindre forbedringer på flyt.
Nei
Alt i ett

BUG: småbarnstilleggg og autovedtak

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/Autovedtak6og18årOgSmåbarnstillegg.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/AutovedtakNyfødtBarnFraFør.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/AutovedtakNyfødtFørsteBarn.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/domene/maler/FellesDelmaler.kt

Autobrev skal ha enhet med i signaturen på brevet.

Feature/autounderskrift på autobrev

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseSpesifikasjon.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7420

Legger til ny avslagsbegrunnelse.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StatusFraOppdrag.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt

Oppdaget ved å lese logger i prod.
Nei
Ikke aktuelt
Alt i ett

Håndterer rekjørSenereException eksplisitt slik at det ikke logges error ved slike feil som kastes.

---

app-prod.teamfamilie.yaml

For å støtte Stigs PR https://github.com/navikt/aad-iac/pull/664/files

Legger til bidrag-grunnlag som pre-auth app i prod

---

app-prod.teamfamilie.yaml

Fikset feil i indentering i nais-prod

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/domene/FeedDto.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/IverksettMotOppdrag.kt
src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/SendFødselsmeldingTilInfotrygdTask.kt
src/main/kotlin/no/nav/familie/ba/sak/task/SendVedtakTilInfotrygdTask.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/SendFødselsmeldingTilInfotrygdTaskTest.kt

slik at infotrygd setter riktig opphørsdato
Flytter Send Vedtak til infotrygd feed til egen task og bruker første utbetalingsdato i stedet for vedtaksdatp

Sender første utbetalingsdato istedenfor vedtaksdato til infotrygdfeed

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VurderTilbakekrevingSteg.kt

stopper migreringsbehandling i simulering når det finnes en feilutbetaling eller etterbetaling

stopper migreringsbehandling i simulering når det finnes en feilutbetaling eller etterbetaling

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeMedBegrunnelser.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksbegrunnelseTest.kt

Favro: (https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6760)
Legg ved barna sine føselsdatoer når det er avslag på søker, men sørg for at begrunnelsen ikke gjelder for barna

Fiks at barnas fødselsdager kommer med om det er avslag på søker

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/common/Tid.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggBarnetrygdGenerator.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/SmåbarnstilleggUtilsTest.kt

Retter bug hvor man kunne få småbarnstillegg uten at barnet som har vært under 3 år får utbetalt barnetrygd.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7398
Nei
Alt i ett

BUG: innvilget småbarnstillegg uten barn under 3 år med utbetaling

---

.github/workflows/build-pr.yml
src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/domene/EndretUtbetalingAndel.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/domene/EndretUtbetalingAndelTest.kt

* Kjør sonar sammen med testene 
* Gjør funksjonell feil til FunksjonellFeil

Feilmelding endret utbetaling

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt

Retter bug: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7463
Tester her:
https://barnetrygd.dev.adeo.no/fagsak/100021901/100034201/vedtak

Bug/vedtaksbegrunnelse for barn 18 år

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt

Mer logging av migrering

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingStegController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VurderTilbakekrevingSteg.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt

håndterte iverksettelse for migreringsbehandling slik at den kan avsluttes med automatisk totrinnskontroll og sender ikke brev

håndterte iverksettelse for migreringsbehandling slik at den kan avsluttes med automatisk totrinnskontroll og sender ikke brev

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingsresultatSteg.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValideringTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/EndretUtbetalingAndelTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FødselshendelseRevurderingTest.kt

Skriver om til å bruke sist iverksatte behandling dersom det ikke finnes behandling som ligger til godkjenning på fagsak.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7402
Har ikke skrevet noen flere tester, så tar innspill på hvordan man evt kunne testet dette på en smidig måte.
Alt i ett

BUG: Utbetalingssikkerhet per barn

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/metrikker/TeamStatistikkService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingServiceTest.kt

Ekskluderer åpne behandlinger som ligger på arkiverte fagsaker. Legger til daglig logging av behandlinger som har ligget lenge.
Nei
Alt iett

Forbedringer team statistikk

---

.github/workflows/build-and-deploy-preprod.yml
.github/workflows/build-and-deploy-prod.yml
.github/workflows/manual-deploy-kafka-aiven.yml

Flytter deploy av kafka topics til egen workflow

flytter deploy av kafka topics på aiven til manuell workflow

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/Aktør.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/IdentController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/IdentHendelseTask.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/personident/IdentHendelseTaskTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentServiceTest.kt

Første del av å lytte på endringer fra PDL.
Lager denne nå for å synce med Marcus.
Tar mulige forbedringer/endringer med teamet i en senere PR.
Nei
Alt i ett

Feature/ del 1 sync ident

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/IverksettMotFamilieTilbake.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VurderTilbakekrevingSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingKlient.kt
src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt

fjerner toggles som vi ikke trenger lenger

Toggles rydding

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt

legg til uregistrerte barn ved avslag på søker
- [] Nei

legg til uregistrerte barn ved avslag på søker

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt

Vi ønsker kun å hente behandling som er sendt til godkjenning og ikke alle som har vært innom steget.

BUG: Legger til ekstra sjekk på at beslutte vedtak steget ikke skal være utført.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt

legger på steg IVERKSETT_MOT_FAMILIE_TILBAKE for årsak småbarnstillegg
TODO: Se på mulighet for å refaktorere noe på BehandlingSteg.kt hentNesteSteg

legger på steg IVERKSETT_MOT_FAMILIE_TILBAKE for årsak småbarnstillegg

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/sivilstand/GrSivilstand.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7413

BUG: Bruker eneste sivilstand dersom det kun finnes en selv om ikke fom er gyldig.

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/VelgFagSystemService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt
src/main/resources/application-dev.yaml
src/main/resources/application-preprod.yaml
src/main/resources/application.yaml
src/test/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/VelgFagsystemIntegrasjonTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/UtgjørendePersonerTest.kt
src/test/resources/application-postgres.yaml

Tar i bruk ny toggle som skal støtte gradvis utrulling via unleash i stedet for hardkodet verdi.
Skal teste dette litt i preprod før det merges :) 
Nei
Blir manuell testing i preprod på denne.
Alt i ett

JavaZone forbedring - gradvis utrulling mot 100% behandling av fødselshendelser i ba-sak

---

src/main/kotlin/no/nav/familie/ba/sak/common/EnvService.kt
src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkService.kt
src/test/kotlin/no/nav/familie/ba/sak/config/ClientMocks.kt
src/test/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/task/FerdigstillBehandlingTaskTest.kt

Fødselshendelses behandlinger ble ikke sendt til datavarehus.

Bugfix for fødselshendelsesbehandlinger til datavarehus(saksstatistikk) 

---

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestSlettVilkår.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårServiceTest.kt

Pushet legge til utvidet barnetrygd på ny bransje med signed commits

kopierte endringer fra feature/rvd_bakover_i_tid_utvidet_barnetrygd bransje slik at det kan meges i master

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingServiceTest.kt

Fikser feil hvor rollback ikke fungerte fordi 'parent' metode ikke var annotert med transactional.
Hvordan sikrer vi oss mot at dette skjer igjen?
Alt i ett

BUG: rollback behandling opprettelse

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/dokument/DokumentController.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7544

BUG: Fjerner dobbel send-brev i url.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/småbarnstillegg/VedtakOmOvergangsstønadService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/SendTilBeslutter.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/BehandleSmåbarnstilleggTest.kt

Opprett vurder livshendelse oppgave i stedet for behandle sak og ferdigstill denne type behandlinger når behandlingen blir sendt til beslutter i tillegg til underkjenningsoppgave og behandle sak oppgave.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7531
Nei
Alt i ett

Småbarnstillegg autovedtak -> manuell behandling lager vurder livshendelse oppgave

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrerPersongrunnlag.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårServiceTest.kt

1. støttet opprettelse av helmanuell migrering
2. genererte perioder i vilkårsvurdering automatisk
- [x ] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇

opprettelse av helmanuell migrering

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt

Oppdatere kjøreplan for migrering/infotrygd ihht. [kjøredatoer](https://navno.sharepoint.com/:x:/r/sites/fag-og-ytelser-stonadsokonomi/_layouts/15/Doc.aspx?sourcedoc=%7B651B1247-4E33-4737-927A-4404D16C0C5D%7D&file=Registrering-%20stopp-%20og%20utbetalingsdatoar2022.xlsx&action=default&mobileredirect=true&web=1&cid=0d0cd82f-16e6-46cc-b7ac-fe60d13714e2) for 2022

Oppdatert kjøreplan for migrering/infotrygd

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/småbarnstillegg/VedtakOmOvergangsstønadService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksbegrunnelseFritekst.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtvidetVedtaksperiodeMedBegrunnelser.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtvidetVedtaksperiodeMedBegrunnelserTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/BehandleSmåbarnstilleggTest.kt

Løser denne: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7527, og legger til litt debuginformasjon til neste gang dette skjer.
Nei
Alt i ett

Debugging i prod/finner ikke segment

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/VelgFagSystemService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/VelgFagsystemIntegrasjonTest.kt

Ingen funksjonell endring, bare for metrikkenes del.

Trekker ut sjekk for statsborgerskap på mor i egen branch for å telle metrikker for denne sjekken.

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevTask.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevTaskTest.kt

Oppretter toggle for å sende autobrev ved opphør av småbarnstillegg
(bittesmå trunk based PR'er, som Henning ønsket hehe)
opprettet toggle her
https://unleash.nais.io/#/features/strategies/familie-ba-sak.autobrev-opphor-smaabarnstillegg

oppretter toggle for sending av autobrev ved opphør av småbarnstillegg

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/AutobrevSmåbarnstilleggOpphørTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/RennameMeTest.kt

Lage spørring som finner riktige løpende behandlinger hvor småbarnstillegg opphører for en gitt måned
Usikker på om spørringen dekker alle caser

Feature/autobrev smabarnstillegg spørring

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/AutovedtakService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/småbarnstillegg/VedtakOmOvergangsstønadService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingMetrikker.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/UtvidetBehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/TilbakestillBehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/VedtakRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/VedtakService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/BehandleSmåbarnstilleggTest.kt

Istedet for å prøve å rydde opp i behandlingen slik at den kan behandles videre rekjører jeg bare vilkårsvurderingssteget slik at saksbehandler kommer til behandlingsresultatsteget etter at behandlingen er henlagt.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7590
Nei
Alt i ett

Resett til behandlingsresultatsteget etter henleggelse autovedtak småbarnstillegg

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/config/ApplicationConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/config/SwaggerConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/ekstern/bisys/BisysController.kt
src/main/resources/application.yaml
src/test/kotlin/DevLauncher.kt

Bruker springdoc i stedet for springfox for swagger, siden springfox er lite maintained
Kun bisys som har swagger
Testet lokalt  og skal testes i miljø Edit: testet ok i miljø
Alt i ett

Bytter fra springfox til springdoc for swagger

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevType.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/Brev.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/EnkeltInformasjonsbrev.kt

Backend for https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6739
Legger til INFORMASJONSBREV_FØDSEL_UMYNDIG og INFORMASJONSBREV_FØDSEL_MINDREÅRIG, men ikke `Informasjonsbrev kan søke` helt enda fordi vi trenger en dokumentliste for det brevet
Har bare lagt til nye typer

Legg til INFORMASJONSBREV_FØDSEL_UMYNDIG og INFORMASJONSBREV_FØDSEL_MINDREÅRIG

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BegrunnelseUtil.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevbegrunnelseTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/TestKlasser.kt
src/test/resources/brevbegrunnelseCaser/AVSLAG_MANGLER_OPPLYSNINGER.json

Legg ved søker på utvidet brevperiode når det er avslag

Legg til søker i utvidet og lag test for case som gikk galt

---

src/main/kotlin/no/nav/familie/ba/sak/task/StartSatsendringForAlleBehandlingerTask.kt

Micro PR for trigging av satsendring i prepro

Bugfix for trigging av satsendring for alle behandlinger i preprod

---

src/main/kotlin/no/nav/familie/ba/sak/task/StartSatsendringForAlleBehandlingerTask.kt

Fjerner properties som ikke brukes

Fjerner properties som ikke brukes i satstendringstask

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonController.kt
src/main/kotlin/no/nav/familie/ba/sak/sikkerhet/TilgangService.kt
src/test/kotlin/no/nav/familie/ba/sak/sikkerhet/TilgangServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/util/BrukerContextUtil.kt

Skriver om til å kun sjekke tilgang for personer som faktisk behandles på behandling og fagsak. Ved henting av person så blir barn man ikke har tilgang til maskert.
Nei
Alt i ett

"Reverter" sjekk på søker + alle relasjoner 

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonClient.kt

Fikser feil: https://logs.adeo.no/app/discover#/doc/tjenestekall-*/tjenestekall-team-teamfamilie-prod-000018?id=hGC4I34B-agyzZKCqX-G

BUG: Prøver å plukke ut strengeste tilgang først og hvis ikke bruker jeg første

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/task/StartSatsendringForAlleBehandlingerTask.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/BehandlingSatsendringTest.kt

Ønsker å kunne kjøre satsendring for alle behandlinge

Går fra Long til Int for sats i finnBehadlingerForSatsendring

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt

Fagsaker blir avsluttet feil månded ettersom stonad_tom er av typen yearmonth men ble sammenlignet med localdate.

Tilkhenting av fagsaker som skal avsluttes.

---

app-preprod.teamfamilie.yaml
app-prod.teamfamilie.yaml
src/main/resources/application.yaml

Raskere kjøring og bedre utnyttelse av resurser i kubernetes

Kjører tasker async og kontinuerlig

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/Aktør.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/Personident.kt

Gir alle brukere tilgang å oppdatere aktoer og personident tabellene

Gir alle bruker tilgang å oppdatere aktoer og personident tabellene

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/Aktør.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/Personident.kt

Disbale adgangskontroll til aktørid og personident.

Feature/disable adgangskontroll til db tabeller aktørid og personident

---

.deploy/nais/kafka/dev/bisys_opphoer_av_barnetrygd.yaml
.deploy/nais/kafka/prod/bisys_opphoer_av_barnetrygd.yaml

Change the retention hours of Bisys kafka topic to 168 (7 days)

change Bisys kafka topic retention hours

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakRepository.kt
src/main/resources/db/migration/V173__oppdater_tilkjent_ytelse_stonad_fom_fra_andel_tilkjent_ytelse.sql
src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceIntegrationTest.kt

Sett riktig stonadFom og stondTom på tilkjentytelse.

Sett riktig stonadfom og stonadtom på tilkjentytelse

---

src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkEventListener.kt

fjernet restriksjon å sende data til dvh for migrerte behandlinger. Dvh skal ignorere det i sin side.

fjernet restriksjon å sende data til dvh for migrerte behandlinger. Dvh skal ignorere det i sin side.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingStegTest.kt

La til en validering for å stoppe helmanuell migreringer i vilkårsurdering hvis minst ett av barna ikke har delt bosted

Stopper helmanuell migreringer i vilkårsurdering hvis minst ett av barna ikke har delt bosted

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/TilbakestillBehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/SatsendringTask.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/BehandlingSatsendringTest.kt

Dersom fagsak har åpen behandling på seg ønsker vi å tilbakestille denne til vilkårsvurderingen i stedet for å feile hardt.
Om den aktive behandlingen ligger til iverksetting eller hos beslutter så feiler den og rekjører igjen ett døgn senere.
Nei
Alt i ett

[parprogrammert med Ida] Feature/satsendring behandling utredes

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringService.kt
src/main/resources/db/migration/V174__kickstart_satsendring_06_01_2022.sql

Trigger satsendringer. Akkurat nå plukkes det kun 100 behandlinger ved hver kjøring.

Legger til task som plukker ut fagsaker som skal kjøre satsendring.

---

.deploy/nais/app-prepod-gcp.yaml
.github/workflows/build-and-deploy-preprod.yml

initiell yaml for GCP med database konfigurasjon

initiell yaml for GCP med database konfigurasjon

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringService.kt

Fikser bug hvor systemet oppretter tasker X ganger noder tilgjengelig. Ingen fagsaker har blitt kludret til av dette, men greit å ha denne sjekken

BUG: Legger til Leader sjekk for å unngå flere tasker/behandlinger på fagsaker.

---

.deploy/nais/app-prepod-gcp.yaml

oppdaterte yaml fil for å fikse syntaks problem

oppdaterte yaml fil for å fikse syntaks problem

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/OppdaterVilkårsvurderingTest.kt

Fikse en bug som stanset en satsendringssak. Sørge for at kun perioder som er oppfylt skal bli dratt med videre fra forrige behandling for utvidet-vilkåret. 

Bugfix/kun kopiere over oppfylte perioder fra utvidet-vilkåret

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/satsendring/SatsendringService.kt

Sjekker om åpen behandling har siste sats og isåfall skal man ikke lage satsendringsbehandling etterpå uansett.

BUG: sjekker om behandling har siste sats først

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StatusFraOppdrag.kt

Slack: https://nav-it.slack.com/archives/C01G9BA8JKZ/p1641897424040700

Forbedring: Endrer til å vente 1 min som blir 100 minutter om det feiler kontinuerlig i stedet for 24t.

---

.deploy/nais/app-preprod-gcp.yaml
.github/workflows/build-and-deploy-preprod_gcp.yml
src/main/kotlin/no/nav/familie/ba/sak/config/KafkaAivenConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/config/KafkaConfig.kt
src/main/resources/application-prepod-gcp.yaml

la til konfigurasjon for å deployere applikasjon i gcp

la til konfigurasjon for å deployere applikasjon i gcp

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingStegTest.kt

Feiler om resultatet er fortsatt innvilget på manuelle migreringsbehandlinger.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7700
Nei
Alt i ett

Validering fortsatt innvilget manuell migrering

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/Aktør.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/Personident.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrerPersongrunnlag.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt
src/test/kotlin/no/nav/familie/ba/sak/ekstern/skatteetaten/SkatteetatenServiceIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/KonsistensavstemmingUtplukkingIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragIntegrasjonTest.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiIntegrasjonTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/VilkårVurderingTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceIntegrationTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakControllerTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/VedtakServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/RevurderingMedEndredeUtbetalingandelerTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårServiceTest.kt

Lagrer som default ikke Aktoer id
See: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7627

Lagrer som default ikke Aktoer id

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt

Ny feilmelding: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7700

Chore: Endrer feilmelding.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtil.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtilsTest.kt

Slack https://nav-it.slack.com/archives/CK59Y6EHE/p1641985650038100
Finn opphørsdato fra opphørsperioder og ikke utbetalingsperioder

finn opphørsdato fra opphørsperioder og ikke utbetalingsperioder

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/IverksettMotOppdrag.kt

Sending av vedtak til Infotrygd feed kan begrenses til første gangen det iverksettes noe på fagsaken.
Mulig det kan være aktuelt å sende vedtak til feed ved andre typer av forrigeIverksatteBehandling enn MIGRERING_FRA_INFOTRYGD_OPPHØRT også..

Sender vedtak til Infotrygd kun ved førstgangs iverksettelse

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårServiceTest.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7729

BUG: Endrer underkategori ved post/delete utvidet vilkår.

---

.deploy/ba-sak-proxy/Dockerfile
.deploy/ba-sak-proxy/nais.yaml
.deploy/ba-sak-proxy/nginx.conf
.github/workflows/deploy-proxy-dev-fss.yml

For å unngå nedetid for andre apper lager vi en proxy som redirigerer trafikkk til gcp

Laget proxy for ba-sak som brukes i en overgangsperiode 

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtil.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/Brev.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/Dødsfall.kt

Setter at `DØDSFALL` brevmalen er et vedtak og endrer navn til `VEDTAK_OPPHØR_DØDSFALL` 
Fant ikke noe sted Brevmal lagres i databasen, så endring i enum burde gå bra. Skrik ut om du er uenig. 
Bare endring i enum

Endre navn DØDSFALL -> VEDTAK_OPPHØR_DØDSFALL og sett vedtak til true

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt

Midlertidig skrudd av støtte for kode 6 inntil det kan behandles 
nei
alt i ett

Kaster migreringsfeil ved kode 6 gradering

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt

Etter datalast i q1 må denne nå settes til 01.01.2022 for å være i synk med Infotrygd
Nei
Gjelder bare preprod

Setter ny vedtaksdato på migreringssaker i preprod

---

.deploy/nais/app-prod-gcp.yaml
.github/workflows/build-and-deploy-prod_gcp.yml
src/main/kotlin/no/nav/familie/ba/sak/config/KafkaAivenConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/config/KafkaConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/ekstern/tilbakekreving/HentFagsystemsbehandlingRequestConsumer.kt
src/main/kotlin/no/nav/familie/ba/sak/statistikk/producer/KafkaProducer.kt
src/main/resources/application-prod-gcp.yaml

Klargjøre ba-sak i prod-gcp

---

.github/workflows/build-and-deploy-prod_gcp.yml

endret pipeline slik at det ikke deployeres automatisk

---

.deploy/nais/app-preprod.yaml
.deploy/nais/app-prod.yaml

Vi opplever for tiden litt kapasitetsproblemer mot db, så prøver med mer kraft
NBNBNB denne fører til nedetid ved deploy

Mer cpu og minne til db i preprod + prod

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/YtelsePersonUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/config/AbstractMockkSpringRunner.kt
src/test/kotlin/no/nav/familie/ba/sak/task/FerdigstillBehandlingTaskTest.kt
src/test/resources/behandlingsresultatPersoner/RV16_ENDRET_FLYTTER_FOM_TIDLIGERE.json

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7795

Legger til test for endring av fom en måned tilbake. Fikser bug i kode.

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/JournalføringController.kt
src/test/kotlin/no/nav/familie/ba/sak/config/IntegrasjonClientMock.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7799
For å unngå proxy-metode for å hente pdf.
Nei
Ikke aktuelt
Alt i ett

Legger til endepunkt for å hente dokument bytearray som PDF uten ressurs som wrapper.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseSpesifikasjon.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7790
Legg til nye begrunnelser
Bør Ikke være nødvendig

Legg til nye begrunnesler

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiService.kt

fikset simuleringsresultat feil

fikset simuleringsresultat feil

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/Utbetalingsperiode.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt

Forbedring av kall mot databasen. 100k i timen for personident og 50k for endret utbetaling andel fordi vi hentet personidenter og endrede andeler per vedtaksperiode x antall standardbegrunnelser for hver gang man hentet utvidet behandling.
Nei

Forbedrer henting av data fra databasen i loop ved henting av gyldige begrunnelser per vedtaksperiode.

---

.deploy/nais/app-preprod.yaml
.deploy/nais/app-prod.yaml

Legger til familie-tilbake i outbound-rules

---

src/main/resources/db/migration/V180__endre_constraint_vedtaksperiode.sql
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceTest.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7575
Fjerner constraint for å tillate endrede utbetalinger i samme periode

Tillat vedtaksperioder i samme periode

---

src/main/resources/db/migration/V182__opprett_tabell_sett_paa_vent.sql

Opprettet tabell sett_paa_vent

Opprettet tabel sett paa vebt

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårServiceTest.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7834

BUG: Tillater å legge til utvidet perioder i vilkårsvurderingen om det allerede foreligger utvidet vilkår på behandlingen.

---

src/main/resources/db/migration/V184__opprett_tabell_po_doedsfall.sql

Lage tabell for dødsfall som inneholder dato for dødsfall + dødsboadresse
Del av denne oppgaven: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7792

Opprett tabell po_doedsfall

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/VelgFagSystemService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/VelgFagsystemIntegrasjonTest.kt

Bug/sak uten løpende infotrygd

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiService.kt

Mulighet p bypasse 409 feilved iverksetting mot økonomi.
Skriver test nå etter at Pr er opprettet.

Mulighet å bypasse 409 feil ved iverksetting mot økonomi

---

.deploy/nais/app-preprod.yaml
.deploy/nais/app-prod.yaml
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/migrering/MigreringRestClient.kt
src/main/resources/application-preprod.yaml
src/main/resources/application-prod.yaml
src/main/resources/application.yaml
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/migrering/MigreringRestClientTest.kt

Varsler ba-migrering om migreringer utført av saksbehandler. Slik at ba-migrering kan verifisere mot infotrygd.
alt i ett

Varsler ba-migrering om migreringer utført av saksbehandler

---

src/main/resources/db/migration/V186__legg_kolonner_til_po_doedsfall.sql

Legge til kolonner på po_doedsfall tabellen som ble glemt i første omgang. 

Legg til kolonner opprettet av/tidspunkt og endret av/tidspunkt

---

.deploy/nais/app-prod.yaml

Skalerer opp ba-sak for å få igjennom konsistensavstemming

Mer minne og cpu

---

src/main/kotlin/no/nav/familie/ba/sak/internal/TestVerktøyController.kt

Ettersom leesah topicen til PDL tidvis er nede i preprod trenger vi en mer smidig måte å teste fødselshendelseløypa på. Dette legger opp til at vi kan teste i preprod selv om leesah ikke produserer meldinger.

Legger til testendepunkt for å trigge fødselshendelse.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdGenerator.kt

Fix for https://logs.adeo.no/app/discover#/doc/tjenestekall-*/tjenestekall-team-teamfamilie-prod-000018?id=lrV6un4BFmyih9jCRe7r
`Invalid value for Year (valid values -999999999 - 999999999): 1000000000`
LocalDateTimeline bruke date.plusDays(1) for å se om det er overlapp i perioder. Setter derfor tom for utvidetvilkår til TIDENES_ENDE - 1 dag når den er null

Bruk TIDENES_ENDE minus én dag

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVent.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/Logg.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentServiceTest.kt

Legger til sett på vent i logginnslagene

Legg til sett på vent i logginnslag

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårServiceTest.kt

fikset bug slik at utvidet barnetrygd kan slettes for helmanuell migrering
- [x ] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️

fikset bug slik at utvidet barnetrygd kan slettes for helmanuell migrering

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/personident/PersonidentServiceTest.kt

Endrer slik at vi kun oppretter task dersom identen skal legges til. Beholder task flyten dersom det å legge til feiler mot db slik at vi kan rekjøre tasken.
Dersom `identSkalLeggesTil` feiler så skal ba-mottak lese meldingen på nytt og prøve igjen. Dette _kan_ skape trøbbel, men såvidt jeg vet er ba-mottak konfigurert slik at den vil prøve på nytt.
Alt i ett

Forbedring: identhendelser

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/InfotrygdBarnetrygdClient.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/InfotrygdFeedClient.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/InfotrygdFeedService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/SendFødselsmeldingTilInfotrygdTask.kt
src/main/kotlin/no/nav/familie/ba/sak/task/SendStartBehandlingTilInfotrygdTask.kt
src/main/kotlin/no/nav/familie/ba/sak/task/SendVedtakTilInfotrygdTask.kt

Små forbedring på logger mot infotrygd-feed og i autobrev

Små loggforbedringer

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt

Oppretter "skyggesak" etter fullført migrering, sånn at det skal være mulig å journalføre nye dokumenter på saken fra Gosys.
Dette er bare en midlertidig quickfix for automatiske migreringer, inntil opprettelse av skyggesak er fikset generelt

Oppretter "skyggesak" etter fullført migrering

---

src/main/kotlin/no/nav/familie/ba/sak/config/KafkaAivenConfig.kt

fjernet ubrukt kafka konfigurasjon

---

src/main/resources/application-prod.yaml

Setter riktig scope for ba statistikk i prod

Setter riktig scope for ba-statistikk

---

src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkController.kt

Ettersender kun stønadsstatistikk på det med utbetalingsoppdrag I= null
Manuelt testet

Kun ettersend iverksatte behandlinger for stønadsstatistikk

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingsresultatSteg.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7822

Ikke valider etterbetaling om behandlingen er migrering

---

src/main/kotlin/no/nav/familie/ba/sak/common/EksternTjenesteKaller.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/FamilieIntegrasjonerTilgangskontrollClient.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonClient.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlIdentRestClient.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlRestClient.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/SystemOnlyPdlRestClient.kt
src/test/kotlin/no/nav/familie/ba/sak/config/IntegrasjonClientMock.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PersonopplysningerServiceTest.kt

Legger til ny ekstern kaller uten bruk av ressurs. Erstatter klientkall i PDL og tilgangskontroll klientene.

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlRestClient.kt

Lagre ned aktøren til medforelder når vi henter fra pdl. 
Veldig lite intuitivt at hentOgLagre-funksjon ikke lagrer med mindre man eksplisitt sier at den skal lagre.

Lagre ident til medforelder

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt

Fikser bug for autovedtak EØS-løypa. Skal ikke utlede behandlingsresultat for personer av type "ANNENPART"

Ikke utled behandlingsresultat for annenpart-type

---

.deploy/nais/azure-ad-app-lokal.yaml
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeUtil.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevBegrunnelseGrunnlagMedPersoner.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevPeriodeGrunnlagMedPersoner.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/MinimertUtbetalingsperiodeDetalj.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/RestBehandlingsgrunnlagForBrev.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksbegrunnelseTest.kt
src/test/resources/brevperiodeCaser/AVSLAG_FOR_SØKER_OG_ETT_BARN.json
src/test/resources/brevperiodeCaser/INNVILGET_FOR_SØKER.json
src/test/resources/brevperiodeCaser/INNVILGET_FOR_SØKER_OG_ETT_BARN.json

Fix for denne feilen: https://sentry.gc.nav.no/organizations/nav/issues/44126/?environment=prod&project=112&query=is%3Aignored
Søker har fire barn med godkjente vilkår far før av og får selv godkjent "bosatt i riket" for perioden. Siden det kun er søker som har utgjørende vilkår kommer ingen av barna med, selv om det riktige er at alle kommer med. 
Sender derfor med alle barna med utbetaling med dersom søker har utgjørende vilkår. 
Endrer avslag for søker til sende med alle barn. Tidligere ble dette kun gjort dersom kun søker hadde utgjørende vilkår.

Feature/utgjørende vilkår søker

---

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestTilkjentYtelse.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/UtvidetBehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeUtil.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonopplysningGrunnlag.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/StandardbegrunnelseUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/domene/MinimertPerson.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/Utbetalingsperiode.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingMetrics.kt
src/main/kotlin/no/nav/familie/ba/sak/sikkerhet/TilgangService.kt
src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkService.kt
src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt
src/test/kotlin/no/nav/familie/ba/sak/dataGenerator/behandling/kjørRevurdering.kt

Prøve å fikse bug for autovedtak EØS. Hvis automatisk EØS fødselshendelse -> legger vi på annenpart i personopplysningsgrunnlaget. Denne PRen fikser at annenpart ikke dukker opp andre steder i koden

Bugfix: Ikke inkluder annenpart i andre deler av koden enn der det brukes til å evaluere lovlig opphold-vilkår

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PdlRestClient.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersongrunnlagService.kt

Kun lagre personident på far og medmor når vi trenger det for å lage person til personopplysningsgrunnlag

Bugfix: ikke lagre aktør til annenforelder på søk

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårServiceTest.kt

La til validering for å stoppe å endre fom før migreringsdato i vilkårsvurdering for migreringsbehandlinger

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/JournalføringController.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/JournalføringService.kt

Bug: https://sentry.gc.nav.no/organizations/nav/issues/44272/?environment=prod&project=112&query=is%3Aunresolved
Vet ikke om dette løser problemet, men håper det. Legger også på mer logging så man kan se hva som blir sendt til dokarkiv om det skulle feile igjen. 

Bug/"dokument mangler tittel"- feil

---

src/main/resources/db/migration/V190__index_saksstatistikkmellomlagring.sql

Index for sendttidspunkt saksstatistikk mellomlagring
ny index. ikke mulig å skrive test

Index for sendt tid for saksstatistikk mellomlagring

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentService.kt
src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkService.kt
src/test/kotlin/no/nav/familie/ba/sak/dataGenerator/SettPåVent/settPåVent.kt
src/test/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkServiceTest.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7904
Oppdaterer datavarehus når sett på vent endrer seg

Feature/sett på vent datavarehus

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/Filtreringsregel.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/FiltreringsreglerFakta.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/FiltreringsreglerService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/utfall/FiltreringsregelIkkeOppfylt.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/utfall/FiltreringsregelOppfylt.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/FiltreringsregelForFlereBarnTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/FiltreringsregelTest.kt

Løsning for https://sentry.gc.nav.no/organizations/nav/issues/44026/?environment=prod&project=112&query=is%3Aunresolved&statsPeriod=14d
Legger til ny filtereringsregel for fødselshendelse. 

Legg på ny filtreringsregel "FAGSAK_IKKE_MIGRERT_UT_AV_INFOTRYGD_ETTER_BARN_FØDT"

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/filtreringsregler/FiltreringsreglerService.kt

Fødselshendelse migreringsdato på fagsak

---

src/main/kotlin/no/nav/familie/ba/sak/common/EksternTjenesteKaller.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/ef-sak/EfSakRestClient.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonException.kt

Fix for feil: https://sentry.gc.nav.no/organizations/nav/issues/44855/?environment=prod&project=112&query=is%3Aunresolved
Etter prat med Johan: https://nav-it.slack.com/archives/CK59Y6EHE/p1645021090339449

Bugfix/kall for overgangsstønad

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8021

Endre feilmelding ved etterbetaling mer enn 3 år tilbake i tid

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonClient.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/domene/OppgaveRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentServiceTest.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7889
Oppdatere oppgavefrist ved "Sett på vent"

Forleng oppgaver på behandling ved sett på vent

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt

`gammelOppgave.fristFerdigstillelse` er en string, så når man legger til `forlengelse` får man bare en legre string. Endrer til å konvertere til LocalDate først

Legg til periode på localdate og ikke string

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/ef-sak/EfSakRestClient.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonException.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/tilbakekreving/TilbakekrevingKlient.kt
src/main/resources/application-preprod.yaml
src/main/resources/application-prod.yaml
src/main/resources/application.yaml

Endrer url mot ef-sak så vi ikke får "//"  i `api//ekstern/perioder/full-overgangsstonad`
Endrer urler så vi bruker service discovery i nais
Oppdaterer metodene i TilbakekrevingKlient

Fjern "/" og benytt discoverable urler

---

src/main/kotlin/no/nav/familie/ba/sak/config/SentryConfiguration.kt

Bruk lenke som er kortere enn 200 tegn i sentry tag

Bruk lenke som er kortere enn 200 tegn i sentry tag

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevKlient.kt

Oppdaterer brev-klient til å bruke ny metode for kall

Oppdater kall mot familie-brev

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/StandardbegrunnelseUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt
src/test/kotlin/no/nav/familie/ba/sak/dataGenerator/behandling/kjørRevurdering.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceUtilsTest.kt

Fjerner feature toggle som har vært skrudd på en stund i prod.

Fjern toggle ENDRET_UTBETALING_VEDTAKSSIDEN og gamle funksjoner

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt

Enabler migrering av utvidet i prod

Enabler migrering av utvidet

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggService.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8082

Bug: Skrivefeil i historikkinnslag

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdGenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdTest.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8065
Nej

Bug: Kast funksjonell feil hvis utvidet-perioden ikke overlapper med barnas andeler

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt

Melding tilbake til bruker om at utvidet er godkjent

Endrer feilmelding til bruker på godkjente sakstyper

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/VedtaksperiodeMedBegrunnelser.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeUtil.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/domene/UtvidetVedtaksperiodeMedBegrunnelser.kt
src/test/kotlin/no/nav/familie/ba/sak/dataGenerator/behandling/kjørRevurdering.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/UtvidetVedtaksperiodeMedBegrunnelserTest.kt

Deloppgave: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8091
Hovedoppgave: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7948
Vis alle perioder uten overlapp

Legg på toggle som fjerner alle endringsperioder

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt

Counter for å telle migrering av type utvidet

Counter for migrering av utvidet

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdGenerator.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7961

Endre feilmeldingstekst ved utvidet-vilkår innenfor samme måned

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveController.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8076

Returner null istedet for å kaste feil hvis aktørId ikke er satt

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/AutobrevService.kt

Logging av behandlingsårsak ved autobrev
Nei

Logger behandlingsårsak ved sjekk av autobrev

---

src/main/kotlin/no/nav/familie/ba/sak/common/Feil.kt

Legger på cause på feiltypene slik at de ikke sluker feilmeldingene.

Legg på cause på Feil, FunksjonellFeil, UtbetalingsikkerhetFeil og RolleTilgangskontrollFeil

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7894
Holder på å skrive tester

Revurdering dødsfall bruker - Sett søkers vilkår til oppfylt tilogmed dødsdato

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/MinimertEndretAndel.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseSpesifikasjonTest.kt

Validerer endret utbetaling slik at man får Funksjonell feil (og ikke alarm i sentry) om riktige felter ikke er satt

Validerer endret utbetaling slik at man får Funksjonell feil (og ikke alarm i sentry) om riktige felter ikke er satt

---

src/test/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/BostedsadresseTest.kt

Hadde disse to testene liggende lokalt som jeg skrev i forbindelse med autovedtak fødselshendelse EØS forrige uke. Tenker at de fint kan bli merget inn, da denne funksjonen ikke ble testet fra før.
- Test funksjonen som vurderer om personer bor sammen

Testing av bostedsadresser

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseSpesifikasjon.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8130

Legg til begrunnelsen REDUKSJON_DELT_BARNETRYGD_HASTEVEDTAK

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/domene/PeriodeResultat.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/UtgjørendeVilkårUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/SanityBegrunnelse.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/TriggesAv.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/domene/utdypendeVilkårsvurderingerUtils.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7167
Toggelen ble lagt til for å brukes frontend

Legg til "Delt bosted: skal ikke deles"

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingStegTest.kt

Revert endringer

---

src/main/kotlin/no/nav/familie/ba/sak/common/RessursUtils.kt

Fjern informasjon om feil i vanlig logg

Fjer error message fra feil i vanlig log

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/SanityBegrunnelse.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/domene/EndretUtbetalingAndel.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/TriggesAv.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValideringTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/TriggesAvTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseSpesifikasjonTest.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-7098
Legg til nye årsaker på endringsperioder
- Allerede utbetalt
- Endre mottaker
Venter på avklaring angående brevbegrunnelser
Skal skrive tester
Alt i ett

Feat/nye årsaker endringsperioder

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt

Fjern "delt bosted"-toggle

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingService.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/LagreMigreringsdatoTest.kt

Dersom fagsaken ikke har lagret migreringsdato prøver vi å hente tidligste vurderte dato fra forrige vedtatte behandling.
Nei
Alt i ett

Bug endre migreringsdato på fagsak hvor migreringsdato ikke er lagret

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/FødselshendelseService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/OpprettTaskService.kt
src/test/kotlin/no/nav/familie/ba/sak/config/IntegrasjonClientMock.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/FødselshendelseServiceTest.kt

Oppretter fremleggsoppgave ved fødselshendelse på mor med eøs medlemskap.
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8153
Nei
Alt i ett

Fremleggsoppgave autovedtak eøs

---

src/main/kotlin/no/nav/familie/ba/sak/ekstern/skatteetaten/SkatteetatenService.kt
src/test/kotlin/no/nav/familie/ba/sak/ekstern/skatteetaten/SkatteetatenServiceIntegrationTest.kt

Slå sammen overlappende perioder. Som kan skje ved endret migreringsdato

Slår sammen perioder i forbindelse med endret migreringsdato

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/EndringstidspunktSerivce.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/EndringstidspunktUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/EndringstidspunktUtilsTest.kt

Retter feil der vi hadde brukt feil funksjon på andel tilkjent ytelse for å gruppere søkers andeler.
Legger også til støtte for 0kr endringer.
Nei
Alt i ett

Bug/endringstidspunkt delt bosted + søker

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BegrunnelseUtil.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/UtgjørendeVilkårUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevBegrunnelseGrunnlag.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/StandardbegrunnelseUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceUtilsTest.kt

Dersom vi en begrunnelse som trigges av utvidet i tillegg til et annet vilkår skal personer for det andre vilkåret komme opp også. 

Hent personer for de andre vilkårene dersom en begrunelse gjelder utvidet i tillegg til andre vilkår

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevUtil.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/SanityBegrunnelse.kt

Tillater begrunnelser uten hjemler. Legger på validering at minst én begrunnelse i brevet må være knyttet til hjemmel.

Tillat begrunnelser uten hjemler

---

src/main/kotlin/no/nav/familie/ba/sak/config/SentryConfiguration.kt

Legger til prosess fra MDC i fingerprint. Det er informasjon om hvilken task som har feilet i prosess i dag som bør fikse problemet vi ser med gruppering av feil som har oppstått i en task.

Sentry task fingerprint

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/simulering/SimuleringService.kt
src/main/kotlin/no/nav/familie/ba/sak/task/IverksettMotOppdragTask.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/UtbetalingsoppdragUtilsTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceTest.kt

Rullet tilbake endring for skaliverksette - viste seg at i noen tilfelder skal forsatt innvilget iverksettes.
Tilbakerulling.

Rullet tilbake endring for skaliverksette

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/småbarnstillegg/VedtakOmOvergangsstønadService.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8231
Nei
Ikke aktuelt
Alt i ett

Sjekker om ef vedtak påvirker fagsak før man går videre med behandling.

---

src/main/resources/db/migration/V195__set_fagsaker_til_løpende.sql
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FødselshendelseHenleggelseTest.kt

7 fagsaker har blitt feilaktig avsluttet. Opprettter et skript for å endre disse til å bli løpende.
DB-skript.

Set fagsaker til status løpende

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseSpesifikasjon.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8223

Legg til nye begrunnelser fra sanity

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8230

Prodsak: Åpner opp for å legge til/fjerne utvidet vilkår på teknisk endring og korrigere vedtak behandlinger.

---

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestFagsak.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningServiceTest.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8247
Eksempel nr2 i favro-kortet
Sende med løpende kategori og underkategori for å vise disse på saksoversikten, i stedet for å bruke behandlingstema fra den aktive behandlingen.

Vis riktig behandlingstema på saksoversikt (fagsak)

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt

Legg på toggle for EØS-sjekk

---

src/main/resources/db/migration/V196__migrerte_behandlinger_sett_behandlingstema.sql

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8247

Db-migrering: Oppdatere behandlingstema på endre migreringsdato med underkategori utvidet

---

src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkService.kt
src/test/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkServiceTest.kt

Endret registertDato som behandlings opprettet tidspunkt

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeUtil.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeUtilTest.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8206

Sorter perioder i brev etter stigende fom-dato

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelServiceTest.kt

Fjern "delt bosted"-validering toggle

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/EndringstidspunktUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/beregning/EndringstidspunktUtilsTest.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8266
Nei
Alt i ett

Bruker tilknyttede endrede utbetalingsandeler til å også vurdere om andelen er endret.

---

src/main/kotlin/no/nav/familie/ba/sak/common/EksternTjenesteKaller.kt
src/main/kotlin/no/nav/familie/ba/sak/config/ApiExceptionHandler.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/IntegrasjonException.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiService.kt
src/test/kotlin/no/nav/familie/ba/sak/common/EksternTjenesteKallerTest.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/IntergrasjonTjenesteTest.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PersonopplysningerServiceTest.kt

Feilen jeg fikser er iverksetting mot oppdrag. Der sjekket vi mot feil exception etter omskrivning til felles ekstern tjenestekaller.
Nei
Alt i ett

Kaster ressurs exception videre for å unngå at vi wrapper exception i en ny exception.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeUtil.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevperiodeData.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevPeriodeUtilTest.kt

* Passer på at fom ikke er null før man sender det inn i compareTo funksjonen. 
* Flytter compare funksjonen for BrevperiodeData inn i klassen.

bruk "fom ?: TIDENES_MORGEN" før fom mates inn i compareTo funksjon.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/BeregningService.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8272
Er det nok å sjekke kun på status? 🤔 

Bug: Oppdater spørring som henter behandlinger som holder på å iverksettes

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/BrevType.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/ManueltBrevRequest.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/Brev.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/domene/maler/VarselOmRevurderingSamboerBrev.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8149

Brev "varsel om revurdering samboer"

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8279

Legg til mulighet for å legge til utvidet-vilkår ved klage

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseSpesifikasjon.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8298

Legg til nye begrunnelser

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt

Legge til støtte for migrering av saker med vilkår om delt bosted
Det er en forenklet første utgave som kun fungerer for personer med avtale om delt bosted for samtlige av barna

Legger til støtte for migrering av saker med vilkår om delt bosted

---

src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt

Skrur ned logglevel på ukjent-landkode i stønadsstatistikk.

Skrur ned logging-level på ukjent landkode for de som ikke har norsk eller utenlandsk addresse

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt

Fjern toggle for brev om varsel om revurdering samboer

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/VelgFagSystemService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/fødselshendelse/VelgFagsystemIntegrasjonTest.kt

Fjern toggle for å automatisk behandle EØS

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/PersonopplysningerService.kt

Defaultverdi for statsborgerskap hvis den ikke finnes i PDL settes til ukjent(XUK)

Defaulter til ukjent statsborgerskap hvis det mangler i PDL

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/Logg.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/DistribuerVedtaksbrev.kt
src/main/kotlin/no/nav/familie/ba/sak/task/DistribuerDokumentTask.kt

Logg at distribuering misslyktes ved ukjent adresse og fortsett behandlingen

---

.deploy/nais/kafka/dev/bisys_opphoer_av_barnetrygd.yaml
.deploy/nais/kafka/prod/bisys_opphoer_av_barnetrygd.yaml
README.md

Setter minimumInSyncReplicas til 2 for kafkaaivenProducerconfig for å unngå å risikere å miste meldinger

Setter minimumInSyncReplicas til 2 

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/DokumentService.kt

Legger til debug for distribuering av brev

---

src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt
src/test/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkServiceTest.kt

Utbetalingsperioder som ikke var sendt til oppdrag ble sendt til datavarehus.
- [ X] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇

Rettet feil i stønadsstatistikk. 

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseUtil.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/MockKompetanseRepository.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/domene/Kompetanse.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseUtilTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/kompetanse/KompetanseServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/util/KompetanseBuilder.kt

Forhåpentligvis forenklet merge av like kompetanser. Pluss forenkling av tester

Fikser merge ved hjelp av tidslinjer

---

src/main/kotlin/no/nav/familie/ba/sak/common/Tid.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/UtvidetBarnetrygdGenerator.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/tidslinjer/VilkårsresultatMånedTidslinje.kt

Skulle vært med på forrige merge 😢

Retter noen bugs i forbindelse med mapping fra dag til måned på vilkårstidslinjer.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/rest/RestTidslinjer.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/tidslinjer/RegelverkPeriodeTidslinje.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/tidslinjer/Tidslinjer.kt

Lager en midlertidig tidslinje med regelverk og kombinerer den med de oppfylte periodene for barnet. På den måten får vi en tidslinje med null, eøs, nasjonal og kan se bort i fra null-perioder.
Ikke noe tester, det kommer i neste PR. Viktigere å få dette ut til fag så de kan teste løsningen.

Forbedring på regelverkstidslinje. 

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/oppgave/OppgaveService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/settpåvent/SettPåVentService.kt

Dersom en oppgave er avsluttet skal den ikke forlenges selv om behandlingen settes på vent

Endre kun frist på oppgaver som ikke er avsluttet

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt

Endre valideringen for om det er den endret delt periode samtidig som endrede utvidet perioder. 
Er allerede tester på dette 

Endre tider til å sjekke overlapp

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8389

Legg til ny begrunnelse for opphør pga bosatt i norge var ikke medlem

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingsresultatSteg.kt

Dra validering ut i egen metode og kast feil dersom det er feil

Dra validering ut i egen metode og kast feil dersom det er feil

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/UtvidetBehandlingService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/verdikjedetester/FødselshendelseFørstegangsbehandlingTest.kt

Del av denne oppgaven: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8314
Trenger ikke sende med vedtaksperioder når det behandlingen er avsluttet.

Ikke send med vedtaksperioder hvis behandlingen er avsluttet

---

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestKompetanse.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/KompetanseController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/util/RevurderKompetaneStatus.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/util/SlåSammenKompetanser.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/util/TilpassKompetanserTilRegelverk.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/util/TrekkFraKompetanser.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/tidslinjer/RegelverkPeriodeTidslinje.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/tidslinjer/Tidslinjer.kt
src/test/kotlin/no/nav/familie/ba/sak/common/DataGenerator.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeServiceTest.kt

Riktig mapping mellom frontend/backend på kompetanser.
Utleder tilOgMed slik fag ønsker sånn at barna grupperes også uendelig fremover i tid og blir ikke stykket opp pga 18 årsvilkåret.
Litt duplisert kode for å få inn endringene, rydder opp i ny PR.
Nei
Ønsker å få ut denne fort, skriver tester i samme PR som opprydningen.
Alt i ett

REST kompetanse + ny logikk for tilOgMed måned på regelverk

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevKlient.kt

Endrer brevklienten til å bruke AbstractRestClient som fikser mye av boilerplate-koden

Forenkle brevklienten

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/EndretUtbetalingAndelValidering.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/domene/EndretUtbetalingAndel.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-2231
- Legg til etterbetaling 3 år som årsak
- Validering

Legg til etterbetaling 3 år 

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/beregning/TilkjentYtelseValidering.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/domene/Vedtaksbegrunnelse.kt

Småendringer på etterbetaling 3 år:
- Tillate segmenter med 0kr utbetaling før gyldig etterbetalingsdato
- Alltid velge eldste søknadstidspunkt

Fix på etterbetaling

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt

Legg til begrunnelse tilleggstekst transporterklæring-deler av etterbetalingen

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8435

Legg til 4 nye begrunnelsestekster

---

src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestFerdigstillOppgaveKnyttJournalpost.kt
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/journalføring/JournalføringService.kt

Fikset valideringfeil når journalpost knyttes til eksisterende behandlinger

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingStegTest.kt

Åpner for migrering av andre sakstyper enn delt bosted i helmanuell løype
Har bare fjernet midlertidig kode

Åpner for manuell migrering av andre sakstyper enn delt bosted i preprod via toggle

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingController.kt

Gi tilgang til veiledere til å hente validering av etterbetaling.

Endre fra saksbehandler til veileder som minimumBehandlerRolle

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/kompetanse/domene/Kompetanse.kt

Bytter navn på enum-konstant for to primærland

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/common/Feil.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/Person.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/bostedsadresse/GrMatrikkeladresse.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/bostedsadresse/GrVegadresse.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/personident/Personident.kt

Oppdaterer avhengigheter som dependabot klager på.
Det har vært en endring i ktlint som gjør at `""".trimMargin()`blir satt på ny linje

Fiks dependabot-oppdateringer

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingController.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/behandlingstema/BehandlingstemaService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/behandlingstema/BehandlingstemaUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrereSøknad.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/VilkårsvurderingSteg.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingUtilsTest.kt

Prøver meg på en forbedring av navn og flyt ved fastsetting av behandlingstema.

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/fagsak/FagsakStatusScheduler.kt

Fjerner scheduled kode som kjørte tidligere i dag. Se https://github.com/navikt/familie-ba-sak/pull/2336 for mer info

Fjern scheduled kode som had kjørt

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/behandlingstema/BehandlingstemaService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/behandlingstema/BehandlingstemaUtils.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/RegistrereSøknad.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingUtils.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/OppdaterVilkårsvurderingTest.kt

Fikser det https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8466

Fikset bug slik at behandlingstema ikke endres automatisk

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vilkårsvurdering/VilkårsvurderingUtils.kt

Det er første forsøk til å forenklere VilkårService ved å bruke felles metoder, refaktorere metoder og bruker funksjonelle metoder når det  er mulig.

første forsøk til å forbedre VilkårService.kt

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingsresultatSteg.kt

Fjerner toggle for etterbetaling 3 år-funksjonalitet.
Nej
Triviell endring. Var ikke testet at valideringen ble gjennomført, så gir ikke mening å legge på test nå som den er fjernet.

Fjern etterbetaling toggle

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/AvstemmingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingHentOgPersisterService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt
src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/AvstemmingServiceTest.kt
src/test/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingHentOgPersisterServiceTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8365
I dag bruker familie-oppdrag fødselsnummer som var i bruk ved iverksettelse for konsistensavstemming. Det medfører noen avvik mot økonomi når person får ny fødselsnummer. For å løse dette sender fagsystem aktiv fødselsnummer til familie-oppdrag.

Sender aktivFødselsnummer til familie-oppdrag for Konsistensavstemming

---

.github/workflows/build-pr.yml

Midlertidig skru av sonar fordi den er nede

Midlertidig skru av sonar fordi den er nede

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/AvstemmingService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/BehandlingRepository.kt

oppdaterte query-en til konsistensavstemming som henter relevante behandlinger. Fjernet aktiv sjekk på behandling tabell. Fagsak status løpende er nok.
Endret slik at aktive fødselsnummer kan hentes for alle som har løpende tilkjent ytelse 
favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8365

slettet aktiv sjekk på behandling tabell

---

pom.xml

Erstatter:
- https://github.com/navikt/familie-ba-sak/pull/2385
- https://github.com/navikt/familie-ba-sak/pull/2381
- https://github.com/navikt/familie-ba-sak/pull/2379
- https://github.com/navikt/familie-ba-sak/pull/2365
- https://github.com/navikt/familie-ba-sak/pull/2357
- https://github.com/navikt/familie-ba-sak/pull/2356
- https://github.com/navikt/familie-ba-sak/pull/2353
- https://github.com/navikt/familie-ba-sak/pull/2351
- https://github.com/navikt/familie-ba-sak/pull/2350
- https://github.com/navikt/familie-ba-sak/pull/2348

Dependabot oppdateringer 20220428-104058

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8591
Venter på en avklaring fra Anna og Birgitte angående innvilgelse-begrunnelsen før jeg merger.
Nop
Ikke så mye å teste her

Legg til 4 nye begrunnelsetekster

---

src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeService.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/vedtaksperiode/VedtaksperiodeUtil.kt
src/test/enhetstester/kotlin/no/nav/familie/ba/sak/dataGenerator/behandling/kjørRevurdering.kt
src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/brev/BrevBegrunnelseTest.kt

Fjerne toggle siden funksjonaliteten har levd bra i prod 1 uke 👍 
Har en oppgave på favro så jeg skal huske å slette toggle i unleash etter å ha merget: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8534
Nop
Ikke så mye å teste

Fjern avtaletidspunkt for delt bosted-toggle

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt
src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt

Bedre logging til securelog for beregnet beløp ulikt og opprydding av togglet funksjonalitet

Migrering: Logging og opprydding av toggle

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/eøs/tidslinjer/rest/RestTidslinjer.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/BeskjæreTidslinje.kt
src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/EndreTid.kt
src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/eøs/tidslinjer/rest/RestTidslinjerTest.kt
src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/BeskjæreTidslinjeTest.kt
src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/util/Tid.kt

Litt opprydding i RestTidslinjer, og setter begrensninger slik at de ikke fortsetter mot uendelig
Nei

Begrenser søkers tidslinjer til når yngste barn blir 18 år

---

src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringService.kt
src/test/integrasjonstester/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt

Åpner opp for migrering av gradert person

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/metrikker/TeamStatistikkService.kt

Etter en serie uheldige hendelser så så vi at teamstatistikken ble kjørt på alle noder og alt for ofte. Dette førte til at vi gikk tom for minne og tom for connections mot database. Justerer derfor ned oppdateringsfrekvens og henter statistikk kun fra leader.

Teamstatistikk justering av oppdateringsfrekvens

---

pom.xml
src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkService.kt
src/test/enhetstester/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkServiceTest.kt

Ny versjon av kontrakt mot DVH. Der har jeg fjernet ubrukte felter og lagt inn kompetanse.
Neste steg er å publisere dette på kafka på aiven, kommer i en periode til å leve 2 versjoner av kontrakt for datavarehus, slik at de får en myk overgang.

Mapping og ny kontrakt for stønadsstatistikk, nå med kompetanse

---

src/main/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkController.kt
src/test/enhetstester/kotlin/no/nav/familie/ba/sak/statistikk/saksstatistikk/SaksstatistikkControllerTest.kt

Feltet i json heter versjon og ikke kontraktversjon

Fikser feil navn på kontraktversjon i patch saksstatistikk

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandlingsresultat/BehandlingsresultatUtils.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8736

Fikset bug slik at behandling får ENDRET_OG_OPPHØRT når ytelsePersonResultat kommer med OPPHØRT og FORTSATT_OPPHØRT

---

src/main/kotlin/no/nav/familie/ba/sak/config/CacheConfig.kt
src/main/kotlin/no/nav/familie/ba/sak/ekstern/skatteetaten/SkatteetatenService.kt

som hjelp til å unngå 504 Gateway Timeout

Legger på cache for personer-endepunktet til skatteetaten-api

---

src/main/resources/db/migration/V205__index_tilkjent_ytelse_andel_tilkjent_ytelse.sql

Indexer for å hjelpe til med skatteuttrekk
db endring. Ruller ut i preprod først

Lagt til et par indekser på andel tilkjent ytelse og tiljent ytelse for å få skatt til å kjøre fortere

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt

Opprinnelig knyttet til denne oppgaven: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8592
Etter merge av denne PR'en (https://github.com/navikt/familie-ba-sak/pull/2449) oppdaget jeg at teknisk endring behandling med resultat fortsatt innvilget henger igjen på "iverksetter vedtak"-steget. Men det som var rart var at det ikke lå noen feilede task i familie-prosessering. Ved å se nærmere på koden så jeg at vi glemte å lagre ned tasken i forrige PR. Legger det på nå.
Nop
Gir ikke helt mening her(?)

Lagre ned ferdigstill behandling-task

---

src/main/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/Standardbegrunnelse.kt

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8560
Legger til to nye begrunnelser, se favro for beskrivelse.
~Venter på avklaring fra funksjonelle for å dobbeltsjekke at dette løser hele oppgaven.~
Gir ikke mening her

Legg til to nye begrunnelser for å bytte mottaker
